vmware/govmomi

- client.go
- storage_resource_manager.go
I'd like to use StorageResourceManager with govmomi.
So, I made PR to support StorageResourceManager. I would be happy if you could merge.
> make storage resource manager

- find/error.go
- find/finder.go
- govc/cli/command.go
- govc/pool/change.go
- govc/pool/create.go
- govc/pool/destroy.go
- govc/pool/help.go
- govc/pool/info.go
- govc/test/clean.sh
- govc/test/pool.bats
- resource_pool.go
* Add usage & description to all commands
* `pool.create` against multiple pools
* `pool.change` against multiple pools
> Work on pool.* commands

- client.go
- client_test.go
> Add PropertiesN function on client struct

- folder.go
I was looking for a method to create a new folder inside a given folder, similar to `folder.CreateDatacenter` and `folder.CreateVM`. This commit adds a suitable `folder.CreateFolder` method.
> Add CreateFolder method

- client.go
- client_test.go
- session_manager.go
- session_manager_test.go
Simple addition to client implementing the SessionIsActive method
> added SessionIsActive to Client

- object/search_index_test.go
Grab the host and domain names from the host's DNS configuration.
> Re-enable search index test

- gen/vim_wsdl.rb
- vim25/types/types.go
This fixes the issue mentioned in the tail end of #247.
> Drop omitempty tag from optional pointer fields

- list/lister.go
> Fix error when using SDRS datastores

- govc/flags/client.go
This removes the need for a shell script fix when restored sessions don't work (#251).
> Add flag to toggle persisting session to disk

- examples/datastores/main.go
> Add example that lists datastores

- govc/pool/info.go
- govc/pool/resource_config_spec.go
This error was introduced with making boolean fields pointers.
> Fix resource pool creation/modification

- CHANGELOG.md
- govc/CHANGELOG.md
- govc/flags/client.go
- vim25/client.go
- vim25/retry.go
- vim25/retry_test.go
> Retry on temporary network errors

- govc/build.sh
- govc/release.sh
This adds a small scripts that builds govc and prepares a draft release.
> Add release script

- list/lister.go
Missing types:
- mo.VirtualApp
- mo.DistributedVirtualSwitch
Fixes #271.
> Add missing types to list.ToElement

- govc/CHANGELOG.md
- govc/flags/client.go
- govc/main_test.go
- govc/release.sh
Also includes unrelated change I hadn't pushed yet.
> Fix govc flag collision

- gen/vim_wsdl.rb
- govc/pool/change.go
- govc/pool/create.go
- govc/pool/info.go
- govc/pool/resource_config_spec.go
- vim25/methods/methods.go
- vim25/soap/client.go
- vim25/types/enum.go
- vim25/types/if.go
- vim25/types/types.go
- Regenerate from 6.0 wsdl
- Refactor govc pool commands now for the ResourceAllocationInfo
interface
> Update to vim25/6.0 API

- object/virtual_device_list.go
- object/virtual_device_list_test.go
Support by-type filter in SelectByBackingInfo
> Add serial port matcher to SelectByBackingInfo

- examples/datastores/main.go
This is modeled after the govc behavior and is needed when the username and/or password contain special characters that makes it unable to specify them in an URL.
> Provide ability to override url username and password

- object/virtual_app.go
Introduce UpdateVAppConfig, PowerOnVApp_Task, PowerOffVApp_Task
and SuspendVApp_Task
> Introduce more VirtualApp methods

- govc/CHANGELOG.md
- govc/flags/datacenter.go
- govc/flags/datastore.go
- govc/flags/host_system.go
- govc/flags/network.go
- govc/flags/resource_pool.go
- govc/flags/virtual_machine.go
- govc/importx/archive.go
- govc/importx/options.go
- govc/importx/ova.go
- govc/importx/ovf.go
- govc/importx/spec.go
* added import.spec target to produce example json
* added -options argument to import.ovf/import.ova targets
* moved -folder argument flag class
* updated change log
* minor formatting changes
* closes #288
> Added the ability to specify ovf properties during deployment

- govc/CHANGELOG.md
- govc/importx/options.go
- govc/importx/ova.go
- govc/importx/ovf.go
- govc/importx/spec.go
- ovf/env.go
- ovf/ovf.go
- ovf/ovf_test.go
* PowerOn - power on the vm
* InjectOvfEnv - inject the ovf properties when deploying to esx
* WaitForIP - display the vm ip address
> Add options to importing an ovf or and ova file

- examples/datastores/main.go
* change enumeration to be more idiomatic to golang
> Misc clean up

- contrib/vagrant/vcsa/create-box.sh
- govc/test/README.md
* added check for greadlink and gmktemp
* added note to install coreutils on Darwin
> Clean up of vcsa creation script

- contrib/vagrant/vcsa/vagrant.sh
- govc/test/README.md
- govc/test/cli.bats
- govc/test/datastore.bats
- govc/test/test_helper.bash
* unset username and password overrides
* correct url parsing to acquire username and password
* added usage for gxargs, greadlink and gmktemp
> Interative clean up of bats testing

- govc/importx/options.go
- govc/importx/ovf.go
- govc/importx/spec.go
* ovf.Property will be used to display full property information
> Added ovf.Property output to import.spec

- govc/importx/ova.go
- govc/importx/spec.go
* allow for an ova file to not have a file extension
* look for *.ovf in the ova tar archive
> Relax the convention around importing an ova

- govc/importx/options.go
- govc/importx/spec.go
* allows for a trimmed down spec that is more managable
* defaults to false
> Added verbose option to the import.spec feature

- govc/flags/search.go
- object/search_index.go
- object/search_index_test.go
Added bool flag instanceUUID to find a VM with instanceUUID if set to true.
> change for looking up a VM using instanceUUID

- session/keep_alive.go
> Fix KeepAlive

- CHANGELOG.md
- govc/CHANGELOG.md
- govc/host/esxcli/firewall_info.go
- govc/host/firewall/find.go
- govc/main.go
- govc/test/firewall.bats
- object/host_config_manager.go
- object/host_firewall_system.go
- Add govc firewall.ruleset.find command
- Add esxcli.GetFirewallInfo method
> Add HostFirewallSystem wrapper

- object/virtual_machine.go
Hi, 
I've just refactored a little bit vsphere resource in Terraform, and it'll be great if you can add this function in the VirtualMachine object.
Regards.
> VirtualMachine: Add Customize function on object.VirtualMachine

- CHANGELOG.md
- find/finder.go
- govc/CHANGELOG.md
- govc/cluster/add.go
- govc/cluster/change.go
- govc/dvs/add.go
- govc/dvs/create.go
- govc/dvs/portgroup/add.go
- govc/host/vnic/info.go
- govc/host/vnic/service.go
- govc/license/assigned.go
- govc/main.go
- govc/test/host.bats
- govc/vm/change.go
- list/lister.go
- object/distributed_virtual_switch.go
- object/folder.go
- object/host_config_manager.go
- object/host_virtual_nic_manager.go
- object/host_vsan_system.go
- object/network_reference.go
More cluster related enhancements
> Add DVS and vSAN support

- object/datastore.go
This method is used for datastore uploads, avoid choose a host that is
not in a known powered on and connected state.
> Check host state in Datastore.AttachedHosts

- govc/extension/register.go
- govc/flags/client.go
- govc/flags/output.go
- govc/importx/options.go
* use streaming decoder where appropriate
> Minor optimization to encoding usage

- govc/ls/command.go
- list/lister.go
This enables ls to look at the objects managed by a particular host.
> Let the lister recurse into a ComputeHost

- govc/cli/command.go
Conforms to most other Unix tools. Makes it easier to spot govc specific errors in script output.
> Print os.Args[0] in error messages

- govc/flags/datastore.go
- govc/importx/vmdk.go
- govc/vm/create.go
- object/datastore.go
Change the errors it returns to include the file or directory that the user attempted to stat.
> Move stat function to object.Datastore

- govc/importx/spec.go
* this was found missing in the vCO/vRO ovf file
> Added check for missing ovf deployment section

- govc/test/cli.bats
- govc/test/datacenter.bats
- govc/test/datastore.bats
- govc/test/device.bats
- govc/test/host.bats
- govc/test/network.bats
- govc/test/pool.bats
- govc/test/vm.bats
Error message output changed in commits 72bdb45 and 0a4c978
> Fix bats tests

- find/finder.go
- govc/flags/datacenter.go
- govc/flags/datastore.go
- govc/flags/network.go
- govc/flags/resource_pool.go
{Datacenter|Datastore|ComputeResource|HostSystem|Network|ResourcePool}OrDefault
They return the requested object or its default value on success or an
error for failure.
> Add some common functions to find/finder.go

- govc/datastore/create.go
- object/datastore.go
which returns the type of file system volume.
> introduce Datastore.Type()

- .drone.yml
- README.md
Adds .drone.yml, updates README to include Drone build status and local Drone build instructions.
Addresses issue #426.
> Enable Drone CI

- CHANGELOG.md
- find/finder.go
- govc/CHANGELOG.md
- govc/flags/datastore.go
- govc/flags/storage_pod.go
- govc/test/vm.bats
- govc/vm/create.go
- govc/vm/disk/attach.go
- govc/vm/disk/create.go
- list/lister.go
- object/storage_pod.go
- object/virtual_device_list.go
- vim25/types/helpers.go
Not finished yet, making PR so progress can be tracked.
> Datastore clusters

- object/virtual_device_list.go
device.floppy.add related tests have been failing since bfe414f
> Fix VirtualDeviceList.CreateFloppy

- govc/vm/disk/create.go
I hope this is helpful to others who require specific disk modes in their environments.
Corrected style issues which @dougm identified in pull request #456 
I hope you find these changes satisfactory, and apologies for the accidental inclusion of my master merge on the prior pull request #456 
Thanks
> Added new govc vm.disk.create -mode option for selecting one the VirtualDiskMode types

- govc/test/test_helper.bash
> test_helper.bash updated to conditionally set env variables

- event/helper.go
- event/manager.go
- govc/events/command.go
- object/list_view.go
- property/wait.go
- view/list_view.go
- view/manager.go
- Tail and Force flag added to govc events command
> Implemented the ablitiy to tail the vSphere event stream

- govc/CHANGELOG.md
- govc/dvs/portgroup/info.go
Cleaned up git history of PR #471 
Includes a few other fixes, using finder instead of search index, making golint happy, etc.
> Add dvs.portgroup.info command

- gen/vim_wsdl.rb
Add internalvim25 and internalreflect and grab urn from the wsdl.
> Remove hardcoded urn:vim25 value from vim_wsdl.rb

- govc/importx/vmdk.go
The import.vmdk command was failing against vCenter with:
govc: Invalid configuration for device '1'.
Switch to using VirtualDeviceList so we have the correct device Key and
ControllerKey set.
Fixes #470
> Use VirtualDeviceList for import.vmdk

- object/datastore.go
- vim25/soap/client.go
Returns a io.ReadCloser which can be used to read the file directly.
> Add datastore.Download method

- govc/device/remove.go
- object/virtual_machine.go
The option allow you unmount the disk from the VM and store disk files in data store.
> device.remove: add keep option

- govc/env/command.go
- govc/flags/client.go
- govc/main.go
- govc/test/cli.bats
- govc/test/test_helper.bash
- scripts/wireshark-esx.sh
- scripts/wireshark-vcsa.sh
Useful as bash scripting helper to parse GOVC_URL.
> Add govc env command

- object/virtual_machine.go
Signed-off-by: Dave Tucker <dave@dtucker.co.uk>
> Add RevertToSnapshot to VirtualMachine object

- find/finder.go
- gen/gen_from_vmodl.rb
- govc/about/command.go
- govc/datacenter/info.go
- govc/flags/debug.go
- govc/folder/info.go
- govc/host/option/ls.go
- govc/host/option/set.go
- govc/main.go
- govc/test/cli.bats
- govc/test/datacenter.bats
- govc/test/folder.bats
- govc/test/host.bats
- object/folder.go
- object/host_config_manager.go
- object/option_manager.go
- scripts/debug-xmlformat.sh
- vim25/mo/entity.go
- vim25/mo/mo.go
In support of https://github.com/vmware/vic/issues/573
> Various enhancements to inspect and navigate the inventory model

- CHANGELOG.md
- govc/CHANGELOG.md
- govc/host/storage/info.go
- govc/host/storage/mark.go
- object/host_storage_system.go
> vSAN related enhancements

- object/datastore.go
> Add filtering for use of datastore service ticket

- govc/events/command.go
> Fixes panic in govc events

- object/virtual_disk_manager.go
Hi,
I've just added a function to query uuid of virtual disk in the VirtualDiskManager object.
Regards.
> Add QueryVirtualDiskUuid function

- object/list_view.go
Implmented add, remove & reset for the ListView object
> Implemented additional ListView methods

- govc/vapp/destroy.go
Right now trying to delete a vApp with no VMs or a powered off vApp ends
up with
The attempted operation cannot be performed in the current state (Powered off).
errors.
> Fix deletion of powered off vApp

- govc/test/vm.bats
- govc/vm/clone.go
- Add Usage and Description
Fixes #568
> Validate vm.clone -vm flag value

- govc/test/guest_operations_test.sh
- govc/vm/disk/attach.go
- govc/vm/guest/download.go
- govc/vm/guest/ps.go
- govc/vm/guest/rmdir.go
- govc/vm/guest/upload.go
- Fix vm.disk.attach with '-persist=false'
- Support stdin in guest.upload
- Support stdout in guest.download
- Support '-json' in guest.ps
- Add '-X' flag to guest.ps (wait for process to exit)
- Rename guest.rmdir '-p' flag to '-r'
> Add govc guest command tests

- govc/datastore/tail.go
- govc/emacs/README.md
- govc/emacs/govc.el
- govc/test/datastore.bats
- object/datastore.go
- object/datastore_file.go
- vim25/soap/client.go
Supports tail and follow of a datastore file over HTTP.
> Add DatastoreFile helpers

- object/datastore_file.go
Rather than close right away, wake up and return io.EOF after 1 final
Read().  The main point of follow.DatastoreFile.Close is to break out of
the blocking Read() call.  We still do that, but also give the
caller any other data that may have come in while we were waiting on the
poll interval ticker.
> Treat DatastoreFile follower Close as "stop"

- session/manager.go
> Add session.Locale var to change default locale

- govc/build.sh
- govc/release.sh
- Use .zip for windows binaries
- Add dryrun mode
- Build/zip in parallel
Fixes issue #610
> Release script updates

- CHANGELOG.md
- govc/CHANGELOG.md
- govc/USAGE.md
- govc/dvs/portgroup/change.go
- govc/dvs/portgroup/spec.go
- govc/flags/version.go
- govc/test/network.bats
- object/distributed_virtual_portgroup.go
- Add vlan flag to dvs.portgroup.add command
- Add object.DistributedVirtualPortgroup.Reconfigure method
Fixes #500
> Add dvs.portgroup.change command

- govc/flags/client.go
- vim25/soap/client.go
Setting the variables in configure function.
Fix from @dougm
> Don't ignore version/manifest for existing sessions

- govc/importx/options.go
- govc/importx/ovf.go
* Support InjectOvfEnv without PowerOn when importing
* Support stdin as import options source
> govc import.ova improvements

- govc/CHANGELOG.md
- govc/USAGE.md
- govc/flags/datastore.go
- govc/vm/migrate.go
> Add storage support to vm.migrate

- find/finder.go
PR #635 assumed that Finder would not be used without having called SetDatacenter.
However, when the Datastore methods are used with absolute paths and without SetDatacenter,
would cause a panic.
> Avoid Finder panic when SetDatacenter is not called

- govc/emacs/govc.el
@dougm I hope this is useful. I needed it because my gopath is (intentionally) not part of my `exec-path`.
> Add govc-executable-name customization option

- govc/emacs/govc.el
Resolves #647 as discussed with @dougm 
* autoloads `auth-source-search`
* only triggers using it if an entry in `govc-urls` does not have a user portion of the URL, in which case it's looked up as a logical `machine` in the `auth-sources`
* backwards compatible
* documentation updated
* `govc-urls` converted to a `defcustom` for user convenience
> govc.el: auth-source integration

- CHANGELOG.md
- govc/CHANGELOG.md
- govc/USAGE.md
- govc/emacs/README.md
- govc/emacs/govc.el
- govc/logs/command.go
- govc/logs/download.go
- govc/logs/ls.go
- govc/test/logs.bats
- object/diagnostic_log.go
- object/diagnostic_manager.go
- Support logs '-n' > VC/ESX BrowseLog max
- Add DiagnosticLog helper
- Add doc for logs commands
> Add '-f' flag to logs command

- govc/test/test_helper.bash
- govc/vapp/destroy.go
- govc/vapp/power.go
- object/virtual_app.go
Also remove VApp suffix to avoid stutter.
> Remove _Task suffix from vapp methods

- govc/host/esxcli/firewall_info.go
- vim25/types/internal.go
- Add missing error check when calling NewExecutor
- Add RetrieveManagedMethodExecuter to type map
> vcsim: esxcli FirewallInfo fixes

- view/container_view.go
- view/manager.go
This is a similar "wrapper" to ListView but for ContainerView.
> Provides object implementation of the ContainerView object and methods.

- govc/importx/spec.go
> Handle the case where e.VirtualSystem is nil

- govc/datastore/cp.go
- govc/datastore/disk/create.go
- govc/datastore/ls.go
- govc/datastore/mv.go
- govc/datastore/vsan/ls.go
- govc/datastore/vsan/rm.go
- govc/emacs/govc.el
- govc/main.go
- govc/test/clean.sh
- govc/test/datastore.bats
- govc/test/datastore_file_manager_test.sh
- govc/test/test_helper.bash
- govc/test/vm.bats
- govc/vm/disk/create.go
- object/datastore_file_manager.go
- object/host_config_manager.go
- object/host_vsan_internal_system.go
* Add DatastoreFileManager API wrapper
* Add HostVsanInternalSystem API wrappers
* Add govc datastore.disk.create command
* Add govc datastore.vsan.ls and datastore.vsan.rm commands
* Use DatastoreFileManager in govc datastore.rm command
>  Add vsan and disk commands / helpers

- govc/vm/guest/tools.go
- object/virtual_machine.go
> Add vm.guest.tools command

- govc/importx/archive.go
- govc/importx/spec.go
* guard for nil VirtualSystem and Network in envelope
> Add check for nil envelope

- govc/USAGE.md
- govc/emacs/govc.el
- govc/metric/info.go
- govc/metric/sample.go
- govc/test/metric.bats
- performance/manager.go
- If unit type is percent, convert to float type / 100
- Add -json support to metric.info command
- Support govc-metric within the MOB
> Add unit conversion to metric CSV

- scripts/govc_bash_completion
This completion script handles some of the basics such as subcommands and appropriate options for each.  Also supplies path information when working with VMs or listing other objects.
Environment variables for authentication must be set for full functionality.
> Add Bash completion script for govc

- govc/CHANGELOG.md
- govc/vm/ip.go
> Add -wait option to govc vm.ip to allow non-blocking query

- govc/object/collect.go
Embedded fields were already included in the output when given just an object.
But when given the optional object field, embedded fields in that value were
not included in the output.
> Include embedded fields in object.collect output

- govc/host/option/ls.go
- govc/host/option/set.go
- govc/main.go
- govc/option/ls.go
- govc/option/set.go
Refactor host.options commands so they can also be used against vCenter
> Add VC options command

- object/datastore_file.go
This change defines a function that allows a user to supply their own custom `tail` behavior. the original `Tail` method has been replaced by a call to this function supplying the default expected `tail` behavior.
> Allow caller to supply custom tail behavior

- examples/hosts/main.go
- examples/virtualmachines/main.go
> New examples: hosts and virtualmachines. WIP

- govc/test/vm.bats
- govc/vm/change.go
- vim25/types/types.go
The generated omitempty tag was preventing removal.
> Support removal of ExtraConfig entries

- guest/file_manager.go
- vim25/soap/client.go
> Add support for guest.FileManager directory download

- Makefile
- simulator/model.go
- simulator/virtual_machine.go
- simulator/virtual_machine_test.go
PR #752 broke some existing tests in vmware/vic
> vcsim: Fix merging of default devices

- govc/vm/guest/ls.go
- toolbox/command.go
- toolbox/command_test.go
- toolbox/toolbox_darwin.go
- toolbox/toolbox_linux.go
- toolbox/toolbox_windows.go
- Populate symlink target in ListFiles response
- Output symlink target in govc guest.ls
> toolbox: fix ListFiles when given a symlink

- simulator/search_index.go
Fix adds method to search Virtual Machine using UUID
> Add FindByUuid method for Virtual Machine

- govc/importx/lease_updater.go
> Avoid panic if ova import task is canceled

- simulator/datastore.go
- simulator/datastore_test.go
- simulator/file_manager.go
- simulator/folder.go
- simulator/host_datastore_browser.go
- simulator/model.go
- simulator/registry.go
- simulator/service_instance.go
- simulator/virtual_disk_manager.go
- simulator/virtual_disk_manager_test.go
- simulator/virtual_machine.go
- simulator/virtual_machine_test.go
- Create .vmdk files for VirtualDisk devices
- Make use of object.DatastorePath
> vcsim: add FileQuery support to datastore search

- govc/host/storage/info.go
- govc/test/host.bats
- object/host_storage_system.go
> Add '-refresh' option to host.storage.info

- event/manager.go
- govc/datastore/ls.go
- govc/datastore/tail.go
- govc/emacs/govc.el
- govc/flags/datastore.go
- govc/host/info.go
- govc/task/recent.go
- ovf/envelope.go
- scripts/vcsa/create-cluster.sh
- scripts/vcsa/create-esxi-vm.sh
- scripts/vcsa/create-vcsa-vm.sh
- Update vcsa scripts to use 6.5U1
- New govc-shell-mode for Emacs
- Fix host.info memory usage
- Fix EventManager category for EventEx type
> Fixup recent tasks output

- govc/emacs/govc.el
- govc/test/vm.bats
- govc/vm/console.go
> Add vm.console command

- govc/host/esxcli/command.go
- govc/host/esxcli/command_test.go
- govc/host/esxcli/executor.go
- internal/methods.go
- internal/types.go
Move internal methods/types to internal package.
> vim25: Move internal stuff to internal package

- govc/dvs/portgroup/info.go
- govc/test/fields.bats
- govc/test/network.bats
- object/distributed_virtual_switch.go
- simulator/custom_fields_manager.go
- simulator/custom_fields_manager_test.go
- simulator/dvs.go
- simulator/dvs_test.go
- simulator/portgroup.go
- simulator/portgroup_test.go
- simulator/service_instance.go
- Add CustomFieldsManager
- Add Portgroup related operations
> Implement missing features in vcsim

- license/manager.go
- simulator/license_manager.go
- simulator/license_manager_test.go
> vcsim: Implement license add/remove

- govc/test/host.bats
- simulator/host_system.go
- simulator/host_system_test.go
> vcsim: Implement enter/exit maintenance mode

- govc/cli/command.go
- govc/test/logs.bats
- vim25/soap/client.go
> Add support for SOAP request operation ID header

- simulator/virtual_machine.go
- The "state" property being empty caused parse errors with pyvmomi
- Increment the "id" as it is documented to be unique per vm
- Set "createTime" to the current time
- Set "quiesced" from the request param
Fixes #859
> vcsim: populate vm snapshot fields

- govc/test/role.bats
- simulator/authorization_manager.go
- simulator/esx/authorization_manager.go
- simulator/service_instance.go
Initial AuthorizationManager support for querying roles and permissions.
Towards #860
> vcsim: add AuthorizationManager

- simulator/virtual_machine.go
- simulator/virtual_machine_test.go
During CreateVM task, if adding a virtual disk device and the filename
is not specified, try to generate a filename, as opposed to throw an
error. This is to mimic the ESX server behavior.
Fixes #863
> vcsim: Generate device filename in CreateVM

- govc/test/role.bats
- simulator/authorization_manager.go
> vcsim: Implement add/update/remove roles

- govc/test/metric.bats
- simulator/esx/performance_manager.go
- simulator/performance_manager.go
- simulator/service_instance.go
Adds the generated perfCounter property.
> vcsim: add PerformanceManager

- govc/events/command.go
I was trying to use the `-json` flag that shows up in `govc events --help`, but wasn't seeing it being used. This patch formats each event as a new json object per line.
I'd be happy to hop on the slack as this patch probably doesn't meet the project requirements.
> govc/events: read -json flag and output events as json

- simulator/ip_pool_manager.go
- simulator/ip_pool_manager_test.go
- simulator/service_instance.go
IpPoolManager doesn't support creating ip pools for now. It has a predefined ipv4 and ipv6 pool and as pool id 1. It will allocate IP address inside that pool. 
Towards #800
> vcsim: Add IpPoolManager

- govc/test/role.bats
- simulator/authorization_manager.go
The privilege list is static, add check that the IDs are valid.
Fold the System.* ID merging into the validation loop.
> vcsim: validate authz privilege ids

- govc/importx/archive.go
- govc/importx/ova.go
- govc/importx/ovf.go
- govc/importx/spec.go
> Support import ova/ovf by URL

- simulator/virtual_machine.go
> vcsim: Add moref to vm's summary

- simulator/host_datastore_system.go
- simulator/registry.go
> vcsim: Generate similar ref value like VC

- govc/vm/clone.go
> govc: Fix VM clone when source doesn't have vNics

- govc/object/collect.go
- govc/test/device.bats
- govc/test/object.bats
- govc/test/test_helper.bash
- simulator/cluster_compute_resource.go
- simulator/dvs.go
- simulator/esx/host_config_info.go
- simulator/esx/host_storage_device_info.go
- simulator/folder.go
- simulator/host_system.go
- simulator/property_collector.go
- simulator/registry.go
- simulator/virtual_machine.go
> vcsim: various property additions

- govc/test/vcsim.bats
- govc/test/vcsim_test.rb
- simulator/session_manager.go
- simulator/simulator.go
> vcsim: use soapenv namespace for Fault types

- README.md
Add installation procedure in README.md for user
> Add installation procedure in README.md

- simulator/ip_pool_manager.go
- simulator/ip_pool_manager_test.go
For simplicity, we don't allow to update an IP Pool which already
allocates IP addresses. It will return a runtime error.
Fixes #800
> vcsim: Implement IpPoolManager lifecycle

- simulator/cluster_compute_resource.go
- simulator/dvs.go
- simulator/entity.go
- simulator/file_manager.go
- simulator/folder.go
- simulator/host_datastore_browser.go
- simulator/host_system.go
- simulator/portgroup.go
- simulator/resource_pool.go
- simulator/snapshot.go
- simulator/task.go
- simulator/virtual_disk_manager.go
- simulator/virtual_machine.go
Helps to make related code (and examples) a bit more concise.
> vcsim: return moref from Task.Run

- govc/test/vm.bats
- govc/vm/upgrade.go
- object/virtual_machine.go
Related to https://kb.vmware.com/s/article/1010675
> Implemented vm.upgrade operation.

- govc/dvs/add.go
- govc/test/network.bats
- simulator/folder.go
> vcsim: Configure dvs with the dvs config spec

- simulator/authorization_manager.go
- simulator/authorization_manager_test.go
> vcsim: copy RoleList for AuthorizationManager

- govc/datastore/disk/inflate.go
- govc/datastore/disk/shrink.go
- govc/test/datastore.bats
- object/virtual_disk_manager.go
> Add datastore.disk inflate and shrink commands

- govc/flags/client.go
If no username is provided, the govc client tries to acquire a local ticket.
When invoked remotely, ESX returns an InvalidRequestFault (VC returns NotSupportedFault).
So, rather than return an error here, fallthrough to Login() with the original User to
to avoid what would be a confusing error message.
Don't try AcquireLocalTicket at all against vCenter as it is unsupported.
Fixes #952
> Ignore AcquireLocalTicket errors

- simulator/host_local_account_manager.go
- simulator/registry.go
- simulator/user_directory.go
AccountManager should deal with the users in UserDirectory.
> Hook AccountManager to UserDirectory

- govc/host/storage/info.go
- govc/test/host.bats
- object/host_storage_system.go
Add '-refreshvmfs' option to host.storage.info
> Add '-rescan-vmfs' option to host.storage.info

- govc/session/ls.go
Avoids negative time deltas in the case of clock skew between ESX/VC and the client host.
> User server clock in session.ls

- simulator/virtual_machine.go
> vcsim: more input spec honored in ReConfig VM

- govc/test/vm.bats
- simulator/virtual_machine.go
- simulator/virtual_machine_test.go
> vcsim: Add VM.MarkAsTemplate support

- object/host_storage_system.go
Added AttachScsiLun function to host_storage_system
> Added AttachScsiLun function

- scripts/vcsa/README.md
- scripts/vcsa/create-cluster.sh
- scripts/vcsa/create-esxi-vm.sh
- scripts/vcsa/create-vcsa-vm.sh
> Bump vcsa scripts to use 6.5U1 EP5

- govc/option/set.go
- simulator/option_manager.go
- simulator/option_manager_test.go
- simulator/vpx/setting.go
> vcsim: add UpdateOptions support

- govc/datastore/disk/cp.go
- govc/datastore/disk/create.go
- govc/test/datastore.bats
> Add datastore.disk.cp command

- govc/flags/cluster.go
- govc/license/assign.go
> govc: add -cluster flag to license.assign command

- simulator/simulator.go
- simulator/virtual_machine.go
No need to keep it open as we only log a few messages per VM.
Fixes #988
> vcsim: avoid keeping the VM log file open

- simulator/model.go
- simulator/virtual_disk_manager.go
- simulator/virtual_machine.go
- simulator/virtual_machine_test.go
Required for testing VirtualDisk attach and detach
> vcsim: respect VirtualDeviceConfigSpec FileOperation

- simulator/virtual_machine.go
> Fix broken datastore link in VM

- .travis.yml
- simulator/os_unix.go
> Fix build on Windows

- simulator/dvs.go
- simulator/host_system.go
- simulator/host_system_test.go
- Implement Destroy task for HostSystem
-  nit PortKeys in DistributedVirtualPortgroup
> Issues 1039 979

- govc/USAGE.md
- govc/usage.sh
Found good example of toc using markdown here:
https://stackoverflow.com/a/448929/1572363
> Print Table of Contents in usage.md for govc

- simulator/event_manager.go
- simulator/event_manager_test.go
> vcsim: add EventManager.QueryEvents

- govc/vm/create.go
Without this option it is not possible to specify that a VM should use
EFI instead of BIOS as firmware type.
The default behaviour (using BIOS) is unchanged.
fixes #1071
> Add -firmware parameter to 'govc vm.create'

- govc/host/esxcli/esxcli.go
> govc: fix host.esxcli error handling

- govc/object/find.go
- govc/test/object.bats
> govc: add json support to find command

- gen/gen.sh
- govc/flags/client.go
- govc/main.go
- govc/session/login.go
- govc/sso/user/create.go
- govc/sso/user/id.go
- govc/sso/user/ls.go
- govc/sso/user/rm.go
- govc/sso/user/update.go
- ssoadmin/client.go
- ssoadmin/client_test.go
- ssoadmin/methods/methods.go
- ssoadmin/methods/role.go
- ssoadmin/types/role.go
- ssoadmin/types/types.go
- sts/client_test.go
- sts/signer.go
- vim25/client.go
- Add ssoadmin.Client for managing users
- Add govc sso.user id, ls, create, update, rm commands
- Use ssoadmin in sts tests to create solution user
Fixes #807
>  Add ssoadmin client and commands

- govc/test/object.bats
- property/filter.go
> Avoid property.Filter matching against unset properties

- govc/test/object.bats
- simulator/property_collector.go
> vcsim: add property collector field type mapping for integer arrays

- object/virtual_device_list.go
- object/virtual_device_list_test.go
> Add vmxnet2, pcnet32 and sriov to VirtualDeviceList.EthernetCardTypes

- simulator/virtual_machine.go
> vcsim: use VirtualDisk CapacityInKB for device summary

- simulator/virtual_machine.go
- simulator/virtual_machine_test.go
Also add one test case to check number of disk and format of disk summary
> save CapacityInKB in thousand delimited format

- govc/session/login.go
- govc/test/session.bats
- sts/client.go
- sts/simulator/simulator.go
- vcsim/main.go
Just enough for Renew and Issue requests to return a token for use with
simulator.SessionManager.LoginByToken
- Add govc session.login '-renew' flag
> vcsim: add STS simulator

- simulator/search_index.go
- simulator/search_index_test.go
added check for `InstanceUuid` when `VmSearch` is true in `FindByUuid`
> added check for `InstanceUuid` when `VmSearch` is true in `FindByUuid`

- govc/emacs/govc.el
- govc/flags/client.go
- govc/sso/service/ls.go
- govc/test/session.bats
- govc/test/sso.bats
- scripts/devbox/.gitignore
- scripts/devbox/README.md
- scripts/devbox/create.sh
- scripts/devbox/provision.sh
- scripts/devbox/vcp-local-up-cluster.sh
- scripts/vcsa/README.md
- scripts/vcsa/create-cluster.sh
- scripts/vcsa/create-esxi-vm.sh
- scripts/vcsa/create-standalone.sh
- scripts/vcsa/create-vcsa-vm.sh
Scripts for running local development binaries on a vSphere VM.
Includes a few related fixes for using govc sso.service.ls in dev environments.
> Add devbox scripts

- govc/test/vm.bats
- govc/vm/disk/attach.go
- govc/vm/disk/change.go
- govc/vm/disk/create.go
> Add -sharing option to vm.disk.create and vm.disk.attach

- examples/hosts/main.go
fix example output.
Signed-off-by: CuiHaozhi <cuihaozhi@chinacloud.com.cn>
> fix example output.

- object/virtual_machine.go
> Add UUID helper for VirtualMachine MO

- simulator/esx/event_manager.go
- simulator/virtual_machine.go
- simulator/virtual_machine_test.go
> vcsim: add ResetVM and SuspendVM support

- performance/manager.go
remove providerSummary cache from Manager struct and ProviderSummary method
> remove providerSummary cache

- object/search_index_test.go
> fix double err check

- govc/dvs/portgroup/info.go
Firewall rule action was accidentally missed in #1210 PR.
> govc: Print action for dvs security groups

- simulator/dvs.go
- simulator/dvs_test.go
> vcsim: add dvpg networks to HostSystem.Parent

- govc/main.go
- govc/vm/guest/download.go
- govc/vm/guest/guest.go
- govc/vm/info.go
- govc/vm/upgrade.go
- object/datastore.go
- simulator/folder.go
- simulator/resource_pool_test.go
- simulator/session_manager.go
- simulator/virtual_machine.go
Changes by the latest version of goimports.
> goimports updates

- simulator/event_manager.go
- simulator/event_manager_test.go
Adds ReadNextEvents, ReadPreviousEvents and ResetCollector methods to EventHistoryCollector
Fixes #1239
> vcsim: add HistoryCollector scrollable view support

- simulator/custom_fields_manager_test.go
Fixes `custom_fields_manager_test.go` test `TestCustomFieldsManager`. It was trying to set a value to custom field that did not exist.
Related #1270
> vcsim: fix custom_fields_manager test

- govc/disk/snapshot/rm.go
- govc/test/disk.bats
- simulator/service_instance.go
- simulator/session_manager.go
- simulator/simulator.go
- simulator/vstorage_object_manager.go
- Add First Class Disk support to vcsim
- Convert disk.bats tests to use vcsim
Fixes #1269
> vcsim: add vslm support

- vcsim/main.go
> vcsim: replace HostSystem template IP with vcsim listen address

- simulator/file_manager.go
- simulator/virtual_machine.go
- simulator/virtual_machine_test.go
> vcsim: fix defaults when generating vmdk paths

- govc/tags/info.go
- govc/test/tags.bats
> Display category name instead of ID in govc tags.info

- .travis.yml
- govc/test/test_helper.bash
- govc/test/vcsim.bats
- simulator/folder.go
> vcsim: add datastore access check for vm host placement

- README.md
- govc/datastore/cluster/change.go
- govc/datastore/cluster/info.go
- govc/disk/create.go
- govc/main.go
- govc/test/datastore.bats
- govc/test/disk.bats
- govc/test/vm.bats
- scripts/devbox/provision.sh
- simulator/folder.go
- simulator/service_instance.go
- simulator/storage_resource_manager.go
- vslm/object_manager.go
- Add vslm.ObjectManager.PlaceDisk method
- Add vcsim support for StorageResourceManager
- Add -datastore-cluster flag to disk.create command
- Add govc datastore.cluster info and change commands
Fixes #740
> Datastore Cluster placement support for First Class Disks

- govc/vm/power.go
This patch adds the `wait` flag to the `vm.power` command in order to make waiting on operations to complete optional. The `wait` flag has a default value of `true` in order to maintain the prior behavior of the power operations.
> vm.power: Make waiting for op completion optional

- pbm/simulator/profiles.go
- pbm/simulator/simulator.go
- pbm/simulator/simulator_test.go
- vcsim/main.go
> vcsim: add PBM support

- govc/test/vm.bats
- govc/vm/create.go
- simulator/esx/setting.go
- simulator/virtual_machine.go
- vcsim: add config.version validation
- vcsim: add UpgradeVM_Task support
Fixes #1240
Fixes #1304
> govc: add vm.create -version option

- simulator/property_collector.go
- simulator/property_collector_test.go
> vcsim: PropertyCollector should not require PathSet

- govc/test/vcsim.bats
- simulator/cluster_compute_resource.go
- simulator/entity.go
- simulator/property_filter.go
> vcsim: support base types in property filter

- simulator/simulator.go
The Detail.Fault field was coded with the field name "Fault",
when it should be "${TypeOfFault}Fault".
This wasn't an issue for Go clients, as the soap.Fault is tagged with
xml:,any - so the name is ignored and only the xsi type is needed.
Fixes #1261
> vcsim: fix fault detail encoding

- govc/vm/keystrokes.go
- govc/vm/putusbscancodes.go
- object/virtual_machine.go
This adds this capability to govc: https://www.virtuallyghetto.com/2017/09/automating-vm-keystrokes-using-the-vsphere-api-powercli.html
> Added Support for PutUsbScanCodes on each VM

- ssoadmin/client.go
Make ssoadmin to support `CREATE GROUP` and `Add Users To Group`.
> ssoadmin:create local group and add users to group

- govc/device/info.go
- govc/device/ls.go
device.ls -json doesn't work for now
issue related: https://github.com/vmware/govmomi/issues/1328
for now, a *flags.VirtualMachineFlag includes *flags.DatacenterFlag,
which in turn includes *flags.OutputFlag. Therefore, "govc device.ls
-help" contains this entry "-json=false           Enable JSON output
" below "Options:""
However, current implementation is missing.
Before this PR, we have:
```
kubo@jumper:~$ govc device.ls -vm.ip=30.1.0.3 -json
ide-200        VirtualIDEController       IDE 0
ide-201        VirtualIDEController       IDE 1
ps2-300        VirtualPS2Controller       PS2 controller 0
pci-100        VirtualPCIController       PCI controller 0
sio-400        VirtualSIOController       SIO controller 0
keyboard-600   VirtualKeyboard            Keyboard
pointing-700 …
```
> Fix device.ls json flag

- vim25/soap/client.go
Fix of https://github.com/vmware/govmomi/issues/1335
> Fix of the missing http body close under soap client upload

- govc/test/vcsim.bats
- simulator/host_system.go
- vcsim/main.go
- Set summary.config.port to vcsim's listen port
- Optionally increment host port if VCSIM_HOST_PORT_UNIQUE=true
Fixes #1311
> vcsim: configure HostSystem port

- govc/flags/datacenter.go
- govc/object/collect.go
- govc/tags/association/attach.go
> govc: fix object.collect error for multiple objects with same path

- govc/license/label.go
- govc/main.go
- govc/test/license.bats
- govc/test/vm.bats
- govc/vm/option/info.go
- simulator/cluster_compute_resource.go
- simulator/environment_browser.go
- simulator/folder.go
- simulator/host_system.go
- simulator/license_manager.go
- govc: add vm.option.info command
- vcsim: add LicenseManager.UpdateLicenseLabel support
- govc: add license.label.set command
Fixes #1345
> vcsim: add EnvironmentBrowser support

- govc/test/vcsim.bats
- vapi/simulator/simulator.go
> vcsim: require authentication in vapi simulator

- .mailmap
- CHANGELOG.md
- CONTRIBUTORS
- govc/CHANGELOG.md
- govc/USAGE.md
- govc/build.sh
- govc/flags/version.go
- govc/object/collect.go
- govc/vm/destroy.go
- govc/vm/disk/attach.go
- govc/vm/network/change.go
- object/common.go
- property/collector.go
Fixes #795
Fixes #1181
Fixes #1201
Fixes #1291
Fixes #1359
Fixes #1366
> Update docs for 0.20 release

- govc/export/ovf.go
- govc/host/cert/install.go
- govc/importx/archive.go
- govc/vm/console.go
- govc/vm/disk/create.go
- govc/vm/guest/auth.go
- govc/vm/guest/ls.go
- govc/vm/guest/run.go
- govc/vm/guest/upload.go
- govc/vm/network/add.go
- govc/vm/network/change.go
- govc/vm/vnc.go
- session/keep_alive.go
- simulator/file_manager.go
- simulator/virtual_machine.go
- simulator/vstorage_object_manager.go
- toolbox/hgfs/archive.go
- toolbox/hgfs/server.go
- vcsim/main.go
- vim25/soap/client.go
- vmdk/import.go
Hi @dougm,
I fixed some trivial [gosec](https://github.com/securego/gosec) issues here. There are many issues more, that I could be fixing later.
> Fix gosec issues

- govc/vcenter/deploy.go
use both folder to support customize
vm folder  in content library ovf deploy
cc @dougm
> support customize vm folder in ovf deploy

- govc/cluster/rule/ls.go
- govc/disk/rm.go
- govc/dvs/portgroup/info.go
- govc/object/collect.go
- govc/vm/network/add.go
- govc/vm/network/change.go
- object/diagnostic_manager.go
- object/virtual_device_list_test.go
- ovf/env.go
- simulator/datastore_test.go
- simulator/host_datastore_browser.go
- test/functional/helper.go
- toolbox/command.go
- toolbox/hgfs/server_test.go
- toolbox/process_test.go
- toolbox/vix/protocol.go
- units/size_test.go
- vapi/library/finder/finder.go
Hi @dougm,
PTAL, I fixed here some **staticcheck** and **gosimple** issues.
> Fix some staticcheck and gosimple issues

- client_test.go
- find/finder.go
- govc/cluster/rule/ls.go
- govc/datastore/ls.go
- govc/vm/keystrokes.go
- object/datastore_file.go
- object/datastore_path.go
- simulator/entity_test.go
- simulator/performance_manager.go
- sts/internal/types.go
- toolbox/command.go
- toolbox/vix/property.go
Hi @dougm,
I fixed some trivial [gocritic](https://github.com/go-critic/go-critic) issues here.
> Fix some gocritic issues

- simulator/folder.go
- simulator/virtual_machine_test.go
> vcsim: set guest.toolsRunningStatus property

- govc/library/item/upload.go
- govc/test/library.bats
- scripts/debug-xmlformat.sh
- vapi/internal/internal.go
- vapi/library/finder/finder.go
- vapi/library/library.go
- vapi/library/library_item.go
- vapi/library/library_item_updatesession.go
- vapi/simulator/simulator.go
- vim25/soap/client.go
Other changes:
- Fix json marshalling of library find results
- Rename library.FindLibraryRequest to library.Find
- Rename library.FindLibraryItemsRequest to library.FindItem
- Set User-Agent in service clients
- Add json support to debug-xmlformat.sh
> vcsim: add content library support

- govc/datastore/cluster/info.go
> govc: add datastore.cluster.info Description

- govc/permissions/remove.go
> govc: add permission.remove -f flag

- govc/option/set.go
> govc: fix option.set for int32 type values

- govc/vm/change.go
> govc: add vm.change vpmc-enabled flag

- object/virtual_machine.go
> Add error check to VirtualMachine.WaitForNetIP

- examples/datastores/main.go
- examples/hosts/main.go
- examples/networks/main.go
Just updating the others examples to use examples.Run method.
> Update examples to use examples.Run method

- gen/gen.sh
- vslm/methods/methods.go
- vslm/types/enum.go
- vslm/types/if.go
- vslm/types/types.go
New First Class Disk related APIs added in 6.7U2
> Add generated vslm types and methods

- govc/test/vcsim.bats
- simulator/folder.go
- simulator/host_system.go
- simulator/object.go
- simulator/virtual_machine.go
> vcsim: use stable UUIDs for inventory objects

- govc/vm/guest/ps.go
> govc: increase guest.ps -X poll interval

- govc/logs/download.go
> govc: change logs.download -default=false

- govc/library/export.go
- govc/library/import.go
- govc/library/session/ls.go
- govc/library/session/rm.go
- govc/test/library.bats
- vapi/internal/internal.go
- vapi/library/library_item_downloadsession_file.go
- vapi/library/library_item_updatesession.go
- vapi/rest/client.go
- vapi/simulator/simulator.go
- vapi/vcenter/vcenter_ovf.go
- Add govc library.export command
- Add library Download Session support
- Rename library 'UpdateSession' to 'Session', same structure for download sessions
- Move vcenter.LocalizableMessage to rest package
> Add library export support

- govc/vm/change.go
> govc: add vm.change hot-add options

- lookup/client.go
- lookup/client_test.go
- lookup/simulator/simulator_test.go
- sts/simulator/simulator.go
> Support external PSC lookup service

- govc/flags/client.go
- govc/test/vcsim.bats
- session/manager.go
- simulator/session_manager.go
- simulator/simulator.go
- vcsim/main.go
> vcsim: add support to override credentials

- govc/flags/client.go
> govc: add context to LoadX509KeyPair error

- govc/main.go
- govc/sso/client.go
- govc/sso/group/create.go
- govc/sso/group/ls.go
- govc/sso/group/rm.go
- govc/sso/group/update.go
- govc/sso/user/create.go
- govc/sso/user/id.go
- govc/sso/user/update.go
- ssoadmin/client.go
> govc: add sso.group commands

- govc/host/vnic/info.go
- govc/test/host.bats
> govc: host.vnic.info -json support

- performance/example_test.go
Creates a new performance example in Go's example style as the others in PR #1505.
> Add govmomi performance example

- govc/datastore/info.go
- govc/flags/datacenter.go
- govc/object/collect.go
- govc/test/datastore.bats
Display info for Datastores shared between hosts
- Add -d flag to object.collect command
> govc: add datastore.info -H flag

- simulator/host_datastore_system.go
Set host datstore as accessible while creating it.
> govcsim: Create datastore as accessible

- object/example_test.go
> examples: add CustomFieldManager.Set

- vslm/global_object_manager.go
> ExtendDisk task is missing the NewCapacityInMB field

- simulator/dvs.go
- simulator/folder.go
> govcsim: Support Default UplinkTeamingPolicy in DVSPG

- govc/tags/association/attach.go
- govc/tags/association/detach.go
- govc/tags/association/ls.go
- govc/test/library.bats
> govc: support library paths in tags.attach commands

- vapi/library/library_item_updatesession_file.go
- Fix invalid fingerprint format (use soap.ThumbprintSHA1)
- Only include fingerprint already trusted by the client or InsecureSkipVerify=true
> Fix library AddLibraryItemFileFromURI fingerprint

- govc/vm/guest/df.go
> govc: add guest.df command

- object/example_test.go
> examples: add ExampleVirtualMachine_Reconfigure

- vapi/library/finder/finder.go
> Don't limit library.Finder to local libraries

- pbm/client.go
Added the FetchCapabilityMetadata method to the client using existing API bindings
> Add FetchCapabilityMetadata method to Pbm client

- vcsim/README.md
Update broken link to the VMware vSphere API Reference of vcsim README.md.
> Update vcsim Readme.md

- govc/flags/datacenter.go
PR #1509 added support for raw ManagedObjectReference, but did not account for Name including a ':'
> govc: validate moref argument

- object/virtual_machine.go
Added a method object.VirtualMachine.QueryChangedDiskAreas() that lists differences between two snapshot of a disk.
> Add VirtualMachine.QueryChangedDiskAreas().

- object/example_test.go
- object/resource_pool.go
> Add ResourcePool.Owner method

- object/example_test.go
> examples: add VirtualMachine.CreateSnapshot

- govc/vm/guest/auth.go
-i Interactive Session for Guest Services
> Add interactiveSession flag

- simulator/session_manager.go
- simulator/view_manager.go
- simulator/view_manager_test.go
> vcsim: avoid race in ViewManager

- simulator/simulator.go
- vapi/internal/internal.go
- vapi/library/library.go
- vapi/library/library_file.go
- vapi/library/library_item.go
- vapi/library/library_item_downloadsession_file.go
- vapi/library/library_item_updatesession.go
- vapi/library/library_item_updatesession_file.go
- vapi/rest/client.go
- vapi/rest/resource.go
- vapi/simulator/simulator.go
- vapi/tags/categories.go
- vapi/tags/tag_association.go
- vapi/tags/tags.go
- vapi/vcenter/vcenter_ovf.go
- Support vapi/simulator extensions
- Move useful internal client helpers to the rest package
> vapi: refactor for external API implementations

- vapi/library/library.go
> vapi: support DeleteLibrary with subscribed libraries

- govc/test/object.bats
- simulator/virtual_machine.go
> vcsim: add VirtualMachine.Rename_Task support

- govc/cli/command.go
Was getting annoyed by typoing govc commands and only getting a giant list returned and having to scroll and find what I wanted.
example usage
```➜  govc git:(cmd-list-filter) ./govc-dev tags
Usage of ./govc-dev filtered by tags
disk.tags.attach
disk.tags.detach
tags.attach
tags.attached.ls
tags.category.create
tags.category.info
tags.category.ls
tags.category.rm
tags.category.update
tags.create
tags.detach
tags.info
tags.ls
tags.rm
tags.update
```
> add simple command list filter

- govc/object/save.go
- govc/test/object.bats
- govc/test/vcsim.bats
- simulator/authorization_manager.go
- simulator/custom_fields_manager.go
- simulator/datacenter.go
- simulator/event_manager.go
- simulator/file_manager.go
- simulator/folder.go
- simulator/host_local_account_manager.go
- simulator/ip_pool_manager.go
- simulator/license_manager.go
- simulator/model.go
- simulator/option_manager.go
- simulator/ovf_manager.go
- simulator/performance_manager.go
- simulator/search_index.go
- simulator/service_instance.go
- simulator/session_manager.go
- simulator/storage_resource_manager.go
- simulator/task_manager.go
- simulator/user_directory.go
- simulator/view_manager.go
- simulator/virtual_disk_manager.go
- simulator/vstorage_object_manager.go
- vcsim/README.md
- vcsim/main.go
- vim25/mo/fixtures/cluster_host_property.xml
- vim25/mo/retrieve.go
- vim25/mo/retrieve_test.go
Remove New* funcs as Model.Load will construct via reflection
Move any remaining New* logic to init() methods call regardless of
using Model.Load or Model.Create
> vcsim: add record/playback functionality

- simulator/feature_test.go
- vcsim/README.md
- Feature details moved to the wiki
- Formatted to be markdown lint clean
> vcsim: update docs

- govc/flags/list.go
- govc/test/vm.bats
- govc/vm/customize.go
- simulator/customization_spec_manager.go
- simulator/model.go
- simulator/virtual_machine.go
vcsim: add CustomizationSpecManager support
> govc: add vm.customize command

- govc/vm/power.go
> govc: add vm.power doc

- session/keep_alive_test.go
The tests were not run unless GOVMOMI_TEST_URL was set to a real vCenter.
> Refactor session KeepAlive tests to use vcsim

- vapi/simulator/simulator.go
This helper will be useful for upcoming changes.
> vcsim: add vim25 client helper to vapi simulator

- vapi/library/library.go
Follow up to #1700 and #1702
Default thumbprint to soap.Client's db (-tls-known-hosts)
Otherwise, set thumbprint to that of the subscription URL host if -k/GOVC_INSECURE is true.
> govc: add default library.create thumbprint

- govc/test/network.bats
- simulator/dvs.go
> vcsim: properly initialize portgroup portKeys field

- govc/USAGE.md
- govc/vm/info.go
> govc: add doc on vm.info -r flag

- object/search_index.go
Some methods are missing: https://code.vmware.com/apis/358/vsphere/doc/vim.SearchIndex.html
Not anymore!
> Implement some missing methods ("*All*" variants) on SearchIndex MOB

- object/customization_spec_manager.go
- object/example_test.go
> Add CustomizationSpecManager.Info method and example

- govc/vm/create.go
> govc: fix vm.create doc regarding -on flag

- govc/datacenter/create.go
> govc: add datacenter create/delete examples

- object/example_test.go
> examples: add VirtualMachine.Customize

- govc/device/boot.go
> govc: add device.boot -secure flag

- object/example_test.go
- simulator/datacenter.go
> examples: add Common.Rename

- govc/cli/register.go
- govc/library/checkin.go
- govc/library/checkout.go
- govc/library/clone.go
- govc/library/deploy.go
- govc/library/info.go
- govc/test/library.bats
- vapi/internal/internal.go
- vapi/simulator/simulator.go
- vapi/vcenter/vcenter_vmtx.go
- Add vapi and vcsim support for VM Template (aka vmtx) related APIs
- Add govc library.clone command
- Add vmtx support to govc library.deploy command
> Content Library: VM Template support

- govc/test/vcsim.bats
- simulator/container.go
- simulator/container_test.go
- simulator/object.go
- simulator/virtual_machine.go
For use within container simulated VMs
Fixes #1709
> vcsim: bind mount BIOS UUID DMI files

- simulator/container.go
I was experimenting with putting a simulated VM container on a non-default network, and vcsim didn't get its IP address, so I've put together this fix.
> vcsim: Get IP address on non-default container network

- performance/example_test.go
> examples: output VM names in performance example

- govc/host/esxcli/esxcli.go
- govc/host/esxcli/response.go
> govc: handle xsd:string responses

- govc/vm/guest/run.go
- guest/toolbox/client.go
By default, guest.run will now use in-guest temporary files for
process I/O.  The new -T flag switches to the original behavior
that depends on govmomi/toolbox running in the guest.
Fixes #1593
Fixes #1514
> govc: remove guest.run toolbox dependency

- object/distributed_virtual_switch.go
- object/distributed_virtual_switch_test.go
> Clarify DVS EthernetCardBackingInfo error message

- CHANGELOG.md
- govc/CHANGELOG.md
- govc/flags/version.go
> Release version 0.22.1

- govc/object/find.go
- govc/test/object.bats
Includes object type in the output.
> govc: add find -l flag

- govc/library/cp.go
- govc/test/library.bats
- vapi/library/library_item.go
- vapi/simulator/simulator.go
- Add library.Manager.CopyLibraryItem client API
- Add vcsim support
- Add govc library.cp command
> Add Content Library item copy support

- govc/flags/folder.go
- govc/test/vm.bats
- govc/vm/migrate.go
- simulator/virtual_machine.go
- Add '-folder' flag to govc vm.migrate command
Fixes #1849
> vcsim: support Folder in RelocateVM spec

- govc/test/vm.bats
- simulator/virtual_machine.go
- simulator/virtual_machine_test.go
Add test and fix for 488205f
Fixes #1854
> vcsim: create vmdk directory if needed

- govc/sso/group/update.go
- ssoadmin/client.go
- Add '-g' flag to support nested groups
- Find{User,Group} can return nil,nil, check to avoid panic.
Fixes #1861
> govc: support nested groups in sso.group.update

- govc/test/object.bats
- property/filter.go
- simulator/virtual_machine.go
> Avoid possible panic in Filter.MatchProperty

- govc/vm/customize.go
> reset all for recursive calls

- govc/flags/client.go
Signed-off-by: Matt Moore <mattmoor@vmware.com>
> Remove extra err check

- govc/importx/spec.go
- govc/test/import.bats
The import.ovf and import.ova already support http/https, but import.spec only worked with local files.
> govc: add import.spec support for remote URLs

- govc/test/vm.bats
- govc/vm/change.go
> govc: add vm.change -uuid flag

- govc/vm/guest/download.go
- govc/vm/guest/upload.go
> govc: add guest directory upload/download examples

- govc/test/vm.bats
- simulator/environment_browser.go
- simulator/virtual_machine.go
> vcsim: support QueryConfigOptionEx GuestId param

- govc/object/find.go
It is possible for objects to be deleted after ContainerView.Find has returned.
In which case the inventory path lookup can result in ManagedObjectNotFound.
Ignore objects in this case, instead of returning an error.
Fixes #1908
> govc: ignore ManagedObjectNotFound errors in 'find' command

- govc/flags/client.go
- govc/session/ls.go
- govc/test/session.bats
Include current REST session (if any)
> govc: add session.ls -r flag

- govc/vm/clone.go
* skip starting the VM when -template flag is selected
* update documentation to include template clone example
resolves  #1900
> govc: improved vm.clone for templates

- govc/session/login.go
- govc/test/session.bats
- vapi/rest/client.go
Supports curl-like interaction with an authenticated SOAP and/or REST session.
> govc: add session.login -X flag

- govc/object/save.go
- govc/test/vcsim.bats
> vcsim: traverse configManager.networkSystem in object.save

- simulator/authorization_manager.go
> vcsim: add AuthorizationManager.HasPrivilegeOnEntities

- govc/datastore/create.go
> govc: add -version flag to datastore.create command

- simulator/folder.go
- simulator/virtual_machine.go
This PR fixes 3 data races that manifest themselves when creating VMs concurrently.
> fix a few data races when creating VMs concurrently

- govc/object/find.go
- govc/test/object.bats
- property/filter.go
> govc: support find with -customValue filter

- simulator/folder.go
- simulator/resource_pool.go
- simulator/view_manager.go
This PR reduces the dependency to exact types in the simulator operations implementation.
> simulator: relax some typing constraints

- lookup/simulator/simulator.go
Previously, registration was only being done once because the
atomic used was a package variable.  That meant the lookupservice
would only register once for the life of the process.  This isn't
ideal for use in unit-tests which start and stop the simulator
for each test.  Subsequent tests wouldn't register the lookup
service and fail.
> Move simulator lookupservice registration into ServiceInstance

- README.md
- govc/flags/version.go
- govc/test/cli.bats
- govc/vm/create.go
- vim25/client.go
- Change vim25.Version default to 7.0
- Add govc vm.create -version alias
- Update docs
> Bump to vSphere version 7

- .mailmap
- .travis.yml
- CHANGELOG.md
- CONTRIBUTORS
- README.md
- govc/CHANGELOG.md
- govc/README.md
- govc/USAGE.md
- govc/host/esxcli/esxcli.go
- govc/object/save.go
- govc/session/login.go
- govc/usage.sh
- govc/vm/guest/run.go
- vcsim/README.md
Fixes #1840
Fixes #1923
Fixes #1149
> Update docs for 0.23 release

- pbm/simulator/simulator.go
> vcsim: add PbmQueryAssociatedProfile method

- simulator/host_network_system.go
- simulator/host_network_system_test.go
> vcsim: add HostNetworkSystem.QueryNetworkHint

- govc/main.go
- govc/namespace/cluster/ls.go
- govc/test/namespace.bats
- vapi/namespace/internal/internal.go
- vapi/namespace/namespace.go
- vapi/namespace/simulator/simulator.go
- vapi/rest/client.go
- vapi/simulator/simulator.go
- vcsim/main.go
- govc: add namespace.cluster.ls command
- vapi: add namespace management client and vcsim support
- vapi: add helper support "/api" endpoint
> vapi: add initial support for namespace management

- vapi/library/example_test.go
> vapi: add Content Library example

- vslm/object_manager.go
> Add ExtendDisk and InflateDisk wrappers to vlsm/object_manager

- govc/host/esxcli/command.go
> govc: support multi value flags in host.esxcli command

- govc/vm/console.go
> govc: add vm.console -wss flag

- govc/main.go
- govc/storage/policy/create.go
- govc/storage/policy/info.go
- govc/storage/policy/ls.go
- govc/storage/policy/rm.go
- govc/test/storage.bats
- pbm/client.go
- pbm/simulator/simulator.go
> govc: add storage.policy commands

- cns/simulator/simulator.go
- govc/main.go
- govc/test/volume.bats
- govc/volume/ls.go
- govc/volume/rm.go
- vcsim/main.go
> govc: add CNS volume ls and rm commands

- govc/vm/disk/change.go
> govc: support sparse backing in vm.disk.change

- examples/events/main.go
- examples/examples.go
Also use govc's session cache for the examples client.
> examples: add events

- view/example_test.go
> examples: add ContainerView retrieve clusters

- simulator/virtual_machine.go
> vcsim: set VirtualDevice.Connectable default for removable devices

- simulator/feature_test.go
This fixes an issue in setups where the code directory doesn't have enough
permissions for a container to access.
This would result in the test hanging until timeout, and dangling containers.
Since there is no need to serve the source code via http in the first place,
generate a dummy file instead, and use it in the test.
> simulator: fix container vm example

- object/authorization_manager.go
- object/authorization_manager_test.go
- simulator/authorization_manager.go
- HasPrivilegeOnEntity
- HasUserPrivilegeOnEntities
- FetchUserPrivilegeOnEntities
Fixes #2132
> vcsim: add AuthorizationManager methods

- govc/vm/disk/attach.go
> govc: document vm.disk.attach -link behavior

- govc/object/collect.go
- govc/test/object.bats
- simulator/folder.go
- simulator/registry.go
- simulator/view_manager.go
govc: fix object.collect ContainerView updates (issue #2108)
> vcsim: support inventory updates in ContainerView

- object/virtual_app.go
- simulator/resource_pool.go
- simulator/resource_pool_test.go
> vcsim: add CloneVApp_Task support

- simulator/datastore.go
- simulator/model.go
- simulator/registry.go
Fix Registry.FindByName lookup for network types
Fixes #1919
Fixes #2028
> vcsim: rewrite vmfs path from saved model

- govc/volume/ls.go
Option -ds flag limits results to a specific datastore.
> govc: add volume.ls -ds option

- object/example_test.go
> examples: add Folder.CreateVM

- govc/release.sh
> SHA-1 deprecated in 2011, sha256sum for releases

- object/example_test.go
- object/virtual_device_list.go
> examples: add NetworkReference.EthernetCardBackingInfo

- simulator/event_manager.go
- simulator/event_manager_test.go
PR #2134 changed EventManager's history ring buffer to a linked list.
Doing the same for EventHistoryCollector as it simplifies the code and
avoid having to lock the EventManager in the Read{Next,Prev}Events methods.
> vcsim: use linked list for EventHistoryCollector

- examples/events/main.go
- simulator/event_manager.go
> vcsim: support EventFilterSpec.Time

- scripts/govc-env.bash
> Little fix for "govc-env --save without config name"

- govc/session/login.go
- govc/test/session.bats
The session.login PATH command set URL.Path directly, causing query string to be escaped.
Switch to url.Parse which properly handles both Path and the optional Query.
- Add more docs on session curl
- Add session curl POST test, including URL query.
> govc: fix session curl when given a URL query

- simulator/virtual_machine.go
> vcsim: set VirtualMachine.Config.CreateDate property

- govc/flags/network.go
Change the address type to automatic
Addresses #2116.
> Change the address type to automatic

- cns/cns_util.go
This PR drops the `ClusterDistribtution` field from `createSpec` and `updateSpec` for operations on vSAN 7.0u1. ClusterDistribution field is only introduced in vSAN 7.0u2 onwards. 
This change also refactors some code in `cns_util.go`
**Testing**
On vsphere 7.0u1:
Before this change, PVC creation fails with error:
```
root@k8s-master:~# kubectl describe pvc
Name:          example-vanilla-block-pvc
Namespace:     default
StorageClass:  example-vanilla-block-sc
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: csi.vsphere.vmware.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Used By:       <none>
Events:
Type     Reason                Age               From …
```
> Drop clusterDistribution from vSAN 7.0 update and create spec elements

- govc/flags/output.go
- govc/test/cli.bats
- nfc/lease.go
- simulator/virtual_machine.go
- task/error.go
- task/wait.go
> govc: include sub task fault messages on failure

- govc/library/update.go
- govc/test/library.bats
- vapi/library/library.go
> govc: add library.update command

- simulator/entity_test.go
- simulator/folder.go
- simulator/resource_pool.go
- simulator/task.go
- simulator/task_test.go
- simulator/virtual_machine.go
Handy to have for external code that works with simulator.Task
> export simulator.task.Wait

- govc/flags/debug.go
- govc/importx/ovf.go
- govc/test/import.bats
- simulator/host_datastore_browser.go
- simulator/http_nfc_lease.go
- simulator/property_collector.go
- simulator/simulator.go
* govc: log invalid NetworkMapping.Name with import.ova command
* vcsim: put verbose logging behind '-trace' flag
* govc: revert pretty print pruning optimization
> Logging related updates

- govc/test/images/update.sh
> govc: update test images URL

- govc/test/vm.bats
- govc/vm/customize.go
> govc: add vm.customize -dns-suffix flag

- Dockerfile.govc
> Fix folder write for govc container

- .github/workflows/govmomi-govc-tests.yaml
> Increase govc tests timeout

- object/vm_guest_test.go
The test was actually broken due to incorrect use of waitgroup (one defer was missing). I removed all concurrency to simplify the test.
Closes: #2381
> Fix VM Guest test and vet warnings

- README.md
simple readme update to add Rancher to the projects list as well as reorganize them all in alpha ordering
> adding rancher to projects and reorganizing in alpha order

- README.md
- govc/README.md
- vcsim/README.md
> Update READMEs with artifacts and Docker images

- govc/README.md
- vcsim/README.md
> Simplify binary download instructions

- vim25/soap/client.go
> Clarify SetRootCAs behavior

- .github/comment-template.md
- .github/workflows/issue-greeting.yaml
Greet (only) first-time contributors when they open a new issue.
Closes: #2406
> Add issue greeting

- govc/README.md
- vcsim/README.md
> docs: Document linker and GOFLAGS for build vars

- .github/workflows/govmomi-check-wip.yaml
Use a dedicated WIP action instead of inline SHELL script.
Closes: #2402
> Add WIP Action

- govc/host/info.go
> govc: Change 'Maintenance Mode' printing in host.info

- README.md
- govc/README.md
> Fix broken Kubernetes vSphere Cloud Provider links

- govc/test/vcsim.bats
- simulator/simulator.go
List types and methods for all namespaces, not just vim25
> vcsim: include all namespaces in /about info

- simulator/container.go
This patch fixes a bug where a data race would occur around access to the `simulator.container.id` field. The race could be produced by running the following test:
```bash
go test -run Example_runContainer -v -race -count 1 ./simulator
```
With this patch, the race no longer occurs.
Closes: _na_
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. If applicable, please also list any relevant details for your test configuration.
To verify the issue, run the following command sans this patch:
```shell
$ go test -run Example_runContainer -v -race -count 1 ./simulator
=== RUN   Example_runContainer
==================
WARNING: DATA RACE
Write at 0x00c000602768 by goroutine 36: …
```
> Fix data race in simulator.container.id

- .github/workflows/codeql-analysis.yml
Set up CodeQL analysis to perform daily security scans on this code base. See if this provides value for us, otherwise revert.
Details on CodeQL: https://codeql.github.com/docs/codeql-overview/about-codeql/
Closes: #2447
Will run daily and report to security analysis section in this repo.
* Toolchain:
* SDK:
this project
> Setup CodeQL Analysis

- Makefile
This change adds a new default `make` target called `help` to the Makefile at the root of this project. The motivation behind adding this target is to help any developer to get a gist of the `make` targets that are available to him/her and briefly describe what each of the targets do.
Here's the output when `make` or `make help` are run:
```
$ make help
Usage:
make [target]
Targets:
all                   Run linters and tests
check                 Run linters
install               Install govc and vcsim
go-test               Runs go unit tests with race detector enabled
govc-test             Runs govc bats tests
test                  Runs go-test and govc-test
doc                   Generates govc USAGE.md
help …
```
> chore: Add make help target

- cns/client_test.go
Recently we added go bindings and updated unit tests to invoke QueryAsync API in `cns/client_test.go`. However, we want to test invocations of the new API only for vSphere version 7.0.3 and above. Because, the API is supported only for vSphere versions 7.0.3 or later. This PR is addressing this issue by adding a vSphere version check before calling the API
Testing done:
Ran the unit tests with latest vSphere version
<pre>
go test -v
client_test.go:990: Successfully queried Volume using queryAsync API. queryVolumeAsyncTaskResult: &types.CnsAsyncQueryResult{
CnsVolumeOperationResult: types.CnsVolumeOperationResult{},
QueryResult:              types.CnsQueryResult{
{
Id: "58e7c9e6-7c89-42d7-8c50-820e6011dd30",
}, …
> Modify QueryAsyncVolume API unit test to be invoked only for vSphere 7.0.3 and above

- vcsim/README.md
Add vcsim in Kubernetes blog post. Also using inline links to reference blog posts. Let me know if this is not desired.
Closes: n/a
* Toolchain:
* SDK:
this project
> docs: Add blog to  `vcsim` README

- vim25/debug/file.go
vim25.debug.FileProvider.files is a shared resource. It should be
protected to avoid concurrent modifications. This change ensure
safe access to the variable by using a mutex.
Concurrent modifications to the `debug.FileProvider.files` resource cause DATA RACE errors. This causes panics in binaries that consume `govmomi` and are running in race detection enabled.
Closes: #(2443)
* Toolchain:
* SDK:
this project
> Protect FileProvider.files to avoid concurrent access

- .github/comment-template.md
Closes: #2473
* Toolchain:
* SDK:
this project
> chore: Fix CONTRIB link in greeting

- .mailmap
- CONTRIBUTORS
- govc/USAGE.md
Updating generated doc
N/A
* Toolchain:
* SDK:
this project
> docs: update govc/USAGE and CONTRIBUTORS

- property/example_test.go
Add example for using property collector with `Wait` (which internally dispatches to `WaitForUpdatesEx`).
Closes: #2514
`go test -v ./property`
* Toolchain:
* SDK:
this project
> examples: Add Property `Wait()` example

- session/cache/session.go
Closes: #2512 
* Toolchain:
* SDK:
this project
> Add Reauth flag to skip loading cached sessions

- govc/library/update.go
- govc/test/library.bats
- vapi/library/library_item.go
Adds support for updating library items (name and description)
Added test to library.bats
this project
> govc: support updating items in library.update command

- govc/vm/rdm/attach.go
Closes: #2536
- [ x] Bug fix (non-breaking change which fixes an issue)
- Deploy VM with standard hard disk, loop over adding 10 RDM with NAA id using govc
govc vm.rdm.attach -device "/vmfs/devices/disks/naa.60000970000xxxxxxxxx533030334132" -vm=govc_test
govc vm.rdm.attach -device "/vmfs/devices/disks/naa.60000970000xxxxxxxxx533030334435" -vm=govc_test
govc vm.rdm.attach …
> Fix for issue 2539 

- simulator/virtual_machine.go
This PR fixes #2558
Closes: #2558
This has been tested in the actual environment where issue was reproduced.
this project
> Fix Nil-Pointer Exception in ResourceAllocation

- simulator/datacenter.go
- simulator/datacenter_test.go
Return array of tasks (one per VM) as result in the task returned
for multi-VM PowerOn operation for datacenter. This enables API caller
to be able to wait on actual VM PowerOn at per VM level.
Closes: #2584
Added a new unit test to verify the change to datacenter PowerOn task implementation code works fine.
The new test can be individually run as:
```
$ go test -run TestDatacenterPowerOnMultiVMs -failfast -v github.com/vmware/govmomi/simulator
=== RUN   TestDatacenterPowerOnMultiVMs
--- PASS: TestDatacenterPowerOnMultiVMs (0.05s)
PASS
ok  	github.com/vmware/govmomi/simulator	0.057s
```
Finds 2 VMs in VPX simulator inventory (under same DC), powers them off first individually, invokes DC PowerOnVM API (single call for 2 VMs), …
> vcsim: Fix PowerOnMultiVMTask() to return per-VM tasks

- govc/task/recent.go
This PR fixes `govc tasks` command to handle command options `-dump`, `-json`, and `-xml` as the help explains.
Closes: #2582
```bash
$ ./govc tasks -dump -n 1
types.TaskInfo{
Key:           "task-64",
Task:          types.ManagedObjectReference{Type:"Task", Value:"task-64"},
Description:   (*types.LocalizableMessage)(nil),
Name:          "PowerOn",
DescriptionId: "VirtualMachine.powerOn",
Entity:        &types.ManagedObjectReference{Type:"VirtualMachine", Value:"vm-63"},
EntityName:    "vm-63",
Locked:        nil,
State:         "success", …
```
> govc: fix tasks to activate option dump/json/xml

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/govmomi-govc-tests.yaml
- RELEASE.md
- govc/USAGE.md
Closes: #2478
- Update `RELEASE` instructions to make sure govc docs are up2date
- Add workflow to catch govc docs inconsistencies
- Remove test details in PR instructions
- update govc `USAGE` so the workflow passes
this project
> Update PR and RELEASE docs

- govc/USAGE.md
> docs: Update govc USAGE

- guest/file_manager.go
- guest/file_manager_test.go
No need to map the guest transfer URL host to the ESX vNIC IP if the URL.Host is already an IP address.
In which case we can also avoid property collection of the vNIC config.
Using the original IP also a must when the ESXi host is dual stack, but the client has only pure IPv6.
Changed the host cache value from URL.Hostname() to URL.Host, so IP-literal form is maintained.
e.g. URL.Hostname() is "fe80::1" when URL.Host is "[fe80::1]:80"
Fixes #2553
this project
> fix: avoid vNIC mapping in guest.TransferURL if URL.Host is an IP

- Makefile
Closes: #2645
Updated stale link in Makefile
> fix updating stale url from Makefile

- simulator/virtual_machine.go
- simulator/virtual_machine_test.go
Currently, the simulator ignores any VApp properties in the VM
creation and Reconfigure workflows.
This change enables users to instantiate or Reconfigure a simulator VM
with VApp properties set. This commit also adds tests to validate the
workflows.
Closes: #2642
this project
> Support Creating/Reconfiguring a simulator VM with VApp properties

- govc/USAGE.md
- govc/library/vmtx_item_info.go
- govc/test/library.bats
- vapi/simulator/simulator.go
- vapi/vcenter/vcenter_vmtx.go
Closes: #2637
Added API to fetch VMTX library item template details
Link to documentation: [https://developer.vmware.com/apis/vsphere-automation/latest/vcenter/api/vcenter/vm-template/library-items/template_library_item/get/]
this project
> Add API fetch vcenter vm template library item details

- .github/workflows/govmomi-build.yaml
- .github/workflows/govmomi-go-lint.yaml
- .github/workflows/govmomi-go-tests.yaml
- .github/workflows/govmomi-govc-tests.yaml
- .github/workflows/govmomi-release.yaml
Uses Go 1.17 for build-related steps and matrix 1.16 and 1.17 for tests
(see #2674)
Closes: #2679
this project
> Update workflow Go versions

- simulator/folder.go
- simulator/folder_test.go
Closes: #2717
Signed-off-by: syuparn <s.hello.spagetti@gmail.com>
Fix vcsim `CreateFolder()` to encode special characters in requested folder name
Closes: #2717 
- add unit tests to check special characters are escaped
this project
> vcsim: Fix CreateFolder to encode folder name

- object/folder.go
- simulator/folder.go
- simulator/folder_test.go
- vim25/methods/unreleased.go
- vim25/types/unreleased.go
Adds new PlaceVmsXCluster method, types and vcsim support.
this project
> Add PlaceVmsXCluster bindings and simulator

- govc/test/vm.bats
- simulator/virtual_machine.go
set summary.guest.{hostName,ipAddress} in CustomizeVM
Closes: #2753
this project
> vcsim: set summary.guest.{hostName,ipAddress} in CustomizeVM

- .github/ISSUE_TEMPLATE/config.yml
Follows: https://github.com/hashicorp/terraform-provider-vsphere/issues/new/choose
Closes: #2761
this project
> Add link to Discussions in New Issue

- object/example_test.go
Example use of `HostConfigManager.OptionManager`
The example itself is also a test.
this project
> examples: add HostConfigManager_OptionManager

- examples/alarms/main.go
- govc/test/vcsim.bats
Closes: #2783 (see: https://github.com/vmware/govmomi/discussions/2782)
this project
> Add Alarm Manager Example

- CONTRIBUTING.md
Provide more detailed walkthrough via blog post reference to new contributors.
Closes: #2799
- n/a
this project
> Add git blog post to `CONTRIBUTING.md`

- simulator/virtual_machine.go
- simulator/virtual_machine_test.go
When vm power state is not powered on, its devices should not be connected.
Closes: #2797
- unit tests in the commit
this project
> vcsim: Fix device connectivity when vm is powered off

- .github/workflows/govmomi-govc-tests.yaml
> Fix `govc` test workflow `cp` binary error

- .github/workflows/govmomi-build.yaml
- .github/workflows/govmomi-go-tests.yaml
- .github/workflows/govmomi-govc-tests.yaml
> chore: Optimize Go CI workflows

- CONTRIBUTING.md
- README.md
- govc/README.md
- vapi/library/finder/README.md
- vcsim/README.md
> docs: Update documentation

- vapi/vcenter/vcenter_ovf.go
Follow up to issue #2843
this project
> fix: use correct vcenter.DeploymentSpec.VmConfigSpec json tag

- .github/PULL_REQUEST_TEMPLATE.md
> docs: Fix broken link in PR template

- simulator/virtual_machine.go
- simulator/virtual_machine_test.go
This fixes disk capacity changing logic in `ReconfigVM_Task`. When reconfiguring existing disk,
- disk capacity cannot be decreased
- capacityInBytes and capacityInKB should not be different
Closes: #2910
this project
> vcsim: Fix disk capacity validation in ConfigureDevices

- simulator/property_collector.go
- simulator/property_collector_test.go
This PR fixes vcsim retrieveProperties to avoid crash caused by invalid pathset which is a property of an array property.
Closes: #2953
this project
> vcsim: Fix RetrieveProperties path validation to avoid panic

- README.md
[Elastic Agent VMware vSphere integration](https://github.com/elastic/integrations/tree/main/packages/vsphere) to the list of projects using govmomi.
Signed-off-by: Essodjolo KAHANAM <essodjolo@kahanam.com>
this project
> Update list of projects using govmomi

- scripts/govc_bash_completion
- Bugfix for escaping spaces
- Additional completion for  -net,  -host, -ds, -pool , -vm.network.change, -disk.label
- Caching for VM name completion
> New feature, bug fix and performance improvement

- session/example_test.go
- vapi/rest/example_test.go
> examples: add session.Manager.LoginByToken

- govc/ls/command.go
- govc/test/ls.bats
> fix: support govc ls -xml flag

- simulator/container.go
Hey there! Not sure if this is something that would be useful, but I figured I'd open a PR for a conversation at least. For context, I'm running in the following environment:
- 2021 M1 MacBook Pro
- Docker v4.18.0
- vcsim built from the main branch
I was receiving the following error from vcsim when trying to run a container-backed VM in vcsim:
```
2023/04/07 16:21:01 tf-edu-ubuntu [/bin/sh -c docker run -d --name vcsim-tf-edu-ubuntu-a27e4e20-6722-5217-bba6-c304ffc5a839 -v vcsim-ubuntu-a27e4e20-6722-5217-bba6-c304ffc5a839:/sys/class/dmi/id:ro nginx:latest]: exit status 125 docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting …
```
> vcsim: Make mounting DMI information optional with container-backed VM

- simulator/container.go
Hey there! As usual, just wanted to put this out there for consideration, but for my user case I found it would be useful to publish ports on container-backed VMs. In my particular case, my use case was that I needed to SSH into the running Docker container and I was struggling with using the local container networking directly. 
I'm not sure if this is the most ideal implementation, but this change looks for a configuration key in the format of `RUN.port.xx` and expects a value to publish the port on. For example, `RUN.port.22 = 2222` will publish port 22 in the container on port 2222 of the host.
If you don't think this is a good addition, feel free to close :) Thanks!
Please describe the tests that you ran to verify your …
> vcsim: Add RUN.port.xx flag to publish ports on container backed VM

- govc/test/disk.bats
- simulator/view_manager.go
> fix: include StoragePod Datastore children in ContainerView

- .github/workflows/govmomi-check-wip.yaml
See: https://github.com/vmware/govmomi/security/dependabot/19
> chore: bump embano1/wip

- simulator/virtual_machine.go
- simulator/virtual_machine_test.go
This patch fixes a bug in the simulator where applying updated values for a VM's ExtraConfig would not take. Nor was it possible to remove values. Both issues are now addressed.
Closes: `NA`
this project
> vcsim: Fix VM ExtraConfig

- vim25/soap/client.go
- vim25/soap/debug.go
> Remove client request log from debug tracing

- vim25/soap/client.go
PR #3161 introduced a race when sharing http transport between soap client and service clients
> fix: avoid modifying client transport outside of NewClient

- .github/workflows/govmomi-build.yaml
- .github/workflows/govmomi-release.yaml
- .goreleaser.yml
- govc/README.md
- vcsim/README.md
Close #3181
Update some fields that should be deprecated in goreleaser
Closes: [#(issue-number)](https://github.com/vmware/govmomi/issues/3181)
this project
> build: Update some goreleaser deprecated fields

- govc/test/sso.bats
- lookup/client_test.go
- lookup/simulator/registration_info.go
- lookup/simulator/simulator_test.go
- ssoadmin/simulator/simulator.go
- Add ssoadmin to lookup simulator
- Add tests validating sts/ssoadmin use of lookup.EndpointURL
> vcsim: add lookup.EndpointURL tests

- simulator/cluster_compute_resource.go
- simulator/host_system.go
- simulator/host_system_test.go
> vcsim: set HostSystem.Config.Host

- vapi/simulator/simulator.go
The ConfigSpec returned by CreateImportSpec() will include devices from the OVF but since the simulator impl just reconfigures the VM with the provided ConfigSpec, those otherwise  unexpected devices won't be removed.  In VM Operator, likely the only user of this API w/ the ConfigSpec param, this would result in an extra Reconfigure to remove the unexpected devices. However, I'd like to be able to assert that a just-created VM matches our expected config.
Verified behavior in VM Operator tests around the deploy w/ ConfigSpec feature.
> vcsim: Remove extra devices in OVF Deploy w/ ConfigSpec

- simulator/race_test.go
- simulator/view_manager.go
- simulator/view_manager_test.go
- view/example_test.go
- view/list_view.go
- view/task_view.go
api: add ListView.Modify method, returns unresolved references
> vcsim: fix ModifyListView to return unresolved references

- govc/USAGE.md
- govc/cluster/change.go
- govc/test/cluster.bats
- simulator/cluster_compute_resource.go
vcsim: apply DasConfig + DrsConfig in ReconfigureComputResource_Task
> govc: add cluster.change '-ha-admission-control-enabled' flag

- govc/USAGE.md
- govc/library/import.go
- govc/library/probe.go
- govc/library/session/ls.go
- govc/library/session/rm.go
- govc/test/library.bats
- vapi/library/library_item_updatesession_file.go
- vapi/simulator/simulator.go
> api: add Content Library update session file APIs

- vapi/tags/tag_association.go
Closes #3320
Unmarshalling works now
> Fixes Missing Tags in AttachedTags

- gen/gen_from_vmodl.rb
- govc/device/info.go
- govc/emacs/govc.el
- performance/manager.go
- vim25/mo/mo.go
BREAKING: follow up to json tags missed in PR #3007 and PR #3247
Closes #3318
> govc: json tag camelCase fixes

- govc/vm/snapshot/tree.go
Implement -json flag to govc snapshot.tree for json output. 
Closes: #3220  
Run snapshot.tree with `-json` flag.
```
./govc snapshot.tree -vm mssql-01 -json -D -s
[
{
"createTime": "2024-02-08T00:05:30.874061Z",
"size": 20440,
"name": "l1",
"current": false,
"childSnapshotList": [
{
"createTime": "2024-02-08T00:05:48.958414Z",
"size": 37769183,
"name": "l2_from_l1",
"current": false,
"childSnapshotList": [
{
"createTime": "2024-02-08T00:06:14.051031Z",
"size": 37769183,
"name": "l3_from_l2",
"current": false,
"childSnapshotList": [
{
"createTime": "2024-02-08T01:58:45.426334Z",
"size": 629166047,
"name": "l4_from_l3",
"current": true,
"childSnapshotList": null
}
]
}
]
}
]
}
]
```
[guidelines]: …
> add -json to snapshot.tree

- .mailmap
- CONTRIBUTORS
- README.md
- RELEASE.md
- scripts/contributors.sh
> docs: update release doc

- govc/library/export.go
- govc/test/device.bats
- view/example_test.go
> fix: govc: use session KeepAlive in library.export command

- vapi/library/library_file.go
Closes: #3386
Add Downloadendpoint field in the library item file struct
Closes: #3386
- [] Bug fix (non-breaking change which fixes an issue)
> api: Add Downloadendpoint field in the library item file struct

- vim25/types/helpers.go
This patch updates the ConfigInfoToConfigSpec helper based on new API fields.
Closes: `NA`
> api: Update ConfigInfoToConfigSpec

- vim25/types/hardware_version.go
- vim25/types/hardware_version_test.go
This patch modifies the behavior of the HardwareVersion.IsValid function so that it returns true if the specified version can be parsed.
There is a new function, HardwareVersion.IsSupported, that acts more like the old behavior of IsValid. IsSupported only returns true when the version is known to GoVmomi.
BREAKING: HardwareVersion.IsValid is more relaxed, consider IsSupported
* HardwareVersion.IsValid returns true if the specified value matches a VMX version format.
* HardwareVersion.IsSupported behaves how IsValid used to behave.
Closes: `NA`
> api: HardwareVersion.IsSupported vs IsValid

- govc/USAGE.md
- govc/test/vsan.bats
- govc/vsan/change.go
- govc/vsan/info.go
- vsan/simulator/simulator.go
govc: add vsan.info -file-service-enabled flag
Issue #3430
> vcsim: add vSAN FileServiceConfig support

- go.mod
- go.sum
- govc/flags/output.go
- govc/importx/options.go
- govc/importx/ova.go
- govc/importx/ovf.go
- govc/importx/spec.go
- govc/library/import.go
- ovf/importer/archive.go
- ovf/importer/importable.go
- ovf/importer/importer.go
- ovf/importer/options.go
- ovf/importer/options_test.go
- ovf/importer/spec.go
- scripts/license.sh
- vim25/progress/loger.go
These changes are to allow using the template importing functionality available as a library.
I didn't add or removed any functionality, only moved things around.
> refactor: make importing templates available as a lib

- govc/library/info.go
- govc/test/library.bats
- internal/helpers.go
- object/namespace_manager.go
- simulator/datastore_namespace_manager.go
- simulator/model.go
- vapi/library/finder/path.go
- vapi/library/finder/path_test.go
govc: add library.info -S flag
vcsim: add DatastoreNamespaceManager
> api: convert vSAN directory name to uuid in ResolveLibraryItemStorage

- object/option_value_list.go
- object/option_value_list_test.go
This patch adds the IsTrue|IsFalse methods to the OptionValuesList helper. The functions return true|false based on the same logic common to vCenter.
Closes: `NA`
The new code has 100% coverage with the following tests:
```shell
$ go test -v -count 1 -run '^TestOptionValueList$/IsTrueOrFalse' ./object
=== RUN   TestOptionValueList
=== RUN   TestOptionValueList/IsTrueOrFalse
=== RUN   TestOptionValueList/IsTrueOrFalse/IsTrue
=== RUN   TestOptionValueList/IsTrueOrFalse/IsTrue/a_nil_receiver_should_not_panic_and_return_false
=== RUN   TestOptionValueList/IsTrueOrFalse/IsTrue/a_non-existent_key_should_return_false
=== RUN   TestOptionValueList/IsTrueOrFalse/IsTrue/a_key_with_true_should_return_true
=== RUN …
```
> api: OptionValues IsTrue|IsFalse

- govc/USAGE.md
- govc/namespace/registervm.go
- govc/test/namespace.bats
- vapi/namespace/namespace.go
- vapi/namespace/simulator/simulator.go
- vapi/resource.go
- vapi/simulator/simulator.go
api: add namespace.RegisterVM binding
vcsim: add namespace/registervm implementation
> govc: add namespace.registervm command

- simulator/cluster_compute_resource.go
- simulator/cluster_compute_resource_test.go
This patch introduces basic support for `ClusterComputeResource.PlaceVm` with the `reconfigure` placement type in vcsim. Since reconfigure is a supported placement type in real vSphere environments, it is essential to ensure that our simulator environment reflects this capability for accurate and comprehensive testing.
Addresses part of: #3540
```
% go test -v -count 1 -run 'TestPlaceVmReconfigure' -coverprofile cover.out ./simulator
=== RUN   TestPlaceVmReconfigure
2024/09/05 16:43:41 unsupported placement type: relocate
--- PASS: TestPlaceVmReconfigure (1.57s)
PASS
coverage: 26.5% of statements
ok      github.com/vmware/govmomi/simulator     1.986s  coverage: 26.5% of statements
```
```
go tool cover -html=cover.out …
```
> vcsim: Support PlaceVm with reconfigure placement type

- object/datastore.go
This allows the NewDatastoreURL to be used without an object.Datastore instance.
> api: extract NewDatastoreURL from Datastore.NewURL method

- simulator/folder.go
- simulator/race_test.go
- simulator/virtual_machine.go
> vcsim: fix RelocateVM_Task related races

- session/manager.go
> fix: synchronize access to session.Manager.userSession

- govc/USAGE.md
- govc/test/vm.bats
- govc/vm/change.go
- simulator/virtual_machine.go
govc: add vm.change -managed-by flag
> vcsim: support clearing ManagedBy field

- vim25/soap/error.go
- vim25/soap/error_test.go
Closes: #3600
Adds unit tests and tested in CAPV.
> Fix error assertion in IsCertificateUntrusted

- cns/methods/unreleased.go
- cns/types/unreleased_types.go
- cns/unreleased_client.go
Added bindings for CNS UpdateVolumeCrypto.
Closes: NA
Tested by the CNS team. 
> cns: Support encryption/re-encryption of volumes

- property/collector.go
- property/collector_test.go
The PropertyCollector update closure passed to WaitForUpdatesEx is only triggered when a non-empty FilterSet occurs.
This is an issue when side effects need to be triggered inside the update function such as notification mechanisms that an update was acknowledged.
It should be the choice of the update closure to determine whether to process the empty FilterSet or not.
Closes #3631
Please include a summary of the change.
Please describe any manual tests done to verify your changes.
> Property Collector updates should be triggered on the empty FilterSet

- cli/object/save.go
- govc/test/license.bats
- simulator/license_manager.go
- vim25/mo/type_info.go
- govc object.save includes licenseAssignmentManager property
- fix: assert Entity interface in mo.Value()
> vcsim: add UpdateAssignedLicense method

- govc/test/import.bats
- ovf/importer/archive.go
- Fix regression introduced in 36ee9a1e / PR #3596
- Add test for remote import.ovf
> fix: govc: import.ovf remote support regression

- lookup/simulator/example_test.go
- lookup/simulator/registration_info.go
- lookup/simulator/simulator.go
- lookup/simulator/simulator_test.go
With this change, List() can be called withing having called RetrieveServiceContent()
> vcsim: fix lookup service deferred registration

- cli/storage/policy/create.go
- govc/USAGE.md
- govc/test/storage.bats
- Simplify code using pbm.CapabilityProfileCreateSpec helper
> govc: Add storage.policy.create '-e' option to enable encryption

- cli/volume/create.go
- cli/volume/ls.go
- cli/volume/rm.go
- cns/simulator/simulator.go
- cns/simulator/simulator_test.go
- govc/USAGE.md
- govc/test/volume.bats
- simulator/vstorage_object_manager.go
vcsim: add disk backing for cns volumes
govc: add volume.create command
govc: add volume.ls query filter flags
> vcsim: add query and metadata support for CNS Volume API

- cli/volume/extend.go
- cli/volume/ls.go
- cli/volume/rm.go
- cli/volume/snapshot/create.go
- cli/volume/snapshot/ls.go
- cli/volume/snapshot/rm.go
- cns/cns_util.go
- cns/simulator/simulator.go
- govc/USAGE.md
- govc/test/volume.bats
govc: add volume.rm -keep flag to retain backing disk
vcsim: don't delete backing disk in CnsDeleteVolume when DeleteDisk==false
chore: Use cns Task helpers in govc volume commands
> govc: add volume.extend command

- .github/workflows/verify-docker-login.yaml
* Added `permissions` section to specify the permissions required for the workflow.
* Simplified the `cron` schedule syntax by removing redundant quotes.
> chore(gh): update docker workflow

- .github/workflows/govmomi-stale.yaml
> chore(gh): update stale workflow

- .github/workflows/govmomi-lock.yml
Adds a workflow to lock closed issues and pull requests.
> chore(gh): add lock workflow

- .github/workflows/govmomi-check-wip.yaml
Updates the WIP check workflow:
> [!NOTE]
> We could consider an enhancement later to automatically set pull requests as draft if the title contains potential WIP patterns.
> chore(gh): update wip workflow

- .github/workflows/govmomi-release.yaml
> chore(gh): update release workflow

- .github/workflows/govmomi-go-lint.yaml
- hack/boilerplate/boilerplate.go.txt
- hack/header/config.json
- hack/header/main.go
Refactors the header check.
```shell
Run go run hack/header/main.go -config="hack/header/config.json"
go run hack/header/main.go -config="hack/header/config.json"
shell: /usr/bin/bash -e {0}
Configuration file: hack/header/config.json
Processing complete.
Total files processed: 109[3](https://github.com/vmware/govmomi/actions/runs/14075181134/job/39416802853?pr=3744#step:4:3)
All processed files have the expected header.
```
Closes #3729
> refactor: header check

- object/virtual_machine.go
- simulator/virtual_machine.go
- simulator/virtual_machine_test.go
Add CreateSnapshotEx method to object.VirtualMachine Api
vcsim: Add object.VirtualMachine.CreateSnapshotEx support
-unit tests
> vcsim: Add object.VirtualMachine.CreateSnapshotEx support

- property/match.go
- property/match_test.go
Closes: #3785
Add support for a match function
Added case to unittest.
> api: Add option to use a filter function as value of  property.Match

- cns/client.go
- cns/client_test.go
- cns/methods/methods.go
- cns/types/enum.go
- cns/types/types.go
This PR adds cnssyncvolume API bindings and tests in client_test.go
added unit tests to test with CNS API.
Note: changes for CnsSyncVolume API are still in progress.
> Add CnsSyncVolume API bindings

- vmdk/disk_info.go
- vmdk/disk_info_test.go
Previously, the GetVirtualDiskInfoByUUID will include all the disks in the disk chain when calculating the total size. If snapshots are taken on the VM, the chain will grow to include all the delta disks for snapshots. 
This change adds a new option `excludeSnapshots` that allows the function to exclude the disks for snapshot, and only include the child most delta disks when calculating the size.
Unit test
> GetVirtualDiskInfoByUUID: Add flag to exclude snapshot disks from size calculation
