vim25/soap/client.go
`govmomi.NewClient` doesn't work when it access to vCenter via https proxy. It seems that `https_proxy` environment variable is ignored with RoundTripper.
=> fix a issue of ignored https_proxy environment variable with https scheme

govc/flags/client.go
Before this change the same session file would be used if the schema was
changed. If a session was valid against an http URL, and then the schema
changed to https, the same session file would be used, which would still
try and use http.
=> Key session file off of entire URL

govc/test/esxbox/Vagrantfile
Vagrant 1.7 expects to be able to replace the insecure key with a
freshly generated one. This doesn't work for an ESX guest yet.
=> Set insert_key = false

govc/importx/archive.go, govc/importx/ova.go
The .ovf file within a .ova archive may not have the same name.
For example:
ova: VMware-vRealize-Log-Insight-2.5.0-2475126.ova
ovf: VMware-vRealize-Log-Insight-2.5.0-2475126_OVF10.ovf
=> Loosen .ovf match in ova.import

CHANGELOG.md, README.md, client.go, govc/.gitignore, govc/build.sh, govc/version/command.go
This marks 0.1.0.
The build script produces a number of govc binaries.
Once this is merged I'm putting those up for download on the release page.
=> Version prep

client_test.go, vim25/soap/client.go
The following prompted these commits:
1. Not specifying the /sdk path in the URL makes the server return a 400 Bad Request
2. The HTTP status code was not checked in the SOAP client and it instead expected every response to contain an XML body. This is not the case when you're not talking to the SDK to begin with, in which case ESX returns a 400 Bad Request. Since the client was expecting a body, but didn't receive one, the error returned was io.EOF (caused by trying to read from an empty body). To fix this, we now capture unexpected HTTP status codes and return an error, instead of trying to read the body. The only statuses I have seen returned from the SDK endpoint are 200 OK and 500 Internal Server Error.
=> HTTP errors

vim25/xml/read.go, vim25/xml/read_test.go
The HostPciDevice type has byte fields for which vSphere can return
negative values. This means the values are serialized following two's
complement, which has to be undone on the client side.
This likely fixes #246.
=> Interpret negative values for unsigned fields

govc/CHANGELOG.md, govc/flags/client.go
It conflicted with the "persist" flag for the vm.disk.attach command.
Should have been caught by tests. It's time to backfill on tests for vm.disk.*.
=> Rename persist flag to persist-session

CHANGELOG.md, find/finder.go, govc/datacenter/create.go, govc/flags/search.go, govc/host/autostart/autostart.go, govc/ls/command.go, govc/pool/change.go, govc/pool/create.go, govc/pool/destroy.go, govc/pool/info.go, govc/vm/info.go
This means that these functions can safely return a not found error for patterns that didn't match any object. It is up to the caller to figure out what to do in case of such an error.
For the govc commands, many will continue executing for the remaining arguments, but exit with a non-zero status to indicate failure for one of the arguments. This is not the case right now, but with this change becomes easier to do so.
=> Change finder functions to no longer take varargs

govc/test/test_helper.bash, govc/test/vm.bats, govc/vm/change.go, govc/vm/info.go
Usage:
Put guestinfos to vm.
```
govc vm.change -vm.ipath=/DATACENTER/vm/folder/vm1 -e="guestinfo.<key1>=<value1>" -e "guestinfo.<key2>=<value2>"
```
Then you can read guestinfo on a guest OS.
```
vmtoolsd --cmd "info-get guestinfo.<key1>"
```
=> Add extraConfig option to vm.change

govc/flags/client.go, govc/test/cli.bats, govc/test/license.bats
Support the `GOVC_USERNAME` and `GOVC_PASSWORD` environment variables.
This enables users to specify usernames and passwords with special characters that prohibit them from being specified as part of the `GOVC_URL` variable.
Fixes #273.
=> Credentials via environment variables

govc/importx/archive.go
The h.Name is like ./foo.ovf, so foo*.ovf can not match the name.
=> Modify archive.go bug

govc/device/info.go, govc/flags/network.go, govc/test/network.bats, govc/test/test_helper.bash, govc/vm/network/change.go
This makes it possible to specify the network hardware address when
creating a vm or change it for an existing vm.
Closes issue #228
=> Add net.address flag

govc/datastore/info.go, govc/test/datastore.bats
Example outputs:
```
% govc datastore.info ...
Name:        datastore1
Type:      VMFS
URL:       /vmfs/volumes/54343bd3-39a85cf2-b68b-000c291e53a2
Capacity:  187.8 GB
Free:      184.6 GB
% govc datastore.info ...
Name:        nfsDatastore
Type:      NFS
URL:       ds:///vmfs/volumes/2da3986c-a152ca17/
Capacity:  492.4 GB
Free:      489.1 GB
Remote:    10.28.239.247:/shared
%  govc datastore.info ...
Name:        vsanDatastore
Type:      vsan
URL:       /vmfs/volumes/vsan:5246f9374fa1cd5c-a5fadb7fd2d1f0b8
Capacity:  1844.4 GB
Free:      1578.2 GB
```
=> Add datastore.info cli command

govc/host/esxcli/esxcli.go, govc/importx/archive.go
The govet Makefile target was complaining about the indentation and import order in the following files.  This change is to make it stop complaining.
=> Make govet stop complaining

.travis.yml
See: http://docs.travis-ci.com/user/migrating-from-legacy
Looks like our travis build hasn't run for ~2 months, not sure if this is why, but we should make this change in any case.
=> Update travis.yml for new infra

ovf/cim.go, ovf/envelope.go, ovf/ovf.go, ovf/ovf_test.go
This models the properties we would need to extract from an OVF to parameterize OVF deployment.
Not yet hooked up to the import functions in govc.
=> Add OVF unmarshalling

session/manager.go
The previous implementation tried to retrieve all properties on the
session manager. The "sessionList" property requires the
"Sessions.TerminateSession" privilege. If the user didn't have this
privilege, this property would be missing from the response and the
response would include a "NoPermission" fault for this property. This
fault was then bubbled up to the user as if the session was invalid.
Change this to only retrieve the "currentSession" property.
Thanks to @skuzye for providing debugging information.
Fixes #251.
=> Only retrieve "currentSession" property

govc/host/esxcli/esxcli.go, govc/test/fields.bats, govc/vm/info.go
Add -hints option to host.esxcli, enables other frontends to parse the simple output format and render table data in their own way
Reduce number of round trips for vm.info property collection
=> Misc govc changes

govc/test/vm.bats, govc/vm/info.go
New '-r' option outputs the same data as the vSphere Client's
"Resources" section.
Make the "General" data optional via '-g' option, but enabled by
default.
=> Add govc vm.info resources option

govc/importx/spec.go
* Originally this was handled implicitly via a blank extension. We now allow for a blank file extension, therefore the 'no file name provided' case needs to be explicit.
=> Handle the import.spec case where no spec file is provided

scripts/vagrant/vcsa/vagrant.sh
Commit bfabd01 switched from perl to sed - MaxSessions regex was only
valid in perl, which broke vagrant.
cc @bruceadowns
=> Fix vcsa ssh config

govc/datastore/download.go, govc/datastore/upload.go, govc/importx/vmdk.go, object/datastore.go, session/manager.go, vim25/soap/client.go
- Add object.Datastore methods to upload/download datastore files using
a service ticket rather than user/pass authentication
- Required for http datastore access when authenticating with client
certificate
- Faster for upload/download of large files to talk to an ESX box
directly than via vCenter
=> Use service ticket for datastore file access

session/keep_alive.go
Seeing NotAuthenticated errors again when using certificate based auth
=> KeepAlive support with certificate based login

govc/vm/info.go
The resource summary (-r) includes the VM network(s), we need to use the
appropriate mo type for DistributedVirtualPortgroup
=> Add DistributedVirtualPortgroup support to vm.info

scripts/govc-env.bash
I got tired of going through my history to run previously run `export GOVC_***` commands.
=> Add bash function to save/load GOVC environments

govc/vm/change.go
NestedHVEnabled=true is the proper way to enable nested HV.
=> Fix vm nested hv option

find/finder.go, govc/test/vm.bats, govc/vm/info.go, object/compute_resource.go, vim25/mo/fixtures/cluster_host_property.xml, vim25/mo/fixtures/hostsystem_list_name_property.xml, vim25/mo/retrieve.go, vim25/mo/retrieve_test.go
Prior to this change, the ClusterComputeResource.Hosts() method would panic.
=> Add ClusterComputeResource.Hosts() support

govc/flags/client.go
- Setting GOVC_MIN_API_VERSION=- will skip the version check
- Skip version check for development builds
=> Option to disable API version check

object/datastore.go
Removes the dcPath as suggested by Doug @ #381
Signed-off-by: S.Çağlar Onur <conur@vmware.com>
=> Let the ESXi to figure out datastore name

govc/host/esxcli/firewall_info.go, govc/host/firewall/find.go, object/host_config_manager.go, object/host_firewall_system.go
iirc, started with a method attached to object.HostFirewallSystem to get the esxcli firewall info, that didn't work out due to cyclic import.
=> Remove host reference from HostFirewallSystem

govc/host/storage/info.go, govc/host/storage/partition.go, govc/main.go, object/host_config_manager.go, object/host_storage_system.go
These commands cannot yet change the host's devices in
any way, only show HBAs, LUNs, and partition tables.
=> Add host storage commands

govc/importx/options.go, govc/importx/ova.go, govc/importx/ovf.go, govc/test/import.bats
Can be specified by setting it as a property in the options file, or by passing it as a command line argument.
=> Specify the new entity's name upon import

govc/flags/client.go, govc/test/test_helper.bash, test/helper.go, vim25/client_test.go, vim25/soap/client.go
By exposing this wrapper, programs other than govc can easily use the
same url defaults as govc (scheme, path).
=> Move govc url.Parse wrapper to soap.ParseURL

scripts/.gitignore, scripts/wireshark-esx.sh, scripts/wireshark-vcsa.sh
Similar to the capture script for ESX. Difference is that this script
captures the traffic between the vSphere Web Client process and vpxd on
the VCSA machine itself.
=> Script to capture vpxd traffic on VCSA

session/keep_alive.go, session/keep_alive_test.go, session/manager.go, vim25/methods/service_content.go
- Switch to CurrentTime in the default handler (smaller payload)
And useful for custom handlers as it requires authentication, whereas
ServiceContent does not
- Add session.Manager TerminateSession method
=> Add support for custom session keep alive handler

object/datastore.go
A datastore could be attached to different hosts in different
clusters.
=> Introduce AttachedClusterHosts

govc/emacs/govc.el
- "Emacs" in the package description line is redundant
- Declare a dependency on Emacs 24.3, for setq-local and tabulated-list-mode
- Don't use an illegal key prefix: C-c [letter] is reserved for
user customisation, as per https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html
In connection with https://github.com/milkypostman/melpa/pull/3546
=> govc.el: minor fixes for distribution as a package

vim25/mo/retrieve.go
Ignore missing alarmActionsEnabled missing property, possible with a
vApp child VM.
=> Update missing property whitelist

.drone.yml
This fixes local `drone exec` execution.
=> added explicit cloning path to drone.yml

govc/README.md, govc/flags/client.go, govc/test/cli.bats, govc/test/images/update.sh, vim25/soap/client.go
Added `-vim-namespace` and `-vim-version` flags to govc. Also set by corresponding env vars documented in README.md
```./govc -vim-namespace urn:vim25 -vim-version 6.0 -k -persist-session=false```
Also updated `govc/test/images/update.sh` since I was getting bad filenames from bintray due to akamai.
Addresses https://github.com/vmware/govmomi/issues/384
=> Add switch to specify protocol version in SOAPAction header

govc/vm/change.go
`govc vm.change -vm=test -e "guestinfo.hello=world=foo"` would result in `guestinfo.hello` having the value **`world`**, rather than **`world=foo`**.
=> Fix vm.change's ExtraConfig values being truncated at equal signs

govc/vm/disk/create.go
I hope this is helpful to others who use thick provisioning in their environments
=> Added arguments to govc vm.disk.create for thick provisioning and eager scrubbing, as requested in issue #254

govc/device/info.go, govc/importx/ovf.go, govc/importx/vmdk.go, object/virtual_device_list.go, object/virtual_device_list_test.go, vim25/types/types.go, vim25/types/types_test.go
The UnitNumber is optional in the wsdl, hence the 'omitempty' directive
causes issues, as evidenced by 2 FIXMEs in the code. This addresses
those FIXMEs, being able to properly distinguish between absent optional
UnitNumber and a properly present zero-valued UnitNumber.
=> Fix issue with optional UnitNumber

govc/device/info.go, govc/flags/network.go, govc/test/device.bats, object/virtual_device_list.go
Filters device.info to devices backed by the given network.
Example use ( cc @hickeng ):
```
% govc device.info -vm /clovervm/vm/bon-368/bon-368 -net Bonneville
Name:               ethernet-1
Type:             VirtualVmxnet3
Label:            Network adapter 2
Summary:          DVSwitch: 36 97 19 50 36 3e fe 71-62 eb 8b f7 43 b1 d9 03
Key:              4001
Controller:       pci-100
Unit number:      8
Connected:        true
Start connected:  true
Guest control:    true
Status:           ok
MAC Address:      00:50:56:99:a7:69
Address type:     assigned
% govc device.info -vm /clovervm/vm/bon-368/bon-368 -net DPortGroup
Name:               ethernet-0
Type:             VirtualVmxnet3
Label:            Network adapter 1
Summary:          DVSwitch: 36 97 19 50 36 3e fe 71-62 eb 8b f7 43 b1 d9 …
```
=> Add -net flag to device.info command

govc/test/ls.bats
Added double quotes to networking tests -- if there's a more precise way to do this please share.
Fixes 465
=> Double quote network name to prevent space in name from failing

.drone.yml, .travis.yml, govc/flags/datacenter.go, govc/flags/output.go
I have found this pretty-printing library (davecgh/go-spew) very useful for discovering underlying data structures when working on new features in govc, and present this new output -dump flag code if there is any interest in inclusion.
Since it's an external library and not included with Go, I suspect there may be a policy on what is allowed to be included in govc. If there is a document on such a policy then I would be interested in reading it for future reference.
Please feel free to close this pull request if there is no interest, or this cannot be merged.
=> Added new -dump output flag for pretty printing underlying objects using davecgh/go-spew

CONTRIBUTORS, govc/pool/destroy.go, govc/test/pool.bats
Adaptations to pool.destroy following issue #479 
Ignore the "-r" switch
Add the "-children" switch to only remove childs
What could also be changed, but i'd like to be sure it is ok:
- remove the "-r" switch completely (i feel it could cause problem to existing script using the switch)
- simplify the pool.destroy test to just create and destroy a pool (not play with child pools)
=> Pool destroy children

govc/test/vm.bats, govc/vm/clone.go
Basic clone functionalities:
- clone to(/from) template
- clone to datastore or storagepod
- folder and resourcepool support
Ability to:
- poweron 
- change cpu or memory
- cutomize via named customization spec
- waitfor ip (if powering on)
=> Add virtualmachine clone to govc

object/virtual_device_list.go
VirtualEthernetCard.AddressType is an optional field, no need to set it
to generated in this helper.
Fixes #492
=> Leave AddressType empty in EthernetCardTypes

object/virtual_machine.go
This commit adds a call to the RemoveAllSnapshots task for a given VM, similar to what can be accomplished in pyvmomi.
=> Added Remove All Snapshot task to Virtual Machine

vim25/mo/type_info.go, vim25/xml/read.go
These are for decoding responses from the in-progress govmomi simulator.  The proper fixes will be more involved, but these small changes have no impact on the non-simulator paths.
=> SOAP decoding fixes

object/datastore.go
This helper was originally optimized within govc to just check if a file
exists.  It isn't much more overhead to get the additional details for a
single file, add the full set for convenience.
=> Get complete file details in Datastore.Stat

govc/importx/ovf.go
In addition to working with ESX, `InjectOvfEnv()` should work with VSphere.
This change causes `govc` to show "Injecting OVF environment..." when using `import.ovf` with the `-options` flag.
However, it doesn't seem to actually *set* the environment variables... The VSphere web-ui still shows no properties being set. :-(
=> InjectOvfEnv() should work with VSphere

CHANGELOG.md, govc/CHANGELOG.md, govc/datastore/mkdir.go, govc/datastore/rm.go, govc/test/datastore.bats, object/namespace_manager.go
VSAN uses uuids to refer to dirents.  Being able to use them directly vs
using their display names is helpful.
=> Support mkdir/rm of namespace on vsan

govc/test/vm.bats, govc/vm/create.go
When -disk.controller and -disk flags are provided, the lookup of a scsi
controller needs to be by device name, not type name.
Fixes #515
=> Fix vm.create disk scsi controller lookup

CONTRIBUTING.md, govc/CHANGELOG.md, govc/README.md, govc/test/cli.bats, govc/version/command.go
The version is now hardcoded, rather than injected by the linker.
=> Add -require flag to govc version command

CHANGELOG.md, govc/CHANGELOG.md, govc/version/command.go, object/common.go, object/common_test.go
These methods need a service ticket, which when run against VC uses the
ObjectName of the selected HostSystem as the URL host.  The Name()
method was returning path.Base(InventoryPath), which defaults to ".",
when we should return an empty string in that case.
Caused by commit 558321d
=> Fix Datastore upload/download against VC

object/datastore.go
The service ticket HostName to use for http access might be different
than the HostSystem.Name used to request the ticket.
=> Use ticket HostName for Datastore http access

find/finder.go, govc/ls/command.go, govc/test/ls.bats, object/common.go, vim25/mo/ancestors.go, vim25/mo/extra.go, vim25/types/helpers.go
In most cases, Finder is used to find a ManagedObjectReference via
InventoryPath.  This change makes the inverse possible, to find the
InventoryPath via a ManagedObjectReference.
=> Add support for Finder lookup via moref

CHANGELOG.md, govc/vm/markastemplate.go, govc/vm/markasvm.go
Add function to govc 'vm' command to mark a VM as a template. Tested OK on vSphere 5.5.
=> Add vm.markastemplate

object/datastore.go
Main use case currently is the govcsim, so turn this option off by
default.  Can be enabled using env or url query string.
Related commits: ff7b5b0, c26c797
=> Disable datastore service ticket hostname usage

govc/importx/ovf.go
On OVF import bind network adapters to the networks specified in the
OVF envelope if they exist on the target.
=> Populate network mapping from ovf envelope

govc/importx/options.go, govc/importx/ovf.go, govc/importx/spec.go
=> govc importx - add more options

govc/flags/search.go
Common InventoryPath field is not initialized in the new objects
returned by SearchIndex - for now do it in the SearchFlag
=> govc - popualte 'Path' fiels in xxx.info output

govc/vm/clone.go
This copies the same behaviour as vm.create and fetches the datastore name.
Otherwise, there's methods called on the datastore object (datastore.Stat) that panic due to the name not being available. Example:
```
$ govc vm.clone -vm=templates/template test_template
panic: expected non-empty name
goroutine 1 [running]:
panic(0xaceb40, 0xc4204361d0)
/home/saracen/go/src/runtime/panic.go:500 +0x1a1
github.com/vmware/govmomi/object.Datastore.Path(0x0, 0x0, 0xc42007db80, 0xc420222d40, 0x9, 0xc420222d60, 0xe, 0xc420435900, 0xa, 0xc4203dca00, ...)
/home/saracen/go_workspace/src/github.com/vmware/govmomi/object/datastore.go:72 +0x1ea
github.com/vmware/govmomi/object.Datastore.Stat(0x0, 0x0, 0xc42007db80, 0xc420222d40, 0x9, 0xc420222d60, 0xe, 0x7fbf3e63c028, 0xc4200122d8, 0xc420435900, ...) …
```
=> Fix missing datastore name with vm.clone -force=false

govc/device/usb/add.go, govc/main.go, govc/test/device.bats
Supports adding USB controllers to VMs.
Fixes #569
=> Add device.usb.add command

object/virtual_machine.go
This is a simple addition to object/virtual_machine.go to to allow for unregistering a VM.
=> Add VirtualMachine.Unregister func

govc/flags/optional_bool.go, govc/flags/optional_bool_test.go
Introduced by go1.7, but the extra check doesn't hurt in any case.
Fixes #577
=> Fix flags.NewOptionalBool panic

object/virtual_device_list.go
Adding defensive checks against nil result from reflect.TypeOf before dereferencing the returned type.
=> Checking result of reflect.TypeOf is not nil before continuing

govc/test/device.bats, object/virtual_device_list.go
- Don't use the SCSI controller's own unit number
- Use the first available unit number, rather than current max + 1
Fixes #552
=> Fix SCSI device unit number selection

object/virtual_device_list.go
CreateSCSIController needs to set the default ScsiCtlrUnitNumber,
otherwise newUnitNumber considers UnitNumber 0 in use.
See PR #588
=> Set default ScsiCtlrUnitNumber

govc/cli/command.go, govc/test/cli.bats
If a '-h' flag is given to govc, output help to stdout and exit with 0.
All other usage errors continue to use stderr and exit with 1.
Fixes #534
=> Add govc -h flag

govc/about/cert.go, govc/flags/client.go, govc/flags/host_connect.go, object/datastore.go, object/host_certificate_info.go, vim25/soap/client.go
Generalize certificate thumbprint validation such that we can use it for
any number of user specified hosts and transparently for service
ticketed hosts.
- Rename host.add/cluster.add 'fingerprint' flag to 'thumbprint'
- Update use of http.DefaultTransport fields to 1.7
- Add -version flag to about.cert command
=> Add service ticket thumbprint validation

govc/device/serial/connect.go, object/virtual_device_list.go, object/virtual_device_list_test.go
This PR adds functionality to device.serial.connect to specify a vSPC proxy URI
=> Adding vSPC proxyURI to govc

session/manager.go
We use to vcenter. If we display performance metrics using the default *NewClient* method, we retrieve metrics in French in one vcenter and in English on the second.
We use : 
```go
govmomi.NewClient(ctx, url, insecureFlag)
``` 
and:
```go
for _, vcenter := range VCenters {
fmt.Printf("== vCenter: %s ==\n", vcenter.Host)
for _, perfCounterInfo := range vcenter.PerfManager.PerfCounter {
groupInfo := perfCounterInfo.GroupInfo.GetElementDescription()
nameInfo := perfCounterInfo.NameInfo.GetElementDescription()
metricName := fmt.Sprintf("%s_%s_%s", namespace, snaker.CamelToSnake(groupInfo.Key), strings.Join(strings.Split(snaker.CamelToSnake(nameInfo.Key), "."), "_"))
fmt.Printf("%s: %s\n", metricName, nameInfo.Summary)
}
}
}
```
Without patch : 
```bash
vsphere_sys_uptime: Total time elapsed, …
```
=> Localization : Set default locale to en_US

govc/cluster/add.go, govc/flags/host_connect.go, govc/host/add.go
When using the '-noverify' flag, use the new object.HostCertificateInfo
helper to get the thumbprint, rather than re-trying the task with the
thumbprint from SSLVerifyFault.
GOVC_TLS_KNOWN_HOSTS can also be used to specify host thumbprints.
=> Improve cluster/host add thumbprint support

object/common.go, object/host_config_manager.go
Avoids panic when used against version that does not support fields
added in 5.5 and 6.0 versions.
Fixes #602
=> Add HostConfigManager field checks

govc/test/vm.bats, govc/vm/snapshot/tree.go
Instead of panic (since Snapshot==nil), exit 0 with no output.
Fixes #611
=> Fix snapshot.tree on vm with no snapshots

CHANGELOG.md, govc/CHANGELOG.md, govc/flags/version.go, govc/test/datastore_tail_test.sh, object/datastore_file.go
If the caller's buffer size is smaller than remaining request body, the
caller would miss data.
Return io.EOF if the file has gone away when we wake up in the poll
loop.
See PR #598
=> Allow DatastoreFile follower to drain current body

govc/CHANGELOG.md, govc/USAGE.md, govc/dvs/create.go
If DVS is created without this flag, only hosts with version >= the VC
version can be added to the DVS by default.
=> Add -product-version flag to dvs.create

CHANGELOG.md, govc/CHANGELOG.md, govc/vm/create.go, object/virtual_device_list.go
Requires vim-version set to 6.5 either via vim-version flag or via
GOVC_VIM_VERSION environment variable. Eg;
```
govc vm.create -vim-version=6.5 -on=false -ds=SSD -net "VM Network" -m 2048 -c 2 -g "vmkernel65Guest" -net.adapter=vmxnet3 -disk.controller nvme esxi
```
=> Add basic VirtualNVMEController support

vim25/soap/client.go
`http.Transport.CancelRequest` is deprecated, and `http.Request.WithContext` should be used instead.
The motivation for this change is that there appears to be a connection leak somewhere in govmomi where it doesn't close response bodies, leaving connections and goroutines leaked. We're running a long-running server that interacts with vSphere fairly regularly, and whenever we have requests that get their contexts cancelled, the goroutine count goes up and the number of open TCP connections to our vSphere API goes up. After digging through the code, I found that this is the only place where HTTP requests are made, and as far as I can see if `soap.Client.do` returns a response, then `soap.Client.Do` will `defer res.Body.Close()`. So, then my guess is that `http.Client.Do` returns a …
=> Attach context to HTTP requests for cancellations

govc/version/command.go
The comparison skips it, so if you set `flags.Version` to `v1.2.3` you can get confusing messages like "version mismatch: git=v1.2.3 vs govc=v1.2.3".
=> govc/version: skip first char in git version mismatch error

govc/USAGE.md, govc/emacs/govc.el, govc/ls/command.go, govc/object/collect.go, govc/test/ls.bats, govc/test/object.bats, property/wait.go, vim25/methods/service_content.go, vim25/mo/ancestors.go
Generic interface to the property.Wait method, where properties can be collected from any managed object.
Emacs interface provides MOB (Managed Object Browser) functionality.
=> Add object.collect command

govc/test/vm.bats, govc/vm/change.go, govc/vm/info.go
This PR adds support for reading and changing SyncTimeWithHost option of ToolsConfigInfo with govc. The example is as follows.
```
$ govc vm.change -h
Usage: govc vm.change [OPTIONS]
Options:
-c=0                                      Number of CPUs
-cert=                                    Certificate [GOVC_CERTIFICATE]
-dc=                                      Datacenter [GOVC_DATACENTER]
-debug=false                              Store debug logs [GOVC_DEBUG]
-dump=false                               Enable output dump
-e=[]                                     ExtraConfig. <key>=<value>
-g=                                       Guest OS
-json=false                               Enable JSON output
-k=true                                   Skip verification of server certificate …
```
=> Add support for reading and changing SyncTimeWithHost option

govc/vm/clone.go, govc/vm/create.go
govc does not provide command line options to describe a VM.
Using the annotation field in VirtualMachineConfigSpec, vm.create and vm.clone now both have this option.
=> Add the option to describe a VM using the annotation option

govc/USAGE.md, govc/test/vm.bats, govc/vm/ip.go, object/virtual_machine.go
With this option, WaitForNetIP can specify NIC(s) by MAC address or device name.
Fixes #653
=> Add device option to WaitForNetIP

govc/main.go, govc/vm/rdm/attach.go, govc/vm/rdm/ls.go, object/virtual_machine.go
govc does not provide command line options to:
- attach RDM using the device name.
- list available devices for a specific VM, retrieving various useful information ( UIDS, Device name, Device path, ... )
=> Attach and list RDM/LUN

govc/vm/disk/change.go
I needed the ability to resize a VM disk once it has been created, so I made a new command: "vm.disk.change".
It allows search of a disk using its name, label, key or even the file path to the vmdk.
It only changes the size, and the mode.
=> Add a command line option to change an existing disk attached to a VM

task/wait.go
Property collector returns nil when it cannot find the task, handle
that case in the Error method which gets called by callback. Otherwise
we panic.
Towards https://github.com/vmware/vic/issues/3868
=> Handle nil TaskInfo in task.Wait callback

task/wait.go, task/wait_test.go
We loop over []types.PropertyChange slice and look for a certain name,
op and value before setting t.info.
t.info could be nil if we can't find a PropertyChange that fits into ruleset.
Handle that and also add a test to test that.
=> Handle nil TaskInfo in task.Wait callback #2

govc/vm/markastemplate.go, govc/vm/markasvm.go
The vm.markasvm command had required the host flag,
but it is optional in the API.
Add the pool flag to avoid specifying a host.
=> Host is optional for MarkAsVirtualMachine

object/datastore_file.go
This removes the deferred call to `Close()` in the datastore file follower's `Read()` method. This prevents `Close()` from being called prematurely when `EOF` is not encountered after a read.
=> Remove deferred Close() call in follower's Read()

govc/USAGE.md, govc/emacs/govc.el, govc/flags/version.go, govc/main.go, govc/metric/change.go, govc/metric/info.go, govc/metric/interval/change.go, govc/metric/interval/info.go, govc/metric/ls.go, govc/metric/performance.go, govc/metric/reset.go, govc/metric/sample.go, govc/test/metric.bats, govc/test/metric_info_test.sh, performance/manager.go, vim25/types/helpers.go
* Convert counter IDs to and from stable names, with caching
* Query available metrics, per resource type and interval
* Query N metric samples by name for N resource instances
* Change level per historical interval and per counter
=> Add performance manager and govc metric commands

find/doc.go, find/finder.go, find/recurser.go, govc/device/info.go, govc/importx/archive.go, govc/test/ls.bats
- Use path.Match everywhere, not filepath.Match
=> Finder: support changing object root in find mode

find/finder.go, object/opaque_network.go, vim25/mo/ancestors.go
While OpaqueNetwork extends the Network type, it requires a backing of type
VirtualEthernetCardOpaqueNetworkBackingInfo
=> Implement EthernetCardBackingInfo for OpaqueNetwork

govc/CHANGELOG.md, govc/vm/ip.go
- Default to 1hr (previous default was infinite)
- Don't error or print anything when time has expired
=> Use Duration flag for vm.ip -wait flag

gen/vim_wsdl.rb, vim25/methods/methods.go, vim25/mo/mo.go, vim25/types/enum.go, vim25/types/if.go, vim25/types/types.go
We were a bit behind as the previous generation was prior to
vmware/rbvmomi@f6907e6
=> Regenerate against current vmodl.db

pbm/client.go, pbm/client_test.go, pbm/pbm_util.go
Added additional wrapper functions for PBM support in govmomi. The below functionalities are included.
-  GetCompatibleDatastores
-  GetNonCompatibleDatastores
-  CreatePbmCapabilityProfileSpec
-  CreatePbmProfile
-  UpdatePbmProfile
-  DeletePbmProfile
-  QueryAssociatedEntity
-  QueryAssociatedEntities
-  GetPbmProfileIDByName
I have also included unit tests for all the above PBM functions. 
Current support is added for CREATING following PBM profiles:
1. VSAN profile.
2. VSAN + SIOC profile.
3. Tag Based profile.
@dougm : Please take a look.
@divyenpatel @tusharnt @pdhamdhere
=> PBM Support in govmomi - Additional PBM functionality

object/virtual_machine.go
I have exported FindSnapshot() so that other packages will be able to access it.
=> Exported FindSnapshot() Method

govc/host/autostart/add.go
This is to allow for per VM config to the HostAutoStartManager.
Also useful to configure an ordered auto startup.
Example:
govc host.autostart.add  -start-order=1 -start-delay=5 vm1 vm2
govc host.autostart.add  -start-order=3 -start-delay=30 vm3
Tested on ESXi 6.0.0
=> Add options to host.autostart.add

object/datastore_file.go
Fixes a small bug where tail called with n == 0 outputs one line.
=> Fix tail n=0 case

object/datastore_file.go
This change slides the slice window one element to the right before passing the string into the `include` function. Previously, the string being passed in was `\nmessage` and is now adjusted to `message\n`.
It also fixes a small bug where a single line was returned even if a `tail` value of `0` was specified.
=> Adjust message slice passed to include

gen/vim_wsdl.rb, govc/USAGE.md, govc/flags/int32.go, govc/test/guest_operations_test.sh, govc/vm/guest/chown.go, govc/vm/guest/file_attr.go, govc/vm/guest/ls.go, govc/vm/guest/mktemp.go, govc/vm/guest/mv.go, govc/vm/guest/touch.go, guest/file_manager.go, vim25/types/types.go
- Remove FileAttr flags from guest.chmod command,
chown functionality moved to its own command
- GuestPosixFileAttributes OwnerId and GroupId fields are now pointers,
rather than omitempty ints to allow chown with root uid:gid
- Add optional path to guest mktemp file methods
- Add guest.touch and guest.mv commands
=> Guest command updates

vim25/types/types.go
[VMware API Doc](https://www.vmware.com/support/developer/vc-sdk/visdk41pubs/ApiReference/vmodl.query.PropertyCollector.WaitOptions.html#maxWaitSeconds) says :
> Data Object - WaitOptions
> field maxWaitSeconds (xsd:int)
> - An unset value causes WaitForUpdatesEx to wait as long as possible for updates.
> - A value of 0 causes WaitForUpdatesEx to do one update calculation and return any results.
> - A positive value causes WaitForUpdatesEx to return null if no updates are available within the specified number of seconds.
As of today the field MaxWaitSeconds in struct WaitOptions is of type **int32** and with tag option **omitempty**. This causes the value 0 to be ignored, and thus the 2nd case listed is not possible.
I changed its type to ***int32** and removed the option **omitempty**. …
=> Fix the WaitOptions struct

gen/vim_wsdl.rb, vim25/types/types.go
This preserves the manual changes made in PRs #738 and #741
to remove omitempty tags from:
- OptionValue.Value
- MaxWaitSeconds WaitOptions
=> Update wsdl generator

simulator/model.go, simulator/virtual_machine.go, simulator/virtual_machine_test.go
Folder.CreateVM does not add these devices, but they are common to need for
testing against the Model VMs.
Fixup (negative) generated device keys to avoid conflicts.
=> vcsim: Add cdrom and scsi controller to Model VMs

vcsim/README.md
Fix corrects the path of vcsim described in README quickstart
guide.
=> Minor correction in README.md

find/recurser.go, govc/emacs/govc.el, govc/test/vm.bats, object/common.go, object/network.go, property/filter.go
This only supports leaf nodes in the inventory path.
For example a Network named "my-net/work".
However, this change does not handle parents containing a '/'.
For example Datacenter named "my-data/center" and Cluster named "my-clus/ter",
these paths will not work:
/my-data/center/vm/my-vm
host/my-clus/ter/my-host
Fixes #592
=> Handle object names containing a '/'

govc/vm/guest/run.go, guest/process_manager.go, guest/toolbox/client.go, toolbox/command.go, toolbox/hgfs/server.go, toolbox/process.go, toolbox/process_test.go, toolbox/service.go, toolbox/service_test.go, toolbox/toolbox-test.sh
Add guest/toolbox.Client that implements http.RoundTripper and
Run method that behaves like exec.Cmd.Run
=> toolbox: add http and exec round trippers

README.md, govc/vm/guest/run.go, property/collector.go, toolbox/README.md, toolbox/command.go, toolbox/command_test.go, toolbox/hgfs/archive.go, toolbox/hgfs/archive_test.go, toolbox/hgfs/protocol.go, toolbox/hgfs/server.go, toolbox/hgfs/server_test.go, toolbox/process.go, toolbox/service.go, toolbox/service_test.go, toolbox/toolbox-test.sh, vcsim/README.md
Directory archive behavior can now be customized via hgfs.ArchiveRead and hgfs.ArchiveWrite
Follow on to PR #763, moving existing code behind the new hgfs.FileHandler interface:
- Transfer of /proc files
- Directory archive support
Fixes:
- Directory upload would hang if data was not in gzip'd tar format
- Log hgfs and vix errors regardless of Trace being enabled
- Doc updates
=> toolbox: make directory archive read/write customizable

toolbox/hgfs/archive.go, toolbox/hgfs/server.go, toolbox/toolbox-test.sh
The url.URL.Query is intended for use as optional params to these methods.
=> toolbox: pass URL to ArchiveHandler Read/Write methods

toolbox/command_test.go, toolbox/vix/protocol.go
Before:
```bash
% govc guest.run h8ctl
govc: ServerFaultCode: A general system error occurred: vix error codes = (1, 0).
```
```xml
<soapenv:Fault>
<faultcode>ServerFaultCode</faultcode>
<faultstring>A general system error occurred: vix error codes = (1, 0).</faultstring>
<detail>
<SystemErrorFault xmlns="urn:vim25" xsi:type="SystemError">
<reason>vix error codes = (1, 0).</reason>
</SystemErrorFault>
</detail>
</soapenv:Fault>
```
After:
```bash
% govc guest.run h8ctl
govc: ServerFaultCode: File h8ctl was not found
```
```xml
<soapenv:Fault>
<faultcode>ServerFaultCode</faultcode>
<faultstring>File h8ctl was not found</faultstring>
<detail>
<FileNotFoundFault xmlns="urn:vim25" xsi:type="FileNotFound">
<file>h8ctl</file>
</FileNotFoundFault>
</detail>
</soapenv:Fault>
```
=> toolbox: map exec.ErrNotFound to vix.FileNotFound

toolbox/service.go, toolbox/service_test.go, toolbox/toolbox-test.sh
We send the IP (and NIC info) in response to the broadcastIP request.
There can be ~30 seconds between the Reset request (1st call) and the broadcastIP request.
For existing VMs, the IP/NIC info is cached in the vmdb and doesn't take as long.
With this change, the IP/NIC info is pushed asap and takes < 1 second
Before:
```
guest.toolsStatus  types.VirtualMachineToolsStatus  toolsOk
Waiting for VM ip from toolbox...30.01
```
After:
```
guest.toolsStatus  types.VirtualMachineToolsStatus  toolsOk
Waiting for VM ip from toolbox...0.06
```
=> toolbox: SendGuestInfo before the vmx asks us to

object/datastore_file.go
Allow repeated calls to Close for datastore file follower without panic.
=> Tolerate repeated Close for file follower

event/processor.go, govc/object/collect.go, govc/object/find.go, govc/test/object.bats, property/wait.go, toolbox/toolbox-test.sh, view/container_view.go, view/list_view.go, view/managed_object_view.go
Refactor property wait related methods:
- Add property.WaitFilter helper
- Expose a more generic property.WaitForUpdates
- Remove property.WaitForView (use property.WaitForUpdates instead)
- Refactor event collector to use property.WaitForUpdates
- Add TraversalSpec method to *View types
=> Add view and filter support to object.collect command

guest/toolbox/client.go, toolbox/process.go, toolbox/process_test.go, toolbox/toolbox-test.sh
Prior to this change, if toolbox.Client.Run started a command that
took longer than a minute to run, it would timeout with:
govc: ServerFaultCode: A general system error occurred: vix error codes = (3016, 0).
With the fault type returned in this case, the client can retry, rather than having to poll
for process status.
=> toolbox: avoid blocking the RPC channel when transferring process IO

govc/vm/guest/download.go, guest/toolbox/client.go, toolbox/hgfs/archive.go, toolbox/hgfs/archive_test.go, toolbox/toolbox-test.sh
In the download case, the "format" query param can be used to specify "tgz" or "tar".
In the upload case, toolbox checks for the gzip header to auto-detect tgz or tar.
=> toolbox: make gzip optional for directory archive transfer

govc/host/info.go
Fix adds information about host's maintenance mode in
host.info command.
Fixes: #771
=> Add info about maintenance mode in host.info

govc/vm/migrate.go
The pool is required if the target host is in a different pool than the current.
=> Default vm.migrate pool to the host pool

govc/device/info.go, govc/test/device.bats
The VirtualDevice type does not have the "Name" field, so we have to inject it via MarshalJSON.
Fixes #823
=> Include "Name" in device.info -json

toolbox/backdoor.go, toolbox/service.go, toolbox/service_test.go
Seen cases where ESX is under heavy load and the toolbox session
cookie is invalidated by the vmx.
This change will backoff the polling loop and also re-open the message
channel to get a new session cookie.
On the guest side, this resulted in a flood of:
Message: Unable to send a message over the communication channel 0
Message: Unable to poll for messages over the communication channel 0
On the vmx site (vmware.log), this resulted in a flood of:
GuestMsg: Channel 0, Protocol error, state: 0
GuestMsg: channel 0: wrong cookie, discarding message.
=> toolbox: reset session when invalidated by the vmx

toolbox/service.go, toolbox/toolbox-test.sh
It was possible for the Stop() method close the RPC channels when
the main loop was in the middle of Send/Receive.
=> toolbox: avoid race when closing channels on stop

object/distributed_virtual_portgroup.go, simulator/dvs.go, simulator/folder.go
The DVS EthernetCardBackingInfo method was originally written to use the
mo.VmwareDistributedVirtualSwitch type due to a limitation that required
the Go type to be the same as the managed object type.
That limitation was fixed in b34f346, allowing for use of base types.
The simulator also uses the base DistributedVirtualSwitch type now to cover that case.
Fixes #843
=> Use base type for DVS backing info

simulator/datastore.go, simulator/os_unix.go, simulator/os_windows.go
The datastore usage is not used by existing tests,
it is just a cosmetic bonus when running govc datastore.info against vcsim.
Fixes #775
=> vcsim: remove use of df program for datastore info

simulator/virtual_machine.go, simulator/virtual_machine_test.go
The Model creates a VirtualDisk for each VM as of defe810, but did not set the disk backing Datastore field.
This field is not optional in the wsdl, Go tolerates this, Python does not.
Fixes #856
=> vcsim: set VirtualDisk backing datastore

object/custom_fields_manager.go
Add new type 'CustomFieldDefList' of type '[]types.CustomFieldDef'.
Change the 'CustomFieldManager.Field' method signature so it returns
the new 'CustomFieldDefList' type. This makes it possible to attach
methods on top of the 'CustomFieldDefList' to search the list. This is
not a breaking change because the underlying type is still
'[]types.CustomFieldDef'.
Add 'CustomFieldDefList.ByKey' method to find a 'CustomFieldDef' by the
'Key' attribute.
Resolves: #854
=> Add method to find a CustomFieldDef by Key

object/custom_fields_manager.go
Rename string input argument from 'key' to 'name'.
The FindKey method returns the key of a given CustomFieldDef. The
search is performed by comparing the input string argument with
each CustomFieldDef 'Name' attribute. Therefore, the input string
argument must be named 'name' instead of 'key'.
Resolves: #864
=> Fix CustomFieldsManager.FindKey method signature

govc/device/boot.go, govc/test/device.bats, object/virtual_device_list.go, object/virtual_device_list_test.go
The device.boot command and VirtualDeviceList.BootOrder can now clear any existing boot order by using DeviceTypeNone.
=> Support clearing vm boot order

simulator/virtual_machine.go, simulator/virtual_machine_test.go
Issue #868 added default behavior for the VirtualDisk backing FileName,
but left the assumption that the Datastore field was also set.
Also remove a few go lint/vet warnings.
Fixes #871
=> vcsim: VirtualDisk file backing datastore is optional

find/recurser.go, govc/test/ls.bats
PR #734 (commit b35abbc) added support for matching object names containing a '/',
but introduced a bug where any suffix would match regardless.
Fixes #815
=> Fix object name suffix matching in Finder

govc/test/vm.bats, govc/vm/register.go, simulator/folder.go, simulator/folder_test.go
- The "as-template" flag has been renamed "template" (as we have in the vm.clone command)
- Add RegisterVm template support to vcsim
- Simplify the vm.register code
Fixes #872
=> Fix vm.register command template flag

govc/events/command.go, govc/test/events.bats
With d4d94f4, 'govc events' outputs the following due to Printf usage:
"[[Fri Oct 13 01:15:06 2017 info User root@192.168.2.1 logged in as govc/0.15.0]] [%!s(MISSING)] %!s(MISSING)"
- Change json field names to uppercase, as we do with other govc commands
- Add "Object" field to json and avoid printing the object header when '-json' is given
- Use time.Time for '-json', as we do in other commands
- A few renames
- CreatedAt -> CreateTime (same as the Event field name, other types use this name too)
- "write" -> "print" (other commands use "write")
- "ev" -> "record"
=> Fix govc events output

govc/test/snapshot.bats, govc/test/vm.bats, govc/vm/clone.go, govc/vm/snapshot/tree.go, object/virtual_machine.go
This is PR #762 with the following changes:
The vm.clone '-link' flag behaves similar to the '-link' flag in other commands, a bool.
The vm.clone '-snapshot' link requires an argument
Add '-C' option to snapshot.tree to print just the name of the current snapshot
Change VirtualMachine.FindSnapshot to return *types.ManagedObjectReference instead of object.Reference
Closes #762
=> Add linked clone and snapshot support to vm.clone

govc/export/ovf.go, govc/main.go, govc/test/export.bats, govc/vm/guest/download.go, nfc/lease.go, nfc/lease_updater.go, object/virtual_machine.go, vim25/soap/client.go
Follow up to #805 - depends on the ovf+nfc lease code moved
from govc import.ovf cli to higher level packages.
Fixes #692
=> Add support for VM export

govc/permissions/remove.go, govc/test/role.bats, simulator/authorization_manager.go
- Implement RemoveEntityPermission, SetEntityPermissions, RetrieveRolePermissions
- Maintain a map to fetch and store permissions, rather than hardcode
- rename "nextId" to "nextID" (avoids go-lint complaint)
=> vcsim: AuthorizationManager additions

gen/gen_from_vmodl.rb, gen/vim_wsdl.rb, govc/pool/change.go, govc/pool/info.go, govc/pool/resource_config_spec.go, simulator/esx/resource_pool.go, simulator/resource_pool.go, simulator/resource_pool_test.go, vim25/types/helpers.go, vim25/types/if.go, vim25/types/types.go
VrpResourceAllocationInfo has been removed in 6.7, so the BaseResourceAllocationInfo
interface is no longer needed.
We already made a breaking ResourcePool related change cc2ed7d,
want to do this before the next govmomi release even though 6.7 has yet to be released.
=> Remove BaseResourceAllocationInfo

govc/importx/options.go, govc/importx/spec.go, govc/test/import.bats
We used to forcefully assign deploymentOption among [small, medium, large]
when we call import.spec on an ova/ovf that doesn't include
deploymentOption. This could generate an option file that cannot be
accepted by import.ova or import.ovf. After this change we only assign
deploymentOption when it's included in ova/ovf file.
Fixes #487
=> import.spec not to assign deploymentOption

govc/test/vm.bats, simulator/model.go, simulator/virtual_machine_test.go, vcsim/main.go
When a VM is created, the power state is off.  The autostart option will call vm.PowerOn when true.
Related: #900
=> vcsim: add autostart option to power on VMs

govc/README.md
Just a little markdown cleanup.
=> readme: fix formatting of listing

govc/flags/client.go, govc/test/cli.bats
In the case of overriding http.DefaultTransport connection params, let's just provide the option(s) via environment
variables for now and not add new flags yet.
=> Remove tls-handshake-timeout flag

simulator/ip_pool_manager.go
IpPoolManager.pools is a map, so order is not guaranteed.  The test would sometimes fail with:
ip_pool_manager_test.go:276: expect query result equal to ...
=> vcsim: preserve order in QueryIpPools

govc/USAGE.md, govc/flags/resource_allocation_info.go, govc/flags/version.go, govc/pool/resource_config_spec.go, govc/test/vm.bats, govc/vm/change.go, simulator/resource_pool.go, simulator/resource_pool_test.go, simulator/virtual_machine.go, simulator/virtual_machine_test.go
Refactored resource pool related flags and simulator so we can use the same logic
for VirtualMachine resource allocation.
=> Add support for cpu + mem allocation to vm.change command

object/virtual_disk_manager_internal.go
Handle method response namespace change in 6.7
=> CreateChildDisk 6.7 support

govc/test/object.bats, simulator/virtual_machine.go
We set the default to 1 in the spec, but did not apply to the config.
Fixes #929
=> vcsim: apply vm spec NumCoresPerSocket

simulator/file_manager.go
Go ignores the empty response, but Python requires it.
Fixes #937
=> vcsim: add MakeDirectoryResponse

govc/USAGE.md, govc/host/shutdown.go
host.shutdown expects HOST as an argument.
=> Corrects host.shutdown

govc/USAGE.md, govc/vm/info.go
Generated `USAGE.md` with `make docs`. Also added some examples
=> Corrects vm.info usage with required args

govc/USAGE.md
Noticed whilst adding vm.info usage in PR https://github.com/vmware/govmomi/pull/950 that datastore.info had not been generated as part of https://github.com/vmware/govmomi/pull/943 so this is a commit of the generated docs
=> Corrects datastore.disk usage which had not been generated

toolbox/command.go, toolbox/command_test.go
The ListFiles handler assumed the 'offset' param was always valid.
It could be invalid if client-side logic is wrong or directory contents have shrunk in between calls.
Either way, we reply with '0' remaining files in this case as open-vm-tools does.
Fixes #934
=> toolbox: validate request offset in ListFiles

gen/Gemfile, gen/Gemfile.lock
without the fix, I have this error:
```console
./gen.sh 
/home/anfernee/go/src/github.com/vmware/govmomi/gen/vim_wsdl.rb:16:in `require': cannot load such file -- test/unit (LoadError)
from /home/anfernee/go/src/github.com/vmware/govmomi/gen/vim_wsdl.rb:16:in `<top (required)>'
from gen_from_wsdl.rb:17:in `require'
from gen_from_wsdl.rb:17:in `<main>'
```
=> Add missing dependency in gen script

simulator/property_collector_test.go, simulator/simulator.go, simulator/simulator_test.go
=> vcsim: workaround xml ns issue with pyvsphere

simulator/host_local_account_manager.go, simulator/host_local_account_manager_test.go, simulator/service_instance.go
Support CUD operations on users. Groups operations are not supported
because they are deprecated in 5.1
Fix #947
=> vcsim: Add HostLocalAccountManager

event/manager.go, event/processor.go
The EventHistoryCollector objects are tied to a session and there is a max per-session.
Without destroying the collectors, we could max out the collectors causing 'govc events' to return empty.
Fixes #948
Fixes #961
=> Destroy event history collectors

govc/test/vm.bats, simulator/virtual_machine.go, simulator/virtual_machine_test.go
Including NestedHVSupported and other values, putting them into vm.Config if they are not nil.
Fix #956
=> vcsim: Honor the input spec in ReConfig VM

object/datastore.go
Avoids a possible panic when waiting for SearchDatastore to complete.
=> Use IsFileNotFound helper in Datastore.Stat

govc/CHANGELOG.md, govc/vm/guest/auth.go
fixes #971 by using SplitN instead of Split and so keeping columns in the password.
=> govc: allow columns in guest login password

simulator/virtual_machine.go
Initialize VM fields with the correct structs, so PropertyCollector can
find and retrieve it for clients.
Fix #968
=> vcsim: Initialize VM fields properly

event/manager.go, event/processor.go, govc/events/command.go, govc/test/events.bats
Filtering specific event types reduces the chance of missing events,
while keeping the event history collector page size on the low side.
=> Add option to filter events by type

govc/USAGE.md, govc/cluster/change.go, govc/cluster/override/change.go, govc/cluster/override/info.go, govc/cluster/override/remove.go, govc/cluster/rule/create.go, govc/main.go, govc/test/cluster.bats, simulator/cluster_compute_resource.go
- Add cluster.override.change command to set VM DRS and HA overrides
- Add cluster.override.remove to remove VM overrides
- Add cluster.override.info to view current VM overrides
- Add cluster.rule.create '-depends' flag to support VM-to-VM dependency rules
=> Add cluster vm override commands

govc/test/vm.bats, simulator/folder_test.go, simulator/property_collector.go, simulator/property_collector_test.go, simulator/registry.go, simulator/session_manager.go, simulator/session_manager_test.go, simulator/simulator.go, simulator/simulator_test.go, simulator/view_manager.go
Sessions are now tracked across requests, supporting per-session managed objects such as
PropertyCollector, PropertyFilter, ContainerView and the SessionManager itself.
Adds TerminateSession() support and includes proper support for Logout()
Fixes #923
=> vcsim: add session support

govc/flags/client.go, govc/session/login.go, govc/session/logout.go, govc/test/session.bats, govc/test/vcsim.bats, simulator/session_manager.go, simulator/session_manager_test.go, simulator/simulator.go, vcsim/README.md, vim25/soap/client.go
- Fix simulator.Service.About to support optional context param
- Don't require govc Login, ServiceContent does not require it
=> Add CloneSession support to govc and vcsim

govc/host/info.go
Need to use CPU threads as the logical processor count, rather than CPU cores.
=> govc: fix host.info CPU usage

gen/vim_wsdl.rb, vim25/types/types.go, vim25/types/types_test.go
Avoids the an issue where Go will omit array elements with a value of '0'.
Fixes #1008
=> Remove omitempty tag from AffinitySet field

Makefile, govc/test/vcsim.bats, simulator/cluster_compute_resource.go, simulator/custom_fields_manager.go, simulator/dvs.go, simulator/folder.go, simulator/host_datastore_system.go, simulator/model.go, simulator/portgroup.go, simulator/property_filter.go, simulator/race_test.go, simulator/registry.go, simulator/registry_test.go, simulator/resource_pool.go, simulator/session_manager.go, simulator/simulator.go, simulator/snapshot.go, simulator/view_manager.go, simulator/virtual_machine.go, simulator/virtual_machine_test.go, vcsim/main.go
The method call dispatcher locks the receiver object, so methods do not need to explicitly do so.
However, methods that touch other objects need to use the Registry WithLock method or helpers that use it underneath.
We may still need to cover some other paths, such as reading within PropertyCollector.  And we can fine tune to opt-out of
locking where it isn't needed.  But the race detector is happier now as-is.
Fixes #990
=> vcsim: avoid data races

govc/importx/archive.go, govc/logs/download.go, govc/vm/console.go, govc/vm/guest/download.go, govc/vm/guest/touch.go, guest/toolbox/client.go, nfc/lease.go, object/datastore.go, object/datastore_file.go, vim25/progress/reader.go, vim25/progress/reader_test.go, vim25/soap/client.go
I hope this finds you well. I am working on a deploy tool to deploy to ESX hosts, I am learning that many of the contexts I pass are not used at lower levels. In short, I am using contexts in a signal handler to reap deploys on termination. It's just not doing that right now. ;)
I attempted to add this to the upload and lease calls so I can get moving on my own project. I hope it finds you well.
I use `(*http.Request).WithContext` to store the context with the request itself, and in other cases I select on the context.
Thanks,
-Erik
=> Leverage contexts in http uploads

govc/test/vcsim.bats, simulator/model.go, vcsim/main.go
- Use the curl '-f' flag so the tests actually fail on 404 Not Found
- Add some Model validation to the tests
- Use Model.Count to get the current totals when stats are fetched
- Remove 'omitempty' tags from Model field that represent object types,
making it easier to validate when an object count should be '0'
=> vcsim: stats related fixes

govc/emacs/govc.el, govc/events/command.go, govc/test/cli.bats, simulator/datacenter.go, simulator/esx/event_manager.go, simulator/event_manager.go, simulator/event_manager_test.go, simulator/folder.go, simulator/folder_test.go, simulator/host_system.go, simulator/property_collector.go, simulator/registry.go, simulator/service_instance.go, simulator/session_manager.go, simulator/view_manager.go, simulator/virtual_machine.go, vim25/types/helpers.go
- Add '-dump' support to govc events command, so we can grab events as Go code
- Workaround 6.5 bug where an internal event type (HostSubSpecificationUpdateEvent) was causing an NPE
- Avoid Go 1.9.3 url.Parse error in cli.bats
- PropertyCollector should return empty arrays
=> vcsim: add EventManager support

govc/object/collect.go, govc/test/object.bats
This change allows for replaying CreateFilter requests from other clients and
generating Go versions of CreateFilter requests than can be dropped into tests.
=> govc: object.collect support for raw filters

govc/test/host.bats, simulator/cluster_compute_resource.go, simulator/folder_test.go, simulator/host_system.go
summary.host should have a reference to the generated moid, not the template esx.HostSystem.Self (ha-host)
Fixes #1021
=> vcsim: update HostSystem.Summary.Host reference

govc/test/object.bats, simulator/virtual_machine.go
In commit 274f3d6 , the config.instanceUuid property was set, but we missed the summary.config field.
Fixes #1022
=> vcsim: set VirtualMachine summary.config.instanceUuid

govc/flags/client.go
PR #983 added the session.login command, but the tests use it with session persistence disabled.
We need the session persisted for the session.login command to be useful outside of testing.
=> Fix session persistence in session.login command

govc/test/test_helper.bash, govc/test/vm.bats, govc/vm/power.go, object/datacenter.go, simulator/datacenter.go, simulator/datacenter_test.go, simulator/entity_test.go, simulator/file_manager.go, simulator/folder.go, simulator/host_system.go, simulator/property_collector_test.go, simulator/registry.go, simulator/search_index.go, simulator/view_manager.go, vcsim/main.go
- Add PowerOnVM method to object.Datacenter
- Add PowerOnMultiVMTask method to simulator.Datacenter
- Add '-M' flag to govc vm.power command
- Make it easier to call vcsim_env multiple times in a single test
- Add vcsim support
=> Add support for Datacenter.PowerOnMultiVM

govc/flags/network.go, govc/test/vm.bats, govc/vm/clone.go, govc/vm/network/change.go, simulator/virtual_machine.go
- Add vcsim support for VirtualDeviceConfigSpecOperationEdit
- vcsim CloneVM now includes source VM's devices and applies VirtualMachineRelocateSpec.DeviceChange
Fixes #960
=> govc: fix vm.clone to use -net flag when source does not have a NIC

object/types.go
Currently, `object.NewReference` returns a generic `Network` object when
called for a `OpaqueNetwork` MO. This has the side effect of breaking
`EthernetCardBackingInfo`, which will no longer contain the information
relevant to NSX that is required to correctly attach to the
logical switch that the backing is trying to connect to.
This corrects this so that such references are correctly returned
`OpaqueNetwork` objects, from which the correct relevant backing formation
can be extracted.
=> object: Return correct helper object for OpaqueNetwork

govc/device/info.go, govc/test/device.bats
As with the 'Name' field, 'Type' is not a field of BaseVirtualDevice,
but is displayed without the '-json' flag.  Inject a 'Type' field as
we do with 'Name' so it is included with '-json'.
Fixes #1037
=> Add 'Type' field to device.info -json output

govc/ls/command.go, govc/test/ls.bats
The ls command flags shouldn't be included with -json, ignore the embedded field.
This avoids the 1.10 json encoding error against the ClientFlag.Login (func) field.
Fixes #1042
=> Avoid json encoding error in Go 1.10

CHANGELOG.md, vim25/progress/reader.go, vim25/progress/reader_test.go
In go1.10 archive/tar Reader is emitting n, io.EOF with n > 0 (which is valid), this PR makes progress.Reader emit a Report in this case so that we get to 100.0% always.
=> In progress.Reader emit final report on EOF.

govc/dvs/portgroup/info.go, govc/flags/version.go, govc/test/network.bats, govc/test/object.bats, object/distributed_virtual_switch.go, simulator/dvs.go, simulator/dvs_test.go, simulator/finder_test.go, simulator/folder.go, simulator/model_test.go, simulator/registry.go
This regression was introduced by 585cf5e , where the DistributedVirtualSwitch
FetchDVPorts wrapper was added to the object package. The new method did not
include the optional 'Criteria' param, so no filtering was applied to the
dvs.portgroup.info command.  The command would panic on uplink portgroups, which
are normally filtered out by default.  But the same panic would happen 0.15 if
the '-uplinkPort' flag is given.
This change also adds an uplink portgroup to simulator switches, which would
reproduce the issue.
The dvs.portgroup.info command now has support for using the '-json' and '-dump' flags.
Fixes #1059
Fixes #1060
=> Fix dvs.portgroup.info filtering

.gitignore, .goreleaser.yml, .travis.yml, Dockerfile, govc/flags/version.go, govc/version/command.go
This sets up `goreleaser` to cut a new `govc` release and automate the publish process through Travis.
It requires `DOCKER_USERNAME`, `DOCKER_PASSWORD` and `GITHUB_TOKEN` to be available on the Travis job for govmomi in order to make deploy succeed (will set up once it's merged).
=> Add goreleaser to automate release process

object/virtual_disk_manager_internal.go
The QueryVirtualDiskInfo_TaskResponse can be in the "internalvim25" namespace,
rather than "vim25", which lead to a panic as the 'Res' field would be nil.
Add the same workaround we use for this issue with CreateChildDisk_TaskResponse,
an "InternalRes" field in the "internalvim25" namespace.
Fixes #1066
=> Avoid possible panic in QueryVirtualDiskInfo

.travis.yml, govc/flags/client.go, govc/session/login.go, govc/test/session.bats, ovf/env.go, ovf/ovf.go, session/manager.go, simulator/session_manager.go, simulator/simulator.go, simulator/simulator_test.go, sts/client.go, sts/client_test.go, sts/internal/types.go, sts/internal/types_test.go, sts/signer.go, sts/signer_test.go, vim25/soap/client.go, vim25/soap/soap.go, vim25/soap/soap_test.go
- Add sts.Client which can issue new tokens via Secure Token Service
- Add sts.Signer which can sign requests, such as SessionManager.LoginByToken
- Add SessionManager.LoginByToken support
- Add '-issue', '-token' and '-actas' flags to govc session.login
=> SAML token authentication support

client_test.go, examples/examples.go, gen/gen.sh, govc/emacs/govc.el, govc/flags/client.go, govc/main.go, govc/object/collect.go, govc/sso/service/ls.go, govc/test/sso.bats, lookup/client.go, lookup/client_test.go, lookup/methods/methods.go, lookup/simulator/registration_info.go, lookup/simulator/simulator.go, lookup/simulator/simulator_test.go, lookup/types/types.go, pbm/client.go, simulator/property_collector.go, simulator/property_collector_test.go, simulator/registry.go, simulator/service_instance.go, simulator/session_manager.go, simulator/simulator.go, simulator/simulator_test.go, simulator/vpx/setting.go, sts/client.go, vcsim/main.go, vim25/client.go, vim25/methods/service_content.go, vim25/soap/client.go
- Lookup Service client API (govmomi/lookup)
- Add namespacing to vcsim to support multiple API endpoints
- Lookup Service API simulator (govmomi/lookup/simulator vcsim plugin)
- Lookup Service CLI client (govc sso.service.ls command)
Fixes #1063
Fixes #1074
=> Lookup Service support

client.go, govc/extension/setcert.go, govc/flags/client.go, govc/session/login.go, govc/test/session.bats, session/manager.go, simulator/session_manager.go, simulator/session_manager_test.go, simulator/simulator.go, vcsim/main.go, vim25/soap/client.go
Originally, a call to soap.Client.SetCertificate configured the client's proxy to use the SDK for every requests.
However, the SDK tunnel is only required for the LoginExtensionByCertificate call itself.  After we have a session,
the normal path can be used without the SDK tunnel.  Use of the SDK tunnel is now limited to within the SessionManager
LoginExtensionByCertificate wrapper.
- Add govc session.login -extension flag
- Add vcsim LoginExtensionByCertificate implementation
- Add govc extension.setcert -set flag (handy for generating test certs)
- Remove govmomi.Client LoginExtensionByCertificate related methods
=> Refactor LoginExtensionByCertificate tunnel usage

simulator/snapshot.go, simulator/virtual_machine.go, simulator/virtual_machine_test.go
vcsim vm.snapshot should be 'nil' if there are not any snapshots
Here are the updated test cases / responses:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:ns0="urn:vim25" xmlns:ns1="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
<SOAP-ENV:Header/>
<ns1:Body>
<ns0:RetrievePropertiesEx>
<ns0:_this type="PropertyCollector">propertyCollector</ns0:_this>
<ns0:specSet>
<ns0:propSet>
<ns0:type>VirtualMachine</ns0:type>
<ns0:pathSet>snapshot</ns0:pathSet>
</ns0:propSet>
<ns0:objectSet>
<ns0:obj type="VirtualMachine">vm-51</ns0:obj>
</ns0:objectSet>
</ns0:specSet>
<ns0:options/>
</ns0:RetrievePropertiesEx>
</ns1:Body>
</SOAP-ENV:Envelope>
```
```xml
<?xml …
```
=> vcsim vm.snapshot should be 'nil' if there are not any snapshots

find/finder.go, simulator/finder_test.go
With all hosts under 2+ levels of folders, finder would return find.NotFoundError.
Fixed to return find.MultipleFoundError instead.
Fixes #1103
=> Finder.DefaultHostSystem should find hosts in nested folders

govc/session/login.go, sts/client.go, sts/client_test.go, sts/internal/types.go, sts/internal/types_test.go, sts/signer.go
Mostly a refactor as "Issue" and "Renew" requests are similar, but also adds new types and their canonicalizers.
Removed time.Time wrapper, using string type instead.
This avoids an issue where xml.Marshal was dropping trailing zeros from the timestamp,
causing an invalid body digest.
Fixes #1093
=> Add STS support for token renewal

govc/test/vm.bats, govc/vm/change.go, govc/vm/clone.go
The VM annotation would only be set if -c or -m were also specified.
Add -annotation flag to vm.change command.
Fixes #1118
=> Fix govc vm.clone -annotation flag

simulator/search_index.go
https://code.vmware.com/apis/358/vsphere#/doc/vim.SearchIndex.html#findByInventoryPath
Finds a managed entity based on its location in the inventory. The path is separated by slashes ('/').
For example, a path should be of the form "My Folder/My Datacenter/vm/Discovered VM/VM1".
A leading slash or trailing slash is ignored.
Thus, the following paths all represents the same object: "a/b", "/a/b", "a/b/", and '/a/b/'.
Slashes in names must be represented using %2f, following the standard URL syntax.
Any object in the inventory can be retrieved using this method, including resource pools and hosts.
=> vcsim: Fixed leading "/" requirement in FindByInventoryPath

simulator/simulator.go
The key is different from the one assigned to the query in the datacenter object. It provokes errors when several datacenters are created.
=> Change key name according to Datacenter object

simulator/os_unix.go, simulator/virtual_machine.go
https://github.com/vmware/govmomi/issues/1121
This only fix stat on linux, not windows. 
Not add test part because I don't have windows machine to test, so it may break if govmomi's CI system has windows platform.
=> vcsim: display correct capacity and free size of datastore.info

govc/object/find.go, govc/test/object.bats
The root path argument without a path spec should only be considered at the root folder or default datacenter level.
Force list mode in this case to avoid recursing into child folders when resolving the root object argument.
=> Avoid recursive root path search in govc find command

govc/datastore/disk/create.go, govc/datastore/disk/info.go, govc/emacs/govc.el, govc/test/datastore.bats, object/virtual_disk_manager.go, simulator/virtual_disk_manager.go
- Add govc datastore.disk.info '-uuid' option to query the disk uuid
- Add govc datastore.disk.create '-uuid' option to set the disk uuid
Fixes #1135
=> Add VirtualDiskManager wrapper to set UUID

govc/importx/ovf.go, govc/test/import.bats
=> govc: import.ovf pool flag should be optional if host is specified

examples/hosts/main.go
make output for host memory use uniform unit
Signed-off-by: CuiHaozhi <cuihaozhi@chinacloud.com.cn>
=> example: uniform unit for host memory

govc/importx/options.go, govc/importx/ovf.go, govc/importx/spec.go
We have several use cases inside our org where we need to upload an OVF or OVA file using govc and immediately mark it as a template. This PR adds a `MarkAsTemplate` option in the `import.ovf/ova` spec.
=> Add option to mark VM as template on OVF/OVA import in govc

govc/host/info.go
This command was incorrectly multiplying the number of CPU packages by the
total number of CPU threads.  The number of CPU threads is across all CPUs,
so it can be used instead.
Example output prior to the fix:
Name:              internal
Path:            /path/to/ESX/host
Manufacturer:    Dell Inc.
Logical CPUs:    112 CPUs @ 2195MHz
Processor type:  Intel(R) Xeon(R) Gold 5120 CPU @ 2.20GHz
CPU usage:       1654 MHz (0.7%)
Memory:          195266MB
Memory usage:    73725 MB (37.8%)
Boot time:       2018-05-11 23:17:05.118699 +0000 UTC
State:           connected
Example output with the fix applied:
Name:              internal
Path:            /path/to/ESX/host
Manufacturer:    Dell Inc.
Logical CPUs:    56 CPUs @ 2195MHz
Processor type:  Intel(R) Xeon(R) Gold 5120 CPU @ 2.20GHz
CPU usage: …
=> Fixed govc host.info logical CPU count

ssoadmin/client.go, vim25/soap/error.go
If the type of fault is not included in the vim25 types registry,
soapFaultError.Error method would panic as the Detail.Fault field is nil.
Fix ssoadmin type registration for the NoPermission fault.
=> Avoid panic if fault detail is nil

simulator/dvs.go
The HostSystem.Network field should only include Network types.
=> vcsim: do not include DVS in HostSystem.Network

govc/test/tags.bats
This PR is to add testing support for govc tags commands. 
Before running the test, please `export GOVC_TEST_URL` first.
Fixes #1165
=> Add testing support for govc tags commands

.travis.yml, Makefile, govc/events/command.go, govc/flags/client.go, govc/object/collect.go, govc/test/vm.bats, property/collector.go, property/wait.go, scripts/debug-xmlformat.sh, simulator/event_manager.go, simulator/property_collector.go, simulator/property_collector_test.go, simulator/property_filter.go, simulator/race_test.go, simulator/registry.go, simulator/session_manager.go, simulator/task.go, simulator/task_manager.go, simulator/view_manager.go, simulator/virtual_machine.go, simulator/virtual_machine_test.go, vim25/mo/retrieve.go, vim25/mo/type_info.go
Prior to this change, clients could only call WaitForUpdatesEx once,
which would return the current state.  The next invocation with Version
given would fail as unsupported.  Clients can now use WaitForUpdatesEx
to wait for multiple updates.
The basic idea is that methods should now update object fields using
the `Registry.Update` method instead of setting fields directly.
`Registry.Update` uses the same PropertyChange structure that is sent as
part of the WaitForUpdatesEx response.  `Registry.Update` will also apply
the PropertyChange(s) to the local object, removing the need to set
fields directly.
- govc commands now use Client.Flag.WithCancel to catch SIGINT,
allowing proper cleanup of collectors
- Add vcsim ListView support to ViewManager
Fixes #922
=> vcsim: add support for PropertyCollector incremental updates

CHANGELOG.md, object/cluster_compute_resource.go
Wraps the `MoveInto_Task` on `ClusterComputeResource`.
=> Add method to move host into cluster

govc/cluster/rule/info.go, govc/cluster/rule/info_flag.go, govc/cluster/rule/ls.go, govc/test/cluster.bats
We've head some problems managing our cluster affinity rules with govc. govc wasn't showing any infos in cluster.rule.ls for 'ClusterVmHostRuleInfo' type rules, that match a host group to a VM group. 
With the proposed change cluster.rule.ls can now show you the type of the rule and the additional details for 'ClusterVmHostRuleInfo' type rules.
=> govc: show rule details for ClusterVmHostRuleInfo rules in cluster.rule.ls

simulator/session_manager.go, simulator/session_manager_test.go
Unlike other per-session objects, the PC singleton has the same ManagedObjectReference regardless of session instance.
If a 2nd Login creates a new session, and PC singleton is used, the Logout of that session would unregister the PC singleton update listener.
Fixes #1195
=> vcsim: Logout should not unregister PropertyCollector singleton

govc/tags/category/create.go, govc/tags/category/update.go, govc/tags/create.go, govc/tags/update.go, govc/test/tags.bats, vapi/simulator/simulator.go, vapi/tags/categories.go, vapi/tags/tag_association.go, vapi/tags/tags.go, vcsim/main.go
- Collapse some duplicate types in the tags package
- tags.bats now works against vcsim
Fixes #1178
=> vcsim: add support for tags API

README.md
Fixes the path to the `LICENSE.txt` file.
=> README: Fix path to LICENSE.txt file

govc/.gitignore, govc/build.sh, govc/dvs/portgroup/info.go, vim25/types/if.go
ATM `dvs.portgroup.info` command doesn't print dvs rules. This is a WIP branch, am I on the right direction?
=> govc: Print DVS rules for dvportgroup

govc/flags/datacenter.go, govc/ls/command.go
Use of '-json' flag in any command sets the Finder all param to true.
Only the 'ls' command makes use of this property collection, so limit it to there.
Fixes #1208
=> Avoid use of Finder all param in govc

govc/importx/archive.go, govc/importx/ovf.go, govc/importx/spec.go
* empty envelope is used when import.spec file is not provided
* includes minor idiomatic clean up
=> Handle empty file name in import.spec

simulator/property_collector.go, simulator/property_collector_test.go
Hi,
I saw recently the new simulator package which is amazing, but I also had problems with the MaxWaitSeconds parameter of WaitForUpdatesEx() function; especially with the 0 value which means : 
> do one update calculation and return any results. [(Doc)](https://www.vmware.com/support/developer/vc-sdk/visdk41pubs/ApiReference/vmodl.query.PropertyCollector.WaitOptions.html#maxWaitSeconds)
With the current code, if I set a value of 0, it always returns **nothing, immediately**, even if there are updates that should be returned (with an exception of the very first call when Version == "").
The main problem in the current code (from what I understood) is coming from the line:
`simulator/property_collector.go:632`
`... = context.WithTimeout(context.Background(), …
=> WaitOption.MaxWaitSeconds in simulator

guest/file_manager.go
This a proposition to fix issue #1232 where TransferURL changes the hostname part of the url even if it's not set to '*' and hence not using the url as it is returned by the server.
(I took the specs from https://www.vmware.com/support/developer/converter-sdk/conv50_apireference/vim.vm.guest.FileManager.html#initiateFileTransferToGuest)
=> replace hostname only if unset

session/keep_alive.go
This change is adding LoginByTokenBody to RoundTrip method which enables
WCP to use session.KeepAlive to maintain a persistent session with VC
using token based login.
=> Adding LoginByToken to RoundTrip routine.

README.md, simulator/model.go, simulator/simulator.go, vcsim/README.md, vcsim/main.go
Resolves issue #1250 
From the README:
Sometimes, especially when debugging software, it can be useful to introduce delays to simulate network latency or a poorly performing vCenter. There are three command line options for dealing with delays.
```-delay <ms>``` Adds a constant delay (experessed in milliseconds) to every call
```-method-delay <method:milliseconds,method:milliseconds...>``` Adds a specified delay to individual methods. If both ```-method-delay``` and ```-delay``` are specified, they are added together
```delay-jitter``` Specifies a jitter, i.e. a random value added to or subtracted from the delay. It is specified as a <i>Coefficient of Variation</i>, which is the same as the standard deviation divided by the mean. A reasonable starting value is 0.5, as it gives a nice …
=> Issue #1250 - Add ability to specify delays

simulator/property_collector.go
Found inconsistent Fault message comparing to real vCenter. When trying to retrieve object which is not found, I should get the message "The object has already been deleted or has not been completely created". 
Steps to test:
1. Create ResourcePool
2. Destroy ResourcePool
3. Try RetrieveProperties with deleted pool identifier
=> vcsim: add fault message to PropertyCollector RetrieveProperties

govc/vm/change.go
As per #1271, i've added an example to document how to enable cpu and memory hotplug on a vm using govc.
=> [doc] add an example for cpu and memory hotplug

govc/disk/create.go, govc/disk/ls.go, govc/disk/register.go, govc/disk/rm.go, govc/disk/snapshot/create.go, govc/disk/snapshot/ls.go, govc/disk/snapshot/rm.go, govc/main.go, govc/test/disk.bats, vslm/doc.go, vslm/object_manager.go
- vslm.ObjectManager provides a higher level API for First Class Disk methods
- New govc disk.* and disk.snapshot.* commands manage FCDs and their snapshots
Fixes #1238
=> Add vslm package and govc disk commands

simulator/dvs.go
=> vcsim: update DVS methods to use UpdateObject instead of setting fields directly

simulator/esx/task_manager.go, simulator/task_manager.go, simulator/vpx/task_manager.go
Adds TaskManager `Description` property templates for VPX and ESX.
Used these versions to capture data:
```
Name:         VMware vCenter Server
Vendor:       VMware, Inc.
Version:      6.5.0
Build:        7119157
```
```
Name:         VMware ESXi
Vendor:       VMware, Inc.
Version:      6.5.0
Build:        5969303
```
=> vcsim: add task_manager description property templates

govc/fields/set.go
This patch adds support to the `fields.set` command for adding new fields when setting the value of a field that does not yet exist. For example, this is what happens when attempting to set a field that does not exist:
```shell
$ govc fields.set my-field my-value OBJECT_PATH
govc: key name not found
```
Using the new `-add` flag, the field will be created upon attempting to set the field's value:
```shell
$ govc fields.set -add my-field my-value OBJECT_PATH
$ govc fields.ls OBJECT_PATH
205  my-field
```
The new `-type` flag also allows users to specify to which managed object type to add new fields when setting them. If no type is specified then a global field is created (see above example). The following example adds a field to just the `VirtualMachine` type:
```shell
$ govc fields.set …
```
=> govc: field.set can now add a missing field

simulator/folder.go, simulator/virtual_machine.go
VM is now added to registry during `NewVirtualMachine` call. `folder.putChild(...)` is called at the start of the function so it always completes, if VM creation fails - it is up to callers to cleanup (`folder.removeChild`). This might be confusing as caller needs to know that VM is added to folder inside and it's up to him to catch a fault and cleanup. This is done to be safer - if cleanup was up to `NewVirtualMachine` it would need to catch all errors (and cleanup then) - any error not caught would result it no cleanup.
Fixes #1288
=> vcsim: update VM configureDevices method to change VM properties with UpdateObject

simulator/virtual_machine.go, vim25/mo/type_info.go, vim25/mo/type_info_test.go
The code was originally written for client side SOAP -> Go inflation,
where struct types were never considered pointers on the wire.
Now that we are using this method in-memory via simulator.Registry.Update,
it is possible to use pointer values.
=> Allow pointer values in mo.ApplyPropertyChange

.travis.yml, Makefile
This patch refactors the Travis-CI builds to use containers when possible. This will shorten the build queue times dramatically. Only when deploying build artifacts for tagged releases will Travis-CI require the VM infrastructure.
The phrase `/ci-deploy` may also be added to the commit message in order to activate the deploy stage for non-release builds.
Please see this [forked build](https://travis-ci.com/akutz/govmomi/builds/91010365) for an example of the new config in action. This PR's [build](https://travis-ci.org/vmware/govmomi/builds/453784582) also demonstrates the new config, but this link will change every time the PR is updated.
=> build: Refactored Travis-CI to use containers

govc/disk/ls.go, govc/disk/tags.go, govc/test/disk.bats, simulator/registry.go, simulator/simulator.go, simulator/vstorage_object_manager.go, vapi/simulator/simulator.go, vcsim/main.go, vslm/object_manager.go
- Add tag related methods to vslm.ObjectManager
- Add vcsim support for vslm.ObjectManager tag methods
- Add govc disk.ls -c and -t options to list tagged disks
- Add govc disk.ls -T option to list tags attached to disks
- Add govc disk.tags.attach and disk.tags.detach commands
=> Tags support for First Class Disks

simulator/snapshot.go, simulator/virtual_machine.go
Updated VM Snapshot methods (Create, Remove, RemoveAll, Revert) to change VM properties with UpdateObject instead of setting directly.
=> vcsim: update VM snapshot methods to change VM properties with UpdateObject

govc/test/vcsim.bats, simulator/virtual_machine.go
- Add a guest.net entry for each network device
- Propagate SET.guest.ipAddress to guest.net[0].ipAddress
=> vcsim: populate VM guest.net field

Makefile, govc/Makefile, govc/build.sh, program.mk, vcsim/Makefile
This patch introduces Makefiles for the two programs `govc` and `vcsim`. Each `Makefile` supports cross-compilation as well as sane defaults. The build script for `govc` has been updated to depend on the `govc`'s `Makefile` to keep things simple.
This PR also changes the default build behavior for `govc` (and introduces it to `vcsim`) so that both programs are compiled as static binaries with no host dependencies.
cc @dougm
=> Makefiles for govc/vcsim; updates  govc/build.sh

govc/test/vcsim.bats, simulator/virtual_machine.go
vm.Config.Files.VmPathName can be a directory or full path to .vmx,
but the logic to support it assumed the .vmx case for any non-empty path.Ext
This prevented having a '.' in the vm directory name.
=> vcsim: allow '.' in vm name

govc/device/info.go, govc/device/ls.go, govc/device/remove.go, govc/test/device.bats, simulator/virtual_machine.go, toolbox/guest_info.go
The device.info command already supports name matching, extend to the ls and remove commands.
=> govc: add device name match support to device.ls and device.remove

nfc/lease_updater.go, simulator/registry.go, toolbox/process.go, vim25/progress/reader.go
Atomic 64-bit counters in structs must be on an even 64-bit boundary, or a panic will occur. See #1330 for details.
Addressed the issue by moving all atomic 64-bit counters to the beginning of their structs, which guarantees that they will fall on a 64-bit boundary.
=> Fixed 64-bit aligment issues with atomic counters

object/virtual_machine.go, simulator/folder.go, simulator/snapshot.go, simulator/virtual_machine.go, simulator/virtual_machine_test.go
This pull request implements `RefreshStorageInfo()` method for `VirtualMachine`.
`RefreshStorageInfo` method can be called explicitly to update `vm.Storage`, `vm.Summary.Storage` and `vm.LayoutEx` properties. This pull request also provides implicitly called methods for updating mentioned properties (also `vm.Layout`).
Notes:
- Taking `VirtualMachine` snapshot now also creates `.vmsn` file (snapshot data file; leaving `.vmem` - snapshot memory, implementation for later - it exists only when VM is powered on or suspended)
- Created 2 methods to manage snapshot files - `createSnapshotFiles` and `removeSnapshotFiles` these can be later extended to create delta disks
- Any file that belongs to `VirtualMachine` now can be found in `vm.LayoutEx.File`. The sizes of these files is used to …
=> vcsim: implement RefreshStorageInfo method for virtual machine

simulator/esx/event_manager.go, simulator/event_manager.go, simulator/event_manager_test.go, simulator/host_system.go
EventManager.formatMessage would panic if an event type was not defined in esx.EventInfo,
now simply leaves FullFormattedMessage as-is in that case.
Add HostRemovedEvent to esx.EventInfo and emit from the HostSystem.Destroy_Task method.
=> vcsim: avoid panic when event template is not defined

vcsim/README.md
Add 2x blog posts about vcsim
- adds 2x blog posts to the README.md file of the vcsim
component to help new users get started and to improve SEO.
This is a documentation change which should have no impact on tests etc.
Signed-off-by: Alex Ellis (VMware) <alexellis2@gmail.com>
=> Add 2x blog posts about vcsim

govc/test/test_helper.bash, govc/test/vcsim.bats, simulator/simulator.go, vcsim/README.md, vcsim/main.go
If the '-httptest.serve' flag is specified without an address,
the default GOVC_URL output will be unusable.  Attempt to replace
with a valid IPv4 address.
- Add vcsim '-l' flag as an alias for '-httptest.serve'
- Fix vcsim_stop race; need to wait for process to exit
=> vcsim: avoid zero IP address in GOVC_URL output

simulator/datastore_test.go, simulator/host_datastore_browser.go
Task.Info.Entity must be of type ManagedEntity, in this case should the Datastore
rather than the HostDatastoreBrowser.
Fixes #1353
=> vcsim: fix SearchDatastore task info entity

simulator/virtual_machine.go
use `Config.DeviceChange` instead of `Location.DeviceChanges` as parameter for device configuration on VM clone. This resolves #1355
=> vcsim: resolve issue making device changes on clone (resolves #1355)

govc/build.sh
This patch fixes the issue described in the comment at https://github.com/vmware/govmomi/pull/1370#issuecomment-461294868.
=> Fix for govc/build.sh wrong dir

nfc/lease.go
The call to progress.NewReader already creates a Tee.
This nesting caused prevented progress from exiting when an error occurs during import.vmdk upload.
=> Remove nested progress.Tee usage

vapi/library/finder/finder.go
This patch fixes the library's finder to support filenames containing the "/" character. Thanks to @dougm for finding this in https://github.com/vmware/govmomi/pull/1380#discussion_r255705011.
=> lib/finder: Support filenames with "/"

go.mod, go.sum, vendor/modules.txt
This patch updates the go.mod manifest to replace the xdr package with a fork.
=> Update XDR to use fork

govc/USAGE.md, govc/vm/snapshot/tree.go
Hi @dougm,
This adds the option of showing snapshots description with the `govc snapshot.tree` command. 
See,
```
$ govc snapshot.tree -vm <hostname> -D -i -d
[snapshot-79157 Feb 15 12:30]  <snapshot name> - <comment>
[snapshot-79157 Feb 15 12:30]  . - <comment>
$ govc snapshot.tree -vm <hostname> -D -i
[snapshot-79157 Feb 15 12:30]  <snapshot name>
[snapshot-79157 Feb 15 12:30]  . 
```
=> Print Snapshots description

lookup/simulator/registration_info.go, simulator/session_manager.go, simulator/simulator.go
It's important to do all global configuration before starting the server. Otherwise, a request could access settings while they're being configured.
=> Fix a race in NewServer().

govc/test/pool.bats, govc/vm/info.go, govc/vm/vnc.go, nfc/lease_updater.go, pbm/client_test.go, pbm/simulator/simulator_test.go, scripts/vcsa/create-vcsa-vm.sh, simulator/esx/task_manager.go, simulator/license_manager_test.go, simulator/performance_manager_test.go, simulator/property_collector_test.go, simulator/vpx/performance_manager.go, simulator/vpx/task_manager.go, task/wait.go, toolbox/hgfs/protocol_test.go, vim25/client.go, vim25/mo/type_info.go, vim25/soap/client_test.go
Hi @dougm,
This fixes some spelling issues found by [codespell](https://github.com/codespell-project/codespell).
See,
```
$ codespell --skip="./.git/*,./vim25/xml*,./vendor*" --ignore-words-list="cas,compres,mor,te,uint"
```
Are you interested in running this at the CI? If you agree, I can send you a PR configuring this at CircleCI as TravisCI does not support mixing **golang** and **python**. See this simple implementation [here](https://github.com/prometheus/node_exporter/blob/master/.circleci/config.yml#L24).
=> Fix codespell issues

gen/vim_wsdl.rb, simulator/simulator.go, simulator/virtual_machine.go, simulator/virtual_machine_test.go, vim25/methods/methods.go
To workaround a property collector issue where a client needs to invoke a PropertyCollector method with a namespace other than vim25.
In this case, the body Response type namespace will be that of the request (e.g. "urn:vsan"), which Go fails to decode when the Res
field tag has the urn:vim25 namespace.
The response body type is already given as an input to RoundTrip(), so there's no need to validate the namespace on the client side
and decoding works as expected.
Added custom encoding to the simulator to add namespace to the response body type.
=> Omit namespace tag in generated method body response types

simulator/host_datastore_system.go
Hi. This PR is addressing the issue reported in #1399 
- OTHER is a valid and compatible FileSystemType in vSphere Management Web SDK
Thanks and Cheers! :beers:
=> Report local Datastore back as type OTHER

simulator/internal/server.go, simulator/internal/testcert.go, simulator/simulator.go
As of Go 1.12, the "httptest.serve" flag is not registered unless it is present in os.Args.
There is no other way to set the httptest.serveFlag variable, breaking vcsim's default setting
of port 8989.
The simulator/internal/{server,testcert}.go files are a copy from Go's 1.11 httptest package.
We can remove "httptest.serve" and replace with vcsim's "l" flag, along with removing other
workarounds for the httptest package in a future PR.
Fixes #1400
=> vcsim: fork httptest server package

.travis.yml, Makefile
Hi @dougm,
I updated Travis CI configuration from Ubuntu "Trusty Tahr" (14.04 LTS) to "Xenial Xerus" (16.04 LTS). See the EOL information [here](https://wiki.ubuntu.com/Releases).
BTW, I upgraded the golang version from 1.11 to 1.12 in a separate commit, so I you don't agree, I can drop it.
=> Update Travis CI configuration

event/processor.go, govc/datacenter/info.go, govc/flags/client.go, govc/flags/cluster.go, govc/object/collect.go, govc/object/find.go, govc/sso/user/create.go, govc/task/recent.go, property/wait.go, simulator/event_manager_test.go, sts/client_test.go
Hi @dougm,
I fixed here some errcheck issues. PTAL, the log types could be others than **Fatal**. See,
```
$ golangci-lint run --skip-dirs '^vim25/xml/*' --disable-all --enable=errcheck
```
=> Add error check for deferred functions

vapi/tags/tags.go
I just have renamed a variable, because it was wrong behaviour (same names for different variables)
=> Fix bug with multiple tags in category

govc/disk/ls.go, object/datastore.go
- Workaround issue where List() returns IDs for disk deleted via VM destroy,
which return a NotFound fault when Retrieve() is called.
- Change Datastore.Path helper to check if the given path is already in datastore URI format.
This makes it simpler to query for path via disk.ls and attach via vm.create, vm.disk.attach, etc.
=> govc: FCD workarounds

govc/disk/ls.go, govc/test/disk.bats, object/datastore.go, simulator/vstorage_object_manager.go, vslm/object_manager.go
Rather than hide NotFound errors (as 18cb914 did), the disk.ls -R
option can be used to reconcile the FCD datastore inventory.
This will remove FCD objects from inventory whos datastore backing
file no longer exists.
- Add disk.ls '-L' option to print the file path instead of name
=> Add support to reconcile FCD datastore inventory

govc/test/vm.bats, govc/vm/change.go, simulator/virtual_machine.go
When a VM is marked as a template, only the name and annotation can be changed.
However, the vm.change command was sending an empty "<tools></tools>" field in the request,
causing vCenter to respond with a NotSupported fault.
Updates vcsim to behave as vCenter does in this case.
Fixes #1430
=> govc: fix vm.change against templates

govc/library/item/upload.go, govc/library/ova.go, govc/vcenter/deploy.go, object/virtual_machine.go, toolbox/command_test.go
Hi @dougm,
I fixed here some trivial staticcheck issues related with never used variables.
See,
```
$ golangci-lint run --skip-dirs '^vim25/xml/*' --disable-all --enable=staticcheck
```
=> Fix staticcheck issues value of `XXX` is never used

govc/test/test_helper.bash, govc/test/vcsim.bats, simulator/internal/server.go, simulator/simulator.go, vcsim/README.md, vcsim/main.go
The package was forked in PR #1400 due to issues with 1.12 and
the httptest.serve flag - this change drops the flag altogether.
=> vcsim: remove httptest.serve flag

object/host_datastore_system.go, object/host_datastore_system_test.go, object/host_storage_system.go
Added ability (and a test that skips unless there is an available snapshot) to resignature vmfs snapshots. Basically [this](https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.storage.doc/GUID-EEFEB765-A41F-4B6D-917C-BB9ABB80FC80.html) flow
=> Support resignature of vmfs snapshots

vsan/methods/methods.go, vsan/types/base.go, vsan/types/if.go, vsan/types/registry.go, vsan/types/types.go
The Go bindings for following vSAN methods are added:
1. VsanPerfGetSupportedEntityTypes
2. VsanQueryVcClusterHealthSummary
3. VsanQuerySpaceUsage
4. VsanPerfQueryPerf
5. VsanQuerySyncingVsanObjects
=> Add vSAN bindings

examples/examples.go, examples/virtualmachines/main.go, simulator/model.go
- Add simulator.Model.Do method, generally useful outside of examples
- Add examples.Run method, which defaults to running the example against vcsim
=> Default to running against vcsim in examples

simulator/host_network_system.go, simulator/host_network_system_test.go
Fixes #1266
`govc host.portgroup.info` now reflects the port group configuration.
The array `NetworkInfo.Portgroup` starts as `host.Config.Network.Portgroup` (containing Management Network & VM Network). It is updated when port groups are added or removed.
=> vcsim: Update NetworkInfo.Portgroup in simulator

sts/signer.go
When http.Request.URL.Port is not set on the client side, is also omitted from the request "Host" header.
In this case, on the server side, the default port value used in the message signature is "80".
This change fixes the case when URL.Port is explicitly set, which is then included in the "Host" header.
=> Fix port signature in REST endpoint token auth

examples/perfmanager/main.go
Example using simulator to see how to collect cpu.used.summation performance counter from VM.
Reference:
https://pubs.vmware.com/vsphere-6-0/index.jsp?topic=%2Fcom.vmware.wssdk.pg.doc%2FPG_Performance.18.3.html
=> Add PerformanceManager example

pbm/simulator/simulator.go, pbm/simulator/simulator_test.go, vim25/soap/client.go
When fields are encoded with xsi type, vim25/xml typeToString() does not have an option to include namespace prefix.
Workaround this by re-trying the lookup with the namespace prefix.
=> Fix pbm field type lookup

govc/test/vcsim.bats, simulator/cluster_compute_resource.go, simulator/host_system.go
All hosts had the same uuid after #1473 was merged.
The SearchIndex test would randomly pass/fail due to this.
=> vcsim: fix host uuid

vcsim/main.go
Currently, vcsim only stops when it receives SIGTERM or SIGINT signals.
This pull request adds the feature "press any key to exit", when the flag `stdinexit` is provided.
I'm using vcsim for unit/integration tests in C# (VMware.VIM)
```cs
var process = Process.Start(new ProcessStartInfo {
FileName = "vcsim",
UseShellExecute = false,
RedirectStandardOutput = true,
RedirectStandardError = true,
RedirectStandardInput = true,
});
process.Kill();
process.StandardInput.Close();
process.WaitForExit();
```
After vcsim is used for testing, the process must be halted.
Killing the process results in remaining temporary files.
Unfortunately, dotnet has no build in functionality to signal a process (SIGTERM).
https://stackoverflow.com/a/15281070/5537074
https://github.com/dotnet/corefx/issues/1838 …
=> vcsim: Press any key to exit

scripts/debug-xmlformat.sh, vim25/soap/client.go, vim25/soap/debug.go
Not all responses from json requests include a Content-Type header.
Use the request extension to determine the response extension.
=> Fix json request tracing

govc/test/tags.bats, vim25/soap/client.go
Use the same transport when creating a service client to preserve options
such as TLSClientConfig.
=> Fix tls config in soap.NewServiceClient

govc/tags/association/ls.go, govc/test/tags.bats, vapi/simulator/simulator.go, vapi/tags/tag_association.go
Add support for multiple tags/objects and '-l' flag to govc tags.attached.ls command
Fixes #1429
=> tags API: add methods for association of multiple tags/objects

event/example_test.go, find/finder.go, object/example_test.go, object/task.go, property/example_test.go, simulator/datastore.go, simulator/model.go, view/example_test.go
Using Go's example style for these tests rather than main functions in the examples/ directory.
These examples will be included in godoc, tested by 'go test' and only run against vcsim.
- Add simulator.Example function to make examples more concise
- Make finder.NewFinder 'all' param optional.  If not specified, also attempts default DC lookup
- Make task.WaitForResult progress param optional
- Add vcsim Datastore.Destroy_Task impl
Fixes #1497
Fixes #1495
Fixes #1478
Fixes #1451
Fixes #1443
=> Add various govmomi client examples

simulator/host_datastore_system.go
While creating datastore maintenance mode is set to None.
Fix add string value 'normal' as the value of datastore maintenance mode.
=> govcsim: Set datastore status as normal

find/finder.go
The `DefaultFolder` is called in `FolderOrDefault` function which is expected to return a folder object of the default folder if the given path the empty.
The `DefaultFolder` object after creating the folder object needs to set the InventoryPath.
This PR fixes the above-mentioned issue.
=> Set the InventoryPath of the folder object in DefaultFolder

vslm/client.go, vslm/global_object_manager.go
Support for FCD Global Object Manager added in 6.7U2.  Implements similar API to existing vslm object_manager but no longer requires clients to track datastores for FCDs.  Also adds searching APIs and per-FCD metadata.
=> VSLM FCD Global Object Manager client for 6.7U2+

README.md
This commit adds the Juju project to the list of users. Juju by Canonical has been using govmomi since at least 2017.
=> Add Juju to projects using govmomi

vslm/global_object_manager.go
interface {} is not * interface{} but the go compiler doesn't seem to mind
=> Fixed type bug in global_object_manager Task.QueryResult

vapi/rest/client.go, vapi/simulator/simulator.go
Added support for the [get method](https://vdc-repo.vmware.com/vmwb-repository/dcr-public/1cd28284-3b72-4885-9e31-d1c6d9e26686/71ef7304-a6c9-43b3-a3cd-868b2c236c81/doc/operations/com/vmware/cis/session.get-operation.html) on the cis session endpoint to both the REST client and the simulator.
=> Add support for the cis session get method

govc/vm/ip.go, object/virtual_machine.go, object/vm_guest_test.go
Parity with WaitForNetIP's v4 option and govc's vm.ip -v4 w/o -a or -n flags.
Fixes #1259
=> Add v4 option to VirtualMachine.WaitForIP

cns/client.go, cns/client_test.go, cns/cns_util.go, cns/methods/methods.go, cns/mo/mo.go, cns/simulator/simulator.go, cns/simulator/simulator_test.go, cns/types/enum.go, cns/types/if.go, cns/types/types.go
This PR is adding go bindings for [CNS APIs](https://vdc-download.vmware.com/vmwb-repository/dcr-public/8ed923df-bad4-49b3-b677-45bca5326e85/d2d90bb6-d1b3-4266-8ce5-443680187a9a/vim.cns.VolumeManager.html) added in vsan 67u3 release.
Fixes: https://github.com/vmware/govmomi/issues/1571
Testing
```
$ pwd
../govmomi/cns
$ export CNS_VC_URL='https://Administrator@vsphere.local:Admin!23@10.160.90.22/sdk'
$ export CNS_DATACENTER='datacenter'
$ export CNS_DATASTORE='cluster1-vsanDatastore'
$ go test -v
--- PASS: TestClient (25.02s)
client_test.go:91: Creating volume using the spec: {DynamicData:{} Name:pvc-901e87eb-c2bd-11e9-806f-005056a0c9a0 VolumeType:BLOCK Datastores:[Datastore:datastore-99] Metadata:{DynamicData:{} ContainerCluster:{DynamicData:{} ClusterType:KUBERNETES …
```
=> CNS go bindings

session/keep_alive.go
Over the last couple of months we have seen test time outs in a project
using govmomi at a frequency of a few failures a week. The reason for
those timeouts lies in a deadlock in the govmomi code driving the keep
alive handler.
In particular, after we sent a Login request we start a timer issuing
keep alive callbacks. Similarly, after issuing a Logout request we stop
this timer.
Every so often we attempt a logout and while in the process of doing so
the timer gets a tick and attempts to log in. Because we wait for all
keep alive handlers to return and do so with a lock held that is also
acquired as part of the timer start that is performed as part of the
login, we deadlock.
To fix this issue this change moves the logic to stop the keep alive
timer before the actual logout call, …
=> Fix deadlock for keep alive handlers that attempt log in

govc/library/deploy.go, govc/library/errors.go, govc/library/export.go, govc/library/import.go, govc/library/rm.go, govc/test/library.bats, vapi/library/finder/finder.go
vCenter supports libraries with the same name, so we need to support
use of library ID instead of name for methods that require a single library.
Fixes #1581
=> Content library: support library ID in Finder

property/wait.go, property/wait_test.go, simulator/session_manager.go, task/wait.go
Leaving PropagateMissing disabled by default; we don't want to change the behavior
for everything as it may surface benign faults in existing programs.
- Use PropagateMissing=true in task.Wait() function as failure to collect the
Task info field must break out of the wait loop.
- vcsim: support override of per-session instance of the PropertyCollector singleton
- Add WaitForUpdates test for MissingSet faults
=> Add option to propagate MissingSet faults in WaitForUpdates

govc/library/deploy.go, govc/test/library.bats, vapi/simulator/simulator.go
- Avoid panic in vcsim if DefaultDatastoreID is not specified
- Change library.deploy -ds flag to optional
- Add library.deploy -profile flag
Fixes #1588
=> vcsim: DefaultDatastoreID is optional in library deploy

govc/test/vm.bats, govc/vm/clone.go, govc/vm/create.go, object/cluster_compute_resource.go, simulator/cluster_compute_resource.go
- Add ClusterComputeResource.PlaceVm wrapper
- Add govc vm.clone -cluster flag
- Add govc vm.create -cluster flag
Fixes #1580
=> vcsim: add PlaceVm support

govc/datacenter/info.go, govc/test/datacenter.bats
With nested folders, the cluster and host count was 0.
Issue #1173 fix the VM count in this case, but clusters and hosts count did not include folders.
=> govc: fix datacenter.info against nested folders

lookup/client_test.go, lookup/simulator/simulator.go, lookup/simulator/simulator_test.go, pbm/simulator/simulator.go, simulator/model.go, simulator/session_manager.go, simulator/simulator.go, sts/simulator/simulator.go, vapi/simulator/simulator.go, vcsim/main.go
Simplify endpoint registration for vapi, lookup, sts, etc.
This feature cannot be enabled by default as it would break existing
tests that currently make these calls directly.  However, both vcsim/main
and Model.Run can take advantage of it.
URL rewriting moved from the sts endpoint to the main simulator, this avoids
the previous dependency of lookup on sts.
=> vcsim: add endpoint registration mechanism

event/example_test.go, object/example_test.go, performance/example_test.go, property/example_test.go, simulator/model.go, view/example_test.go
The wrapper around Model.Run is useful outside of examples.
Add a new Model.Run Test wrapper intended for use in tests.
=> vcsim: rename Example to Run

vapi/rest/client.go, vapi/rest/client_test.go, vapi/simulator/simulator.go
Rename Client.Get to Client.Session and return the session info.
A nil Session is returned when not authenticated.  This allows callers
to disambiguate between http.StatusUnauthorized and other errors,
as the soap session.Manager.UserSession method does.
=> vapi: return info with current session query

govc/vm/keystrokes.go
govc vm.keystrokes -vm=demo123 -s=“Space would be nice”
govc: invalid Character   in String: Space would be nice
Add 0x2c
=> vm.keystrokes -s (Allow spaces)

simulator/virtual_machine.go
If you want to update ipAddress in ExtraConfig in a VirtualMachine without a NIC, it crashes. Better to have the operation be a no-op if there's no NIC.
=> Check whether there's a NIC before updating guest.ipAddress

property/collector.go, view/container_view.go, vim25/mo/retrieve.go, vim25/mo/retrieve_test.go
Change the method signature to []types.ObjectContent which can be used
not just with RetrieveProperties(), but also RetrievePropertiesEx() and ContinueRetrievePropertiesEx()
=> Replace LoadRetrievePropertiesResponse with LoadObjectContent

simulator/example_test.go, simulator/model.go
Clients using soap.ParseURL for example are expecting https by default.
- Add simulator.Test example
=> vcsim: use TLS in simulator.Run

session/manager.go
Windows may return an error other than those matching os.IsNotExist(),
such as ERROR_INVALID_NAME.  Use os.IsPermission() instead.
Fixes #1612
=> Fix error check in session.Secret

sts/signer.go
Prior to the change, only Solution Users could use HoK tokens.
Fixes #1622
=> Support HoK tokens with Interactive Users

simulator/virtual_machine.go
Given that vcsim creates a VirtualMachineConfigSpec from a VirtualMachineCloneSpec, it needs to manually copy over fields that are important. By adding this line, it ensures that extraConfig from the clone spec is added to the extraConfig in the vm being cloned
=> Ensure that extraConfig from clone spec is added to VM being cloned

govc/USAGE.md, govc/vm/keystrokes.go
as mentionned in https://github.com/vmware/govmomi/issues/1621
```-la true -rc true```  will silently parse la as true and rc as false.
Not sure what is wrong with the flag parsing, but fixing at least the example in the description.
=> Fix description of vm.keystrokes

object/distributed_virtual_portgroup.go, object/distributed_virtual_switch.go, object/network.go, object/network_reference.go, object/opaque_network.go, object/vmware_distributed_virtual_switch.go
When using NetworkList from Finder a list of interfaces is returned meaning you'd need to make a similar looking switch to type caste back to the proper type which is a bit annoying if you're just trying to get InventoryPath. Adding a helper method to NetworkReference to grab and return it.
=> add GetInventoryPath to NetworkReference interface

govc/object/collect.go, govc/test/object.bats
Commit c35a532 added validation for ManagedEntity types, but this breaks
morefs for types that don't extend ManagedEntity - such as mo.*Manager types.
=> Fix object.collect with moref argument

object/virtual_machine.go
Added an IsTemplate helper method to help when using finder to help split VMs if you only need Templates. Makes this possible instead of having to use a Retrieve or something heavier that fills out VirtualMachine.Config:
```
vms, err := finder.VirtualMachineList(ctx, "*")
if err != nil {
return nil, err
}
var templates []string
for _, vm := range vms {
if isTemplate, err := vm.IsTemplate(ctx); err == nil && isTemplate {
templates = append(data, vm.InventoryPath)
}
}
```
=> added IsTemplate vm helper

govc/device/cdrom/insert.go
For errors such as datastore not specified, cdrom.insert should report the error.
=> Report errors when cdrom.insert fails

vslm/global_object_manager.go
In the current code base, govmomi/vslm does not throw any errors even if API tasks are completed with error state, which would be confusing to govmomi client. Make the fix to throw errors as expected.
=> vslm: Fix to throw errors on tasks that are completed with error state

govc/README.md, govc/flags/debug.go, vim25/debug/debug.go, vim25/debug/file.go, vim25/debug/log.go
Most important part of this PR is the Scrub method added to the debug output to remove your password from the logs. To do this I just wrote a wrapper CloseWrite for FileType and to debug easier I wrote a LogType so decided to include it in the PR.
LogType uses go's log package and fakes a write/close to pass to the TeeReader and instead run a `log.Print()` on the contents which are normally written to file. This will show debug in your console while the command is running. @dougm would love your feedback as output is a bit messy but I didn't want to rock the boat too hard and kept some of file output like filename etc.
I additionally added a -debug to default to the stdout LogType method if no GOVC_DEBUG_PATH is not set so you don't magically write some log files without the govc user …
=> Debug Update to Add a Password Scrubber and stdout style LogType

govc/tags/info.go, govc/tags/ls.go
You can have two tags with the same name in vsphere only in different category. This updates tags.ls to send back the Category name so it makes more sense why there are two tags with the same name and removes the break in tags.info which made info only return 1 result and makes it work more like if you pass an empty string to tags.info which shows the info for all the tags in the system.
Example
```➜  govc git:(govc-tags) ✗ ./govc-dev tags.ls
New Tag      Luthers Tag Category
Luthers Tag  Luthers Tag Category
New Tag      asdf
```
Before my change
```
➜  govc git:(govc-tags) ✗ ./govc-dev tags.info "New Tag"
Name:           New Tag
ID:           urn:vmomi:InventoryServiceTag:ee4de041-48d8-4709-b5a5-d08add628c75:GLOBAL
Description:
Category:     Luthers Tag Category
UsedBy: []
```
After my …
=> Update tags.ls and tags.info to Support Tags with Same Name

sts/signer.go
Commit d296a5f added support HoK tokens with Interactive Users.
But if s.user is non-nil (in the case of govc session.login -issue), the Issue
request includes an empty principal, resulting in:
govc: ns0:RequestFailed: Empty principal name is not allowed
=> Avoid empty principal in HoK token request

cns/cns_util.go
Version `6.9.0` is not the stable vSAN Client Version we should use.
As per `sdk/vsanServiceVersions.xml` - `vSAN 6.7U3` is the right stable version we should be using.
Testing
-------
Executed test on vSphere 67u3 release to confirm APIs are returning correct task result containing objects with vsan namespace.
```
$ pwd
/Users/divyenp/go/src/github.com/vmware/govmomi/cns
$ export CNS_VC_URL='https://Administrator@vsphere.local:Admin!23@10.160.68.110'
$ export CNS_DATACENTER="datacenter"
$ export CNS_DATASTORE="vsanDatastore"
$ go test -v
--- PASS: TestClient (21.79s)
client_test.go:91: Creating volume using the spec: {DynamicData:{} Name:pvc-901e87eb-c2bd-11e9-806f-005056a0c9a0 VolumeType:BLOCK Datastores:[Datastore:datastore-39] Metadata:{DynamicData:{} …
```
=> Set stable vSAN client version

govc/fields/ls.go
Since you can't assign every field to MO type I added the ManagedObjectType to the table output. Also added -t filter to limit the list to only certain Manage Object Types.
```
➜  govc git:(field-type) ./govc-dev fields.ls
1    AutoDeploy.MachineIdentity                                  HostSystem
203  asdffffff                                                   VirtualMachine
2    com.vmware.vcIntegrity.customField.scheduledTask.action     ScheduledTask
3    com.vmware.vcIntegrity.customField.scheduledTask.signature  ScheduledTask
4    com.vmware.vcIntegrity.customField.scheduledTask.target     ScheduledTask
➜  govc git:(field-type) ./govc-dev fields.ls -t VirtualMachine
203  asdffffff  VirtualMachine
➜  govc git:(field-type) ./govc-dev fields.ls -t ScheduledTask
2 …
```
=> adding managed obj type to table

govc/test/vcsim.bats, simulator/container.go, simulator/feature_test.go
Rather than require users to supply a json encoded argument list,
let sh|bash do the work of parsing.
=> vcsim: simplify container vm arguments input

govc/cli/command.go, govc/test/cli.bats
3e3d351 added usage suggestions, this follow up does:
- make 'govc -h' behave as it used to
- if there are no command suggestions, print the complete list of commands
=> govc: fixup usage suggestions

object/distributed_virtual_switch.go
As we discussed in issue: https://github.com/vmware/govmomi/issues/1667
Open this PR to add a new method in order to provide a way for developers to update ports on a distributed virtual switch.
=> Add a method to update ports on a distributed virtual switch

session/keep_alive.go, session/keep_alive_test.go
The call to stop() triggered by a handler error would cause a deadlock.
Avoid the use of deferring notifyWaitGroup.Done(), instead calling it explicitly
on both return paths.
Note that the deadlock was not seen within the test until adding the defered
calls to Logout()
=> Avoid possible deadlock in KeepAliveHandler

object/host_config_manager.go, object/host_config_manager_test.go
Every ManagedObjectReference field in the HostConfigManager is optional.
Some can clearly be nil due to version and we already check for those:
https://code.vmware.com/apis/196/doc/vim.host.ConfigManager.html
This change adds nil checks for every field regardless of version.
=> Add nil checks for all HostConfigManager references

gen/vim_wsdl.rb, vim25/types/types.go, vslm/types/types.go
Another field optional in the wsdl, but with Go's "omitempty" semantics prevents a value of '0'.
Fixes #1686
=> Generate pointer type for ResourceReductionToToleratePercent

object/host_system.go, object/host_system_test.go, simulator/esx/host_config_info.go
Currently hostsystem ManagementIPs chooses 1st CandidateVnic in
hosts Config.VirtualNicManagerInfo.NetConfig property as the mgmt ip.
This is not correct. This changes switches to using  SelectedVnic
property for a management nicType instead.
Testing Done: Added a unittest.
Used govc to upload file to datastore and verified that IP chosen
was based on SelectedVnic property.
=> Fix hostsystem ManagementIPs call

go.mod, govc/library/create.go
Added SSL Thumbprint option to create library subscription.  Call was failing in both govc and postman without a valid SSL thumbprint present in the JSON
=> Added SSL Thumbprint option to create

govc/flags/cluster.go, govc/vm/clone.go, govc/vm/create.go
PR #1589 added the '-cluster' flag to vm.clone and vm.create commands.
However, the GOVC_CLUSTER env var should not be used as a default.
Fixes #1712
=> govc: avoid env for -cluster placement flag

gen/vim_wsdl.rb, vim25/types/types.go, vslm/types/types.go
This reverts commit 5e6f5e3f91cefdf32ec1e56cf99a14e41aa03abd.
=> Revert "gen: retain omitempty field tag with int pointer types"

simulator/virtual_machine.go
As vCenter/ESX validates, UnitNumber cannot be nil when creating a new VirtualDisk.
This validation would cause tests to fail starting with PR #1687 , fixed in PR #1723
=> vcsim: validate VirtualDisk UnitNumber

simulator/container.go
E.g. for passing it through to a Kubernetes cloud-provider.
The var is VMX_CONFIG_UUID.
=> Pass vm.Config.Uuid into the "VM" container via an env var

govc/test/vcsim.bats, simulator/container.go, simulator/model.go
"docker rm -v .." does not removed named containers,
add "docker volume rm ..." to remove it.
- Use the same name for containers and volumes:
"vcsim-$vm_name-$vm_uuid"
- Remove any remaining containers in Model.Remove
=> vcsim: remove container volumes

govc/emacs/govc.el, govc/sso/service/ls.go, govc/test/sso.bats, lookup/simulator/registration_info.go, lookup/simulator/simulator_test.go, sts/client.go
The "sso:sts" service type is obsolete, update to "cs.identity".
=> Move to cs.identity service type for sts endpoint

govc/host/esxcli/esxcli.go
=> govc: default to simple esxcli format when hints fields is empty

simulator/folder.go, simulator/object.go, simulator/resource_pool.go, simulator/simulator.go, simulator/virtual_machine.go
The Context.Caller field avoids deadlocks when using Registry.WithLock,
it should always be set to the current method invocation's "This" reference.
=> vcsim: automatically set Context.Caller

ssoadmin/client.go
The "sso:admin" service type is obsolete, update to "cs.identity".
=> Move to cs.identity service type for sso admin endpoint

simulator/race_test.go, simulator/registry.go, simulator/virtual_machine.go
It is possible the VM's parent folder is destroyed in the middle of a VM Destroy call,
return ManagedObjectNotFound in that case.
=> vcsim: avoid possible panic in VirtualMachine.Destroy_Task

vslm/global_object_manager.go
The param `changeId` is missing in constructing the VslmQueryChangedDiskAreas struct in the implementation of QueryChangedDiskArea Go API. Fixed it in this PR.
=> VSLM: fixed the missing param in the QueryChangedDiskArea API impl

simulator/simulator.go, vim25/examples_test.go, vim25/retry.go, vim25/soap/client.go
- simulator.StatusSDK can be used to respond with any status code
- soap.Client returns a url.Error instead of errors.New for HTTP status codes
- Custom error type implements the Temporary interface for use by retry handlers
- Add vim25.TemporaryNetworkError example
=> Add retry support for HTTP status codes

vslm/global_object_manager.go
The RetrieveSnapshotDetails API is necessary for the incremental backup of FCD or CNS block volume. Somehow, the API is not added initially.
=> Added the missing RetrieveSnapshotDetails API in VSLM

govc/library/info.go, govc/test/library.bats
- The -l flag outputs Size and Item count for Libraries
- The -l flag outputs 'Datastore Path'
- The -L flag outputs only the Datastore Path
Example use: Content Library iso file as VM cdrom backing
Fixes #1697
=> govc: add optional library.info details

govc/library/deploy.go, vapi/vcenter/vcenter_ovf.go
This addresses issue #1718 so you can deploy an OVA from the content library _and_ specify properties typically required to deploy an OVA.
We're using this to deploy nsx-unified-appliance-2.5.0.0.0.14663978 from our local content library.
=> Add OVF properties to library deploy

govc/dvs/change.go, govc/dvs/create.go
The requirement of the additional`Operation` field on `LinkDiscoveryProtocolConfig` requires the check of the flag, rather than direct binding to the `Protocol` field in the config spec. They need to be set together if the protocol is provided.
=> Add ability to set DVS discovery protocol on create and change

govc/cli/command.go, govc/vm/guest/guest.go, govc/vm/guest/run.go, guest/file_manager.go, guest/toolbox/client.go, toolbox/toolbox-test.sh
- Propagate exit code to govc's exit code
- Default to cmd.exe /c on Windows (required for i/o redirection)
- Default to /bin/bash -c on Linux (convenience)
- Fix process exit polling
- Remove toolbox specific guest run implementation
=> govc: guest.run improvements

govc/vm/create.go
=> govc: add 5.0 to vm.create hardware version map

object/distributed_virtual_portgroup.go, object/distributed_virtual_portgroup_test.go
The error message sounded like a permission issue with the DVPG itself, rather than the Switch.
Attempt to make the error message more clear, add comments and vcsim based test.
Closes #1517
=> Clarify System.Read privilege requirement for PortGroup backing

govc/library/sync.go, govc/test/library.bats, vapi/internal/internal.go, vapi/library/library.go, vapi/library/library_item.go, vapi/simulator/simulator.go, vapi/vcenter/vcenter_vmtx.go
- vAPI: add sync client APIs
- vAPI: add helpers to sync subscribed library OVF items to local library VMTX items
- vcsim: support sync APIs
- govc: add library.sync command
=> Add Content Library synchronization support

govc/vm/guest/auth.go, govc/vm/guest/getenv.go, govc/vm/guest/guest.go, govc/vm/guest/kill.go, govc/vm/guest/ps.go, govc/vm/guest/run.go, govc/vm/guest/start.go
8a069c27 added the -i flag to all guest.* commands,
but it only applies to ProcessManager methods, not used for FileManager.
=> govc: guest -i flag only applies to ProcessManager

sts/client_test.go, sts/internal/types.go
The string type prefix changed from 'xs' to 'xsd', resulting in "Signature is invalid"
error when issuing ActAs tokens.
Fixes #1785
=> Fix AttributeValue.C14N for 6.7u3

Makefile, vim25/client.go
Make sure we use vim25/xml everywhere.
No functional harm in this case, but reduces govc binary size a bit (190K)
=> Avoid encoding/xml import

simulator/virtual_disk_manager.go
This change makes the simulator behave more like a real vCenter in the presence
of missing VMKDs. In particular, it conforms to an expectation of VCP, which
allows to use the simulator with that k8s provider.
=> fix simulator disk manager fault message.

govc/flags/client.go
As sha1 becomes less secure, let's move to sha256 where possible.
Since the client hashes the URI to determine what stored session to reuse,
potential collisions (as unlikely as they might be) could open the way to
session hijacking. Using sha256 affords better protection.
=> govc: save sessions using sha256 ID

govc/cli/command.go, govc/flags/output.go, govc/test/cli.bats, govc/test/vm.bats
- Default to indented output by default for -{json,xml,dump}
- Add xml output option
- Format errors if possible when -{json,xml,dump} is given
=> govc: output formatting enhancements

object/common.go, object/common_test.go, object/network.go
Using mo.ManagedEntity does not work with network entities as mo.Network
has its own Name field. Switching to ObjectContent which works with all
types, avoiding the 2nd call for network types.
- Fix comment regarding InventoryPath (see #734)
=> Simplify ObjectName method

govc/object/collect.go, govc/test/object.bats
The main use case for -o is to output a Managed Object structure as Go code,
for use within vcsim.  It also provides a more concise version of -json and
-xml encoded structures, compared to the default ObjectUpdate version.
=> govc: add object.collect -o flag

govc/test/tags.bats, vapi/simulator/simulator.go
vCenter allows tags with the same name, provided the category is not the same.
=> vcsim: support tags with the same name

govc/vm/create.go, govc/vm/option/info.go
Also output the possible guest IDs from vm.option.info
=> govc: fix doc for -g flag (guest id) choices

simulator/virtual_machine.go
It is possible the VM's parent folder is destroyed in the middle of a VM Unregister call,
avoid a panic in that case.  See also: 1427d581 (#1744)
=> vcsim: avoid possible panic in UnregisterVM_Task

govc/library/clone.go, govc/test/library.bats, vapi/simulator/simulator.go, vapi/vcenter/vcenter_ovf.go, vapi/vcenter/vcenter_vmtx.go
The library.clone flag only supported cloning as VM Template (vmtx),
but the UI supports both vmtx and ovf.
Fixes #1814
=> govc: add library.clone -ovf flag

govc/flags/output.go, govc/importx/spec.go, govc/test/import.bats
As of d2e6b7df, the output of '-json' is indented by default.
Make use of that behavior with the import.spec command.
Enable several import tests against vcsim.
=> govc: use OutputFlag for import.spec

vim25/client.go
The UseServiceVersion method was hardcoded to the vim25 namespace,
allow the method to be used with other namespaces.  For example:
c := cns.NewClient(...)
err = c.UseServiceVersion("vsan")
=> Add Namespace support to UseServiceVersion

govc/cluster/group/ls.go, govc/test/cluster.bats
The '-l' flag will output the group type and unique id.
The complete BaseClusterGroupInfo structure is also included
for use with format flags (-{json,dump,xml})
=> govc: add cluster.group.ls -l flag

toolbox/toolbox-test.sh
The current releases fail to boot with 1G memory, bump to 2G.
Switch to stable coreos release.
=> toolbox: bump test VM memory for current CoreOS release

lookup/client.go, lookup/simulator/simulator_test.go
As of d7430825, lookup.NewClient uses ServiceContent.Setting.
However, there is existing code that creates vim25.Client without
initializing ServiceContent, resulting in a nil pointer dereference.
The use of Setting was only needed for external PSC, make it optional
to avoid the NPE.
=> Avoid ServiceContent requirement in lookup.NewClient

CHANGELOG.md, CONTRIBUTING.md, govc/flags/client.go, govc/flags/host_connect.go, session/manager.go, vapi/library/library.go, vapi/library/library_item_updatesession_file.go, vim25/soap/client.go
Now there is a "prettier" way to customize things like certificate verification (at your own risk)
=> Expose Soap client default transport 

govc/test/vm.bats, simulator/virtual_machine.go
While VM objects can live anywhere in the inventory, the datastore path for VM files is limited.
Rename the VM datastore path to be unique, unless full path to .vmx is specified.
=> vcsim: support VMs with the same name

govc/flags/library.go, govc/library/create.go, govc/library/info.go, govc/library/publish.go, govc/library/subscriber/create.go, govc/library/subscriber/info.go, govc/library/subscriber/ls.go, govc/library/subscriber/rm.go, govc/main.go, govc/test/library.bats, vapi/internal/internal.go, vapi/library/library.go, vapi/library/library_item.go, vapi/simulator/simulator.go, vapi/vcenter/vcenter_vmtx.go
Quoting the H5 UI:
> Subscriptions allow a bi-directional relationship between Publisher and Subscriber libraries.
> This enables you to synchronize content both from the Publisher (Publish) and from the Subscriber (Sync).
- vapi: add library/subscriptions bindings
- vapi: add PublishLibrary binding
- vcsim: add library/subscriptions support
- vcsim: add publish support
- govc: add '-pub' flag to library.create (enable publishing)
- govc: add Publication section to library.info
- govc: add library.publish command
- govc: add library.subscriber.{create,rm,ls,info} commands
=> Add Content Library subscriptions support

govc/library/deploy.go, vapi/vcenter/vcenter_ovf.go
Resolve #1856
As per the VMware vSphere Automation SDK REST 6.7.0 API documentation (ref. https://code.vmware.com/apis/366/vsphere-automation/VMware-vSphere-Automation-SDK-REST-6.7.0/docs/apidocs/operations/com/vmware/vcenter/ovf/library_item.deploy-operation.html) the `deployment_spec.additional_parameters` field contains additional OVF parameters that may be needed for the deployment.
> Examples of OVF parameters that can be specified through this field include, but are not limited to:
> vcenter.ovf.deployment_option_params
> vcenter.ovf.extra_config_params
> vcenter.ovf.ip_allocation_params
> vcenter.ovf.property_params
> vcenter.ovf.scale_out_params
> vcenter.ovf.vcenter_extension_params
Given the above the correct `@class` for specifying deployment option params is …
=> Replaced `ClassOvfParams` with `ClassDeploymentOptionParams`

govc/USAGE.md, govc/vm/disk/attach.go
Resolve #1833
The rationale for this change is to have a consistent `backing.DiskMode` override logic in `vm.disk.attach`:
|`link`|`persist`|`mode`|old `DiskMode`|new `DiskMode`|
|---|---|---|---|---|
|`true`|`true`||`persistent`|`independent_persistent`|
|`true`|`false`||`nonpersistent`|`independent_nonpersistent`|
|`false`|`true`||`persistent`|`persistent`|
|`false`|`false`||`nonpersistent`|`nonpersistent`|
|`true`|`true`|`undoable`|`persistent`|`undoable`|
|`true`|`false`|`undoable`|`nonpersistent`|`undoable`|
|`false`|`true`|`undoable`|`persistent`|`undoable`|
|`false`|`false`|`undoable`|`nonpersistent`|`undoable`|
Note: the **default** behaviour changed from `persistent` to `independent_persistent` given that by default both `link` and `persist` are `true`.
=> Disk mode should override default value in vm.disk.attach

govc/USAGE.md, govc/export/ovf.go
Resolve #1348
Added a new `prefix` boolean parameter to toggle target name prefixing of image filenames in `export.ovf`.
`govc/USAGE.md` has been updated accordingly.
Note: it defaults to `true` in order not to change the previous default behavior.
=> Added prefix toggle parameter to govc export.ovf

property/collector.go
=> Fixed ContainerView.RetrieveWithFilter fetch all specs if empty list of properties given

govc/vm/change.go
Supports "Reserve all guest memory" option
Issue #1871
=> govc: add vm.change '-memory-pin' flag

govc/test/network.bats, simulator/virtual_machine.go
The generateMAC function was using the VM UUID for all NICs, so multiple NICs had the same MAC.
Add the device UnitNumber to make each MAC unique.
Fixes #1879
=> vcsim: unique MAC address for VM NICs

govc/compute/policy/create.go, govc/compute/policy/ls.go, govc/compute/policy/rm.go, govc/main.go, govc/test/compute.bats, vapi/compute/internal/internal.go, vapi/compute/policy.go, vapi/compute/simulator/simulator.go, vapi/internal/internal.go, vcsim/main.go
- Add vAPI REST client support
- Add govc compute.policy.{ls,rm.create} commands
- Add simulator support and bats tests
=> Compute Policy support

govc/compute/policy/ls.go, vapi/compute/policy.go
When compute.policy.ls is given an argument, list only the specific policy or capability.
=> govc: support optional compute.policy.ls argument

govc/library/export.go, vapi/internal/internal.go, vapi/rest/client.go, vapi/simulator/simulator.go
Cookie based authentication will be deprecated soon, switch to using
header based authentication by default.
Note: for vCenter versions that doesn't support vmware-use-header-authn,
rest.Client will continue to use cookie authn transparently via Go's
http.Client cookie.Jar
=> vapi: prefer header authn to cookie authn

vslm/global_object_manager.go
Fix the types of errors returned from VSLM tasks to be their originl vim faults rather than just wrappers of localized error msg. With this change, API users of govmomi/vslm will be able to handle vslm task errors by checking their BaseMethodFault types rather than by checking their error messages.
Signed-off-by: Lintong Jiang <lintongj@vmware.com>
=> Fix the types of errors returned from VSLM tasks 

govc/test/session.bats, govc/test/vcsim.bats, simulator/session_manager.go
Return NotFound fault if session key does not exist.
- Switch remaining session tests to use vcsim
- Add session persist test
- Use mktemp --tmpdir when creating test directories
=> vcsim: validate session key in TerminateSession method

object/task.go
SetTaskState lets you set the state of the task.
SetTaskDescription sets the description of the task in the UI
UpdateProgress changes the progress bar of the task in the UI.
=> Add SetTaskState SetTaskDescription UpdateProgress to object package

govc/object/collect.go, property/wait.go
vCenter caps WaitForUpdates to 100 max, when doing so sets the Truncated field to true.
Check this field in object.collect to avoid truncating results.
Fixes #1893
=> govc: avoid truncation in object.collect

govc/library/checkin.go, govc/library/checkout.go, govc/test/library.bats
This feature is included with vSphere 7
=> govc: enable library.checkout and library.checkin by default

govc/test/vm.bats, simulator/virtual_machine.go
- Add MarkAsVirtualMachine method
- MarkAsTemplate now sets the vm ResourcePool = nil and MarkAsVirtualMachine sets the ResourcePool.
- CloneVm now requires the spec.location.pool param when cloning a template
- MarkAsTemplate returns NotSupported if the vm is already a template
Fixes #1896
=> vcsim: VM templates do not have a ResourcePool

simulator/registry.go, simulator/virtual_disk_manager.go, simulator/virtual_machine.go, simulator/vstorage_object_manager.go
This is part of a fix for #1841.
It allows custom implementations of the VirtualDiskManager to be registered into
the registry without disrupting internal use of the corresponding singleton, as
long as they match VirtualDiskManagerInterface.
The methods there are extended to include a *simulator.Context. Even though the
default implementations don't need it, custom implementations might.
=> simulator: add interface for VirtualDiskManager

govc/about/cert.go, govc/flags/client.go, govc/session/login.go, govc/session/logout.go, govc/sso/client.go, govc/sso/user/id.go, govc/test/session.bats, session/cache/example_test.go, session/cache/session.go, vapi/rest/client.go, vim25/client.go
- Add govc support for persistent REST sessions
- Add REST support to session.login command (including token auth)
Fixes #1873
Fixes #1810
=> Refactor govc session persistence into session/cache package

vapi/simulator/simulator.go
Subscribers share the same Item map, we need the LOCAL library to find the .ovf on disk.
The test was flaky since we'd randomly find the SUBSCRIBED library instead of LOCAL,
causing the test to fail.
=> vcsim: fix flaky library subscriber test

simulator/esx/host_system.go
HostSystem has a required field 'LicensableResource': https://code.vmware.com/apis/704/vsphere/vim.HostSystem.html#field_detail
This causes some clients that validate manditory fields with an error that might look like: 'Missing value for non-optional field resource'
The MOB view of a vanilla *real* ESXi host might look something like:
---------------------------------------------------------
| Name     | Type          | Value                      |
---------------------------------------------------------
| resource | KeyAnyValue[] | resource["numCpuPackages"] |
---------------------------------------------------------
This commit fills in this value with a sensible value that matches the NumCpuPackages specified in host_hardware_info,
and prevents clients from failing when encountering …
=> Add non-null HostLicensableResourceInfo to HostSystem

govc/test/import.bats, simulator/ovf_manager.go
The vcsim OvfManager.CreateImportSpec implementation assumed the
Disk ovf:capacityAllocationUnits attribute is always present and would
panic if it wasn't.
Return the Disk capacity without any conversion to fix this case.
Fixes #1909
=> vcsim: avoid panic if ovf:capacityAllocationUnits is not present

session/cache/session.go
Follow up to #1898 - use the same defaults as Terraform for session file cache.
=> Default to separate session cache directories

govc/test/sso.bats, lookup/simulator/registration_info.go, lookup/simulator/simulator.go, lookup/simulator/simulator_test.go, simulator/event_manager.go, simulator/event_manager_test.go
Commit 08adb5d6 (#1740) removed the obsolute sso:sts type in favor of cs.identity,
but PowerCLI still uses sso:sts.
Commit 43d69860 (#1595) changed endpoint registration to happen before vcsim's TLS cert is known,
leaving ServiceEndpoints.SslTrust empty, but PowerCLI requires this field be non-empty.
=> vcsim: fixes for PowerCLI

simulator/virtual_machine.go, simulator/virtual_machine_fault_test.go
When adding a DVPG backed network to a VM, vCenter requires that all hosts in the ResourcePool
are connected to the DVS.
=> vcsim: validate DVS membership

sts/internal/types.go, vim25/xml/read.go
The vim25/xml sync in #1800 broke delegated HoK signatures,
due to an empty AttributeValue.Type in the RequestSecurityToken body.
Make use of the 'typeattr' field flag to ensure the Type field is
properly marshaled in this case.
=> Fix delegated Holder-of-Key token signature

guest/file_manager.go, guest/file_manager_test.go
Avoid using host.Config if nil, SDK doc says "This might not be available for a disconnected host."
=> Avoid possible nil pointer dereference in guest TransferURL

govc/test/vcsim.bats, simulator/virtual_machine.go
In order to set a VM guest net.config ipAddress, a VM ethernet card device must be present.
The original code worked fine for existing VMs, but we need to apply ExtraConfig after devices
for SET to work properly when creating new VMs.
Issue #1928
=> vcsim: apply ExtraConfig after devices

govc/vm/clone.go
When -cluster is specified, PlaceVm returns the HostSystem and Datastore
to use in the VirtualMachineRelocateSpec.  No need to set the spec Pool
field unless the -pool flag is also specified.
Fixes #1936
=> govc: vm.clone ResourcePool is optional when -cluster is specified

pbm/client.go, pbm/client_test.go
Add `GetProfileNameByID` functionality to govmomi. 
Also added a sample test code to test this function.
```
TestClient: client_test.go:284: VSAN-SIOC Profile: "2d8a11a7-6da5-4f9e-a3ae-b308aeb90500" successfully created
TestClient: client_test.go:297: VSAN-SIOC profile: "2d8a11a7-6da5-4f9e-a3ae-b308aeb90500" and retrieved profileID: "2d8a11a7-6da5-4f9e-a3ae-b308aeb90500" successfully matched
TestClient: client_test.go:309: vsan-sioc profile: "Kubernetes-VSAN-SIOC-TestPolicy" and retrieved profileName: "Kubernetes-VSAN-SIOC-TestPolicy" successfully matched
TestClient: client_test.go:316: Profile: [{DynamicData:{} UniqueId:af9ec97a-7ad1-4d38-bd67-693c1b3b8f58} {DynamicData:{} UniqueId:2d8a11a7-6da5-4f9e-a3ae-b308aeb90500}] successfully deleted
```
cc @divyenpatel @dougm
=> Add GetProfileNameByID functionality to PBM

cns/client.go, cns/client_test.go, cns/cns_util.go, cns/types/if.go, cns/types/types.go
This PR does the following
-  Add BackingDiskUrlPath and CnsAlreadyFault go bindings to CNS APIs
-  Update CreateVolume CNS Util  to include BackingDiskUrlPath
-  Add sample test for Create CNS API using backing disk Url path
Logs for sample test code
```
TestClient: client_test.go:668: Creating volume using the spec: types.CnsVolumeCreateSpec{
Name:       "pvc-901e87eb-c2bd-11e9-806f-005056a0c9a0",
Datastores: nil,
Metadata:   types.CnsVolumeMetadata{
ContainerCluster: types.CnsContainerCluster{
ClusterType:   "KUBERNETES",
ClusterId:     "demo-cluster-id",
VSphereUser:   "Administrator@vsphere.local",
ClusterFlavor: "VANILLA",
},
EntityMetadata:        nil,
ContainerClusterArray: nil,
},
BackingObjectDetails: &types.CnsBlockBackingDetails{
CnsBackingObjectDetails: …
```
=> Add BackingDiskUrlPath and CnsAlreadyFault go bindings to CNS APIs

cns/client_test.go, cns/cns_util.go, cns/types/types.go
This PR does the following
1. In CNS Client test, add retry logic to create a CNS volume with backingdiskUrlPath. This time it will catch CnsAlreadyRegisteredFault and print the log message.
2. Fix binding for CnsAlreadyRegisteredFault
executed all tests in cns/client_test.go and adding relevant logs related to this PR.
```
TestClient: client_test.go:668: Creating volume using the spec: types.CnsVolumeCreateSpec{
Name:       "pvc-901e87eb-c2bd-11e9-806f-005056a0c9a0",
Datastores: nil,
Metadata:   types.CnsVolumeMetadata{
ContainerCluster: types.CnsContainerCluster{
ClusterType:   "KUBERNETES",
ClusterId:     "demo-cluster-id",
VSphereUser:   "Administrator@vsphere.local",
ClusterFlavor: "VANILLA",
},
EntityMetadata:        nil,
ContainerClusterArray: nil,
}, …
```
=> Add retry tests for CNS Create API with backingdiskUrlPath and fix CNS binding for CnsAlreadyRegisteredFault

vcsim/README.md
I found a mistake for markdown link parenthesis of vcsim Readme.
This PR is modified that.
=> Modify parenthesis for markdown link

simulator/host_system.go, simulator/search_index.go, simulator/virtual_machine.go
This change relaxes some strong constraints on the exact type of VM and host
objects in the SearchIndex.
Previously, when registering a custom implementation of those objects the
SearchIndex would simply fail to find them. Using the corresponding MO instead
removes that limitation.
=> simulator: relax excessive type assertions in SearchIndex

govc/flags/resource_pool.go, govc/importx/ovf.go, govc/test/import.bats, simulator/ovf_manager.go, simulator/resource_pool.go
VirtualApp extends ResourcePool, so the govc -pool flag should support VirtualApp types.
Fixes #1956
=> govc: support VirtualApp with -pool flag

cns/simulator/simulator.go
This change is to add logic in simulator's CnsCreateVolume to return default HealthStatus "green" when creating a volume.
Test Result
```
lipingx-a01:simulator lipingx$ go test . -v
=== RUN   TestSimulator
--- PASS: TestSimulator (0.04s)
PASS
ok  	gitlab.eng.vmware.com/hatchway/govmomi/cns/simulator	3.962s
```
=> Add logic to return default HealthStatus in CnsCreateVolume.

simulator/cluster_compute_resource.go, simulator/datacenter.go, simulator/datastore.go, simulator/dvs.go, simulator/entity.go, simulator/entity_test.go, simulator/file_manager.go, simulator/folder.go, simulator/folder_test.go, simulator/host_datastore_system.go, simulator/host_network_system.go, simulator/host_system.go, simulator/model.go, simulator/portgroup.go, simulator/property_collector_test.go, simulator/registry.go, simulator/service_instance.go, simulator/virtual_machine.go
The previous approach had the following issues:
- some private methods were attached to Folder, when they really applied to
mo.Folder. As a result, they prevented using a custom implementation of a
simulator folder object
- the putChild/removChild methods didn't lock the folder properly, generating
data races
To address the former, move from private Folder methods to functions that take
a *mo.Folder as first parameter, and adjust call sites.
To address the latter, we need to add proper locking on the *mo.Folder object.
But unfortunately we need the session locking for these, as these operations
are (also) applied during some simulator.Folder API operations, meaning that the
folder is already locked for these.
As a result, we need to pass a simulator.Context around, and adjust the …
=> simulator: refactor folder children operations

vapi/simulator/simulator.go, vapi/tags/tag_association.go
Added method for attaching a tag to multiple objects following this documentation:
https://vdc-download.vmware.com/vmwb-repository/dcr-public/1cd28284-3b72-4885-9e31-d1c6d9e26686/71ef7304-a6c9-43b3-a3cd-868b2c236c81/doc/operations/com/vmware/cis/tagging/tag_association.attach_tag_to_multiple_objects-operation.html
Tested with vCenter 6.5 and 6.7.
=> Add support for attach-tag-to-multiple-objects

govc/library/export.go, govc/session/login.go, govc/session/ls.go, session/cache/session.go, vapi/rest/client.go
Required for the upcoming KeepAlive support.
=> vapi: sync access to rest.Client.SessionID

govc/flags/client.go, govc/library/deploy.go, govc/library/import.go, session/keep_alive.go, session/keep_alive_test.go, session/keepalive/example_test.go, session/keepalive/handler.go, session/keepalive/handler_test.go, simulator/session_manager.go, vapi/simulator/simulator.go
Refactor the SOAP based session.KeepAlive into its own package that
can be used for both SOAP and REST sessions.
Expose the Start and Stop methods for use with cache.Client (e.g. govc)
Enable KeepAlive in govc library.{deploy,import} commands
Fixes #1832
Fixes #1839
=> Add REST session keep alive support

vcsim/README.md
I modified markdown link. 
Because this link goes to incorrect link (404 Not Found).
=> vcsim: modify markdown link at README.md

govc/USAGE.md, govc/vm/guest/run.go
Adding another example for using guest.run. One that passes the datacenter and login credentials.
=> providing examples for govc guest.run

simulator/view_manager.go
I introduced a regression in #1967, by not handling a nil mo.Reference before
calling getManagedObject(), which leads in some cases to:
panic: reflect: call of reflect.Value.Elem on zero Value
This change just restores the old behavior of doing nothing if the Reference is
nil (thus couldn't be cast into any of the known managed object types)
=> simulator: fix handling of nil Reference in container walk

pbm/pbm_util.go
Pbm Client test results
```
asumit$ go test  ./pbm 
--- FAIL: TestClient (9.53s)
client_test.go:59: PBM version=2.0
client_test.go:137: checking 8 datatores for compatibility results
client_test.go:162: CheckRequirements results: 104
client_test.go:207: VSAN Profile: "3b139387-61e3-418c-bbab-dedaae8ce3a6" successfully created
client_test.go:214: Profile: "3b139387-61e3-418c-bbab-dedaae8ce3a6" exists on vCenter
client_test.go:218: Found 8 compatible-datastores for profile: "3b139387-61e3-418c-bbab-dedaae8ce3a6"
client_test.go:222: Found 96 non-compatible datastores for profile: "3b139387-61e3-418c-bbab-dedaae8ce3a6"
client_test.go:226: 96   8   8
client_test.go:227: datastore count mismatch
client_test.go:283: VSAN-SIOC Profile: "979e678b-860c-4ea7-bbef-4aa072a5d7d3" successfully created …
```
=> Adding subProfileName in pbm.CapabilityProfileCreateSpec

simulator/virtual_machine.go, simulator/virtual_machine_test.go
simulator CreateSnapshotTask should return the created snapshot mo-ref on success,
similar to vSphere behavior
issue #1991
=> vcsim: CreateSnapshotTask now returns moref in result

govc/importx/ovf.go, govc/test/import.bats, govc/test/network.bats, govc/vm/network/add.go, list/lister.go, simulator/dvs.go
vCenter doesn't allow duplicate port group names within the network folder when creating via the UI
or the AddDVPortgroupTask() API. However, NSXt 3.0 can do so via other (unknown) means. With this
condition, govc would fail to map the given network name to its managed object reference.
To workaround this, a raw MO ref can now be used in the NetworkMapping, instead of the Network name
or inventory path.
Related history:
223168f0 * Add NetworkMapping section to importx options.
e3c3cd0a * Populate network mapping from ovf envelope (#546)
Fixes #1996
=> govc: support raw object references in import.ova NetworkMapping

govc/appliance/logging/forwarding.go, govc/main.go, govc/vcsa/log/forwarding.go, vapi/appliance/logging/forwarding.go
Appliance logging config can be retrieved via the VAPI REST
endpoint.  The govc output is as follows.
```
$ govc appliance.logging.forwaring
Hostname:  10.186.54.118
Port:      5480
Protocol:  TLS
Hostname:  2.2.2.2
Port:      9999
Protocol:  TLS
```
=> Add appliance log forwarding config handler and govc verb

govc/library/export.go, govc/library/import.go, govc/test/library.bats, vapi/rest/client.go
PR #1884 switch REST from Cookie to Header authentication. This caused existing
Content Library use of file Upload/Download to break with 401 Unauthorized
responses.
These wrappers simply add the vmware-api-session-id header to the requests.
=> vapi: use header authentication in file Upload/Download

govc/test/vcsim.bats, simulator/host_network_system.go, simulator/model.go
The simulator.HostNetworkSystem wrapper was not included in the refactor to
support 'vcsim -load'
Fixes #2106
=> vcsim: use HostNetworkSystem wrapper with -load flag

govc/test/cluster.bats, simulator/host_system.go, simulator/object.go, simulator/object_test.go
If HostConnectSpec.HostName is an IP address, also use it to set
Config.Network.Vnic[0].Spec.Ip.IpAddress
Fixes #1981
=> vcsim: set HostSystem IP in cluster AddHost_Task

cns/client_test.go, cns/cns_util.go
Fixes https://github.com/vmware/govmomi/issues/2010, https://github.com/kubernetes-sigs/vsphere-csi-driver/issues/249
Fixed issue reported by @SandeepPissay at - https://github.com/kubernetes-sigs/vsphere-csi-driver/pull/235#discussion_r437054326
QueryVolumeInfo can take multiple Volumes IDs as input and should returns an array of BaseCnsVolumeOperationResult.
In this PR, I am adding function `GetTaskResultArray` to help retrieve array of BaseCnsVolumeOperationResult for all specified volumes in the QueryVolumeInfo request.
Testing Done.
**Request**
```
client_test.go:224: Calling QueryVolumeInfo using: []types.CnsVolumeId{
{
Id: "759f3fa8-f692-4a8e-b65c-3fcd56d0f947",
},
{
Id: "c2c2d2bb-f864-4e4f-9bde-39ca6b1302b6",
},
{
Id: "6885ca7d-09a3-40f5-9706-475cbd479934",
},
}
```
**Response** …
=> added support for returning array of BaseCnsVolumeOperationResult for QueryVolumeInfo API

object/virtual_machine.go
Signed-off-by: Yassine TIJANI <ytijani@vmware.com>
This checks if a config isn't nil, before returning an uuid this can happen under some cases see: https://vdc-download.vmware.com/vmwb-repository/dcr-public/b50dcbbf-051d-4204-a3e7-e1b618c1e384/538cf2ec-b34f-4bae-a332-3820ef9e7773/vim.VirtualMachine.html
cc @dougm
=> check if config isn't nil before returning an uuid

simulator/virtual_machine.go
This change is for honoring the InstanceUuid provided by caller in case of VM cloning.
Actual vSphere supports this scenario.
=> Honoring the instance uuid provided in spec by caller

object/virtual_machine.go
Simple change to add wrappers around AttachDisk_Task and DetachDisk_Task,
to allow calling them from the VirtualMachine object.
Fixes #1846
=> Add AttachDisk and DetachDisk wrappers for the virtualMachine object.

find/finder.go, object/example_test.go
Rather than suggest Finder.Element to get an object's inventory path,
refactor to an InventoryPath function that does not require a Finder
instance.
examples: add VirtualMachine.ResourcePool
Fixes #2078
=> finder: simplify direct use of InventoryPath func

govc/device/pci/add.go, govc/device/pci/ls.go, govc/device/pci/remove.go, govc/main.go
also enable list command to display available pci passthrough devices
this allows automation or human to associate pci passthrough device
Signed-off-by: leslie-qiwa <leslie.qiwa@gmail.com>
https://github.com/vmware/govmomi/issues/1563
=> add / remove pci passthrough device for one VM

find/finder.go, govc/object/find.go, govc/test/object.bats, internal/helpers.go
Useful for finding object parents, such as the Datacenter for a given inventory path.
=> govc: add find -p flag

vim25/xml/marshal.go, vim25/xml/marshal_test.go, vim25/xml/read.go, vim25/xml/typeinfo.go, vim25/xml/xml.go, vim25/xml/xml_test.go
Applied via:
% cd ~/go/src/github.com/golang/go
% git diff go1.13.6..go1.15 src/encoding/xml > encoding-xml.patch
% cd ~/go/src/github.com/vmware/govmomi/vim25/xml
% patch -p4 < ~/go/src/github.com/golang/go/encoding-xml.patch
Diff after sync: https://gist.github.com/dougm/a941f77324a6172712430c3ff9ff8c63
=> vim25/xml: sync with Go 1.15 encoding/xml

simulator/race_test.go, simulator/registry.go, simulator/view_manager.go
PR #2069 attempted to fixed a race, but introduced a panic - missed because race_test.go did
not check the return error.
=> vcsim: fix ListView.Modify

sts/signer.go
The only request that is signed by this method always has an empty body:
https://vmware.github.io/vsphere-automation-sdk-rest/vsphere/operations/com/vmware/cis/session.create-operation.html
The 'bodyhash' header param of an empty string is still required in the signature however.
But should the request body be non-empty, we need to use sha256.Sum256() as @dgryski pointed out.
=> sts: fix SignRequest bodyhash for non-empty request body

govc/test/vm.bats, govc/vm/clone.go
=> govc: fix vm.clone panic when target VM already exists

vsan/client.go, vsan/client_test.go, vsan/methods/methods.go, vsan/types/types.go
Added couple of vsan api interface which is required for my e2e-test automation
Testing Done:
go test -v
```
--- PASS: TestClient (4.04s)
=== RUN   TestVsanQueryObjectIdentities
TestVsanQueryObjectIdentities: client_test.go:128: Printing clusterConfig:
&types.VsanObjectIdentityAndHealth{
Health:       (*types.VsanObjectOverallHealth)(nil),
Identities:   &types.VsanObjectIdentity{Uuid:"84c65a5f-46ed-c821-dedf-02005e6ac5d0"},
RawData:      "",
SpaceSummary: nil,
}
--- PASS: TestVsanQueryObjectIdentities (4.71s)
PASS
ok      github.com/vmware/govmomi/vsan  8.770s
```
=> vSAN methods QueryVsanObjects and VsanQueryObjectIdentities has been added 

cns/client_test.go, cns/cns_util.go, cns/types/types.go
This pull request is adding a go binding for ClusterDistribution to support CNS telemetry and also make cns/client.go backward compatible to vsan67u3 and vsan70 by dropping optional fields not known to the prior releases.
Testing:
For VC version > 7.0
```
% export CNS_VC_URL='https://Administrator@vsphere.local:Admin!23@10.78.100.14/sdk'
% export CNS_DATACENTER='VSAN-DC'
% export CNS_DATASTORE='vsanDatastore'
% go test -v
--- PASS: TestClient (32.61s)
client_test.go:128: Creating volume using the spec: types.CnsVolumeCreateSpec{
Name:       "pvc-901e87eb-c2bd-11e9-806f-005056a0c9a0",
Datastores: []types.ManagedObjectReference{
{Type:"Datastore", Value:"datastore-36"},
},
Metadata: types.CnsVolumeMetadata{
ContainerCluster: …
```
=> Add ClusterDistribution field for CNS telemetry

simulator/search_index.go
fatal error: concurrent map iteration and map write
goroutine 43135 [running]:
runtime.throw(0x10562ad, 0x26)
/goroot/src/runtime/panic.go:774 +0x72 fp=0xc0007dd040 sp=0xc0007dd010 pc=0x42f872
runtime.mapiternext(0xc0007dd108)
/goroot/src/runtime/map.go:858 +0x579 fp=0xc0007dd0c8 sp=0xc0007dd040 pc=0x410c79
github.com/vmware/govmomi/simulator.(*SearchIndex).FindByUuid(0xc0002f8f00, 0xc001e898b0, 0x0, 0x0)
/gopath/src/github.com/vmware/govmomi/simulator/search_index.go:126 +0xfe fp=0xc0007dd178 sp=0xc0007dd0c8 pc=0xba53ae
runtime.call32(0xc0005110b0, 0xc0016c03c0, 0xc00166f6c0, 0x1000000020)
/goroot/src/runtime/asm_amd64.s:539 +0x3b fp=0xc0007dd1a8 sp=0xc0007dd178 pc=0x45ac8b
reflect.Value.call(0xf85260, 0xc0002f8f00, 0x1a13, 0x10092c3, 0x4, 0xc00166f680, 0x1, 0x1, 0xb, 0xb, ...) …
=> Fix for fatal error in VCSim: concurrent map iteration and map write

govc/README.md, govc/test/cli.bats, simulator/session_manager.go, vim25/soap/client.go
vCenter login methods include the Secure flag in Set-Cookie responses.
Go's cookiejar impl does not send secure cookies unless the URL scheme is https.
This prevents use of govmomi/govc against the non-TLS vpxd endpoint (127.0.0.1:8085)
To enable use of secure cookies in this case: export GOVMOMI_INSECURE_COOKIES=true
To make vcsim include the Secure flag in Set-Cookie responses: export VCSIM_SECURE_COOKIES=true
=> Add option to disable secure cookies with non-TLS endpoints

object/virtual_device_list.go
Problem: Add two network cards to a VM, code like https://github.com/rancher/machine/blob/master/drivers/vmwarevsphere/vm.go#L109-L126 
* vsphere6.7 allowed this
* vsphere7 returns a duplicate key error `com.vmware.vim.vpxd.vmprov.duplicateDeviceKey`
Fix: You can change the key yourself with similar rand code e.g. add `netdev.GetVirtualDevice().Key = int32(rand.Uint32()) * -1` in the code above but ultimately if you don't know that vsphere7 will return the error it's very hard to track down and should probably be fixed in govmomi.
@dougm if there are more places this -1 thing is going to be an issue I have no problem adding this change in more places just let me know what to look for, obviously the only place we had issues today is with network cards.
Related Issue: …
=> Change EthernetCardTypes key return from -1 to rand neg int32

govc/dvs/portgroup/spec.go
Current govc implementation only creates vlan based port group
This pull requests
- Preserves the usage of the default vlan based port group creation/modification
- Add two flags -vlan-mode and -vlan-range, so users can create trunking port group with a list of ranges
- the default range is all -> 0 - 4094
=> support trunk mode port group

cns/client.go, cns/client_test.go, cns/methods/methods.go, cns/types/if.go, cns/types/types.go
This pull request is adding a go binding for new CNS API `Relocate`.
`Relocate` migrates the given volume to the specified target datastore and returns a `vim.Task` to track the progress and overall state of the migration operation.
API throws 
- `vim.fault.NotFound` in case the block volume is not found
- `vim.fault.InvalidArgument` in case of invalid input arguments
- `vim.fault.AlreadyExists` in case volume already exists in the target datastore
- `vim.fault.CnsFault` in case of any other failure scenario.
Testing
```
$ pwd
.../govmomi/cns
$ export CNS_VC_URL='https://Administrator@VSPHERE.LOCAL:Admin!23@10.92.206.216/sdk'
$ export CNS_DATACENTER='test-vpx-1602615587-4149-wcp.wcp-app-platform-sanity'
$ export CNS_DATASTORE='vSANDirect_10.92.218.55_mpx.vmhba0:C0:T6:L0'
$ export …
```
=> go binding for CNS RelocateVolume API

object/virtual_device_list.go
Update AssignController to return a negative random int32 instead of -1 per vsphere7 resrictions on adding devices with the same key resulting in an error.
Related Issues: https://github.com/rancher/rancher/issues/25404
Per this code: https://github.com/rancher/machine/blob/master/drivers/vmwarevsphere/create.go#L162-L181
We add a disk + cdrom, since CreateDisk and CreateCdrom both call AssignController the Key on both devices are -1. This will also fix CreateFloppy and CreateSerialPort
See also: https://github.com/vmware/govmomi/pull/2154
@dougm Same problem, different func
=> change negative one to rand neg int32

govc/namespace/cluster/disable.go, govc/namespace/cluster/enable.go, govc/namespace/cluster/enable_test.go, govc/storage/policy/info.go, govc/storage/policy/ls.go, govc/storage/policy/rm.go, govc/test/namespace.bats, vapi/namespace/internal/internal.go, vapi/namespace/namespace.go, vapi/namespace/simulator/simulator.go, vapi/rest/resource.go, vapi/rest/resource_test.go
Hi!
This covers some functionality I wanted to use for programmatically enabling Kubernetes in Vsphere. I saw some TODO comments around this so hopefully this PR is welcome.
This did turn out to be more involved than I initially expected, this covers:
- Structs corresponding to the enable spec from the API added to the VAPI package, along with EnableCluster and DisableCluster functions
- Corresponding cluster.namespace.enable and cluster.namespace.disable commands
- Also added ListCompatibleDistributedSwitches and ListCompatibleEdgeClusters to VAPI, which are needed to get the IDs for these objects in the format expected by the API
- Simple E2E test via govc/bats with the vcsim returning success on the relevant endpoint
- Ran the corresponding commands against my own Vsphere installation, …
=> govc (+ vapi): namespace.cluster.enable for enabling namespaces on a cluster

cns/client_test.go, cns/simulator/simulator.go, cns/simulator/simulator_test.go, cns/types/types.go
This change is to add Placement object in CNS CreateVolume response. Also modify the related unit test.
With this change, volumeCreateResult returns Placement object.
```
volumeCreateResult &{CnsVolumeOperationResult:{DynamicData:{} VolumeId:{DynamicData:{} Id:a9b3d651-39c4-4018-8aea-f58f7eda0e2e} Fault:<nil>} Name:pvc-901e87eb-c2bd-11e9-806f-005056a0c9a0 PlacementResults:[{Datastore:Datastore:datastore-36 PlacementFaults:[]}]}
```
Full Test Result:
```
lipingx-a01:cns lipingx$ go test -v
--- PASS: TestClient (12.32s)
client_test.go:133: Creating volume using the spec: types.CnsVolumeCreateSpec{
Name:       "pvc-901e87eb-c2bd-11e9-806f-005056a0c9a0",
Datastores: []types.ManagedObjectReference{
{Type:"Datastore", Value:"datastore-36"},
},
Metadata: …
```
=> Add Placement object in CNS CreateVolume response and related tests.

govc/vm/option/info.go, simulator/environment_browser.go
vcsim would panic if Spec is nil.
Change govc vm.option.info to set Spec only if needed,
providing coverage in the existing govc/test/vm.bats:vm.option.info test
=> vcsim: QueryConfigOptionEx Spec is optional

cns/simulator/simulator.go, cns/simulator/simulator_test.go
This change is to make CnsCreateVolume to return PlacementResult for static provisioning. Also add unit test for this case.
Test Result:
```
lipingx-a01:simulator lipingx$ go test -v .
=== RUN   TestSimulator
--- PASS: TestSimulator (0.06s)
simulator_test.go:120: volumeCreateResult &{CnsVolumeOperationResult:{DynamicData:{} VolumeId:{DynamicData:{} Id:fake-volume-Handle} Fault:<nil>} Name:test PlacementResults:[{Datastore:Datastore:/var/folders/q6/vmy5pmc12vd9bq12y9t3_1g400_y41/T/govcsim-DC0-LocalDS_0-382707820@folder-5 PlacementFaults:[]}]}
simulator_test.go:189: volumeCreateResult &{CnsVolumeOperationResult:{DynamicData:{} VolumeId:{DynamicData:{} Id:f598b2ed-dea2-49c2-b61e-195a3c36747f} Fault:<nil>} Name:test PlacementResults:[{Datastore:Datastore:/var/folders/q6/vmy5pmc12vd9bq12y9t3_1g …
```
=> Change CnsCreateVolume to return PlacementResult for static provisioning

govc/dvs/portgroup/add.go, govc/dvs/portgroup/spec.go
=> govc: add dvs.portgroup.{add,change} '-auto-expand' flag

govc/USAGE.md, govc/flags/datastore.go, govc/flags/folder.go, govc/flags/resource_pool.go, govc/vm/instantclone.go, object/virtual_machine.go
=> Added Instant Clone feature

vapi/simulator/simulator.go, vapi/tags/errors.go, vapi/tags/tag_association.go, vapi/tags/tag_association_test.go
This PR adds support for the missing multiple-tags-to-object (attach/detach) APIs which are important for efficiency and performance especially in large environments (many tags/objects) and environments with high churn (Kubernetes controllers, event-driven systems).
The following changes were made:
- Add attach-multiple-tags-to-object and detach-multiple-tags-from-object APIs
- Add BatchError(s) types
- Add minimum simulator APIs (see note below)
- Add/update comments to describe error behavior in detail
- Add black-box tests (against simulator)
Example output handled in a `main.go` with the `log` package where some tags could not be assigned to a valid reference:
```bash
2020/12/15 13:47:25 could not attach tags: [error: 0 type: cis.tagging.attach.invalidArgument.cardinality.error …
```
=> Add batch APIs for multiple tags to object

vsan/client.go, vsan/client_test.go
VsanHostConfigInfoEx is a property of HostVsanSystem in "vsan" namespace, which is an extension of vim25types.VsanHostConfigInfo.
Adding function to retrieve this property from given vsanSystem.
=> Add function to get vsan host config

simulator/container.go
Follow up to 1f3fb17 (#2189)
Provide option to use an image other than busybox via env VCSIM_BUSYBOX
=> vcsim: include stderr in log message when volume import fails

govc/dvs/portgroup/info.go, vim25/types/if.go
XML unmarshal would panic unless there is a IP traffic qualifier for traffic filtering.
This change reverts the interface changes that were made in #1210
Fixes #2196
=> Fix DvsNetworkRuleQualifier interface

gen/vim_wsdl.rb, govc/test/vcsim.bats, simulator/folder.go, simulator/model.go, sts/simulator/simulator.go, vim25/types/types.go
- The PowerCLI sts client double quotes the SOAP-Action header, resulting in:
sts: unsupported action="http://docs.oasis-open.org/ws-sx/ws-trust/200512/RST/Issue"
- NetworkSummary.IpPoolId needs to be empty if the network is not associated with an IP pool
- Set the required field DistributedVirtualPortgroup.Config.Type
=> vcsim: fixes for PowerCLI Get-VirtualNetwork

property/example_test.go
Mirror the error return used earlier in this example. `golint` noted the omission when I copied the example locally to examine return values:
```
ineffectual assignment to `err` (ineffassign)
```
=> ExampleCollector_Retrieve: Add missing err return

README.md
The [VMware Event Router](https://github.com/vmware-samples/vcenter-event-broker-appliance/tree/development/vmware-event-router) component within the [VMware Event Broker Appliance (VEBA) project](https://github.com/vmware-samples/vcenter-event-broker-appliance) utilizes govmomi.  
cc @embano1 
Signed-off-by: William Lam <wlam@vmware.com>
=> Updated projects to include VMware Event Broker Appliance

simulator/event_manager.go, simulator/event_manager_test.go, simulator/race_test.go
Fix Next/Previous methods:
The original implementation only applied to the LatestPage ring buffer.
Switch EventManager's history to use a linked list that goes beyond the
LatestPage size.
Fix SetCollectorPageSize: had caused duplicate events in LatestPage
Fixes #2134
=> vcsim: fix EventHistoryCollector fixes
