vmware/govmomi

govc/object/save.go, simulator/environment_browser.go
By default vcsim's QueryConfigOption has a very minimal response.
With this change, record/replay includes the entire structure.
Fixes #2228
=> vcsim: record/replay EnvironmentBrowser.QueryConfigOption

simulator/datastore.go
The vmfs path from a saved inventory may include a ':', e.g. 'vsan:52eb3a2d910-...'
Fixes #2231
=> vcsim: escape datastore name

govc/device/pci/add.go
As described in the issue https://github.com/vmware/govmomi/issues/2248,
`DeviceId` string attribute of `VirtualPCIPassthroughDeviceBackingInfo` object should contain the hexadecimal value of PCI device's DeviceID instead of decimal value.
Passing the decimal value does not lead to a govc execution error but prevents the targeted virtual machine boot as the real PCI device's DeviceID does not match the one stored in virtual machine VMX data.
This fix has been tested on 7.0u1 and 6.7.0u3 ESXi hosts and resolved the issue on both 2 hosts.
=> Fix govc device.pci.add: incorrect DeviceID value

cns/client_test.go, cns/types/types.go
This PR is updating the fields for ConfigureVolume ACLs API bindings in CNS types.
With this change we will be able to invoke ConfigureVolumeACL API using CNS client.
Updated the file volume test in cns/client_test.go and verified that the new fields/types work as expected and invoke the API correctly.
```
chethanv-a01:cns chethanv$ go test -v
./client_test.go:60:2: datastoreForMigration declared but not used
./client_test.go:65:2: resporcePoolPath declared but not used
FAIL    github.com/vmware/govmomi/cns [build failed]
chethanv-a01:cns chethanv$ go test -v
client_test.go:682: Creating CNS file volume using the spec: {DynamicData:{} Name:pvc-file-share-volume VolumeType:FILE Datastores:[Datastore:datastore-42] Metadata:{DynamicData:{} …
```
=> Update ConfigureVolumeACLs bindings in cns types

cns/client_test.go, cns/types/types.go
This PR is a minor change to update the volume ACL spec to add delete field. This is needed to revoke/remove permissions for a given volume.
```
$ go test -v
client_test.go:682: Creating CNS file volume using the spec: {DynamicData:{} Name:pvc-file-share-volume VolumeType:FILE Datastores:[Datastore:datastore-42] Metadata:{DynamicData:{} ContainerCluster:{DynamicData:{} ClusterType:KUBERNETES ClusterId:demo-cluster-id VSphereUser:Administrator@vsphere.local ClusterFlavor:VANILLA ClusterDistribution:OpenShift} EntityMetadata:[] ContainerClusterArray:[{DynamicData:{} ClusterType:KUBERNETES ClusterId:demo-cluster-id VSphereUser:Administrator@vsphere.local ClusterFlavor:VANILLA ClusterDistribution:OpenShift}]} BackingObjectDetails:0xc0003689c0 Profile:[] …
```
=> Update volume ACL spec to add delete field

.goreleaser.yml
hello，I am going to submit mips64le architecture，The main reasons for adding support for mips64le architecture are:
1、The mips64le architecture is also the mainstream cpu architecture (amd64, arm64), which is used by many users;
2、Golang supports cross compilation, and mips64le is officially supported.
3、This project is an underlying dependency library of the kubernetes project  [k/k](https://github.com/kubernetes/kubernetes), therefore I wish to submit this patch.
Therefore, I hope that the release package also supports the mips64le architecture, which is convenient for more users.
Signed-off-by: houfangdong houfangdong@loongson.com
=> Update .goreleaser.yml for support a new cpu architecture 

ovf/envelope.go, ovf/fixtures/ttylinux.ovf, ovf/ovf_test.go
ovf.Unmarshal() didn't have much test coverage other than the govc import.ova bats tests.
Update ovf/ovf_test.go to validate these fields are properly unmarshaled.
=> ovf: add Config and ExtraConfig to VirtualHardwareSection

cns/client.go
This PR adds a constant for vSAN 7.0U1 release. This version will be used by CSI, just like for older versions.
=> Add vSAN 7.0U1 release constant

govc/flags/client.go, session/keep_alive_test.go, vim25/examples_test.go, vim25/retry.go, vim25/retry_test.go, vim25/soap/client.go
To maintain backward compatibility introduced new optional
variable in retry struct and new function with parameter
retryAttempts.
- Add vim25.RetryTemporaryNetworkError to replace deprecated vim25.TemporaryNetworkError
- Export IsTemporaryNetworkError function
- Add test to retry network error
Fixes #2266
=> vim25: fix race in TemporaryNetworkError retry func

govc/vm/snapshot/tree.go, object/virtual_machine.go
Add support for snapshot size calculations
- govc: Add size (`s`) flag to `snapshot.tree` subcommand
- Add `object.SnapshotSize` and helper functions
to support calculating snapshot size from other
client code
Credit to @dougm for providing successive code examples,
explanation and guidance for understanding the required
steps to implement this support.
As noted on GH-2243, code provided by @dougm was (AFAIK)
based heavily on existing C# code for PowerCLI
implementation of the `Get-Snapshot` cmdlet.
- credit: @dougm
- fixes vmware/govmomi#2243
=> Add govc snapshot size command, standalone SnapshotSize function

govc/USAGE.md, govc/cluster/override/change.go
Since vSphere API 6.5 it is possible to set cluster HA restart priority also to `lowest` and `highest` (see [API ref](https://vdc-download.vmware.com/vmwb-repository/dcr-public/da47f910-60ac-438b-8b9b-6122f4d14524/16b7274a-bf8b-4b4c-a05e-746f2aa93c8c/doc/vim.cluster.DasVmSettings.RestartPriority.html)). 
This is only missing in the CLI help message and in the usage documentation, the command itself using `highest` or `lowest` is already working.
=> Update cluster.override.change help message

govc/cluster/override/change.go, govc/cluster/override/info.go, govc/cluster/override/remove.go, govc/test/cluster.bats, simulator/cluster_compute_resource.go
This PR implements a new feature in configuring VM HA overrides with govc by adding `-ha-additional-delay` that configures `vSphere HA Additional Delay`:
=> govc: implement vSphere HA additional delay and ready condition

govc/test/snapshot.bats, simulator/snapshot.go
=> vcsim: fix Task.Info.Entity in RevertToSnapshot_Task

vim25/soap/error.go
govc optionally allows JSON formatted output. In certain cases, e.g.
when a SOAP error is thrown, that causes the JSON output to be empty due
to unexported fields in the struct.
Closes: #2278
=> Marshal soapFaultError as JSON

govc/flags/host_system.go, govc/test/vm.bats
vm.migrate combines the use of VM SearchFlag (-vm.uuid, -vm.path, etc) with HostSystemFlag.
When a -vm.* flag is used, it causes the error:
expected HostSystem entity, got VirtualMachine
Add a check for the SearchFlag type to avoid this.
=> govc: fix vm.migrate search index flags

govc/metric/info.go, govc/metric/interval/info.go, govc/metric/ls.go, govc/metric/performance.go, govc/metric/sample.go, govc/test/metric.bats, performance/manager.go
- Add '-g' group flag to metric.info
- Support interval name in '-i' switch
- metric.interval.info: format Interval, add Available Samples
- Include per-instance-only metrics in metric.info and metric.ls (#704)
- Fix metric.sample '-n' flag
Fixes #704
=> govc: metric command enhancements and fixes

session/manager.go
Added an extra method to the Session Manager to expose the `UpdateServiceMessage` method.
It was already defined as part of the vim25 methods & types, just missing from the session manager wrapper.
Let me know if there is anything else I need to submit with this PR.
=> Added UpdateServiceMessage to Session Manager

vslm/client_test.go
The client_test validates register disk method in globalobjectmanager and invokes cnscreatevolume 
```
$ export VOLUME_PATH="https://10.186.43.166/folder/04c14d60-ce81-e7b1-0d7a-02009d67ced5/vm-12.vmdk?dcPath=datacenter&dsName=vsanDatastore"
chethanv-a01:vslm chethanv$ go test -v
client_test.go:75: Successfully registered disk with path https://10.186.43.166/folder/04c14d60-ce81-e7b1-0d7a-02009d67ced5/vm-12.vmdk?dcPath=datacenter&dsName=vsanDatastore as FCD with storage object id 99c12eef-b5c5-49cf-873a-d6e380e2bc7a
client_test.go:106: Creating volume using the spec: types.CnsVolumeCreateSpec{
Name:       "pvc-abc123",
Datastores: nil,
Metadata:   types.CnsVolumeMetadata{
ContainerCluster: types.CnsContainerCluster{
ClusterType: …
```
=> Add client_test for vslm package to validate register disk method

vslm/object_manager.go
As outlined in #2308, it looks like when #2067 was committed it only
supported calling `ExtendDisk` and `InflateDisk` on ESXi hosts and not
against vCenter.
This fixes the problem by adding the same logic used by other VSLM
methods to switch between vCenter and ESXi tasks.
=> Add support for calling vCenter for VLSM ExtendDisk and InflateDisk

vim25/progress/reader.go, vim25/soap/client.go
Fixing a bug that caused a progress reader to be created but never used in soap.client.WriteFile.
In addition, treating the situation in which a reader size is invalid and returning 0 as the progress in those cases. I suppose -1 might also work here.
=> Fixes in SOAP download progress

examples/events/main.go, examples/examples.go
Fixes err variable shadowed in example.go which caused the examples to
fail silently on some errors, e.g. TLS issues when not passing
`-insecure`.
Minor documentation improvements on the example and start stream from
-10min instead of -1h to reduce load on vCenter backend.
Closes: #2322 
=> Fix events example

.github/workflows/govmomi-go-build.yaml, .github/workflows/govmomi-go-lint.yaml, .github/workflows/govmomi-go-test.yaml, .github/workflows/govmomi-stale.yaml
First step towards migrating from Travis to Github Actions.
This PR adds four actions:
- Code style (linting and vetting)
- Tests with matrix (different Go versions)
- Build with matrix (different platforms and Go versions)
- Close stale issues (warn after 90d, close after another 30d of
inactivity)
Code style, tests and build are 1:1 copies of the Travis CI jobs (with
added matrix tests). 
**Note:** These actions will run on every push/PR against main/master. The Travis pipeline will be kept for some transition period thus users will see multiple checks in their PRs.
Credit to the Knative team as source of inspiration.
=> Use Github Actions

vsan/client.go
Add a well-known ManagedObjectReference constant to allow access
to the vSAN stretched cluster management system.
Signed-off-by: James Peach <jpeach@vmware.com>
=> Add the vSAN stretched cluster reference.

govc/device/boot.go, govc/test/device.bats
Avoid reverting from efi to bios when device.boot is used without specifiying the -firmware option
=> govc: remove device.boot -firmware default

README.md
Uses build and test action status badges (from default branch)
Closes #2331 
=> Use Github Actions Status Badges

cns/client.go, cns/client_test.go, cns/cns_util.go, govc/flags/client.go, govc/flags/debug.go, govc/namespace/cluster/enable.go, govc/session/login.go, govc/sso/client.go, govc/sso/service/ls.go, govc/storage/policy/create.go, govc/storage/policy/info.go, govc/storage/policy/ls.go, govc/storage/policy/rm.go, govc/test/cli.bats, govc/volume/ls.go, govc/volume/rm.go, lookup/client.go, pbm/client.go, ssoadmin/client.go, sts/client.go, vsan/client.go, vsan/client_test.go
Follow up to #2263 , the new '-verbose' flag depends on soap.RoundTripper chaining,
which was only supported by the vim25.Client.  This change enables chaining for all
other endpoint clients.
=> Add chainable RoundTripper support to endpoint clients

README.md
Adds badges and links to:
- latest release
- godoc
- go modules version used
New layout:
Closes #2334 
=> Add godoc and mod version badges

govc/cluster/stretch.go
Add a new command `cluster.stretch` that wraps the API to convert
a vSAN cluster into a stretched vSAN cluster.
Co-authored-by: Jamie Monserrate <monserratej@vmware.com>
=> Add a stretched cluster conversion command.

go.mod, go.sum, govc/object/tree.go, govc/test/object.bats, vendor/github.com/a8m/tree/.gitignore, vendor/github.com/a8m/tree/.travis.yml, vendor/github.com/a8m/tree/LICENSE, vendor/github.com/a8m/tree/README.md, vendor/github.com/a8m/tree/color.go, vendor/github.com/a8m/tree/compileall.sh, vendor/github.com/a8m/tree/csort_bsd.go, vendor/github.com/a8m/tree/csort_generic.go, vendor/github.com/a8m/tree/csort_unix.go, vendor/github.com/a8m/tree/modes_bsd.go, vendor/github.com/a8m/tree/modes_unix.go, vendor/github.com/a8m/tree/modes_unsupported.go, vendor/github.com/a8m/tree/node.go, vendor/github.com/a8m/tree/sort.go, vendor/github.com/a8m/tree/stat_unix.go, vendor/github.com/a8m/tree/stat_unsupported.go, vendor/modules.txt, view/container_view.go
This patch adds a "tree" command to govc that behaves like the Linux tree command. "govc tree PATH" prints a tree-like structure of the inventory.
This first-pass is incredibly slow and needs to be optimized. Here's some example output while listing the networks:
```shell
$ ./govc tree /SDDC-Datacenter/network
/SDDC-Datacenter/network
├── VMC Networks
│   ├── SI_LogicalSwitch_40584124-5a85-479b-a5ef-07806a2d1b73
│   ├── SI_LogicalSwitch_4e59f062-7af8-4cbc-ac1a-3a9a40511d16
│   ├── SI_LogicalSwitch_beb34a4f-50c5-4f39-b953-a9861a919747
│   ├── SI_LogicalSwitch_de819edf-141f-498c-bf9a-b706d63352b7
│   ├── VMOTION
│   ├── VSAN
│   ├── cgw-dhcp-ls
│   ├── cross-vpc-ls
│   ├── direct-connect-ls
│   ├── mgmt-app-network
│   ├── mgmt-ls
│   ├── mgw-dhcp-ls
│   ├── nsx-dlink0-vls
│   ├── o-vmk0-ls …
```
=> The tree command

govc/test/cluster.bats, simulator/simulator.go, vcsim/main.go, vsan/simulator/simulator.go
cns/simulator implements a subset of the vsan namespace.
Add vsan/simulator to implement other vsan related methods,
starting with the ConvertToStretchedCluster method.
Add cluster.stretch bats test.
Issue #2235
=> vcsim: add vsan simulator

.dockerignore, .goreleaser.yml, Dockerfile.govc, Dockerfile.vcsim
Fixes #2045
Allows vcsim to be built within the docker container rather than built externally and copied in.
=> Update vcsim Dockerfile

govc/flags/debug.go, govc/session/ls.go, govc/test/session.bats
A principal may not have permission to view all sessions, but it can always view its own.
- Add MissingSet + Faults to -verbose PropertyCollector output
=> govc: add session.ls -S flag

.github/workflows/govmomi-check-wip.yaml
Any PR title starting with `WIP` will fail this status check to prevent accidental merges.
Closes: #2341
=> Add action to block WIP PRs

simulator/property_collector.go
When WaitForUpdatesEx() finds an empty Version string, it collects the
current state and then installs the PC as a "RegisterObject" handler
with the registry. If the object is updated after collecting its state
but before the PC is installed as a handler, those updates will be
missed.
This ordering addresses the issue of missing updates, but it introduces
a separate potential issue: that an update would be delivered twice if
the update happens after installing the PC as a RegisterObject but
before the object state is collected. The update would appear in the
initial state, but also be collected by the update callbacks.
=> Fix race in simulator's PropertyCollector

simulator/virtual_machine.go
If something like finder is used to retrieve the list of VMs in a
folder, it is possible that the list may include VMs that are not yet
fully constructed.
In this case, property.Wait() might observe theoretically-impossible
values, like <nil> for a VM's powerState.
This can cause TestRace (race_test.go) to hang.
The solution is to wait until the VM is fully initialized before adding
it to the folder. Because some initialization code expects the VM to
have a real MO reference, we have to use Registry.reference(vm) to
assign the new VM a reference (this is normally called by the
add-to-folder code; so thankfully it is idempotent).
=> simulator: Wait until VM creation completes before adding to folder

.github/workflows/govmomi-build.yaml, .github/workflows/govmomi-check-wip.yaml, .github/workflows/govmomi-go-lint.yaml, .github/workflows/govmomi-go-tests.yaml, .github/workflows/govmomi-govc-tests.yaml, .github/workflows/govmomi-stale.yaml, .goreleaser.yml, Dockerfile.vcsim, Makefile, README.md, go.mod, govc/USAGE.md, govc/build.sh, govc/flags/client.go, govc/flags/version.go, govc/flags/version_test.go, govc/test/vcsim.bats, govc/version/command.go, program.mk, vcsim/README.md, vcsim/main.go, vendor/modules.txt
First PR towards fully automating the release process with `goreleaser`. Cutting a release is still done manually, but using the goreleaser configuration provided in this PR. Once we gain confidence in the associated Github Actions workflows we can finally switch towards full release automation. This PR also adds more tests and build verification.
⚠️ **BREAKING** Release artefacts created by the provided `goreleaser` configuration use a different naming template. In addition, the `386` `GOARCH` is dropped. This is to allow scripts to easily download and reference the correct binary per platform/arch (e.g. using `uname`). Example for `vcsim`:
```bash
vcsim_FreeBSD_armv6.tar.gz
vcsim_Windows_x86_64.zip
vcsim_Darwin_arm64.tar.gz
vcsim_Darwin_x86_64.tar.gz
vcsim_Linux_mips64le.tar.gz …
```
=> First step towards release automation

govc/test/object.bats, simulator/registry.go
cluster moid values have "domain" prefix in real VC, not "clustercomputeresource"
folder moid values have "group" prefix.
=> vcsim: add moid value mapping mappings

.github/workflows/govmomi-build.yaml, .github/workflows/govmomi-release.yaml, .goreleaser.yml
This PR marks the final changes towards fully utilizing Github Actions for CI in govmomi.
Changes:
On **any** push (commit) to this repo using a tag starting with "v", e.g. `v0.25.0` a release action will be triggered.
Binaries and Docker images for govc/vcsim will be created and uploaded to a new release on this repo (binaries) respectively Docker hub (container images). A CHANGELOG with the commits since the previous tag will be added to the release notes (can be modified afterwards). The same goreleaser configuration is used as during the build verification action to avoid inconsistencies and early catch regressions.
Note: the following error in the release check is due to this PR run not being able to read the secrets from the repo (which is by design to protect repos):
```
Run docker …
```
=> Add action to automate release

.github/workflows/govmomi-build.yaml, .github/workflows/verify-docker-login.yaml
Runs every night to verify Docker credentials and avoid surprises during release. Removed from build Action since PR runs don't have access to secrets (for good reason).
Closes: #2361
=> Add Cron Docker Login Action

.goreleaser.yml
In addition to binaries, only the following files will be included in the release tarballs:
- CHANGELOG.md
- LICENSE.txt
- README.md
Closes: #2370
=> Exclude go files in release tarball

toolbox/command.go, toolbox/command_test.go, toolbox/process/process.go, toolbox/process/process_test.go, toolbox/service_test.go
This allows vcsim to use the process manager without depending on the backdoor RPC package.
=> toolbox: move process management to its own package

cns/client.go, cns/client_test.go, cns/methods/methods.go, cns/types/types.go
This PR is adding go bindings for `QueryAsync` API which helps in retrieving volume information.
Invoking `QueryAsync` API in `cns/client_test.go`
```
client_test.go:133: Successfully queried Volume using queryAsync API. queryVolumeAsyncTaskResult: &types.CnsAsyncQueryResult{
CnsVolumeOperationResult: types.CnsVolumeOperationResult{},
QueryResult:              types.CnsQueryResult{
{
Id: "233bfd99-3a92-410c-962d-2351dba5f702",
},
DatastoreUrl:         "",
Name:                 "pvc-12d9a1f1-238a-42a6-83ee-9e47f406636c",
VolumeType:           "BLOCK",
StoragePolicyId:      "",
Metadata:             types.CnsVolumeMetadata{},
BackingObjectDetails: &types.CnsBlockBackingDetails{
CnsBackingObjectDetails: …
```
=> Add bindings for CnsQueryAsyncVolume API

cns/simulator/simulator.go, cns/simulator/simulator_test.go
This PR is adding queryAsync API in simulator. This is helpful for clients to simulate QueryAsync API mostly in their unit tests
```
simulator chethanv$ go test -v
=== RUN   TestSimulator
simulator_test.go:120: volumeCreateResult &{CnsVolumeOperationResult:{DynamicData:{} VolumeId:{DynamicData:{} Id:fake-volume-Handle} Fault:<nil>} Name:test PlacementResults:[{Datastore:Datastore:/var/folders/lp/5y1nj2ss6jg588yfj874lspw0000gq/T/govcsim-DC0-LocalDS_0-370437992@group-5 PlacementFaults:[]}]}
simulator_test.go:189: volumeCreateResult &{CnsVolumeOperationResult:{DynamicData:{} VolumeId:{DynamicData:{} Id:686c9835-c98d-43ce-abd0-f956b2fcbf93} Fault:<nil>} Name:test PlacementResults:[{Datastore:Datastore:/var/folders/lp/5y1nj2ss6jg588yfj874lspw0000gq/T/govcsim-DC0-LocalDS_0-370437992@group-5 …
```
=> Add queryAsyncVolume in simulator

cns/types/types.go
This PR is adding bindings for `CnsVolumeNotFoundFault` in cns types. This is useful to determine if Cns Delete Volume returned `notFound` fault.
=> Add NotFoundFault in cns types

govc/test/guest.bats, govc/test/test_helper.bash, govc/test/vcsim.bats, govc/test/vm.bats, simulator/container.go, simulator/guest_operations_manager.go, simulator/guest_operations_manager_test.go, simulator/virtual_machine.go, toolbox/hgfs/hgfs_freebsd.go, toolbox/process/process.go
The original plan was to run govmomi/toolbox inside the container.
Pros: toolbox uses Go's stdlib for process and file ops, no shelling out and parsing command output.
Cons: would require binary added to containers, manage the process lifecycle and transport (e.g. unix socket).
With this change, we instead use a hybrid of the toolbox.ProcessManager and docker exec.
Pros: negates the cons listed above.
Cons: shelling out to docker exec and having to parse output in some cases (e.g. ListFiles)
=> vcsim: add guest operations process support

govc/test/vcsim.bats, govc/test/vm.bats
This patch fixes an issue where some bats tests fail because the `uuidgen` command is not present. The `vcsim` binary includes `uuidgen` for this reason, and thus the two locations where `uuidgen` was used directly have been updated to call `vcsim uuidgen` instead.
=> Use "vcsim uuidgen" for bats tests

govc/test/README.md
This patch updates the README for the govc tests to indicate how users can run the tests like they would be run by GitHub Actions with the `act` command.
=> Update govc test docs with act

.github/workflows/issue-greeting.yaml
This change will send greetings only to users currently not associated with the repo, i.e. no previous commits, no members of the org, no owners, etc. which seems to be a better option for this behavior.
Closes: #2412
=> Only greet unassociated users

.chglog/config.yml, .github/comment-template.md, CONTRIBUTING.md
Will add this to CHANGELOG.md (and every release) highlighting all commits with `chore: ...` prefix.
Example:
<a name="v0.25.0-next"></a>
> Release Date: 2021-05-05
- add guest operations process support
- Add issue greeting
- Add WIP Action
- Remove dep files
- Clean up documentation
- Remove unused release script
- Automate CHANGELOG
- Add chore section to CHANGELOG [e39dfdc8]
- chore: Add issue greeting [cac1d8d7]
- chore: Add WIP Action [0f1c3f89]
- chore: Remove dep files [921ad37a]
- docs: Document linker and GOFLAGS for build vars [2719c229]
- Clarify SetRootCAs behavior [f3645a96]
- toolbox: add hgfs freebsd stub [c368e57f]
- vcsim: add guest operations process support [35a42af5]
- Set RoundTripper in ssoadmin.NewClient [64e55d81]
- chore: Clean up documentation [1d4ce94a]
- …
=> Add chore section to CHANGELOG

.github/workflows/govmomi-govc-tests.yaml, Makefile, govc/test/sso.bats
Isolate `govc` SSO-related tests as separate workflows, marked as experimental so they don't fail the run in case of cancellation.
Note: Only running the SSO-related tests with one go version (1.15) for now and timeout of 3m.
Kudos to @akutz for pinning the issue down to the SSO tests and making the relevant Makefile/tests changes.
Closes: #2425
=> fix: Isolate SSO govc tests

govc/main.go, govc/vcsa/proxy/proxy.go, vapi/appliance/networking/proxy.go
govc: Add support for getting the VC proxy and no-proxy configuration
Introduced the vAPI bindings and the implementation for those
govc output:
```
HTTP proxy:          Enabled
Server:    http://10.186.17.218
Port:      80
Username:  user
HTTPS proxy:         Disabled
FTP proxy:           Enabled
Server:  http://google.com
Port:    21
No Proxy addresses:  localhost, 127.0.0.1
```
=> govc: Add support for getting the VC proxy and no-proxy configuration

govc/README.md, vcsim/README.md
Github has a (non-obvious) way to link to the latest release files. I also added a note about the `tar` command requiring root permissions.
=> install bin doc: permalink to latest version

vcsim/README.md
I modified uasge of vcsim readme. 
Because it is old.
Closes: na
I download vcsim v0.25.0 & ran `vcsim -h` 
```
$ uname -a
Darwin volaaanja 19.6.0 Darwin Kernel Version 19.6.0: Mon Apr 12 20:57:45 PDT 2021; root:xnu-6153.141.28.1~1/RELEASE_X86_64 x86_64
$ ~/local/go/bin/vcsim version
Build Version: 0.25.0
Build Commit: bb0307eb
Build Date: 2021-04-16T16:00:59Z
```
=> vcsim: Modify Usage of README

eam/simulator/agent.go, eam/simulator/simulator.go, eam/simulator/simulator_test.go, simulator/registry.go, simulator/simulator.go
This patch adds support for pre-auth handlers in vC Sim. This enables SDKs registered with vC Sim to return their own errors if a session does not exist.
This patch includes a validation of this behavior by asserting the EAM simulator should return `EamInvalidLogin` when a session is not present instead of `vim.NotAuthenticated`.
Closes: _NA_
```shell
$ go test -v -run TestNotAuthenticated -count 1 ./eam/simulator
=== RUN   TestNotAuthenticated
=== RUN   TestNotAuthenticated/TerminateSession
=== RUN   TestNotAuthenticated/ValidateFaults
=== RUN   TestNotAuthenticated/ValidateFaults/vim.NotAuthenticated
=== PAUSE TestNotAuthenticated/ValidateFaults/vim.NotAuthenticated
=== RUN …
```
=> Support pre-auth handlers in vC Sim

cns/client.go, cns/client_test.go, cns/methods/methods.go, cns/types/if.go, cns/types/types.go
Add CNS Snapshot APIs binding in govmomi. It works with vSphere 7.0 and above. 
- [ x ] New feature (non-breaking change which adds functionality)
Testing Done:
- Run the integration test with latest vSphere version
- Run the integration test with previous vSphere version (>= 7.0)
Before running the integration test, please make sure the following …
=> Add CNS Snapshot APIs in govmomi/cns

eam/types/enum.go, eam/types/types.go, gen/gen.sh, pbm/methods/methods.go, pbm/types/enum.go, pbm/types/if.go, pbm/types/types.go, sms/methods/methods.go, sms/types/enum.go, sms/types/if.go, sms/types/types.go, vim25/methods/methods.go, vim25/mo/mo.go, vim25/types/enum.go, vim25/types/if.go, vim25/types/types.go, vslm/methods/methods.go, vslm/types/enum.go, vslm/types/if.go, vslm/types/types.go
This patch updates the file `gen/gen.sh` to use vCenter 7.0U2 HotPatch 4 (build `17986435`) as the source for generating types and client bindings for the following packages:
* `eam`
* `pbm`
* `sms`
* `vlsm`
* `vim25`
Please note that all of the packages sans `eam` have also had their copyright headers updated to reflect `2014-2021`.
Closes: _NA_
The following commands were executed locally:
* `make lint`
* `make install`
* `make test`
None of the above checks produced any errors.
this project
=> Update generated types to vCenter 7.0U2 HP4 (build 17986435)

.github/workflows/govmomi-go-tests.yaml, Makefile
This patch updates the GitHub Test Action to use the Makefile for running the tests. New options are included in the Makefile to make it easy to parameterize certain values, such as:
* test count
* test timeout
* race history size
The Makefile has also been updated so that certain options that are parameterized independently, ex. TEST_COUNT, will force an error if a person tries to specify them in the raw via TEST_OPTS. For example:
```shell
$ TEST_OPTS=-race make test
Makefile:126: *** The -race flag is enabled by default & cannot be specified in TEST_OPTS.  Stop.
$ TEST_OPTS="-count 1" make test
Makefile:122: *** Use TEST_COUNT to override this option.  Stop.
$ TEST_OPTS="-timeout 5m" make test
Makefile:130: *** Use TEST_TIMEOUT to override this option.  Stop.
```
Closes: _NA_
Please …
=> Update GitHub Test Action to use Makefile

.chglog/CHANGELOG.tpl.md, CHANGELOG.md
Commit SHAs were missing in the highlight sections. Also, commit SHAs are now left-aligned and tab-separated for a cleaner appearance.
Closes: #2460
<a name="v0.26.0"></a>
> Release Date: 2021-05-24
- [0e7012d0]	Add support for getting the VC proxy and no-proxy configuration ([#2435](https://github.com/vmware/govmomi/issues/2435))
- [6afb8ff9]	Change 'Maintenance Mode' printing in host.info
- [d31941c8]	Modify Usage of README. (based on v0.25.0)
- [4fea687c]	include all namespaces in /about info
- [bd3467d4]	avoid edit device panic when DeviceInfo is nil
- [35a42af5]	add guest operations process support
- [a796d3fc]	Add make help target
- [8bc8fd28]	Add issue and PR templates
- [60e33916]	Document commit prefixes
- [cac1d8d7]	Add issue …
=> chore: Add and reorder commits in CHANGELOG

govc/vm/guest/guest.go, govc/vm/guest/run.go
- Add '-w' flag to guest.run
Closes: #2446
=> govc: fix default guest.run path for unsupported Windows guests

govc/vm/guest/download.go, govc/vm/guest/guest.go, govc/vm/guest/run.go, govc/vm/guest/upload.go, guest/toolbox/client.go, guest/toolbox/example_test.go, simulator/model.go
Add simulator.RunContainer method, simplifies Go tests that depend on container backed simulated VMs.
Move some initialization from govc to a `toolbox.NewClient` method that can be reused.
Closes: #2458
this project
=> examples: add toolbox Client.Run

simulator/virtual_machine.go
This change checks the device type and sets ChangeTrackingSupported property for the simulated VM accordingly.  
Before enabling change tracking for VM, we validates if change tracking is supported or not by checking the Capability.ChangeTrackingSupported property. While writing unit test we are using vcsim for getting simulated VM but we cant test our functionality after checking ChangeTrackingSupported, since it is always nil.
Ran virtual_machine_test.go (package simulator) to see if this property is populated or not.
=> vcsim: Sets "ChangeTrackingSupported" property of the simulated VM

.chglog/RELEASE.tpl.md, .chglog/config.yml, .github/workflows/govmomi-build.yaml, .github/workflows/govmomi-release.yaml, .github/workflows/verify-docker-login.yaml, CHANGELOG.md, CONTRIBUTING.md, RELEASE.md
This PR updates the CHANGELOG and release notes generation process and layout:
- Use different templates for release notes (shown in Github Release) and `CHANGELOG.md`
- Release notes will now include issue references in commit lines (when available, detected with `Closes` or `Fixes` pattern matching) 
- `CHANGELOG.md` will **not** include issue references in output
- Include additional highlights for documentation, examples, and bug fixes
- Update CONTRIBUTING guide to explain how to use these prefixes
- Add BREAKING changes section to release notes/CHANGELOG, detected when using `BREAKING:` in commit message body
- Build, Docker login and release workflow can now be triggered manually (dispach)
- Updated CHANGELOG.md with changes
- CHANGELOG.md as part of a release does not have to be …
=> chore: Update CHANGELOG implementation

performance/manager.go, simulator/performance_manager.go, simulator/performance_manager_test.go
- Add performance.Manager.QueryCounter method
Fixes #2440
New test added to cover the `QueryPerfCounter` method.
this project
=> vcsim: fix panic in QueryPerfCounter method

simulator/vstorage_object_manager.go
Add support to vcsim for ExtendDisk_Task in VSLM. This allows you to
change the capcity of a FCD when using vcsim without the simulator
throwing an error.
Fixes part of #2480
1. Start vcsim
2. Create a first class disk with govc (`govc disk.create -size 24G test-disk`)
3. Make note of the UUID and write code similar to the following:
```go
task, err := manager.ExtendDisk(ctx, ds, 40*1024)
if err != nil {
log.Fatal(err)
}
err = task.Wait(ctx)
if err != nil {
log.Fatal(err)
}
dsk, err := manager.Retrieve(ctx, ds, diskUUID) …
```
=> vcsim: Implement VSLM ExtendDisk_Task

.chglog/CHANGELOG.tpl.md, .chglog/RELEASE.tpl.md
The `BREAKING` section in the corresponding CHANGELOG/release notes lacked details on the actual commit introducing a breaking change. See below for an example how this PR addresses this.
<a name="v0.26.1"></a>
> Release Date: 2021-06-07
- [0736a32a]    Include commit details in BREAKING section (#2482)
Add a context to funcXYZ [3ba9cc21]:
`funcXYZ()` now requires passing a `context.Context`
- [3ba9cc21]    feat: Add a context to funcXYZ
- [0736a32a]    chore: Include commit details in BREAKING section (#2482)
Closes: #2482
Run `git-chglog` to create the example output above.
this project
=> Include commit details in BREAKING section

eam/simulator/simulator_test.go
This is a bit of an exotic issue.
The current implementation of eam simulator test assumes the specific behavior of the standard go test runner: that both the `simulator` and `simulator_test` packages are linked into a single binary. This way, the test module can implicitly rely on the fact that the simulator module's `init()` function has run, registering the SDK endpoint that the test uses.
In a different, non-standard, test runner model where potentially 2 binaries are used instead, that assumption breaks, leading to a test failure. (requests on /eam/sdk then get a 404)
This change makes it explicit that there's a dependency to that `init()` function, but doesn't have any functional impact on the tests as run in `go test` …
=> explicitly import eam/simulator in test

govc/object/collect.go
Add help text for type flag aliases for `object.collect` subcommand to mirror help text provided for the `find` subcommand (as suggested by @dougm).
Closes: #2491
Relying on CI
this project
=> govc: Add object.collect type flag alias help

cns/client.go, cns/client_test.go, cns/cns_util.go, cns/methods/methods.go, cns/simulator/simulator.go, cns/simulator/simulator_test.go, cns/types/types.go
**Summary**: Added CNS QuerySnapshots binding, simulator testcases and client testcases and added the simulator test cases for CreateSnapshots and DeleteSnapshots APIs as well.
- [ x ] New feature (non-breaking change which adds functionality)
Testing Done:
- Unit test using govmomi simulator
```
=== RUN   TestSimulator
TestSimulator: …
```
=> Added CNS QuerySnapshots binding, simulator testcases and client testcases

simulator/virtual_machine.go
Just set the Dest Host properly in the clone task
Closes: #2495
- [ X] Bug fix (non-breaking change which fixes an issue)
- [X ] Test with packer (after a bug fix in it)
this project
=> Rightly take the host parameter into account while cloning a VM on a cluster

govc/cluster/change.go
Closes: #2506
The govc's `cluster.change` command allows enabling DRS on a cluster and also setting the automation level. However, it doesn't allow changing the vmotionRate on the DRS Config.
I'm automating some stuff where I want to dynamically change the vmotionRate and this change allows me to add it to my automation.
Closes: #2506 
I have a vCenter on which I tested the CLI and verified from the MOB the value did reflect. I also tested some negative cases giving the value > 5 and < 1. And the command obviously fails.
I also tested the command locally to ensure the help message does print out info about how to use the new option:
```
~/c/l/s/g/a/govmomi (issue-2506) go run govc/main.go cluster.change -h
Usage: …
```
=> [feature] govc: Allow cluster.change to set ClusterDrsConfigInfo.vmotionRate

govc/test/vm.bats, simulator/virtual_machine.go
The object.VirtualMachine.WaitForNetIP method depends on both the Virtual NIC's MacAddress and
the MacAddress reported by vmware-tools (guest.net[].macaddress property).
With this we can enable WaitForNetIP testing (govc vm.ip) against vcsim.
Related: #2510
`vm.ip` bats test enabled against vcsim
this project
=> vcsim: propagate CustomizeVM MacAddress to Virtual NIC

govc/test/vm.bats, object/virtual_machine.go
Fixes WaitForNetIP when the vm contains a manual mac address which may contain uppercase characters.
Closes: #2509 
this project
=> make processing of mac addresses case insensitive

govc/test/object.bats, simulator/registry.go
Real vCenter uses a `domain-c` prefix, rather than just `domain-`
Adjusted test in object.bats
this project
=> vcsim: use 'domain-c' prefix for cluster moids

simulator/registry.go, simulator/task.go
The use of an interface method (mo.Reference) to get an object's lock can cause a read race.
The race detector doesn't follow what happens in the interface impl (most impls just return the `Self` field).
Prefer the mo 'Self' field via reflection to avoid this race.
Existing tests pass, in particular simulator/race_test.go after removing the special case for use of `*ListView.Self` in the `Registry.locker()` method.
this project
=> vcsim: avoid race when fetching object Locker

govc/test/vm.bats, simulator/virtual_machine.go
If a VM's host is InMaintenanceMode, certain tasks should return InvalidState,
such as CustomizeVM and PowerOnVM.
`vm.customize` test puts the vm host in MM and attempts to customize the vm, expecting failure (InvalidState)
this project
=> vcsim: check if VM host InMaintenanceMode

govc/main.go, govc/test/vsan.bats, govc/vsan/change.go, govc/vsan/info.go, vsan/client.go, vsan/simulator/simulator.go
- vsan.change command adds the ability to set VsanUnmapConfig
- vsan.info command adds the ability to inspect vSAN cluster config
- vcsim: add support for VsanClusterGetConfig and VsanClusterReconfig methods
Fixes #1965
Co-authored-by: Tanay Kothari <tkothari@vmware.com>
Co-authored-by: Doug MacEachern <dougm@vmware.com>
=> govc: add vsan info and change commands

cns/client.go, cns/client_test.go, cns/simulator/simulator_test.go
This PR is updating the CnsQueryAsync API request parameters to handle empty values for QuerySelection. Without this change the API will return "VolumeId" field only when empty QuerySelection is passed. Instead, the API is expected to return entire Volume{} struct with all the fields(not just volumeId) when empty QuerySelection is passed. The fix is essentially changing the API request to consume pointer to QuerySelection which can be set to nil when clients choose to pass empty QuerySelection in order to fetch all fields from QueryAsync API.
Ran the existing unit test:
**Before:**
```
client_test.go:881: Successfully queried Volume using queryAsync API. queryVolumeAsyncTaskResult: &types.CnsAsyncQueryResult{ …
```
=> Update CnsQueryAsync API request parameters to handle empty values for QuerySelection

object/virtual_device_list.go, object/virtual_device_list_test.go
Fix `VirtualDeviceList#CreateEthernetCard()` to always generate negative device keys so that they will not collide with existing keys.
Closes: #2536
- ensure all device have negative device keys in CreateEthernetCard unittest
* Toolchain:
* SDK:
this project
=> fix: generate negative device key

guest/file_manager.go, guest/file_manager_test.go, internal/helpers.go, internal/helpers_test.go, object/host_system.go
InitiateFileTransfer{To,From}Guest methods return an ESX host's inventory name (HostSystem.Name).
This name was used to add the host to vCenter and cannot be changed
(unless the host is removed from inventory and added back with another name).
The name used when adding to VC may not resolvable by this client's DNS, so we prefer an ESX management IP.
However, if there is more than one management vNIC, we don't know which IP(s) the client has a route to.
Leave the hostname as-is in that case or if the env var has disabled the preference.
Added new tests to file_manager_test.go
this project
=> fix: avoid use of vNIC IP in guest.TransferURL if there are multiple

govc/USAGE.md, govc/test/vm.bats, govc/vm/change.go
The `vm.change` command allows setting extra values via `-e`, however, they have to be inline and are, hence, subject to the `getconf ARG_MAX` value of the local shell. To allow larger contents, e.g. for Fedora CoreOS Ignition configs, providing a file path and processing it internally is required.
Closes: #2488
I added some bats tests in `govc/test/vm.bats` similar to the existing extraConfig tests. Don't have a (local) ESX instance I can use to run the tests, though 🤷‍♂️ . Also I am not sure whether I can simply turn on the the GitHub Actions and have them run the tests for me. Would it be possible for you guys to add a pull request workflow that does run all tests?
this project
=> govc: Add feature to read file contents for ExtraConfig

program.mk
Closes: #2608
Recent go versions throw go install: -i flag is deprecated
this project
=> chore: Remove -i parameter in go install

vapi/internal/internal.go, vapi/rest/client.go, vapi/rest/client_test.go, vapi/simulator/simulator.go
This patch adds support for setting custom HTTP headers when using the VAPI REST client. This is useful for setting header tokens in order to make specific calls idempotent, like the one for deploying a VM from an OVF in content library.
Closes: NA
this project
=> Set custom HTTP headers for VAPI calls

event/example_test.go, event/manager.go, task/manager.go, task/wait_test.go
Prior to #2535 both managers implemented mo.Reference via the embedded 'object.Common' field,
but that field was removed.
this project
=> Implement mo.Reference interface in task+event managers

find/finder.go, govc/test/network.bats, property/filter.go, simulator/dvs.go, simulator/entity.go, simulator/model.go, simulator/portgroup.go, view/container_view.go
With standard vSphere networking, Portgroups cannot have the same name within the same network folder.
With NSX, Portgroups can have the same name, even within the same Switch. In this case, using an inventory path
results in a MultipleFoundError. A MOID, switch UUID or segment ID can be used instead, as both are unique.
- Add ContainerView.FindAny method
- Add nsx backing and SegmentId defaults to the simulator for testing
- Add simulator support for renaming a Portgroup, only allowing nsx to have duplicate names
Note that applications using `Finder.Network` do not require any code changes to use this functionality. Only the go module dependency needs to be bumped to include this change.
- Added TestFindNetwork that uses …
=> Support finding Portgroups by ID in Finder.Network

object/tenant_manager.go, simulator/model.go, simulator/registry.go, simulator/tenant_manager.go, simulator/tenant_manager_test.go, simulator/vpx/service_content.go
Add simple implementation of TenantManager in simulator to support
calls for marking, unmarking, retrieving service provider entities.
Adding support for TenantManager API (mark/unmark/retrieve "service provider" object)
in vcsim would help develop components that make use of TenantManager API functionality.
Closes: issue-2587
- Added a new unit test that tests various API inputs for the TenantManager mark/unmark/retrieve APIs.
- Added a new unit test to verify old vim client won't see TenantManager moref entry in ServiceContent but new vim clients would see it.
```
$ go test -v -run "TestTenantManager*" -failfast -v github.com/vmware/govmomi/simulator
=== RUN   TestTenantManagerForOldClients
--- PASS: …
```
=> vcsim: Add TenantManager support in simulator

eam/simulator/agent.go, simulator/cluster_compute_resource.go, simulator/custom_fields_manager.go, simulator/customization_spec_manager.go, simulator/datacenter.go, simulator/datastore.go, simulator/dvs.go, simulator/entity.go, simulator/folder.go, simulator/host_datastore_system.go, simulator/host_network_system.go, simulator/host_system.go, simulator/model.go, simulator/performance_manager.go, simulator/performance_manager_test.go, simulator/portgroup.go, simulator/portgroup_test.go, simulator/property_collector.go, simulator/registry.go, simulator/resource_pool.go, simulator/service_instance.go, simulator/session_manager.go, simulator/snapshot.go, simulator/task.go, simulator/view_manager.go, simulator/virtual_disk_manager.go, simulator/virtual_machine.go, simulator/vstorage_object_manager.go
The goal of this PR is to start changing references to the global simulator.Map to hopefully reduce the occurrence of data race conditions as seen in #2570.
This work is being split into multiple PRs, starting with this one that just adds more usage of the `context.Map` where available. See discussion [here](https://github.com/vmware/govmomi/pull/2571#issuecomment-944784134) for further context.
The biggest change required here was having to use a `SpoofContext()` for the `simulator/eam` calls that directly schedule VM related tasks.
References: #2570 
This was tested against the existing test cases. There are some unrelated existing failures such as #2651 that are present in `master`.
this project
=> Issue 2570 Patch 1: Use more `ctx.Map` references instead of the global simulator.Map

simulator/datacenter.go, simulator/event_manager.go
This PR introduces independent `simulator.Context` for the multiple tasks spawned by `PowerOnMultiVM`.
Closes: #2650
this project
=> Fixes data race in simulator.EventManager.PostEvent

.github/workflows/govmomi-build.yaml, .github/workflows/govmomi-release.yaml, CHANGELOG.md
The CHANGELOG.md is now sorted in semver order, i.e. v0.24.2 will be
sorted before v0.25.0 and not before v0.27.1 as before. This fixes
cherry-picks and is more intuitive for the reader. Also, only
semver-compliant tags are included. This is to work around a bug in
git-chlog and also drop any non-semver compliant tags from the log
Closes: #2638 #2655
this project
=> fix: CHANGELOG sorting and generation

simulator/virtual_machine_test.go
Modify the simulator VM VApp tests to deep compare expected and actual
errors.
this project
=> Fix: Deep compare errors in simulator VM tests

object/host_system.go, object/host_system_test.go
If the HostSystem.Config or HostSystem.Config.VirtualNicManagerInfo fields are nil, the ManagementIPs method would panic.
I was not able to reproduce this situation in a real VC, even with disconnecting a host from VC.
Assuming this state is possible while an ESX host is being upgraded. Updated the test to nil both fields to ensure we don't panic.
this project
=> fix: avoid possible panic in HostSystem.ManagementIPs

govc/vcsa/proxy/proxy.go
Closes: #2664
fix: govc vcsa.net.proxy.info doesnt give output in json format
Closes: #2664
Exposes components in `proxyResult` so that json encoder can output the information.
- Bug fix (non-breaking change which fixes an issue)
Ran the unit tests in the package
```
zhusa@zhusa-a02 govmomi % go test
PASS
ok      github.com/vmware/govmomi       0.279s
zhusa@zhusa-a02 govmomi % cd govc
zhusa@zhusa-a02 govc % go test
PASS
ok      github.com/vmware/govmomi/govc  0.280s
```
Run govc vcsa.net.proxy.info to confirm the change works
```
zhusa@zhusa-a02 govc % ./govc vcsa.net.proxy.info --json=true -u administrator@vsphere.local@10.161.166.146
{
"Proxy": {
"ftp": {
"port": -1
},
"http": {
"server": "http://proxy.vmware.com",
"port": …
```
=> fix: govc vcsa.net.proxy.info doesnt give output in json format

simulator/finder_test.go, simulator/model.go, simulator/model_test.go, simulator/search_index_test.go
This fix aligns the behavior of vcsim with the documentation for the
`pool` and `machine` model flags.
When no child pools are created, i.e. `pool` is not specified, VMs will
be deployed in the root resource pool of a cluster, i.e. `RP0`. The VMs
will also be prefixed with the corresponding resource pool. In order to
not break standalone host behavior, VMs deployed on a standalone host
will not carry a resource pool identifier in their name. See the linked
issue for deployment examples and naming.
The total number of VMs deployed in a VPX model is the result of the
number of datacenters, clusters and resource pools.
BREAKING:
The name of virtual machines deployed in `vcsim` in a cluster (and
optionally child resource pools) has changed to include the
corresponding resource pool name. VM …
=> fix: Distribute vcsim VMs across resource pools

govc/test/vm.bats, govc/vm/destroy.go
With PR #2532 , vm.destroy was returning after the 1st VM was destroyed.
this project
=> fix: govc vm.destroy only destroys the 1st argument

vim25/types/fault.go
Adds `types.IsAlreadyExists` helper to easily identify whether an error was thrown due to an object already existing.
Closes: #2675
this project
=> Add `IsAlreadyExists` error helper

go.mod
This PR upgrades the `go` directive in `go.mod` file by running `go mod tidy -go=1.17` to enable [module graph pruning](https://golang.org/ref/mod#graph-pruning) and [lazy module loading](https://golang.org/ref/mod#lazy-loading) supported by Go 1.17 or higher.
**Note 1:** This does not prevent users with earlier Go versions from successfully building packages from this module.
**Note 2:** The additional `require` directive is used to record indirect dependencies by Go 1.17 or higher, see https://go.dev/ref/mod#go-mod-file-go.
Manually tested by running `make test`.
this project
=> build: upgrade go directive in go.mod to 1.17

govc/flags/datacenter.go, govc/test/fields.bats
When using the object name instead of absolute/relative paths, e.g. in `govc field.set`, the finder could return duplicate objects. This change errors out if the specified (object) path is not absolute/relative.
Closes: 2561
this project
=> govc: Require full or absolute paths

govc/test/vcsim.bats, simulator/cluster_compute_resource.go, simulator/host_system.go
The simulator.ClusterComputeResource.AddHost method uses the compiled in esx.HostSystem template by default,
as does simulator.AddStandaloneHost.
With this change, if the HostConnectSpec.UserName is that of a HostSystem.Name in the given Cluster or
of a standalone host, use that HostSystem as the template.
this project
=> vcsim: add support for cloning HostSystems

govc/USAGE.md, govc/main.go, govc/namespace/service/activate.go, govc/namespace/service/create.go, govc/namespace/service/deactivate.go, govc/namespace/service/info.go, govc/namespace/service/ls.go, govc/namespace/service/rm.go, govc/test/namespace.bats, vapi/namespace/internal/internal.go, vapi/namespace/simulator/simulator.go, vapi/namespace/supervisorsvc.go, vapi/simulator/simulator.go
Signed-off-by: Ricardo Katz <rkatz@vmware.com>
Initial work on supporting vSphere Namespaces supervisor services.
Right now it's possible to:
* List
* Enable
* Disable
* Remove
* Create
TODO: Write VCSIM things
Tested with a real cluster. Still will check to write some unit tests
this project
=> govc: add support for supervisor services deploy

govc/USAGE.md, govc/export/ovf.go, object/virtual_machine.go
Added ExportSnapshot to object.VirtualMachine. Added a -snapshot flag to the govc export.ovf command. This allows users to export a running VM from a stable snapshot. Useful for backups etc.
this project
- [N/A] I have added tests that prove my fix is effective or that my feature works (simulator doesn't support this)
=> Added vm::ExportSnapshot and snapshot flag to export.ovf

simulator/session_manager.go
Spotted while looking at something else.
=> Fix typo in (simulator.Context).WithLock() comment

go.mod, sts/signer.go, sts/signer_test.go
Closes: #2696
Hostname that's an IPv6 address is expected to be surrounded by square brackets (like in URL), however govmomi uses url.Hostname() which strips those square brackets: https://github.com/vmware/govmomi/blob/master/sts/signer.go#L281
https://pkg.go.dev/net/url#URL.Hostname says:
Hostname returns u.Host, stripping any valid port number if present.
If the result is enclosed in square brackets, as literal IPv6 addresses are, the square brackets are removed from the result.
This may lead to authentication failure for services that use govmomi. This change added the check for IPv6 host and add the brackets.
Previously, vCenter deployed with pure IPv6 failed to authenticate dcli request; after this change, the dcli request …
=> fix: Add IPv6 support for signing HTTP request

govc/test/vm.bats, simulator/virtual_machine.go
Closes #2706
The vcsim CloneVM_Task method was sharing the config.hardware.device property
between the source and target VMs. The target VM now has a copy of the device
list so changes to it won't change the source VM's device list.
this project
=> vcsim: copy device list when cloning a VM

simulator/custom_fields_manager.go, simulator/object_test.go
The govmomi simulator currently has unexpected behavior when trying to update the custom fields of a VM. Instead of replacing the old value with the new one, it creates a duplicate key with the new value. More details in https://github.com/vmware/govmomi/issues/2687
Closes: https://github.com/vmware/govmomi/issues/2687
I suggest ignoring whitespace when reviewing.
Updated relevant unit test to account for updating custom values.
this project
=> vcsim: Allow updating custom fields

govc/USAGE.md, govc/vm/change.go
This PR adds support for scheduling a hardware upgrade for a VM.
Closes: #2647
I tested this on vcenter 6.7. Listed below are the results from upgrading vmx-13 to latest (vmx-15).
Query current version:
```
./govc vm.info -u <vcenter> -dc <datacenter> -json <vm> | jq '.[]? | .[]? | .Config.Version'
"vmx-13"
```
Query current policy:
```
./govc vm.info -u <vcenter> -dc <dc> -json <vm> | jq '.[]? | .[]? | .Config.ScheduledHardwareUpgradeInfo'
{
"UpgradePolicy": "never",
"VersionKey": "",
"ScheduledHardwareUpgradeStatus": "none",
"Fault": null
}
```
Schedule upgrade:
```
./govc vm.change -u <vcenter> -dc <dc> -vm <vm> -scheduled-hw-upgrade-policy=always
```
Verify scheduled upgrade:
```
./govc vm.info -u <vcenter> -dc <dc> -json …
```
=> govc: Add support for VM hardware upgrade scheduling

govc/USAGE.md, govc/main.go, govc/test/vcsa_shutdown.bats, govc/vcsa/shutdown/cancel.go, govc/vcsa/shutdown/get.go, govc/vcsa/shutdown/poweroff.go, govc/vcsa/shutdown/reboot.go, vapi/appliance/shutdown/shutdown.go, vapi/simulator/simulator.go
Closes: #2672
This PR adds Appliance shutdown API's mentioned https://developer.vmware.com/apis/vsphere-automation/latest/appliance/appliance/shutdown/
Closes: #2672 
- Tested Manually on live vCenter Server
- Added the govc-test
this project
=> Add Appliance shutdown API

govc/session/login.go, sts/client.go, sts/client_test.go, sts/signer.go
govmomi had support for public key auth to issue a HoK token, this change adds support for using a HoK token to issue a HoK token.
Added sts/client_test.go:TestIssueTokenByToken, which runs against a real vCenter/STS
this project
=> sts: support issuing HoK token using HoK token

govc/importx/spec.go, govc/test/import.bats
PR #1885 added support for remote ovf files, but not ova.
Closes: #1836
this project
=> fix: support govc import.spec for remote ova

simulator/dvs.go, simulator/dvs_test.go, simulator/folder.go, simulator/model.go
Fix vcsim `FetchDVPorts` to set `portgroupKey` field to the portgroup moid and `port` field to the port number respectively
Closes: #2726
```bash
$ vcsim &
$ export GOVC_URL=https://user:pass@127.0.0.1:8989/sdk GOVC_INSECURE=true
$ govc dvs.portgroup.info DVS0
PortgroupKey: dvportgroup-11
DvsUuid:      fea97929-4b2d-5972-b146-930c6d0b4014
VlanId:       0
PortKey:      0
PortgroupKey: dvportgroup-13
DvsUuid:      fea97929-4b2d-5972-b146-930c6d0b4014
VlanId:       0
PortKey:      0
```
this project
=> vcsim: Fix keys in DistributedVirtualPorts

vapi/namespace/simulator/simulator.go, vapi/simulator/simulator.go
In PR #2668 we refactored the 'StatusOK' method into a 'Status' method, which we don't need without a response body,
as w.WriteHeader can be used directly instead.
=> vcsim: revert vapi.Status() method

CONTRIBUTING.md
Ask contributors to not use `force` pushes during review.
Closes: #2736
n/a
this project
=> Clarify squash in CONTRIBUTING

govc/USAGE.md, govc/main.go, govc/sso/idp/ls.go, govc/test/sso.bats, ssoadmin/client.go, ssoadmin/methods/methods.go, ssoadmin/simulator/simulator.go, ssoadmin/types/types.go, vcsim/main.go
ssoadmin: add IdentitySources API bindings
govc: add sso.idp.ls command
vcsim:  add ssoadmin simulator
Closes: #2738
Tested against real vCenter and added vcsim support for the ssoadmin endpoint
this project
=> ssoadmin: add IdentitySources API bindings

govc/USAGE.md, govc/namespace/cluster/enable.go, vapi/namespace/namespace.go, vapi/rest/resource.go, vapi/rest/resource_test.go
Was receiving an error when running namespace.cluster.enable (with Vcenter 7U2):
```
govc: error in compatible switch lookup: GET https://VCENTER-HOST/api/vcenter/namespace-management/edge-cluster-compatibility?cluster=domain-c8&compatible=true&distributed_switch=50+32+27+0c+a8+8e+db+57-33+db+9e+e7+6e+49+58+ca: 500 Internal Server Error
```
It seems like vCenter is no longer accepting the parameter strings query-encoded (" " -> "+") and instead wants them to be URL-encoded (" " -> "%20"). Both ways should be valid, but only the second is now accepted. This isn't how go encodes strings, so it requires a bit of working-around.
Also noticed that the example given in the help no longer works, an additional mandatory parameter is needed
not work as …
=> fix: switch url encoding for namespace.cluster.enable edge cluster lookup

cns/client_test.go, cns/types/types.go
Add BackingDiskObjectId go bindings in CnsBlockBackingDetails to CNS API.
This field is only for vsan and vvol.
issues: #2744 
**Testing:**
Executed govmomi/cns/client_test.go 
1. **For vsan datastore** 
export CNS_VC_URL='https://Administrator@vsphere.local:Admin!23@10.78.116.147/sdk'
export CNS_DATACENTER='vcqaDC'
export CNS_DATASTORE='vsanDatastore'
```
client_test.go:278: Successfully Queried Volumes. queryResultBackingDiskObjectIdTest: &types.CnsQueryResult{
{
Id: "1d65a09c-1fb7-4e7a-bf8a-4501d8971a46",
},
DatastoreUrl:    "ds:///vmfs/volumes/vsan:52ba6157403606a4-6332b4a97562ad04/",
Name:            "pvc-901e87eb-c2bd-11e9-806f-005056a0c9a0",
VolumeType:      "BLOCK",
StoragePolicyId: "aa6d5a82-1c88-45da-85d3-3d74b91a5bad", …
```
=> Add BackingDiskObjectId go bindings to CNS API

sts/client_test.go, sts/signer.go, sts/signer_test.go
PR #2701 (ebeaa71b) added IPv6 support for signing HTTP request,
but was treating all IPs as v6.
Added tests and ran against real vCenter using `govc session.login -r ...`
this project
=> fix: rest.Client.LoginByToken invalid signature

vapi/tags/categories.go, vapi/tags/categories_test.go
`GetCategories()` would fail if a category was deleted between the initial `ListCategories()` and `GetCategory()` details loop which is not atomic. This fix ignores any `404`s while retrieving category details.
I did not change the method signature as I consider this a bug fix and not a breaking API change.
I updated the doc strings to line wrap and be more consistent in this file.
Closes: #2710
Added a unit test simulating concurrent deletes while calling `GetCategories()`.
this project
=> Ignore concurrent deletes in `GetCategories()`

vim25/debug/debug_test.go, vim25/soap/debug.go
The govmomi soap and rest clients ensure Request.Body is not nil, but custom clients may not.
this project
=> fix: avoid debug trace if http.Request.Body is nil

cns/client_test.go, examples/tasks/main.go, go.mod, govc/flags/debug.go, govc/flags/output.go, toolbox/guest_info.go, vsan/client_test.go, vslm/client_test.go
Go.mod contains two replace directives. This commit moves the replaced packages directly in the required.
It allows to `go install github.com/vmare/govmomi/govc@latest` with go 1.17.
Otherwise we get:
```
go install github.com/vmware/govmomi/govc@latest
go install: github.com/vmware/govmomi/govc@latest (in github.com/vmware/govmomi@v0.27.3):
The go.mod file for the module providing named packages contains one or
more replace directives. It must not contain directives that would cause
it to be interpreted differently than if it were the main module.
```
=> fix: Allow go 1.17 to go install

.chglog/config.yml, CONTRIBUTING.md
Add new `api: ` commit prefix and guideline for `govmomi` API-related changes, e.g. new/changed bindings, etc.
Example output:
<a name="v0.28.0"></a>
> Release Date: 2022-02-17
- [a587742b]	avoid debug trace if http.Request.Body is nil
- [7e2ce135]	Ignore concurrent deletes in GetCategories
- [a7c6f15b]	Allow go 1.17 to go install
- [d1f0fd97]	Add XYZ bindings
- [40e6cbc8]	Add Appliance access API
- [949ef572]	Add Appliance shutdown API's
Closes: #2763
Generated `CHANGELOG` (see example above).
this project
=> Add api: commit prefix

object/virtual_device_list.go
Add Support for 
Closes: #2765 
Yes
VM Creation
Before:
```
govc vm.create -m 2048 -c 2 -g freebsd64Guest -net.adapter vmxnet3vrdma -net=Management -disk.controller pvscsi -ds=vsanDatastore -dc=Datacenter -cluster=Cluster vm-name
govc: unknown ethernet card type 'vmxnet3vrdma'
```
After:
```
./govc vm.create -m 2048 -c 2 -g freebsd64Guest -net.adapter vmxnet3vrdma -net=Management -disk.controller pvscsi -ds=vsanDatastore -dc=Datacenter -cluster=Cluster vm-name
echo $?
0
```
this project
=> Added Support for vrdma NIC Type

object/example_test.go, object/virtual_device_list.go, object/virtual_device_list_test.go
Simplify finding VM GPU devices with `VirtualDeviceList.SelectByBackingInfo` and add example.
Closes: #2769
this project
=> api: add GPU support to VirtualDeviceList.SelectByBackingInfo

object/distributed_virtual_switch.go
LACP reconfiguration on DVS is not exposed. This PR adds API to configure.
Closes: #([2774](https://github.com/vmware/govmomi/issues/2774))
New feature (non-breaking change which adds functionality)
Manually tested.
=> Reconfigure LACP API for DVS

govc/USAGE.md, govc/dvs/create.go
When creating distributed and nested switches, you will often want to provide only a single uplink port, or in the case of a 4 port nic, utilize 4 ports.  This feature was missing from dvs.create.
I also added a local check to ensure that you don't try and create a DVS with 0 or invalid ports, as vSphere won't let you do that.
No dependencies
Resubmission of PR: https://github.com/vmware/govmomi/pull/2499
Closes: #2314
- I used the code that  @dougm provided in the issue, and put modified the code. I compared what I received in the simulator with the output Doug provided by running the Powershell command.
- I then powered up my homelab and tested this against VSphere 7.0 u2 and created a DVS with 1 uplink port, 3, 1030. 
Added a …
=> [resubmission] adding govc: add dvs.create '-num-uplinks' flag to control number of uplinks for a new distributed switch

simulator/host_datastore_system.go, simulator/host_datastore_system_test.go, vapi/simulator/simulator.go
Fix NFS datastore moids in vcsim so that they are unique to each datastore.
This fixes the issue that multiple `CreateNfsDatastore` requests except the first one does not work.
Closes: #2767
1. Start vcsim
1. create NFS Datastore `ds1` on `DC0_C0_H0` by govc
1. create NFS Datastore `ds2` on `DC0_C0_H0` by govc
```bash
$ govc datastore.create -name /ds1 -type nfs DC0_C0_H0
$ govc datastore.create -name /ds2 -type nfs DC0_C0_H0
$ govc datastore.info
Name:        LocalDS_0
Path:      /DC0/datastore/LocalDS_0
Type:      OTHER
URL: …
```
=> vcsim: Fix NFS datastore moid collision

vim25/types/types.go, vim25/types/unreleased.go
Add a new type of cluster action.
Add a new type of cluster action used for placing a VM. This action inherits from InitialPlacement action because it conveys the resource pool and host for placing the VM. In addition, it also has the VM's ConfigSpecwhich is used for indicating the recommended datastore for each virtual disk in VM's ConfigSpec.
this project
=> Add a new type of cluster action

govc/datastore/disk/inflate.go, govc/datastore/disk/shrink.go
Fix arguments validation in `datastore.disk.inflate` and `datastore.disk.shrink` to ensure vmdk is specified.
Closes: #2791 
Since command line arguments are invalid, govc shows usage help.
```bash
$ ./govc datastore.disk.inflate
Usage: ./govc datastore.disk.inflate [OPTIONS] VMDK
Inflate VMDK on DS.
Examples:
govc datastore.disk.inflate disks/disk1.vmdk
Options:
-cert=                              Certificate [GOVC_CERTIFICATE]
-dc=                                Datacenter [GOVC_DATACENTER]
-debug=false                        Store debug logs …
```
=> govc: Fix arguments validation in datastore.disk.inflate/shrink

simulator/folder.go, vim25/types/unreleased.go
The ClusterClusterInitialPlacementAction type is the expected action
type in the PlaceVmsXCluster response. While here, also define and use
the xClusterPlacement reason code.
Instead of returning the PlacementAction action type (via calling PlaceVm under the covers) return the expected ClusterClusterInitialPlacementAction type, along with the new, expected reason code.
Client code against simulator works as expected. Verification of this E2E against actual in-flight.
```
--- PASS: TestPlaceVmsXCluster (1.38s)
```
- [] My code follows the CONTRIBUTION [guidelines](./../CONTRIBUTING.md) of
this project
=> vcsim: Use new action type in simulator PlaceVmsXCluster response

govc/test/vcsim.bats
The `powerclicore` image used in the `govc-test` target is now available (pushed) on Github's own package registry (`ghcr.io/embano1/powerclicore`). The image is exactly the same (`sha256:09b29f69c0653f871f6d569f7c4c03c952909f68a27e9792ef2f7c8653235668`) as the originally used image `projects.registry.vmware.com/pez/powerclicore`.
This provides some efficiency, availability and performance gains.
Closes: #2794
this project
=> Use powerclicore on `ghcr.io`

vim25/types/helpers.go, vim25/types/helpers_test.go
This patch introduces a helper so that a `VirtualMachineConfigInfo` can be converted to an equivalent representation as a `VirtualMachineConfigSpec`.
Closes: NA
this project
=> ConfigInfo2ConfigSpec

govc/USAGE.md, govc/cluster/module/create.go, govc/cluster/module/ls.go, govc/cluster/module/rm.go, govc/cluster/module/vm_add.go, govc/cluster/module/vm_rm.go, govc/main.go, govc/test/cluster.bats
Add govc cluster.module command
This is a little easier than trying to remember the vapi HTTP calls. Note that modules.ls does output the MoIDs since that is what the API returns: a later improvement might be to resolve those to their friendlier inventory names.
Against real VC, and added bats test
this project
=> govc: Add CLI command cluster.module

govc/USAGE.md, govc/vm/guest/auth.go
`govc` now throws a clear error message when `username` (via `-l` or `GOVC_GUEST_LOGIN`) is not set.
Closes: #2812
this project
=> `govc guest` validate username

object/virtual_device_list.go, object/virtual_machine.go, object/virtual_machine_test.go
Config spec helpers have logic to clear the DiskFileOperation for existing disks,
when 'CapacityInKB' is '0'. But we also need to check 'Capacity'.
Refactor some duplicate code into a separate function.
Closes #2805
Added `TestDiskFileOperation`
this project
=> fix: DiskFileOperation must consider both capacity fields

govc/USAGE.md, govc/device/clock/add.go, govc/device/info.go, govc/main.go, govc/test/device.bats, object/virtual_device_list.go
add 'device.clock.add' command - Add precision clock device to VM
Closes: #2834
Tested against real vCenter + vcsim
this project
=> govc: add 'device.clock.add' command

govc/emacs/govc.el
Switching back to json-pretty-print-buffer, which works again, and json-mode-beautify does not. :shrug:
Emacs 27.2 
this project
=> emacs: fix json mode

Dockerfile.vcsim
The `vcsim` Dockerfile now uses `ENTRYPOINT` for the `vcsim` binary and
`CMD` for default listener address `0.0.0.0:8989`. A user can now easily
overwrite the default behavior without having to specify `/vcsim`
explicitly since it is the defined `ENTRYPOINT`.
Closes: #2841 
this project
=> vcsim: Update Dockerfile

govc/USAGE.md, govc/library/info.go
Fixed docs for govc library.info w/-json
When -json comes after the "library/item" then it does not trigger JSON output.
=> Fixed docs for govc library.info w/-json

govc/cli/register.go, govc/library/deploy.go, govc/test/library.bats, vapi/simulator/simulator.go, vapi/vcenter/vcenter_ovf.go
- govc: add library.deploy '-config' flag
- vcsim: add content library VmConfigSpec support
- api: add VmConfigSpec field to content library DeploymentSpec
Closes: #2843
this project
=> Add content library VmConfigSpec support

vsan/types/enum.go
The string value 'allflash' can not be used to add disk to all flash disk group, So here changes it to 'allFlash'. 
Closes: #2846 
I have reproduced the issue #2846 in my lab cluster. And succeeded to add ssd disk to existing disk group of type of all flash.
this project
=> fix:fail to add ssd disk into allflash disk group

govc/flags/search.go
When cloning a VM if you specify the `-host.dns` flag it throws the error `expected VirtualMachine entity, got HostSystem`, this is because the SearchFlag instance is saved in the context with a static `searchFlagKey`
Closes: #2849 
I successfully cloned a VM by using this command:
`./govc vm.clone -vm "TestDHCP" -host.dns "esxi-eu-dev-01.example.com" testvm`
this project
=> govc: Use unique searchFlagKey when calling NewSearchFlag

vslm/client_test.go, vslm/global_object_manager.go
This PR is correcting `SetControlFlags` and `ClearControlFlags` APIs to supply Volume ID.
When we call these APIs without Volume ID, APIs fail with `ServerFaultCode: VolumeId is empty.`
- Bug fix (non-breaking change which fixes an issue)
Created VMDK and executed tests
```
% go test -v
client_test.go:60: Successfully registered disk with path https://10.187.116.17/folder/29be9662-ce3c-0818-fd35-0200ad8e5983/test-disk.vmdk?dcPath=VSAN-DC&dsName=vsanDatastore as FCD with storage object id e60716d1-6447-4041-9b2a-ca45bebbdd35
client_test.go:91: Creating volume using the spec: types.CnsVolumeCreateSpec{
Name:       "pvc-abc123",
Datastores: nil,
Metadata:   types.CnsVolumeMetadata{
ContainerCluster: …
```
=> correct SetControlFlags and ClearControlFlags APIs

govc/USAGE.md, govc/test/vm.bats, govc/vm/migrate.go
PR #2850 fix a search flag issue with the vm.clone command, but caused an issue with the vm.migrate command.
Rather than embed the SearchFlag directly, vm.migrate needs to embed the VirtualMachineFlag
Issue #2849
this project
=> fix: govc: disambiguate vm/host search flags in vm.migrate

vslm/client_test.go
`FCD_KEEP_AFTER_DELETE_VM` is not correct control flag.
correcting test to use correct control flag VslmVStorageObjectControlFlagKeepAfterDeleteVm with value `keepAfterDeleteVm` 
Bug fix (non-breaking change which fixes an issue)
Validated control flag in this PR - https://github.com/kubernetes-sigs/vsphere-csi-driver/pull/1762 
cc: @chethanv28 @bandyopadhyays-vmware
=> Fix: use correct controlflag for vslm SetControlFlags API test

simulator/virtual_machine.go
Mitigates a panic situation in the `simulator` panic, where an unguarded interface conversion to SoapFault can potentially cause a panic in dependents if they call on a number of simulator methods without waiting for inflight tasks to complete.
Reference: https://github.com/vmware/govmomi/issues/2393#issuecomment-828116732
Closes: `nil`
this project
=> fix: Interface conversion panic in pkg simulator

simulator/folder.go, simulator/virtual_machine.go, simulator/virtual_machine_test.go
Fix vcsim `createVM` to encode special characters in requested vm name
Closes: #2873
this project
=> vcsim: Fix createVM to encode VM name

govc/metric/info.go, govc/metric/ls.go, govc/test/metric.bats, performance/manager.go, simulator/performance_manager.go
Newer versions of vCenter may return a CounterId via QueryAvailablePerfMetric()
which does not have a corresponding PerfCounterInfo entry in PerformanceManager's
perfCounter property. This results in a panic by a few of the govc metric commands
and any application using performance.Manager.AvailableMetric with Sort enabled.
While this may be a bug in vCenter, it is included in some recent release versions.
This workaround avoids the panic by ignoring any CounterId w/o a PerfCounterInfo.
Also updated vcsim's PerformanceManager.QueryCounter to match real vCenter's behavior.
Where null is returned for an unknown CounterId.
Closes #2835
Tested against vCenter build 55745184 (unreleased 8.0).
Updated vcsim to add this behavior, which …
=> fix: avoid possible panic in govc metric commands

internal/version/version.go, vim25/soap/client.go, vim25/soap/client_test.go
If a user does not provide a custom `user-agent` via `client.UserAgent` a default request header `user-agent` will be constructed using `ClientName/ClientVersion (GOVERSION;GOOS;GOARCH)` syntax, e.g. `govmomi/0.28.0 (go1.18.3;linux;amd64)` and added to each outgoing HTTP request (SOAP/VAPI).
Adds a new `version.go` file in `internal/package`. The version number gets bumped on every release (see TODO below).
I decided to put this change in `client.Do` because there's multiple ways to construct a `Client`. `Do` is the place where we have full control over the new behavior without touching existing constructors, etc.
See comments in the PR review section for further details on the proposed implementation.
Not considering this a breaking change:
- currently we don't set a `user-agent` header …
=> Add versioned user-agent header

.github/workflows/govmomi-release.yaml, RELEASE.md
Updates the release automation workflow to incorporate required automation changes introduced by PR #2872 .
Starting with release `v0.29.0` (strictly speaking with the commit when this PR is merged to `master`), the release automation will not use tags to trigger the workflow anymore but release branches, e.g. `release-0.29`. The whole process is done through the Github UI (only a release branch needs to be created upfront) using a `workflow_dispatch` trigger . See `RELEASE.md` for all details.
A dry-run mode is available (default) to simulate a release without pushing/creating artifacts, etc. This would detect most (but not all) issues during a release.
This streamlines the release process for patch/maintenance (e.g. `v0.29.1` on `release-0.29`) and new releases (e.g. `release-0.30`). 
> …
=> Update release automation

simulator/virtual_machine.go
When an Ethernet card is added, an entry for the card is appended to
the VMs Guest.Net. If the Ethernet card is later removed, this entry
was not removed. If Customize() is later called, it will fail with a
NicSettingMismatch error because the Guest.Net still contains an entry
for the removed card.
In configureDevice() always append to the VM's Guest.Net so it is kept
consistent because vcsim Edit operation is done by removing and then
adding the device.
If a VM originally has one card that is then removed and a new card added, vcsim Customize will fail with:
LocalizedMethodFault: {
DynamicData: {},
Fault: <*types.NicSettingMismatch | 0xc00097f7d0>{
CustomizationFault: {
VimFault: {
MethodFault: {FaultCause: nil, FaultMessage: nil},
},
},
NumberOfNicsInSpec: 1,
NumberOfNicsInVM: 2,
}, …
=> vcsim: Remove VM Guest.Net entry when removing Ethernet card

vim25/soap/client_test.go
Replace incomplete sentinel error name in these tests:
- TestMultipleCAPaths
- TestInvalidRootCAs
Closes: #2883
*Please describe the tests that you ran to verify your changes. Provide
details for your test configuration.*
- passed
- unrelated test failure (see output below)
<details>
<summary>test failure output</summary>
```
--- FAIL: ExampleClient_Run (0.50s)
panic: ServerFaultCode: GuestOperationsUnavailable [recovered]
panic: ServerFaultCode: GuestOperationsUnavailable
goroutine 1 [running]:
testing.(*InternalExample).processRunResult(0xc000019ca8, {0x0, 0x0}, 0x4, 0x0, {0xdb7e80, 0xc000152050})
/usr/local/go/src/testing/example.go:91 +0x505 …
```
=> fix: Typos in vim25/soap/client CA tests

object/virtual_device_list.go, object/virtual_device_list_test.go
Fix `VirtualDeviceList#AssignController` to always generate negative device keys so that they will not collide with existing keys.
Closes: #2881
this project
=> fix: generate negative device key in AssignController

eam/methods/methods.go, eam/types/types.go, gen/gen.sh, pbm/methods/methods.go, pbm/types/enum.go, pbm/types/if.go, pbm/types/types.go, simulator/property_collector.go, simulator/simulator.go, sms/methods/methods.go, sms/types/enum.go, sms/types/if.go, sms/types/types.go, vim25/methods/methods.go, vim25/mo/mo.go, vim25/types/enum.go, vim25/types/if.go, vim25/types/types.go, vslm/methods/methods.go, vslm/types/enum.go, vslm/types/if.go, vslm/types/types.go
This patch updates the generated types to the version for the upcoming release in order to support internal and partner driven development that depends on GoVmomi.
this project
=> Update generated types

simulator/virtual_machine.go, simulator/virtual_machine_test.go
Fix `ReconfigVM_Task` in vcsim so that both of `CapacityInBytes` and `CapacityInKB` in VirtualDisk are updated.
Closes: #2889
this project
=> vcsim: Fix disk capacity fields in ReconfigVM_Task

simulator/virtual_machine.go, simulator/virtual_machine_test.go
This fixes datastore freespace changing logic in `ReconfigVM_Task`.
When virtualDisk's size is changed, datastore freespace decreases by disk capacity difference.
Closes: #2894
this project
=> vcsim: Fix datastore freespace changed by ReconfigVM_Task

govc/test/host.bats, simulator/host_system.go, simulator/host_system_test.go
This PR introduces support for host disconnect/reconnect to vcsim, with associated `bats` tests.
As both operations are so closely related to each other, I've tested them together through disconnecting then reconnecting a host in the simulator. Happy to update to follow a different approach if the project prefers things done a different way.
Closes: #2899
I've not been able to run the full test suite on my machine (first time contributing and think I have some missing dependencies which cause some tests to time out) but tests relating to the …
=> vcsim: support disconnect/reconnect host

govc/USAGE.md, govc/flags/library.go, govc/library/create.go, govc/library/info.go, govc/library/policy/ls.go, govc/main.go, govc/namespace/cluster/enable.go, govc/test/library.bats, vapi/internal/internal.go, vapi/library/library.go, vapi/library/security_policy.go, vapi/resource.go, vapi/simulator/simulator.go
Security policies are important as they allow vCenter to secure content
at rest instead of requiring on thumbprints or TLS, which only verifies
you are talking to the correct server, but does nothing if the contents
themselves are compromised.
This changes adds a new cli command to support querying existing
library security policies. Support was added for creating new libraries
with a security policy and querying libraries that may have a security
policy attached.
Support was added to the vcsim mux to handle the /api endpoint for the
library module, since this endpoint is not served on /rest endpoints.
I thought this approach made more sense than a new mux since the
changes to add support for this were fairly minor. Having one module for
all library functions made sense organizationally, …
=> govc: Support creating content libraries with security policies

simulator/model.go
Set initial value to virtualDisk.StorageIOAllocationInfo in the simulator model so that `govc vm.disk.change` to `vcsim` does not panic.
Closes: #2904
```bash
$ govc device.info -vm DC0_H0_VM0 "disk-*"
Name:           disk-202-0
Type:         VirtualDisk
Label:        disk-202-0
Summary:      10,485,760 KB
Key:          204
Controller:   pvscsi-202
Unit number:  0
File: …
```
=> vcsim: Fix StorageIOAllocationInfo of VirtualDisk

govc/namespace/cluster/enable.go, vapi/namespace/namespace.go, vapi/namespace/simulator/simulator.go
Added support for vDS networking and the Avi Load Balancer.
Tested on 7.0u2 and 7.0u3.
Added strongly typed fields for enums that were previously freeform strings.
Needed as part of the new terraform-provider-namespace-management project located here (not public yet): https://github.com/vmware-tanzu-labs/terraform-provider-namespace-management
=> Ensured namespace-management works on 7.0u2+ with wider configuration options

simulator/snapshot.go, simulator/virtual_machine.go, simulator/virtual_machine_test.go
This PR fixes snapshot tasks in vcsim to update virtual machine's `rootSnapshot` properly.
Closes: #2912
```bash
$ govc snapshot.create -vm DC0_H0_VM0 snapshot1
$ govc snapshot.tree -vm DC0_H0_VM0 -i
[snapshot-67]  snapshot1
[snapshot-67]  .
$ govc vm.info -json DC0_H0_VM0 | jq .VirtualMachines[].RootSnapshot
[
{
"Type": "VirtualMachineSnapshot",
"Value": "snapshot-67"
}
]
$ govc snapshot.create -vm DC0_H0_VM0 snapshot2
$ govc snapshot.tree -vm DC0_H0_VM0 -i
[snapshot-67]  snapshot1
[snapshot-69]  snapshot2
[snapshot-69]  .
$ govc vm.info -json …
```
=> vcsim: Fix snapshot tasks to update rootSnapshot

govc/events/command.go, govc/test/events.bats
Since key is an important and fundamental value for
identifying events, this patch changes it to be
included in the json or plain text output of
"govc events" command.
this project
=> govc: add event key for json and plain text output

toolbox/hgfs/hgfs_openbsd.go
Fix build on OpenBSD, add hgfs stub.
Basically I need this for telegraf, so this is untested with VMware vSphere APIs.
=> toolbox: add hgfs OpenBSD stub

simulator/vpx/service_content.go
The uuid.NodeID function returns the node's (first) nic hardware address.
Using this makes ServiceContent.InstanceUuid unique, yet stable.
=> vcsim: use node id for ServiceContent.InstanceUuid

cns/client_test.go, cns/types/enum.go
This PR adds new query selection parameters, to be obtained as a result of query volume request(s) to CNS. These parameters, when specified as input to CNS query volume APIs (`QueryAllVolume` / `QueryVolumeAsync`), obtains datastore URL and storage policy ID for requested volume(s) from CNS.
These parameters will be used to query the specific volume details of datastore URL and storage policy ID in vSphere CSI driver code.
Tested `QueryAllVolume` API with new parameters from `cns/client_test.go`
```
...
client_test.go:732: Successfully Queried all Volumes. queryResult: &types.CnsQueryResult{
{
Id: "6e5ab646-c23c-4ee5-90cd-95ff4e34d365",
}, …
```
=> Add new query selection parameters for QueryAllVolume/QueryVolumeAsync API

cns/client_test.go, cns/types/enum.go
This PR addresses review comments for https://github.com/vmware/govmomi/pull/2951 from @chethanv28 
How Has This Been Tested?
Tested QueryAllVolume API with new parameter from cns/client_test.go
...
client_test.go:732: Successfully Queried all Volumes. queryResult: &types.CnsQueryResult{
{
Id: "6e5ab646-c23c-4ee5-90cd-95ff4e34d365",
},
DatastoreUrl:         "ds:///vmfs/volumes/vsan:5200264f8423829b-138888a14230b49d/",
Name:                 "pvc-901e87eb-c2bd-11e9-806f-005056a0c9a0",
VolumeType:           "BLOCK",
StoragePolicyId:      "aa6d5a82-1c88-45da-85d3-3d74b91a5bad",
Metadata:             types.CnsVolumeMetadata{},
BackingObjectDetails: &types.CnsBlockBackingDetails{
CnsBackingObjectDetails: …
=> Update query selection parameter name

.gitignore, cns/client.go, cns/client_test.go, cns/methods/methods.go, cns/types/types.go
This PR adds cnsreconfigpolicy API bindings and static check fixes in client_test.go
Added new block client_test.go for this API
```bashsashrith@sashrith-a01 ~/csi/govmomi/cns cnsreconfigpolicy* ⇡ 3m 35s ❯ export CNS_VC_URL='https://administrator@vsphere.local:Admin!23@10.92.1.36/sdk'
export CNS_DATACENTER="VSAN-DC"
export CNS_DATASTORE="vsanDatastore"
export CNS_SPBM_POLICY_ID_4_RECONFIG="aa6d5a82-1c88-45da-85d3-3d74b91a5bad"
sashrith@sashrith-a01 ~/csi/govmomi/cns cnsreconfigpolicy* ⇡ ❯ go test -v 2>&1 >testrun4.log
sashrith@sashrith-a01 ~/csi/govmomi/cns cnsreconfigpolicy* ⇡ 2m 53s ❯ cat testrun4.log
...
client_test.go:1308: Volume created sucessfully. volumeId: dbd29ab6-6ec6-4d4d-8ff6-260fd989c9b7 …
```
=> cnsreconfigpolicy bindings and static check fixes in client_test.go

object/virtual_device_list.go
Closes #2956
Signed-off-by: Sunny Carter <sunny.carter@metaswitch.com>
https://github.com/vmware/govmomi/issues/2956 
Is your feature request related to a problem? Please describe.
SR-IOV, Single Root I/O Virtualization, allows a single NIC (termed the Physical Function - PF) to be shared between a bounded number of VMs, providing a Virtual Function (VF) network interface to each VM. It is used for high-performance throughput on the network interface.
In VMWare, Ethernet devices of UnitNumber 7-19 are non-SRIOV. Ethernet devices of UnitNumber 45-36 descending are SRIOV.
Current code uses the UnitNumber to determine the device name, but it only takes into account non-SRIOV devices.
It is necessary to have a different stable name for SRIOV devices that takes this into account, otherwise …
=> api: Add SRIOV device names

govc/host/esxcli/esxcli.go
This PR fixes `govc host.esxcli` runtime error occurred when no arguments specified.
Closes: #2960
```bash
$ ./govc host.esxcli
./govc: no argument
```
=> govc: fix host.esxcli runtime error occurred when no arguments specified

task/history_collector.go
This change fixes the recentTasks errors in the task historyCollector. TaskHistoryCollector does not have a recentTask property, so this method always fails.
Update recentTasks to latestPage to fix this bug.
Test code:
```
taskManager := task.NewManager(vcClient.VimClient())
filterSpec := types.TaskFilterSpec{
ActivationId: []string{actID},
}
collector, err := taskManager.CreateCollectorForTasks(ctx, filterSpec)
if err != nil {
return nil, errors.Wrapf(err, "failed to create collector for tasks")
}
defer func() {
retErr = collector.Destroy(ctx) …
```
=> Fix: use latestPages in task HistoryCollector

simulator/folder.go, vim25/types/unreleased.go
PlaceVmsXCluster request has two optional bool fields as to whether host and/or datastore selection is required as a part of the placement response.
Update simulator PlaceVmsXCluster response to include the ConfigSpec only when the datastore selection is required to match real VC behavior.
Note that the simulator handling of DatastoreRecommRequired is just an initial pass, and something we'll likely need to improve on later. My immediate need is just for HostRecommRequired.
Verified client behavior against both VC and vcsim
this project
=> Add optional recommRequired PlaceVmsXCluster req arguments

govc/test/vm.bats, simulator/virtual_machine.go, simulator/virtual_machine_test.go
This PR fixes CloneVM_Task error handling so that cloning a vm with duplicated name fails
Closes: #2983
```bash
$ go run main.go
task failed: *types.DuplicateName
$ govc tasks -n 1
Task                                     Target                         Initiator                         Queued   Started Completed Result
CloneVm                                  vm-55                          vcsim                           13:52:45  13:52:45  13:52:45 error   [*types.DuplicateName]
```
this project
=> vcsim: Fix duplicated name check in CloneVM_Task

govc/USAGE.md, govc/library/info.go, govc/library/trust/create.go, govc/library/trust/info.go, govc/library/trust/ls.go, govc/library/trust/rm.go, govc/main.go, govc/test/library.bats, vapi/internal/internal.go, vapi/library/library_item.go, vapi/library/trusted_certificates.go, vapi/simulator/simulator.go
api: add Content Library security compliance support
govc: add libray.trust{ls,info,create,rm} commands
Closes #2980
this project
=> api: add Content Library security compliance support

govc/USAGE.md, govc/main.go, govc/sso/lpp/info.go, govc/sso/lpp/update.go, ssoadmin/client.go
Closes: #2975
It extends govc functionality with GetLocalPasswordPolicy and UpdateLocalPasswordPolicy methods, which are already here.
The new sso.lpp.get and sso.lpp.update commands are available
Tools like Ansible can read the state before do any change.
The check mode in Ansible modules can work also.
```
Description: The Number Of The Beast
MinLength: 0
MaxLength: 1
MinAlphabeticCount: 0
MinUppercaseCount: 0
MinLowercaseCount: 0
MinNumericCount: 0
MinSpecialCharCount: 0
MaxIdenticalAdjacentCharacters: 1
ProhibitedPreviousPasswordsCount: 1
PasswordLifetimeDays: 666
```
`govc sso.lpp.update -PasswordLifetimeDays 0 -Description "The Great Zeroing"`
`{
"LocalPasswordPolicy": {
"Description": "The Great Zeroing", …
=> govc: Add sso.lpp.get and sso.lpp.update commands

govc/flags/output.go, govc/host/info.go
**govc**
* host.info writes always write to os.Stdout instead of the provided writer
* OutputFlag.Write always write to os.Stdout instead of the provided writer
Closes: #2995
To reproduce the issue see the code in issue #2995.
This code is also used to test the fix.
Besides the test code, govc was also tested against a live environment.
this project
=> Issue 2995

.github/PULL_REQUEST_TEMPLATE.md, .github/comment-template.md, .github/workflows/codeql-analysis.yml, .github/workflows/govmomi-build.yaml, .github/workflows/govmomi-go-lint.yaml, .github/workflows/govmomi-go-tests.yaml, .github/workflows/govmomi-govc-tests.yaml, .github/workflows/govmomi-release.yaml, .goreleaser.yml, CONTRIBUTING.md, RELEASE.md, find/doc.go, govc/README.md, govc/build.sh, govc/emacs/govc.el, internal/version/version.go, scripts/devbox/README.md, scripts/vcsa/create-esxi-vm.sh, simulator/doc.go, toolbox/README.md, vapi/library/finder/README.md
This patch prepares the repository for moving to the `main` branch. The following steps were taken to identify and change valid occurrences of `master` to `main`:
1. Replace obvious patterns:
```shell
grep -rIl 'govmomi/[^/]\{1,\}/master' * | xargs -n1 -I% \
sed -i.m2m -e 's~govmomi/\(.*\)/master~govmomi/\1/main~g' % && \
find . -name '*.m2m' -type f -delete
```
1. Replace instances in `RELEASE.md`:
```shell
sed -i.m2m -e 's~master~main~g' RELEASE.md && rm -f RELEASE.md.m2m
```
1. Replace instances in `CONTRIBUTING.md`:
```shell
sed -i.m2m -e 's~vmware/master~main~g' CONTRIBUTING.md && \
rm -f CONTRIBUTING.md.m2m
```
1. Replace instances in `.goreleaser.yml`:
```shell
sed -i.m2m -e 's~govmomi/\(.*\)/master~govmomi/\1/main~g' \
.goreleaser.yml && rm -f .goreleaser.yml.m2m
```
1. Replace …
=> Move to main

ssoadmin/client.go
With this change, we are modifying the default result limit of the ssoadmin client from 100 to 2 147 483 647 (`math.MaxInt32`).
This is the path of least resistance to fixing the issue mentioned in #3004, another possible way is to take the value as a user input through an environment variable or flag, but that might result in API changes.
Closes: #3004 
```
export GOVC_URL=<redacted>
export GOVC_USERNAME=<redacted>
export GOVC_PASSWORD=<redacted>
export GOVC_INSECURE=1
for ID in $(seq -w 101); do 
USER="test-issue-user-$ID";
echo "creating user …
```
=> fix: Pin the result limit of ssoadmin client to its MAX

govc/USAGE.md, govc/sso/idp/default.ls.go, govc/sso/idp/default.update.go, ssoadmin/client.go, ssoadmin/methods/methods.go, ssoadmin/types/types.go
It extends the govc functionality with GetDefaultDomains and SetDefaultDomains methods (sso idp)
It adds a command sso.idp.default.ls to get and sso.idp.default.update to set the default sso idp
Closes: #3023 
```
$ govc sso.idp.default.ls -json
{
"DefaultIdentitySource": [
"corp.local"
]
}
$ govc sso.idp.default.ls
Default identity provider source(s): corp.local
```
```
$ govc sso.idp.default.update corp.localzz
$ govc sso.idp.default.update corp.localzz
$ govc sso.idp.default.update corp.localzzz
govc: ServerFaultCode: Domain 'Identity Provider 'corp.localzzz' does not exist.' does not exist.
$ govc sso.idp.default.ls
Default identity provider source(s): corp.localzz
``` …
=> govc: Add feature to get and set default idp

eam/types/types.go, gen/vim_wsdl.rb, pbm/types/types.go, sms/types/types.go, vim25/types/types.go, vslm/types/types.go
This patch removes the JSON tag for properties named "This" of type "ManagedObjectReference" as VMware's SOAP over JSON project does not use this.
This patch also ensures any of the "ArrayOf" types use the type discriminator name "_value" for the name of the type's single field which is a slice.
Closes: NA
this project
=> Remove JSON tag for "This" / ArrayOf "_value"

govc/USAGE.md, govc/importx/archive.go, govc/importx/ovf.go, govc/test/images/update.sh, govc/test/import.bats, nfc/lease.go, simulator/http_nfc_lease.go
This patch enhances govc import.ova command to validate the checksum of an uploaded file (e.g. .vmdk file in .ova) - as computed by the remote server with the checksum listed in the ova manifest (.mf file in .ova). govc import.ova takes a new optional flag to indicate strict checksum validation.
(This govc enhancement needed a small tweak in nfc/lease.go code to actually return manifest data in GetManifest() API.)
This patch also modifies simulator to compute checksum of uploaded file and return that metadata through HttpNfcLeaseGetManifest() call.
govc ova import test now has a new sub-test to test for ova with valid checksum and ova with invalid checksum.
Closes: #1978
- Ran govc ova import existing tests as well as newly …
=> govc: Add checksum validation to govc import.ova

govc/test/vcsim.bats, govc/test/vm.bats, vcsim/main.go
- Commit 1991de51 recently changed the json tag for ArrayOf types
- Fix 'vcsim run container' test when using MacOS / Docker desktop
- Change vcsim/main.go to open the fifo after its running
The vcsim/main.go change may fix the random hangs we see in GH Actions. I was seeing random hangs locally when running all bats tests on MacOS.  Each time, the bats tests would be hung reading from the fifo here: https://github.com/vmware/govmomi/blob/99336079d7934f742f729c3d74ebdf8e4bdd6f4a/govc/test/test_helper.bash#L59
Not certain this will fix the random hangs in GH Actions, but there's no reason to open the fifo for writing until we have the data that'll be written to it anyhow.
=> chore: bats related fixes

govc/test/vcsim.bats, simulator/container.go
This is needed to support the VirtualMachine.WaitForNetIP helper against vcsim
Added tests to vcsim.bats that cover `VirtualMachine.WaitForIP()`
this project
=> vcsim: add guest.net.ipConfig

govc/USAGE.md, govc/flags/optional_string.go, govc/flags/optional_string_test.go, govc/library/create.go, govc/library/info.go, govc/library/update.go, vapi/library/library.go, vapi/library/library_item.go, vapi/simulator/simulator.go
This commit changes library item description field from string to a string pointer. 
This can help distinguish if the item description is unset or set to an empty string when updating the library item.
BREAKING: change Item.Description type from string to *string in package library.
This commit changes library item description field from string to a string pointer. 
This can help distinguish if the item description is unset or set to an empty string 
when updating the library item.
Sending a UpdateLibraryItem request with this change, and set …
=> Use string pointer for library item/library description field.

govc/USAGE.md, govc/vm/change.go
Closes: #3055
Add VM IOMMU enablement support in govc
Closes: #3055 
```
[ ~/github/govmomi/govc ]# ./govc vm.change
Usage: ./govc vm.change [OPTIONS]
Change VM configuration.
To add ExtraConfig variables that can read within the guest, use the 'guestinfo.' prefix.
Examples:
govc vm.change -vm $vm -mem.reservation 2048
govc vm.change -vm $vm -e smc.present=TRUE -e ich7m.present=TRUE
govc vm.change -vm $vm -cpu-hot-add-enabled -memory-hot-add-enabled
govc vm.change -vm $vm -e guestinfo.vmname $vm
govc vm.change -vm $vm -f …
```
=> govc: Add feature VM IOMMU enablement support

find/finder.go, find/finder_test.go, govc/test/import.bats, list/lister.go, simulator/finder_test.go
Datacenter's network folder may contain items with the same name.
For clusters that have one such instance of a given network name, the cluster inventory path will be unique.
Example:
```console
% govc ls -l -t DistributedVirtualPortgroup /DC/host/compute-cluster
/DC/host/dev-cluster/vnet-domain-c9:f6555e6e-051f-4eec-9275-78ba7f689335-test-gc-e2e-demo-ns-91610-0 (DistributedVirtualPortgroup)
/DC/host/dev-cluster/seg-domain-c9:f6555e6e-051f-4eec-9275-78ba7f689335-test-gc-e2e-demo-ns-0 (DistributedVirtualPortgroup)
/DC/host/dev-cluster/vm-domain-c9:f6555e6e-051f-4eec-9275-78ba7f689335-vif-default-network-0 (DistributedVirtualPortgroup)
/DC/host/dev-cluster/containerswitchavi-1 (DistributedVirtualPortgroup)
/DC/host/dev-cluster/containerswitch-1 (DistributedVirtualPortgroup) …
```
=> api: support find.Network by cluster path

govc/USAGE.md, govc/sso/idp/ldap_update.go, ssoadmin/client.go, ssoadmin/methods/methods.go, ssoadmin/types/types.go
Closes: #3057
It extends the govc functionality with the following methods:
- RegisterLdap
- UpdateLdap
- UpdateLdapAuthnType
It adds a command sso.idp.ldap.update to add/update LDAP sso idp
```
abo@mitac:~/Code/govmomi/govc$ go run . sso.idp.ls
Name          Server URL                        Type             Domain         Alias
-             -                                 System Domain    vsphere.local
-             -                                 Local OS         dafak
corp.local    ldap://powershell.corp.local:389  ActiveDirectory  corp.local      CLOUD
corp.locala   ldap://powershell.corp.local:389  ActiveDirectory  corp.locala
corp.localo   ldap://powershell.corp.local:389  ActiveDirectory  corp.localo
corp.localzz …
```
=> govc: add sso.idp.ldap.update command

govc/test/sso.bats, govc/test/vcsim.bats, simulator/session_manager.go, ssoadmin/simulator/simulator.go, vapi/simulator/simulator.go
The ssoadmin endpoint is now used for authentication for both SOAP and REST endpoints. Previous behavior is retained:
- By default, any non-empty username + password is authenticated
- If vcsim '-username' and '-password' flags are given, only those credentials can be used for authentication
Additional users can be added via the ssoadmin APIs or using govc for example:
```console
% govc sso.user.create -p password govc
```
Closes:  #2852
Added bats tests
this project
=> vcsim: add ssoadmin user and group management

gen/vim_wsdl.rb, vapi/internal/internal.go, vapi/simulator/simulator.go, vapi/tags/tag_association.go, vapi/vcenter/vcenter_ovf.go, vim25/types/types.go, vim25/types/types_test.go
This patch manually introduces the ServerGuid field to the generated types.ManagedObjectReference type. This field is used internally at VMware and not part of the public WSDL, but given internal projects make use of this field, it is helpful for GoVmomi to know about it so it can be part of serialization/deserialization for both XML and JSON.
Closes: `NA`
By running the new unit tests:
```shell
$ go test -v -run TestManagedObjectReference -count 1 ./vim25/types
=== RUN   TestManagedObjectReference
=== RUN   TestManagedObjectReference/with_server_GUID
=== RUN   TestManagedObjectReference/with_server_GUID/xml
=== RUN   TestManagedObjectReference/with_server_GUID/json
=== RUN   TestManagedObjectReference/sans_server_GUID
=== RUN …
```
=> Add ServerGuid to generated MoRef type

govc/test/vm.bats, govc/vm/console.go
The poweredOn check makes sense with wss, capture and h5 arguments - but not if you want the plain VMRC link, since that works perfectly fine with powered off VMs.
Closes: #2127
(see https://github.com/vmware/govmomi/pull/3059#issuecomment-1474295537 for duplicated PR)
connecting to a powered off machine:
(not necessary things strikethrough, if you do not agree, please tell me)
=> govc: dont check poweredOn for vm.console vmrc requests

govc/test/vcsim.bats
The test uses govc object.collect to wait for 1 update. The following rename command may happen before the background process is parked in WaitForUpdates, leaving object.collect to hang.
=> chore: fix WaitForUpdates bats test race

vim25/json/discriminator.go, vim25/json/discriminator_test.go, vim25/types/json_test.go, vim25/types/testdata/vminfo-invalid-type-name-value.json
This patch updates the behavior of the JSON codec package so that if the decode operation cannot convert a value into the destination type, the error is no longer ignored silently, but returned so the caller can handle it.
This patch also adds tests to validate these cases.
Please note this _is_ potentially a breaking change since previously, if `{"_typeName":"string", "_value":true}` was decoded, the result would have been an empty string. Now the result is an error returned from the decode operation that would read `json: cannot unmarshal bool into Go value of type string`.
Closes: `NA`
Several unit tests have been added to validate the test cases. …
=> chore: Err on json.Decode for invalid type/vals

object/search_index.go, object/search_index_test.go
This enables ` SearchIndex.FindByInventoryPath` to set inventory path to the returned object.
Closes: #3095
this project
=> api: set inventory path in SearchIndex.FindByInventoryPath

simulator/performance_manager.go, simulator/performance_manager_test.go
In performance_manager QueryPerf, only limit the number of samples generated to maxSample when maxSample is greater than 0 and the number of samples to generate is greater than maxSample.
Closes: #3097
this project
=> fix: maxSample defaults to 0 when not specified by client so no samples are returned

simulator/performance_manager.go, simulator/performance_manager_test.go
Adds "csv" format support to the QueryPerf API implementation in govcsim; performance counter data is generated the same as before, but if the client specifies "csv" format, samples are converted to CSV before being returned, otherwise the "normal" format is returned (previous behaviour).
Closes: #3103
this project
=> govcsim: Add CSV format support to QueryPerf API; Closes #3103

CONTRIBUTORS, govc/USAGE.md, govc/main.go, govc/test/volume.bats, govc/volume/snapshot/create.go, govc/volume/snapshot/ls.go, govc/volume/snapshot/rm.go
Adds support for interacting with snapshots of CNS volumes by implementing the following commands:
- `govc volume.snapshot.create ID DESC`
Creates a snapshot of the CNS volume with volume id `ID` with the description `DESC`.
- `govc volume.snapshot.ls ID`
Lists all snaphots of the CNS volume with volume id `ID`
- `govc volume.snapshot.rm SNAP_ID VOL_ID`
Removes the snapshot with snapshot id `SNAP_ID` from the CNS volume with the volume id `VOL_ID`
The commands `volume.snapshot.ls` and `volume.snapshot.rm` support batch operations that make it possible to list all snapshots of multiple volumes or delete multiple snapshots at once. For example it's possible to delete all snapshots of all volumes using `govc volume.snapshot.rm $(govc volume.snapshot.ls -i $(govc volume.ls -i))`.
All commands …
=> govc: Add support for CNS volume snapshots

govc/flags/debug.go
=> fix: avoid govc -verbose flag panic if an UpdateSet is nil

govc/USAGE.md, govc/cluster/mv.go, govc/test/cluster.bats, simulator/cluster_compute_resource.go
Move hosts into a cluster.
vcsim: add ClusterComputeResource.MoveInto_Task support
Closes #2524
added new bats tests
this project
=> govc: add cluster.mv command

vim25/json/discriminator.go, vim25/types/json_encoding.go, vim25/types/json_encoding_test.go
Added mapping for float.
Fixed the mappings for byte to use uint8.
Changed type name lookup order to use the external mapping before built-in table. This fixes int deserialization.
Closes: #3121
this project
=> fix: byte, float and int (de) serialization

govc/host/esxcli/executor.go
Include full fault details in error message, otherwise we get
```
EsxCLI.CLIFault.summary
```
And cannot diagnose the SDK errors
Closes: #3073
Verified fix against live environment that returns the error for objects that are not found
this project
=> Detailed error message for execli errors

simulator/search_index.go, simulator/search_index_test.go
This PR fixes FindByInventoryPath so that it can respond the root folder `/`.
Closes: #3119
this project
=> vcsim: Fix FindByInventoryPath to handle root folder

govc/host/esxcli/esxcli.go, govc/host/esxcli/executor.go
PR #3072 added fault detail to the error message, breaking existing code at runtime.
=> fix: add esxcli.Fault and revert Error() string

vim25/json/discriminator.go, vim25/json/discriminator_test.go, vim25/types/json.go, vim25/types/json_test.go
This change adds support for `binary` and `dateTime` in JSON.
For `binary` golang `[]byte` JSON serialization matches the vCenter format. Thus adding the name ot the maps was enough.
For `dateTime` the format of `time.Time` `Marshaler` and `Unmarshaler` matches vCenter format. The discriminator code required support for custom marshaling logic. In addition the name had to be mapped.
Closes: #3127
this project
=> fix: support `binary` and `dateTime` in JSON

govc/test/vcsim.bats, simulator/virtual_machine.go, simulator/virtual_machine_test.go
GuestShutdown and GuestStandby methods don't block when called in real vCenter, but the VM power state transition won't happen until somtime after the guest has actually shutdown. It is also possible for shutdown to hang indefinitely. To simulate such behavior, an internal task is now used to transition state, which can be optionally delayed.
=> vcsim: async guest shutdown and standby

simulator/container.go
Howdy! One more quick feature that I found useful in some of my local testing, though perhaps I misunderstood if there's an existing way to do this. It seemed that for container-backed VMs in vcsim, there was no way to inject a 1:1 environment variable, only using the `guestinfo.ABC` flag which would then translate the key for the environment variable to something along the lines of `VMX_GUESTINFO_ABC `.
For some context where this became useful to me, in the process of automating with vcsim, I needed to provide a few environment variables when the container was first started to configure the software that was running inside.
Feel free to close if this isn't useful, though!
Please describe the tests that you ran to verify your …
=> vcsim: Add RUN.env flag to inject environment variables to container-backed VM

simulator/esx/host_system.go
according [Enum HostStandbyMode(vim.HostSystem.StandbyMode)](https://vdc-repo.vmware.com/vmwb-repository/dcr-public/c476b64b-c93c-4b21-9d76-be14da0148f9/04ca12ad-59b9-4e1c-8232-fd3d4276e52c/SDK/vsphere-ws/docs/ReferenceGuide/vim.HostSystem.StandbyMode.html), StandByMode should not be empty.
we noticed it when we tried to replace a "real test vcenter" with vcsim
this project
=> vcsim: set StandbyMode default to "none"

cns/client.go, cns/client_test.go, cns/methods/methods.go, cns/types/types.go
This PR adds cnssyncdatastore API bindings and tests in client_test.go
Added new block in client_test.go for this API
```bash
sashrith@sashrithELVDQ ~/csi/govmomi cnssyncdatastore ⇡ ❯ export CNS_DATACENTER="VSAN-DC"                 
export CNS_DATASTORE="vsanDatastore"
sashrith@sashrithELVDQ ~/csi/govmomi cnssyncdatastore ⇡ ❯ go test -v 2>&1 >~/testrun1.log
sashrith@sashrithELVDQ ~/csi/govmomi/cns cnssyncdatastore* ⇡ 1m 27s ❯  tail ~/testrun1.log                             
}
client_test.go:934: Deleting volume: [{DynamicData:{} Id:51014d9f-a965-4caf-b670-6d908b2eb105}]
client_test.go:958: Volume: "51014d9f-a965-4caf-b670-6d908b2eb105" deleted sucessfully
client_test.go:1360: Calling syncDatastore on …
```
=> add cnssyncdatastore API bindings

vim25/soap/client.go
=> fix: share http.Transport with service clients

.goreleaser.yml
`replacement` has been deprecated for gorelease, need to use new syntax
Closes: #https://github.com/vmware/govmomi/issues/3169
this project
=> fix build: Remove some gorelease field deprecated field

govc/USAGE.md, govc/flags/network.go, govc/test/network.bats
When user add network adapter type `vmxnet3vrdma`, they can configure the protocol `rocev2/rocev1`. This is only supported on adapter type `vmxnet3vrdma`.
Closes: #https://github.com/vmware/govmomi/issues/3167
Built on a linux machine. Example output
Correct help message
```
kubo@keDgLYFEehvWP:~/govmomi/govc$ ./govc vm.network.add  --help
Usage: ./govc vm.network.add [OPTIONS]
Add network adapter to VM.
...
-net.address=                   Network hardware address
-net.protocol=                  Network device protocol. Applicable to …
```
=> govc: Add device protocol configuration for vm.network.add

object/virtual_device_list.go, object/virtual_device_list_test.go
Hey there! Not totally sure if this was the best approach, but I was revisiting some behavior in vcsim, specifically the PCI offset for NIC devices discussed in #907 and #2060. The tl;dr is that when creating a VM in vcsim (either with `govc` or the Terraform provider), the NIC that gets created has the following attributes:
Created with:
```
govc vm.create -m 2048 -c 2 -g ubuntu64Guest -net.adapter e1000 -disk.controller pvscsi -pool DC0_C0/Resources -net "VM Network" test-vm
```
Creates the following NIC
```
govc device.info -vm test-vm ethernet--6
Name:               ethernet--6
Type:             VirtualE1000
Label:            ethernet--7
Summary:          VM Network
Key:              203
Controller:       pci-100
Unit number:      1
Connected:        true
Start connected:  true
Guest …
```
=> vcsim: apply PCI UnitNumber offset of 7 for ethernet

README.md
We've been using govmomi to great success for quite a while for the vcenterreceiver component of opentelemetry's contrib distribution. Was hoping to that we could be listed as another success story in the notable users of the great library that has been built here https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/vcenterreceiver 🚀 
If there is a process for this let me know, but figured I'd just shout out the great work and usefulness of this library 😄 
Closes:   didn't think an issue was necessary but happy to create one :) 
Feel free to see change here: https://github.com/schmikei/govmomi/tree/notable-user-otel-contrib
[guidelines](https://github.com/vmware/govmomi/blob/main/CONTRIBUTING.md) …
=> Add opentelemetry collector contrib as Notable User in README

vim25/soap/error.go
Check the error chain when checking if error is x509 related. This should be compatible with both golang 1.20 and 1.19
Closes: #https://github.com/vmware/govmomi/issues/3174
Compiles CPI with 1.20 and configures CPI with tlsthumbprint, and the error doesn't appear.
this project
=> fix: check the error chain when validating if it's x509 error

govc/test/datastore.bats, object/datastore.go
When constructing the datastore URL using a *soap.Client, there may be edge cases where VC and ESX schemes differ. Allow using an environment variable to override this instead of assuming homogeneous schemes.
- Update the vcsim datastore bats test to test this.
- Also updated the same bats test to use vcsim instead of just ESX for datastore upload.
- Verified that a client using HTTP to VC (via govmomi.NewClient()) and HTTPS to ESX worked as expected during datastore file upload.
this project
=> Allow picking datastore upload URL scheme by env

.github/workflows/govmomi-release.yaml
Close #3179
According to https://github.com/actions/setup-go/issues/328. Now have to quote '1.20' version unless it will pull golang 1.2 instead
Closes: #https://github.com/vmware/govmomi/issues/3179
this project
=> build: quote golang version in release file to workaround issue in github action

Makefile, gen/.gitignore, gen/Dockerfile, gen/Makefile, gen/README.md, gen/gen.sh
This patch:
* Introduces a cross-arch `./gen/Dockerfile` for generating the vim types.
* Documents the process at `./gen/README.md`.
* Introduces a Makefile target `generate-types` for generating the vim types.
* Enables `./gen/gen.sh` to automatically update the VIM version in `vim25/client.go`.
* Ensures `./gen/rbvmomi/vmodl.db` is downloaded if it does not already exist when generating types.
Closes: `NA`
`make generate-types`
this project
=> chore: Dockerfile & steps for generating types

internal/helpers.go, internal/helpers_test.go, lookup/client_test.go, lookup/simulator/simulator.go, simulator/model.go, simulator/simulator.go, ssoadmin/client.go, ssoadmin/client_test.go, ssoadmin/simulator/simulator.go, sts/client.go, sts/client_test.go, sts/simulator/simulator.go
- For local clients on vCenter, lookup service can be omitted and local Envoy processes can be used instead, along with 'system-' prefixed variants of SSOAdmin/STS. This avoids the need to discover the vCenter SSO domain and avoids an extra round trip.
- Also extends simulator to allow aliasing the same SDK to multiple paths as part of the RegisterSDK() method. Moves vimService, ssoadmin, STS simulators to this model.
- Using an env var with a fallback default to allow testing.
- Existing unit tests
- On VC: created a client pointing at localhost:1080 and verified that lookup service was not used.
- Added unit tests that break lookup service URLs and ensure that ssoadmin/sts clients still work. …
=> Bypass lookup svc for STS and SSOadmin clients

.github/PULL_REQUEST_TEMPLATE.md
The current pull request template has the contribution guidelines on 3 lines. To me, this looks a little sloppy.
I change the line so it it is a single line in both markdown and the html output.
If you prefer it be formatted as a single line without the link pulled out, just let me know.
Heh, describing a change to the PR template in a PR is a little meta.
Before
======
this project
After
=====
---
This is a documentation/github only change
I modified this PR comment to follow the format.
I viewed with a markdown editor
=> Remove spacing in new pull request template contribution checklist item

simulator/datastore.go, simulator/datastore_test.go
Fixed the implementation of `RefreshDatastore` in the VC simulator to set the response field when there is no fault (i.e. happy path) in order to avoid serialization problems.
Closes: #3198
=> vcsim: Fix RefreshDatastore to return a valid response

vim25/soap/client.go, vim25/soap/client_test.go
When passing an endpoint as `https://some.vcenter.tld/` to govc (or soap client), it will consider the leading / as part of the path and not add the `/sdk`.
This leads to errors when consuming vCenter API.
While passing the leading "/" may be desired, I'm not sure if there's a better way to turn this error more intuitive.
This PR also adds some unit tests on ParseURL function
- Added unit tests
- Tested soap.ParseURL with and without the change, and passing the URL as `https://some.vcenter.tld` with and without the …
=> Trim leading slash on soap path

govc/USAGE.md, govc/cluster/module/rm.go, govc/test/cluster.bats
This PR adds a `-file` flag to the `govc cluster.module.rm` command.
Deleting lots of cluster modules takes a long time.
E.g. deleting 10k cluster modules using bash and the current implementation would take ~5 mins. Example command:
```sh
while read -r ID; do govc cluster.module.rm $ID ; done < modules.txt
```
With this PR the following would do the same and only take ~30s:
```sh
govc cluster.module.rm - < modules.txt
```
- extracted all existing modules via `govc cluster.module.ls | awk '{print $2}' > modules.txt`
- ran …
=> govc: Add -file flag to cluster.module.rm to delete a list of cluster modules read from a file

govc/library/import.go
This fixes a dropped `err` variable in `govc/library`.
=> govc/library: fix dropped error

govc/vm/snapshot/tree.go
Explicitly reassign the iteration variable used for listing virtual machine snapshots to fix the `gosec` G601 "Implicit memory aliasing in for loop" error.
=> govc: Fix memory aliasing in for loop (gosec G601)

govc/datacenter/info.go
`govc datacenter.info` is printing the wrong VM count, as it is doing the query based on root folder and not on the used datacenter reference.
This way, with multiple datacenters the count will be always the total of VMs regardless of what datacenter they are, instead of a per dc count.
This PR fixes this count, setting the right property on Containerview to use the datacenter and not the root folder
=> Fix datacenter output on govc

simulator/model.go
When we invoke simulator model's `Create` function, there is no way of passing simulator context and in `NewServiceInstance` function we end up overwriting global registry, as referenced below :
```
func NewServiceInstance(ctx *Context, content types.ServiceContent, folder mo.Folder) *ServiceInstance {
// TODO: This function ignores the passed in Map and operates on the
// global Map.
Map = NewRegistry()
ctx.Map = Map
s := &ServiceInstance{}
s.Self = vim25.ServiceInstance
s.Content = content
Map.Put(s)
```
ref : https://github.com/vmware/govmomi/blob/c63291aa18123977bb7a143222437d37613c9da6/simulator/service_instance.go#L36
We can go around this issue and create our own `ServiceInstance` for a model without overwriting global registry but this also means we are unable to leverage the …
=> [simulator] Introduce separation between NewServiceInstance function invocation & infra creation

govc/vm/clone.go
The fix in https://github.com/vmware/govmomi/pull/1938 may have broken the cloning VM from a template when using the 'cluster' option as shown in #3208 
This fix uses the resource pool from the Cluster when cloning template into a VM.
Closes: #3208 
The fix has been tested towards vSphere 6.3
- No dependent changes
=> Bug #3208 - Clone template fails when using 'cluster' option

go.mod, go.sum, govc/USAGE.md, govc/device/model/tree.go, govc/main.go
This patch introduces the `govc device.model.tree [-backings]` command for printing either the VirtualDevice or VirtualDeviceBackingInfo type hierarchy as a tree.
Closes: `NA`
1. Built `govc` with:
```shell
make -C govc install
```
2. Ran `govc device.model.tree`:
```shell
VirtualDevice
├── VirtualCdrom
├── VirtualController
│   ├── VirtualIDEController
│   ├── VirtualNVDIMMController
│   ├── VirtualNVMEController
│   ├── VirtualPCIController
│   ├── VirtualPS2Controller
│   ├── VirtualSATAController
│   │   └── VirtualAHCIController
│   ├── VirtualSCSIController
│   │   ├── ParaVirtualSCSIController
│   │   ├── VirtualBusLogicController
│   │   ├── VirtualLsiLogicController
│   │   └── VirtualLsiLogicSASController
│   ├── VirtualSIOController
│ …
```
=> govc: Command to print device/backings model as tree

govc/USAGE.md, govc/main.go, govc/test/vm_dataset.bats, govc/vm/dataset/create.go, govc/vm/dataset/entry/get.go, govc/vm/dataset/entry/ls.go, govc/vm/dataset/entry/rm.go, govc/vm/dataset/entry/set.go, govc/vm/dataset/info.go, govc/vm/dataset/ls.go, govc/vm/dataset/rm.go, govc/vm/dataset/update.go, simulator/dataset.go, simulator/snapshot.go, simulator/virtual_machine.go, vapi/internal/internal.go, vapi/simulator/simulator.go, vapi/vm/dataset/dataset.go, vapi/vm/internal/internal.go, vapi/vm/simulator/simulator.go, vcsim/main.go
Implement support for the [VM data sets API](https://developer.vmware.com/apis/vsphere-automation/latest/vcenter/vm/data_sets/) introduced in vSphere 8.0. 
[Data sets](https://core.vmware.com/resource/vsphere-datasets) provide a mechanism to share data between the vSphere management layer (i.e. vCenter and ESX) and the VM guest OS. See the [VMware Guest SDK Programming Guide](https://developer.vmware.com/docs/16962/vmware-guest-sdk-programming-guide/GUID-AEC8BE71-FA22-4A87-8C6F-F4EBE95AA8DE.html) for details on using data sets from within the guest OS of a VM.
Using data sets from within a VM guest OS seems to be out of scope for `govmomi` at the moment:
`govmomi` has a guest `toolbox` sub-project but it is an alternative to the VMware tools daemon. `govmomi` does not have an alternative …
=> Add support for VM data sets

guest/file_manager.go, guest/toolbox/client.go, internal/helpers.go, internal/helpers_test.go, object/datastore.go
- vCenter has a local Envoy process exposed over a Unix socket dedicated for host connectivity.
- During requests that involve traffic to ESX, when the envoy sidecar is in use (localhost:1080) in the VC client, leverage the envoy host gateway.
- Avoid keeping the connection alive since we're only using it for one request to the host. (ie. no connection pool to the host(s) being maintained here)
Note: I think it would make sense to enhance vcsim to support this host gateway socket, but from what I could tell, the existing vcsim tests for things like datastore upload only run vcsim with an ESX - I could not find anything in place to simulate both VC and ESX.
=> Use Envoy sidecar for guest and datastore file transfer.

govc/USAGE.md, govc/about/command.go, govc/device/info.go, govc/emacs/govc.el, govc/license/label.go, govc/session/ls.go, govc/vm/ip.go, govc/vm/option/info.go
=> docs: update govc jq examples with correct case

govc/importx/options.go, govc/importx/options_test.go, govc/importx/ovf.go, govc/importx/spec.go
v0.31.0 changed the json case of generated types, which breaks existing PropertyMapping used in the -options input spec
Fixes #3245
=> fix: case insensitive govc import.ova PropertyMapping

govc/USAGE.md, govc/device/pci/add.go, govc/device/pci/ls.go, govc/flags/env.go, govc/main.go, govc/object/save.go, govc/test/vm.bats, govc/vm/option/info.go, govc/vm/option/ls.go, govc/vm/rdm/attach.go, govc/vm/rdm/ls.go, govc/vm/target/capabilities.go, govc/vm/target/info.go, object/compute_resource.go, object/environment_browser.go, object/virtual_machine.go, scripts/license.sh, simulator/environment_browser.go
vcsim: add EnvironmentBrowser methods and record/replay support
api: add object.EnvironmentBrowser helper methods
govc: add vm.option.ls, vm.target.info and vm.target.cap.ls commands
BREAKING: removed object.VirtualMachine.QueryConfigTarget method
- Use object.VirtualMachine.EnvironmentBrowser().QueryConfigTarget instead
Added new bats tests.
this project
=> vcsim: EnvironmentBrowser improvements

guest/toolbox/client.go, object/datastore.go, vim25/soap/client.go
guest file transfer and ticketed datastore file transfer use direct ESX connections. The connection should be only be used for a single request, ensure this by disabling client side.
=> api: disable HTTP Keep-Alive for direct ESX connections

govc/cli/command.go, govc/extension/setcert.go, govc/host/cert/install.go, govc/importx/archive.go, govc/library/export.go, govc/library/trust/create.go, govc/namespace/service/create.go, govc/session/login.go, govc/vm/change.go, session/cache/session.go, session/manager.go, simulator/feature_test.go, simulator/host_datastore_browser.go, simulator/model.go, simulator/simulator.go, simulator/simulator_test.go, simulator/virtual_machine.go, sts/signer.go, toolbox/command.go, toolbox/command_test.go, toolbox/hgfs/archive.go, toolbox/hgfs/archive_test.go, toolbox/hgfs/server_test.go, toolbox/process/process.go, toolbox/service_test.go, vapi/rest/client.go, vapi/rest/client_test.go, vapi/simulator/simulator.go, vim25/soap/client.go, vim25/soap/json_client_test.go
"io/ioutil" has been deprecated since Go 1.19: As of Go 1.16
this project
=> chore: remove refs to deprecated io/ioutil

vapi/rest/client.go
soap.Client sends OperationID as part of the soap body header.
vapi uses the `X-Request-ID` http header.
=> vapi: add support for OperationID header

simulator/container_virtual_machine.go
It appears that the simulated VM logic is supposed to handle cases when svm (the receiver) is nil (eg. when you spin up a VM without using a backing container. (I think this might have been introduced by fdb4d84763b8b28f3dc94b1a2a0b0f60aae2eb55 )
This would lead to a panic due to the conditional in question attempting to access svm.vm.Runtime.PowerState immediately after.
Inverting the check to return GuestOperationsUnavailable if `svm == nil` seems the simplest way to address this. To my knowledge, Go will short circuit evaluation.
- Used a go workspace, updated a vcsim based unit test involving guest file transfer. Verified that test no longer panicked, but returned a GuestOperationsUnavailable soap fault.
(still trying to …
=> vcsim: Handle prepare guest operations when svm is nil

vim25/soap/client.go
This change adds the ability to check whether a given thumbprint is known to the soap client.
Isolated testing of the implemented func that traverses a map. None of the other thumbprint-related funcs have unit tests, so decided not to add anything new just to iterate over the values of a map.
=> vim25/soap: add ability to check whether a thumbprint is known to the soap client

pbm/client.go
Some additional PBM/SPBM methods where not exposed. This methods should be used by CAPV later to query storage policy per disk, instead of getting the whole list of Entities and iterating over it
Executed some local tests on this method to get the storage profile of virtual disks
=> Add additional PBM methods

simulator/property_collector.go, simulator/property_collector_test.go
This PR fixes RetrievePropertiesEx in vcsim to handle empty property name (like `.`).
Closes: #3275
```bash
$ ./govmomi/vcsim/vcsim &
$ govc object.collect VirtualMachine:vm-55 .
```
=> vcsim: Fix PropertyCollector to handle empty property

simulator/container_host_system.go
This fixes a dropped `err` variable in the `simulator` package.
=> simulator: fix dropped error

object/datastore.go, object/datastore_test.go
Helper to set Datastore InventoryPath and DatacenterPath, needed by NewURL() to compose an upload/download endpoint URL
Fixes #3267
=> api: add object.Datastore.FindInventoryPath

simulator/snapshot.go
Applying the confirmed fix for [RevertToSnapshotTask](https://github.com/vmware/govmomi/pull/2292/files#diff-7720135e571206f9738817ceaa27adc9faf2b64bd649e0d3c42f052b4de8c279R150) to [RemoveSnapshotTask](https://github.com/vmware/govmomi/blob/44d6f8d509be126e200c4a29973d83170357d616/simulator/snapshot.go#L114).
Closes: #3298
Using vcsim:
1. Create a snapshot.
2. Wait for the create snapshot task to complete.
3. Attempt to delete the snapshot.
4. Wait for the remove snapshot task to complete.
=> vcsim: Fix [BUG] vcsim raises TypeError for RemoveSnapshotTask

simulator/esx/performance_manager.go, simulator/performance_manager.go, simulator/vpx/performance_manager.go
This populates the historical intervals based upon the server type.
Currently a real vCenter server has this set with default values, but the simulator has it empty.
```
vcsim 127.0.0.1:9191 &
export GOVC_URL=https://user:pass@127.0.0.1:9191/sdk GOVC_INSECURE=true
govc metric.interval.info
m.pm.HistoricalInterval:  0
load HistoricalInterval
m.pm.HistoricalInterval (final):  0
```
```
vcsim 127.0.0.1:9191 &
export GOVC_URL=https://user:pass@127.0.0.1:9191/sdk GOVC_INSECURE=true
govc metric.interval.info
performance/manager/HistoricalInterval
m.pm.HistoricalInterval:  0
load HistoricalInterval
m.pm.HistoricalInterval (final):  4
ID:                   300
Enabled:            true
Interval:           5m
Available Samples:  288
Name:               Past Day
Level:              1
ID: …
```
=> Add default Historical Intervals to the simulator

pbm/simulator/simulator.go
This PR adds the PbmQueryAssociatedProfiles method, which is required to test CAPV machine provisioning with vcsim.
After this change will merge, it will be possible to:
- start using vcsim as a vCenter replacement while running CAPV e2e tests
- use vcsim to stress test CAPV without the need of real infrastructure
- use vcsim to improve the speed of CAPV local development iterations
cc @randomvariable @sbueringer @chrischdi 
=> add PbmQueryAssociatedProfiles method

vapi/rest/client.go, vapi/rest/client_test.go
Closes: #3309
During the implementation of https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2535 we have realized it is hard to check what was the error returned from the rest/http layer of vAPI.
This PR creates a util function that can be used to check if a returned error from rest contains a specific http Status code.
Closes: #3309
Extended current rest Session test to also do an invalid internal call and check the returned error
=> fix: expose util for rest status return

cns/types/types.go
CNS added separate fault CnsSnapshotCreatedFault for cases where snapshot creation is completed, but post-processing failed (like failed to update db). We wanted to handle this fault in CSI driver, so adding this new CNS fault in this repo.
=> Changes to add CNS fault CnsSnapshotCreatedFault

cns/types/types.go
Changes to fix xml tag used for SnapshotId in CnsSnapshotCreatedFault
Simulated CnsSnapshotCreatedFault manually and verified CreateSnapshot API's response using client_test.go.
With tag "snapshotId", we are getting snapshotId as "" in the fault.
```
client_test.go:372: Failed to create snapshots: fault=(*types.LocalizedMethodFault)(0xc0004ad300)({
DynamicData: (types.DynamicData) {
},
Fault: (types.CnsSnapshotCreatedFault) {
CnsFault: (types.CnsFault) {
BaseMethodFault: (types.BaseMethodFault) <nil>,
Reason: (string) (len=24) "Snapshot already created"
},
VolumeId: (types.CnsVolumeId) {
DynamicData: (types.DynamicData) {
},
Id: (string) (len=36) "357c83c0-467a-4228-a736-81b2b24a7e40"
},
SnapshotId: …
```
=> Changes to fix xml tag used for SnapshotId in CnsSnapshotCreatedFault

vcsim/main.go
This PR fixes `-method-delay` option to delay task state updates
Closes: #3323
```bash
$ vcsim -method-delay "PowerOff:10000"
$ govc vm.power -off -force DC0_H0_VM0
Powering off VirtualMachine:vm-55... OK
$ govc tasks | grep PowerOff
PowerOff                                 vm-55                          vcsim                           12:26:39  12:26:39         - running [ 0% Task:task-66]
$ govc tasks | grep PowerOff
PowerOff                                 vm-55                          vcsim                           12:26:39  12:26:39 …
```
=> vcsim: Fix -method-delay option to update task states

find/finder.go, govc/object/collect.go, govc/object/find.go, object/example_test.go, object/task.go, pbm/client_test.go, pbm/simulator/simulator_test.go, property/collector.go, property/collector_test.go, property/example_test.go, property/filter.go, property/match.go, property/match_test.go, property/property_test.go, property/wait.go, property/wait_test.go, simulator/property_collector_test.go, simulator/session_manager_test.go, task/wait.go, vapi/namespace/simulator/simulator.go, vapi/tags/example_test.go, view/container_view.go, view/example_test.go
This patch introduces Ex variants for many of the property collector types/methods to take advantage of the remote API DestroyPropertyFilter. Now it is possible to use a single property collector for waiting for updates and remove previously added filters.
```
BREAKING: The semantics around the helper functions in the
property package have changed. Please review any
code that calls this package to ensure it is
compatible with the new behaviors.
```
Closes: `NA`
=> api: WaitForUpdatesEx & DestroyPropertyFilter

vim25/soap/client.go
When reviewing data from vCenter for troubleshooting and analysis it is hard to distinguish where the request comes from. Having the govmomi and golang version is helpful. As we now have increasing number of go clients we need more data.
The go debug value produce din tests is like
"__debug_bin2861234748 govmomi/0.31.0 (go1.20.5;darwin;arm64)"
Add the executable name to the default user agent 
Closes: #3339 
- [ X] New feature (non-breaking change which adds functionality)
=> Self identify the executable making calls to vCenter

vim25/mo/retrieve.go
A previous change reverted behavior that ignored indexed property updates in favor of a panic. While we don't implement persistence for partial updates, some consumers rely on this behavior to test property collector updates on specific fields.
This change reverts a03f4735570027d2e6e2bc9cb7584a0af19f9353q to the previous behavior allowing downstream consumers to rely on this field for testing PC updates until full support for indexed fields is implemented.
Closes: #3349
=> Re-enable PC updates for indexed properties

simulator/virtual_machine.go, simulator/virtual_machine_test.go
This patch updates the simulator to update a VM's `config.changeVersion` and `config.modified` if the VM is reconfigured.
Closes: `NA`
=> api: Simulate vm config.changeVersion and config.modified

cns/types/types.go
Add "AggregatedSnapshotCapacityInMb" in  "CnsBlockBackingDetails" struct.
- [ X] New feature (non-breaking change which adds functionality)
Run unit test, and can see this new field is available in the QueryVolume result.
client_test.go:244: Successfully Queried Volumes. queryResult: &types.CnsQueryResult{
{
Id: "1aea2f18-d51c-4c67-a793-3c03d587100a",
},
DatastoreUrl:    "ds:///vmfs/volumes/65b980ec-15046ef0-c7e0-0200aec77050/",
Name:            "pvc-901e87eb-c2bd-11e9-806f-005056a0c9a0", …
=> Add "AggregatedSnapshotCapacityInMb" to cnstype

cns/client_test.go, cns/types/types.go
This change is to add  "AggregatedSnapshotCapacityInMb" to CnsSnapshotCreateResult and CnsSnapshotDeleteResult.
- [x ] New feature (non-breaking change which adds functionality)
Run unit test. In the unit test result, field  "AggregatedSnapshotCapacityInMb" is available in  CnsSnapshotCreateResult and CnsSnapshotDeleteResult
```
client_test.go:355: Creating snapshot using the spec: []types.CnsSnapshotCreateSpec{
{   
Id: "1cf88bdc-0b1d-4198-b995-50319ed6865d",
},
Description: "example-vanilla-block-snapshot",
},      
}       
client_test.go:379: snapshotCreateResult: &types.CnsSnapshotCreateResult{
CnsSnapshotOperationResult: types.CnsSnapshotOperationResult{},
Snapshot: …
```
=> Add  "AggregatedSnapshotCapacityInMb" to CnsSnapshotCreateResult and CnsSnapshotDeleteResult.

simulator/virtual_machine.go, simulator/virtual_machine_test.go
This patch updates the simulator to correctly handle VM hardware upgrades so the property `summary.config.hwVersion` is updated when the hardware is upgraded.
Closes: NA
=> fix: Update summary.config.hwVersion in simulator

cns/client_test.go, cns/cns_util.go, cns/types/types.go
Add `ServiceLocator` type to `CnsVolumeRelocateSpec` to facilitate cross-vCenter volume migration
1. Deployed two vCenters and enabled vCenter FSS to support cross-vCenter volume migration.
2. Ran the tests for same vCenter migration and cross-vCenter migration after setting the appropriate environment variables.
3. Ran the unit tests for volume migrations and verified that both tests were successfully executed.
Environment variables set:
```
export CNS_VC_URL=https://<src-vc-user>:<src-vc-password>@<src-vc-ip>
export CNS_DATACENTER=VSAN-DC …
```
=> Add service locator to CNS RelocateVolume spec

go.mod, go.sum, govc/USAGE.md, govc/test/vm.bats, govc/vm/create.go, simulator/cluster_compute_resource.go, simulator/environment_browser.go, simulator/esx/host_config_info.go, simulator/host_system.go, simulator/virtual_machine.go, simulator/virtual_machine_test.go, vim25/types/hardware_version.go, vim25/types/hardware_version_test.go
This patch enhances the simulator's support for the upgradeVm API as well as introduces the helper type `vim25/types.HardwareVersion` for parsing and comparing VMX hardware versions.
Closes: NA
```
$ go test -v -count 1 -run 'TestUpgradeVm' ./simulator
=== RUN   TestUpgradeVm
=== RUN   TestUpgradeVm/InvalidPowerState
=== RUN   TestUpgradeVm/InvalidState
=== RUN   TestUpgradeVm/InvalidState/MaintenanceMode
=== RUN   TestUpgradeVm/InvalidState/Template
=== RUN   TestUpgradeVm/InvalidState/LatestHardwareVersion
=== RUN   TestUpgradeVm/NotSupported
=== RUN …
```
=> vcsim: Enhanced sim support for upgrade VM

lookup/client.go
currently, lookup client by default fetches the uri from "config.vpxd.sso.sts.uri" value if service content set . With envoy sidecar enabled, this MR is to first check for envoy sidecar url if present and use the same.
=> fix: lookup client to use envoy sidecar url if enabled

govc/about/cert.go, govc/test/cli.bats, object/host_certificate_info.go, vim25/soap/client.go
vSphere in general is moving from SHA1 to SHA256 based TLS certificate thumbprints. This change allows use of SHA256 thumbprint when connecting to vCenter.
govc: the about.cert command '-thumbprint' flag now outputs SHA256 instead of SHA1
=> Add support for SHA256 thumbprint based vCenter authentication

govc/task/create.go, govc/task/set.go, govc/test/extension.bats, govc/test/tasks.bats, simulator/extension_manager.go, simulator/model.go, simulator/registry.go, simulator/task.go, simulator/task_manager.go
- needed an easier way to control Task state when testing, so added TaskManager.CreateTask and Task methods for updating state (wcpsvc also uses these methods)
- in real VC, CreateTask requires a taskID from an Extension, so went ahead and added basic ExtensionManager support too (and with this enabled govc extension bats)
=> vcsim: add ExtensionManager and TaskManager.CreateTask support

lookup/client.go, lookup/client_test.go
EndpointURL returns FQDN:443 as endpoint url even if envoy sidecar enabled. This MR updates to bypass lookup service if envoy sidecar enabled.
=> fix: endpoint url to bypass lookup service if envoy sidecar enabled

govc/vm/snapshot/tree.go
golang builtin println is meant for debugging only and prints always to stderr
Print json to stdout instead of stderr.
Closes: https://github.com/vmware/govmomi/issues/3392
Run command:
`govc snapshot.tree -json -vm $vm 2> /dev/null`
Obverve json appearing in the terminal.
=> govc: snapshot.tree json output to stdout

govc/USAGE.md, govc/task/recent.go, govc/test/object.bats, govc/test/tasks.bats, govc/test/vcsim.bats, simulator/event_manager.go, simulator/event_manager_test.go, simulator/history_collector.go, simulator/property_collector.go, simulator/task_manager.go, simulator/task_manager_test.go
refactor portions of 'EventHistoryCollector' to 'HistoryCollector' for use with 'TaskHistoryCollector'
TaskHistoryCollector provides a way to collect Task history beyond the 10 minute max of the 'RecentTask' property.
And unlike 'RecentTask', can filter based on Task state and collect tasks of child entities.
govc: add history flags to 'tasks' command
Closes #2567
=> vcsim: add TaskHistoryCollector support

object/task.go, property/wait.go
Remove deprecation for task.Wait and task.WaitForResult as per discussion in https://github.com/vmware/govmomi/issues/3394
Closes: #3394
Not test, it is only a godoc change
=> Remove deprecation for task.Wait and task.WaitForResult

govc/test/vcsim.bats, simulator/finder_test.go, simulator/resource_pool.go
=> fix: vcsim: re-parent children in ResourcePool.Destroy

vim25/client.go, vim25/soap/client.go
This method only changes fields in soap.Client
Moving it allows UseServiceVersion to be called after NewServiceVersion.
=> api: move vim25.Client.UseServiceVersion to soap.Client

.goreleaser.yml
Enable rpm package build for several archs.
Closes: #3404 
=> build(deps): enable rpm builds and add archs

property/collector.go, property/collector_test.go, property/example_test.go, simulator/property_collector.go, simulator/virtual_machine.go, vim25/mo/retrieve.go
'RetrieveProperties' is deprecated since 4.1
Use RetrievePropertiesEx + ContinueRetrievePropertiesEx to collect in batches.
=> api: change RetrieveProperties to collect results in batches

.goreleaser.yml
Previously, we enabled rpm builds. However, only 'govc' was added. Let's add 'vcsim', too, as the package name 'govmomi' implies it.
Closes: #3413
=> build(deps): add vcsim to rpm

govc/USAGE.md, govc/namespace/create.go, govc/namespace/info.go, govc/namespace/ls.go, govc/namespace/update.go, govc/namespace/vmclass/create.go, govc/namespace/vmclass/info.go, govc/namespace/vmclass/ls.go, govc/test/namespace.bats, vapi/namespace/simulator/simulator.go
Including a few other minor changes for the new set of namespace commands.
=> govc: add default output formatting for namespace commands

govc/USAGE.md, govc/library/evict.go, govc/library/info.go, govc/test/library.bats, vapi/library/library.go, vapi/library/library_item.go, vapi/simulator/simulator.go
Closes: #3400
This change exposes the vSphere API to evict the subscribed content library to free up storage capacity.
The vSphere API evicts the cached content of an on-demand subscribed library. This operation allows the cached content of a subscribed library to be removed to free up storage capacity. This operation will only work when a subscribed library is synchronized on-demand.
Closes: #3400
Ran the govc tests locally
acharyasreej@acharyasreY5WYK test % ./library.bats
library.bats
✓ library
✓ library.import
✓ library.deploy
✓ library.clone ovf
✓ library.deploy vmtx
✓ library.vmtx.info
✓ library.pubsub
✓ library.subscriber example
✓ library.create.withpolicy
✓ library.findbyid
✓ library.trust
✓ library.session
✓ …
=> api: Expose vSphere API to evict subscribed content library

govc/extension/info.go, govc/test/extension.bats, simulator/extension_manager.go
d9af2a2 added simulator.ExtensionManager but did not included this method.
govc: use ExtensionManager.FindExtension when given a single KEY arg, rather than fetch the entire list.
Closes #2644
=> vcsim: add ExtensionManager.FindExtension method

vapi/library/library_item_updatesession_file.go
Add the optional SSLCertificate field to TransferEndpoint in content library API so it can be specified to probe remote transfer endpoint or upload file from remote endpoint by pull. The field is already in the ProbeResult as an optional field.
Closes: #3420
=> api: add SSLCertificate to TransferEndpoint in content library API

govc/USAGE.md, govc/library/import.go, govc/test/library.bats, vapi/library/library_item_updatesession_file.go
This PR updates the `AddLibraryItemFileFromURI` API with an optional [LibraryItemFileChecksumInfo](https://developer.vmware.com/apis/vsphere-automation/latest/content/data-structures/Library/Item/File/ChecksumInfo/) that the server can use to verify the uploaded library file content. 
It also updates the govc `library.import` command accordingly with the new checksum arguments (`-c` for checksum value & `-a` for checksum algorithm).
```console
$ govc library.import -pull checksum-test https://releases.ubuntu.com/14.04.6/ubuntu-14.04.6-server-amd64.iso
$ govc library.ls checksum-test/
/checksum-test/ubuntu-14.04.6-server-amd64
$ govc library.import -a=foo -pull checksum-test https://releases.ubuntu.com/14.04.6/ubuntu-14.04.6-server-amd64.iso
govc: invalid checksum algorithm: foo
$ govc …
```
=> api: add checksum validation in Content Library update session file API

pbm/simulator/simulator.go
Add PbmCheckCompatibility method in pbm simulator code similar to PbmCheckRequirements.
This simulator function is getting called from the vSphere CSI plugin unit tests. Without this function following error is observed.
```
“failed to find datastore compatibility with storage policy ID <storage-policy-ID>. Error: ServerFaultCode: PbmPlacementSolver:placementSolver does not implement: PbmCheckCompatibility”
```
Unit tests in vSphere CSI plugin using Storage Policy were using workaround till now, so PbmCheckCompatibility function in simulator was not getting called. But to test the relevant code in CSI, we are planning to remove this workaround. So, we need to implement simulated function …
=> Add PbmCheckCompatibility method in pbm simulator

govc/USAGE.md, govc/cluster/override/change.go, govc/datastore/cluster/change.go, govc/dvs/portgroup/spec.go, govc/host/autostart/add.go, govc/host/vnic/service.go, govc/importx/spec.go, govc/vm/change.go, govc/vm/create.go, govc/vm/disk/create.go
Make use of generated enum lists added in #3426
=> chore: govc: use generated enum lists

vapi/vcenter/consumptiondomains/associations/associations.go, vapi/vcenter/consumptiondomains/consumptiondomains_test.go, vapi/vcenter/consumptiondomains/simulator/simulator.go, vapi/vcenter/consumptiondomains/zones/zones.go, vcsim/main.go
Adding bindings for the [consumption domains API](https://developer.broadcom.com/xapis/vsphere-automation-api/latest/vcenter/consumption_domains/) (a.k.a. vSphere Zones)
Related: https://github.com/hashicorp/terraform-provider-vsphere/issues/2185
Tested against a live VC.
Created a simulator for the new endpoints and added a unit test that verifies the contract.
=> feat: Bindings for vSphere Zone APIs

govc/library/create.go, vapi/internal/internal.go, vapi/library/example_test.go, vapi/library/library.go, vapi/library/library_item_storage.go
This PR adds a new set of APIs to retrieve library item storage, as defined in https://developer.broadcom.com/xapis/vsphere-automation-api/v8.0U1/content/library/item-storage/
Closes: N/A
Consumed this API in an operator running in the internal Supervisor cluster and verified the expected Storage URI retrieved for each file available in a content library item:
```
fileInfo:
- cached: true
name: ubuntu-20.04-vmservice-v1alpha1.20210528.ovf
sizeInBytes: "10552"
storageURI: ds:///vmfs/volumes/... <redacted>
version: "1"
- cached: true
name: ubuntu-20.04-vmservice-v1alpha1.20210528-disk1.vmdk
sizeInBytes: "1426063360"
storageURI: ds:///vmfs/volumes/... <redacted>
version: "1"
```
=> api: Add library item storage APIs

nfc/lease.go, nfc/lease_updater.go
With this change we are recording the SSL thumbprint for the host the device URL refers to. This is done so that clients of the nfc wrapper can perform their own SSL verification using the recorded thumbprint if necessary. The thumbprint is stored in the FileItem struct, but the New constructor is not modified so as not to introduce any breaking changes.
Please note that the thumbprint is recorded only for the import case (when deploying an OVF in my case) since that is the only necessary path for our internal usage.
Closes: `NA`
I have performed isolated testing against both a vCenter and a ESXi host. I have observed that the thumbprint is recorded and accessible through the `FileItem` struct as expected.
[guidelines]: …
=> nfc: Record the SSL thumbprint for the host the (device) URL refers to

govc/object/collect.go, govc/test/object.bats, object/extension_manager_test.go, object/virtual_machine_property_test.go, simulator/extension_manager.go, simulator/property_collector.go, simulator/property_filter.go, simulator/virtual_machine.go, vim25/mo/retrieve.go, vim25/mo/type_info.go, vim25/mo/type_info_test.go
PropertyCollector supports use of index (unique key) to collect a single array element. Further, a property path may also be applied to the given element.
=> vcsim: add PropertyCollector index support

govc/USAGE.md, govc/device/cdrom/insert.go, govc/flags/datastore.go, govc/library/info.go, govc/test/library.bats, govc/vm/create.go, vapi/library/finder/path.go, vapi/library/library_item_storage.go, vapi/simulator/simulator.go
govc: support Content Library iso files for cdrom backing
The 'device.cdrom.insert' and 'vm.create -iso' commands can now a URL with 'library' scheme to back a cdrom device from a Content Library.
api: refactor 'library.info -L' functionality into library PathFinder helper.
Fixes #3213
=> vcsim: add library item storage API support

govc/vm/disk/change.go
PR #3424 switched from the deprecated CapacityInKB field to CapacityInBytes. That PR focus was to fix an issue with the simulator, but broke against real vCenter. Just leaving CapacityInKB as-is makes vCenter happy again.
Fixes #3464
=> fix: govc vm.disk.change should only modify CapacityInBytes

govc/USAGE.md, govc/namespace/create.go, govc/namespace/flag.go, govc/namespace/info.go, govc/namespace/update.go, govc/storage/policy/info.go, govc/storage/policy/ls.go, govc/test/namespace.bats, govc/vm/create.go, pbm/pbm_util.go, vapi/namespace/namespace.go
api: add pbm.DatastoreMap for finding compatible Datastores
- add pbm.ProfileMap for finding storage profiles by name
govc: add vm.create '-profile' and '-place' flags
api: add storage_specs field to Namespace related structures
govc: add '-storage' flag to namespace.create and namespace.update commands
- The '-cluster', '-library' and '-storage' flags can be specified by name, rather than ID
- The namespace.info command outputs cluster, library and storage by name, rather than ID
=> Add storage profile related api and govc helpers

object/option_value_list.go, object/option_value_list_test.go
This patch introduces the type `OptionValueList` in the `object` package. This new type simplifies working with `[]vimtypes.BaseOptionValue` properties such as ExtraConfig.
Closes: `NA`
```shell
=== RUN   TestOptionValueList
=== RUN   TestOptionValueList/OptionValueListFromMap
=== RUN   TestOptionValueList/OptionValueListFromMap/a_nil_map_should_return_nil
=== RUN   TestOptionValueList/OptionValueListFromMap/a_map_with_string_values_should_return_OptionValues
=== RUN   TestOptionValueList/OptionValueListFromMap/a_map_with_values_of_varying_numeric_types_should_return_OptionValues
=== RUN   TestOptionValueList/OptionValueListFromMap/a_map_with_pointer_values_should_return_OptionValues
=== RUN   TestOptionValueList/Get
=== RUN …
```
=> api: OptionValueList helper

govc/USAGE.md, govc/storage/policy/create.go, govc/test/storage.bats
New '-z' flag enables Zonal topology for multi-zone Supervisor
Uses the sub profile as created by the H5 UI, see for example:
```
govc storage.policy.info -json wcp-zonal | jq .policies[].profile.constraints.subProfiles
```
```json
[
{
"name": "Consumption domain",
"capability": [
{
"id": {
"namespace": "com.vmware.storage.consumptiondomain",
"id": "StorageTopology"
},
"constraint": [
{
"propertyInstance": [
{
"id": "StorageTopologyType",
"value": "Zonal"
}
]
}
]
}
]
}
]
```
=> govc: add storage.policy.create zonal option

gen/gen_from_vmodl.rb, gen/vim_wsdl.rb, govc/USAGE.md, govc/host/cert/info.go, govc/host/tpm/info.go, govc/host/tpm/report.go, govc/library/trust/info.go, govc/main.go, govc/object/collect.go, govc/object/save.go, govc/test/host.bats, govc/test/object.bats, object/host_certificate_info.go, object/host_certificate_manager.go, object/host_system_test.go, simulator/customization_spec_manager.go, simulator/esx/host_config_info.go, simulator/esx/host_storage_device_info.go, simulator/esx/host_system.go, simulator/host_certificate_manager.go, simulator/host_system.go, simulator/model.go, simulator/property_collector.go, vcsim/main.go, vim25/mo/mo.go, vim25/types/byte_slice.go, vim25/types/byte_slice_test.go, vim25/types/helpers.go, vim25/types/helpers_test.go, vim25/types/types.go
Go's encoding/xml package and vCenter marshal '[]byte' differently:
Go encodes the entire array in a single xml element, for example:
```xml
<foo>
<bar>hello</bar>
</foo>
```
vCenter encodes each byte of the array in its own xml element, example with same data as above:
```xml
<foo>
<bar>104</bar>
<bar>101</bar>
<bar>108</bar>
<bar>108</bar>
<bar>111</bar>
</foo>
```
This behavior is hardwired, see the xml/encoding source for the handful of []byte special cases along the lines of:
```go
if reflect.Slice && slice element type == reflect.Uint8
```
While govmomi maintains a fork of Go's xml/encoding package, we prefer to further diverge.
Proposed solution is to use a 'ByteSlice' type that implements xml marshaling as vCenter does,
but otherwise behaves just as `[]byte` does.
Commits that …
=> fix: xml marshal byte array fields as vCenter does

simulator/tenant_manager_test.go, simulator/vpx/service_content.go
* Tests were skipped to support older clients (<6.9).  Since supported clients have support for TenantManager, unskipped the test and removed the OldClients test.
- [ *] Bug fix (non-breaking change which fixes an issue)
- [ x] Ran `go test -v -test.name=TestTenant` which passed.
- [ x] Ran `make test` which failed on `TestHostContainerBacking` because I don't have docker installed(?).
- [ x] I have added tests that prove my fix is effective or that my feature works
- [ x] New and existing unit tests pass locally with my changes
=> Re-enable TenantManager in vcsim

govc/USAGE.md, govc/datastore/disk/extend.go, object/virtual_disk_manager.go, simulator/virtual_disk_manager.go, simulator/virtual_disk_manager_test.go
Adding a binding for `extendVirtualDisk` on `VirtualDiskManager`.
https://github.com/hashicorp/terraform-provider-vsphere/issues/851
Extended the tests for `virtual_disk_manager.go` with new scenarios that cover
1.[POSITIVE] Extending a disk
2.[NEGATIVE] Attempting to shrink a disk
3.[NEGATIVE] Attempting to extend a disk that does not exist
The simulation for virtual disks did not include metadata for the disk size.
I've modified it so that it writes the size value (in KB) in the file itself.
Manually verified the same scenarios on a real VMDK.
=> api: Add ExtendVirtualDisk method on VirtualDiskManager

gen/vim_wsdl.rb, vim25/types/types.go
This is needed for the use case of setting CoresPerNumaNode to '0'.
=> api: change CoresPerNumaNode to a pointer type

vmdk/disk_info.go, vmdk/disk_info_test.go, vmdk/import.go, vmdk/import_test.go
This patch introduces the helper function GetVirtualDiskInfoByUUID for getting the capacity and size information for a virtual disk with a provided UUID.
Closes: `NA`
```shell
$ go test -v -count 1 -run 'TestGetVirtualDiskInfoByUUID' ./vmdk
=== RUN   TestGetVirtualDiskInfoByUUID
=== RUN   TestGetVirtualDiskInfoByUUID/w_cached_properties
=== RUN   TestGetVirtualDiskInfoByUUID/w_cached_properties/diskUUID_is_empty
=== RUN   TestGetVirtualDiskInfoByUUID/w_cached_properties/no_matching_disks
=== RUN   TestGetVirtualDiskInfoByUUID/w_cached_properties/one_disk_w_VirtualDiskFlatVer2BackingInfo
=== RUN   TestGetVirtualDiskInfoByUUID/w_cached_properties/one_disk_w_VirtualDiskSeSparseBackingInfo
=== RUN …
```
=> api: GetVirtualDiskInfoByUUID for getting capacity/size info

vmdk/disk_info.go, vmdk/disk_info_test.go
This patch adds a simulator test for GetVirtualDiskInfoByUUID. I merged https://github.com/vmware/govmomi/pull/3482 without adding these changes, but they _were_ part of my local testing recorded in that PR description, so please refer to https://github.com/vmware/govmomi/pull/3482 for a full description.
Closes: `NA`
See https://github.com/vmware/govmomi/pull/3482
=> api: Add simulator test for GetVirtualDiskInfoByUUID

simulator/cluster_compute_resource.go, simulator/cluster_compute_resource_test.go
Closes: #3485
We are using vcsim for some workflows, and we need to simulate checking the DRS automation cluster attribute.
We need the following to be supported / reflected on VCSim:
```
clusterSpec1 := types.ClusterConfigSpecEx{
DrsConfig: &types.ClusterDrsConfigInfo{
Enabled:           types.NewBool(true),
DefaultVmBehavior: types.DrsBehaviorFullyAutomated, // Set DRS to fully automated
},
DasConfig: &types.ClusterDasConfigInfo{
Enabled: types.NewBool(true),
},
}
task1, err := cl1.Reconfigure(ctx, &clusterSpec1, false)
```
[guidelines]: …
=> vcsim: Add support for DRS automation levels

.github/workflows/codeql-analysis.yml
CodeQL is reporting errors. I have simplified and modified the workflow configuration much like I recently did for the `terraform-provider-vsphere`.
Note that the actions now use the `@<commit_hash>` vs arbitrary major version (e.g. @v3).
=> chore: fix codeql

performance/manager.go
This pull request exports the `Unit` field in the `MetricSeries` struct within the performance package and adds a corresponding JSON tag. This change allows for external access to the `Unit` field,
Closes: #3494
outside the performance package
=> Exporting Unit field in MetricSeries struct for external use. Closes issue#3494.

govc/vm/create.go, object/virtual_device_list.go
Adds support for creating SATA controllers.
Closes: #1219
```sh
Running tool: /usr/local/bin/go test -timeout 30s -run ^TestCreateSATAController$ github.com/vmware/govmomi/object
ok  	github.com/vmware/govmomi/object	(cached)
```
=> api: add sata controller

govc/vm/check/compat.go, govc/vm/check/config.go, govc/vm/check/flag.go, govc/vm/check/relocate.go, object/vm_compatability_checker.go, object/vm_provisioning_checker.go
Use the CheckTestType enum as the testType arg type instead of a string in the VmCompatibilityChecker and VmProvisioningChecker functions.  The req task structs end up getting auto generated using the string type so we need to do a little unfortunate conversion.
Add check test type param to the govc commands
=> api: use CheckTestType in compat and provisioning checkers

ovf/parser.go, ovf/parser_test.go
This PR implements a more-robust parser designed to parse the `capacityAllocationUnits` field of the `DiskSection` of an OVF Envelope and return the number of equivalent bytes. This parser operates on a restricted form of the ABNF grammar defined in DSP0004.
=> implement capacityAllocationUnits parser

govc/test/import.bats, ovf/importer/spec.go, simulator/ovf_manager.go, simulator/virtual_machine.go
PR #3427 changed to using generated enum lists in various govc commands.
This also changed the default DiskProvisioning value from "flat" to "monolithicSparse",
which results in a DeviceUnsupportedForVmPlatform fault when importing.
This change restores the default to "flat".
The default values for IPProtocol and IPAllocationPolicy had not changed,
but this commit explicitly sets their values rather than using first element of the generated list.
Fixes #3483
vcsim: add ovf DiskProvisioning validation
=> fix: restore govc import.spec DiskProvisioning default value

govc/task/create.go, govc/test/tasks.bats, simulator/task.go
PR #3451 changed mo.ApplyPropertyChange() to panic() on invalid property path. CancelTask had such a property for TaskInfo, 'canceled'. Fixed to 'cancelled' and adds test coverage for the CancelTask method.
Fixes #3506
=> vcsim: fix panic in CancelTask

alarm/manager.go, govc/USAGE.md, govc/alarm/create.go, govc/alarm/info.go, govc/alarm/rm.go, govc/alarm/state.go, govc/events/command.go, govc/events/post.go, govc/flags/datacenter.go, govc/main.go, govc/object/save.go, govc/test/alarms.bats, govc/test/events.bats, simulator/alarm_manager.go, simulator/event_manager.go, simulator/model.go, simulator/registry.go, simulator/vpx/alarm_manager.go
vcsim: add AlarmManager
govc: add alarm commands
api: add alarm package with helpers for AlarmManager and Alarms
govc: add event.post command
fix: govc: output Message field for 'EventEx' types
=> Add vCenter Alarm support

govc/test/vcsim.bats, property/collector.go, property/example_test.go, property/wait.go, simulator/property_collector.go, simulator/property_collector_test.go
In the PR #3331 refactor WaitOptions was changed to pass by value, rather than reference.
The Truncated value needs to be propagated from WaitForUpdatesEx response to the caller.
Fixes #3501
vcsim: implement WaitForUpdatesEx pagination support
Default [WaitOptions.MaxObjectUpdates](https://dp-downloads.broadcom.com/api-content/apis/API_VWSA_001/8.0U3/html/ReferenceGuides/vmodl.query.PropertyCollector.WaitOptions.html) default to 100 as real vCenter does.
=> fix: govc object.collect truncation

govc/USAGE.md, govc/session/login.go, govc/test/session.bats, session/manager.go, simulator/session_manager.go
Helper method for calling [vim.SessionManager.impersonateUser](https://dp-downloads.broadcom.com/api-content/apis/API_VWSA_001/8.0U3/html/ReferenceGuides/vim.SessionManager.html#impersonateUser)
govc: add session.login '-as' flag to impersonate user
vcsim: add SessionManager.ImpersonateUser method
Closes #3507
=> api: add session.Manager.ImpersonateUser method

eam/types/enum.go, eam/types/types.go, gen/gen.sh
This patch updates the generated types for eam to include "authenticationSchema" in AgentConfigInfo.
An new parameter called "authenticationSchema" has been added to the
AgentConfigInfo in the EAM API. This parameter is used add an option for authentication scheme in agent config to access OVF urls.
Closes: #3521 
The HooksHookInfo struct is updated to SolutionsHookInfo. 
and ArrayOfHooksHookInfo struct is updated to ArrayOfSolutionsHookInfo.
This might break existing things.
@akutz @dougm 
Relied on GitHub actions for testing.
=> api: update eam bindings to include authentication schema with eam-vcenter build 24075398

object/datacenter.go, object/datacenter_test.go
The {vm,host,datastore,network} folders are always relative to a Datacenter InventoryPath. However, the Datacenter.Folders method was using the Datacenter name, rather than InventoryPath.
Fixes #3523
=> fix: use complete InventoryPath in Datacenter.Folders

vim25/json/discriminator.go, vim25/types/json_test.go
This patch fixes a panic that occurred when encoding nil interface pointers to JSON using the vimtype JSON encoder.
Closes: `NA`
```
go test -v -count 1 -run '^TestSerialization$/^ConfigSpec$'  ./vim25/types
```
=> api: Fix panic when encoding nil iface ptrs to JSON

vim25/types/helpers.go, vim25/types/helpers_test.go
This patch adds a ToString helper function for invoking on any vim type. If the specified value is a primitive type, the returned string is generated using Sprintf. Otherwise the returned string is created first by attempting to marshal the data using the vimtype JSON encoder, and if that fails, the stdlib JSON encoder. If that fails, then `fmt.Sprintf("%v")` is used.
Closes: `NA`
```shell
go test -v -count 1 -run '^TestToString$' ./vim25/types
```
The following screenshot also demonstrates there is 100% code coverage for this new function:
=> api: ToString for vim types

govc/USAGE.md, govc/datastore/create.go
Closes: #3519
govc: Add support for providing size while we create a VMFS datastore
Tried to create a VMFS datastore without size argument in govc cli, so that it takes the entire size of disk into consideration(default case)
`go run main.go datastore.create -type VMFS -name vmfs61 -version 6 -disk eui.b8fa2f975ecc490ea090a46404568540 ocsqe-virt07.lab.eng.blr.redhat.com`
Tried to create a VMFS datastore with some size in govc cli
`go run main.go datastore.create -type VMFS -name vmfs61 -version 6 -disk eui.b8fa2f975ecc490ea090a46404568540 -size …
=> govc: Add '-size' flag to datastore.create

cns/client_test.go, cns/types/types.go
Add BackingDiskPath to BackingObjectDetails
Added a unit test and it is passing.
Unit testing logs:
```
client_test.go:316: Calling QueryVolume using queryFilter: types.CnsQueryFilter{
VolumeIds: []types.CnsVolumeId{
{
Id: "2cb3e6b7-3275-411f-9eaa-7b508572ea5f",
},
},  
Names:                        nil,
ContainerClusterIds:          nil,
StoragePolicyId:              "",
Datastores:                   nil,
Labels:                       nil,
ComplianceStatus:             "",
DatastoreAccessibilityStatus: "",
Cursor:                       (*types.CnsCursor)(nil),
HealthStatus:                 "",
}       
client_test.go:322: Successfully Queried Volumes. queryResultBackingDiskPathTest: …
```
=> Add BackingDiskPath to BackingObjectDetails

simulator/simulator.go, simulator/virtual_machine.go, simulator/virtual_machine_test.go
This patch adds support for "encrypting", "recrypting", and "decrypting" VMs in vC Sim. Please note, no encryption is actually used, and this change only impacts the state machine semantics. For example, if a VM is reconfigured to be encrypted, then retrieving the VM's "config.keyId" property will return the ID of the key and provider used to encrypt the VM.
Closes: `NA`
```
$ go test -v -count 1 -run 'TestEncryptDecryptVM' -coverprofile cover.out ./simulator
=== RUN   TestEncryptDecryptVM
=== RUN   TestEncryptDecryptVM/encrypt
=== RUN   TestEncryptDecryptVM/encrypt_w_already_encrypted
=== RUN   TestEncryptDecryptVM/encrypt_w_powered_on
=== RUN   TestEncryptDecryptVM/encrypt_w_snapshots
=== RUN   TestEncryptDecryptVM/decrypt
=== RUN …
```
=> vcsim: Support VM crypto spec in vC Sim

govc/USAGE.md, govc/disk/attach.go, govc/disk/create.go, govc/disk/detach.go, govc/flags/storage_profile.go, govc/library/clone.go, govc/library/deploy.go, govc/namespace/create.go, govc/namespace/flag.go, govc/test/disk.bats, govc/test/namespace.bats, govc/test/vm.bats, govc/vm/create.go, govc/vm/disk/attach.go, govc/vm/disk/create.go, object/virtual_machine.go, simulator/virtual_machine.go, simulator/vstorage_object_manager.go
This includes support both First Class Disks and "classic" VM Disks.
govc: add disk.create '-profile' flag
govc: add vm.disk.create '-profile' flag
govc: add vm.disk.attach '-profile' flag
chore: govc: add common StorageProfileFlag
api: add VirtualMachine.AddDeviceWithProfile method
vcsim: add VirtualMachine AttachDisk and DetachDisk methods
govc add disk.attach and disk.detach commands
api: VirtualMachine.AttachDisk unitNumber param is optional
=> Add support for using storage profiles when creating and attaching VirtualDisks

vapi/library/library.go, vapi/library/library_test.go, vapi/simulator/simulator.go
Add the optional state info and server guid to Library type, both fields are the info for read only (get API), also update the fields to the library simulator and example test accordingly.
Closes: #3542
Unit tests via simulator
=== RUN   TestManagerCreateLibrary
created library example
--- PASS: TestManagerCreateLibrary (0.36s)
PASS
=> Update library state info to content library API

simulator/cluster_compute_resource.go, simulator/cluster_compute_resource_test.go
This patch introduces basic support for `ClusterComputeResource.PlaceVm` with the `relocate` placement type in vcsim. Since relocate is a supported placement type in real vSphere environments, it is essential to ensure that our simulator environment reflects this capability for accurate and comprehensive testing.
Closes: #3540 
All of the added unit tests simulate behavior (i.e., expected Faults/Recommendations) when testing the same `PlacementSpec` against a real vSphere environment.
```
% go test -v -count 1 -run 'TestPlaceVm' -coverprofile cover.out ./simulator
=== RUN   TestPlaceVmReconfigure
2024/09/06 14:56:08 unsupported placement type: unsupported
--- PASS: TestPlaceVmReconfigure (1.76s)
=== RUN   TestPlaceVmRelocate
--- …
```
=> vcsim: Support PlaceVm with relocate placement type

eam/simulator/simulator_test.go, fault/fault.go, fault/fault_example_test.go, fault/fault_test.go, vim25/soap/error.go, vim25/types/fault.go
This patch adds support for the new, top-level `fault` package with helper functions such as `As`, `In`, and `Is` for testing and traversing Golang `error` types and VMware `fault` types.
Closes: `NA`
With the command:
```shell
go test -v -count 1 -cover ./fault
```
The results shows there is 100% code coverage:
```shell
=== RUN   TestAs
=== RUN   TestAs/err_is_nil
=== PAUSE TestAs/err_is_nil
=== RUN   TestAs/err_is_not_supported
=== PAUSE TestAs/err_is_not_supported
=== RUN   TestAs/target_is_nil
=== PAUSE TestAs/target_is_nil
=== RUN   TestAs/target_is_not_pointer
=== PAUSE TestAs/target_is_not_pointer
=== RUN   TestAs/target_is_not_pointer_to_expected_type
=== PAUSE TestAs/target_is_not_pointer_to_expected_type
=== RUN …
```
=> api: Fault helpers

govc/USAGE.md, govc/vm/create.go
Add support to create vms with thick provisioned disks to govc.
This adds the following config options:
```
-disk.eager=false      Eagerly scrub new disk
-disk.thick=false      Thick provision new disk
```
Closes: #3526
```govc vm.create -cluster 'clustername' -folder foldername -pool=poolname -disk-datastore=datastorename -disk.eager=false -disk.thick=true -disk=100GB -c=10 -m=16384 -g=debian10_64Guest '-net=netname' -net.adapter=vmxnet3 -disk.controller=pvscsi -on=false vmname```
- its a trivial change
- I was not able to find an existing test that checks for disk creation on vm.create, nothing to add there.
- was not able to find a relevant existing test.
[guidelines]: …
=> govc: Support thick/eager disk opts on vm.create

crypto/manager_kmip.go, crypto/manager_kmip_test.go, simulator/crypto_manager_kmip.go, simulator/model.go, simulator/registry.go
This patch adds support for the `crypto` package, which introduces manager for the `CryptoManagerKmip` instance and several of its APIs, such as getting the default provider, checking if the provider is native, listing providers, and generating a new key.
Closes: `NA`
The following command may be run to test the client:
```shell
go test -v -count 1 -cover ./crypto
```
It has >80% code coverage (it is difficult to produce more without simulating errors):
```shell
=== RUN   TestCryptoManagerKmip
=== RUN   TestCryptoManagerKmip/RegisterKmipCluster
=== RUN   TestCryptoManagerKmip/GetClusterStatus
=== RUN   TestCryptoManagerKmip/UnregisterKmsCluster
=== RUN   TestCryptoManagerKmip/IsValidProvider
=== RUN   TestCryptoManagerKmip/GetDefaultKmsClusterID
=== …
```
=> api: Helpers for key management servers

simulator/crypto_manager_kmip.go, simulator/folder.go, simulator/virtual_machine.go, simulator/virtual_machine_test.go
This patch adds support to vcsim for generating encryption keys using the default provider (if one exists) for new VMs that specify they are to be encrypted, but do not specify a key ID or provider ID.
Closes: `NA`
```shell
$ go test -v -count 1 -run 'TestCreateVmWithDefaultKeyProvider|TestCreateVmWithGeneratedKey|TestEncryptDecryptVM' ./simulator
=== RUN   TestEncryptDecryptVM
=== RUN   TestEncryptDecryptVM/encrypt
=== RUN   TestEncryptDecryptVM/encrypt_w_default_key_provider
=== RUN   TestEncryptDecryptVM/encrypt_w_generated_key
=== RUN   TestEncryptDecryptVM/encrypt_w_already_encrypted
=== RUN   TestEncryptDecryptVM/encrypt_w_powered_on
=== RUN   TestEncryptDecryptVM/encrypt_w_snapshots
=== RUN   TestEncryptDecryptVM/decrypt
=== RUN …
```
=> vcsim: Gen enc key w default provider on createvm

pbm/client.go, pbm/client_test.go, pbm/methods/internal_methods.go, pbm/simulator/profiles.go, pbm/simulator/simulator.go, pbm/simulator/simulator_test.go, pbm/types/internal_types.go
This patch supports querying a PBM profile for IOFILTERS, which indicates if the profile supports encryption.
Closes: `NA`
```shell
$ go test -v -count 1 -run TestSupportsEncryption ./pbm
=== RUN   TestSupportsEncryption
=== RUN   TestSupportsEncryption/valid_profile_id
=== RUN   TestSupportsEncryption/invalid_profile_id
--- PASS: TestSupportsEncryption (0.74s)
--- PASS: TestSupportsEncryption/valid_profile_id (0.40s)
--- PASS: TestSupportsEncryption/invalid_profile_id (0.35s)
PASS
ok  	github.com/vmware/govmomi/pbm	1.143s
```
There is nearly 100% coverage for the new code:
And the changes do not break the existing PBM code:
```shell
$ go test -v -count 1 ./pbm ./pbm/simulator
--- SKIP: TestClient (0.00s)
=== RUN …
```
=> Support querying PBM profile for IOFILTERS

crypto/doc.go, govc/USAGE.md, govc/kms/add.go, govc/kms/export.go, govc/namespace/cluster/logs.go, govc/test/kms.bats, vapi/crypto/crypto.go, vapi/crypto/doc.go, vapi/crypto/internal/internal.go, vapi/crypto/simulator/simulator.go, vapi/rest/client.go, vcsim/main.go
api: add vapi/crypto package with support for native KMS
api: add rest.Client.DownloadAttachment method
=> govc: add native kms provider support

vim25/soap/client.go
Revert soap.Client http.Transport back to manual construction, rather than Clone() (see 313aa85)
Disable ForceAttemptHTTP2 by default, as we currently see degraded transfer rates with large file uploads.
Closes #3564
=> api: disable http.Transport.ForceAttemptHTTP2 by default

simulator/cluster_compute_resource_test.go, simulator/folder.go, simulator/folder_test.go, vim25/types/unreleased.go
The PlaceVmsXCluster API is being updated to provide placement recommendations for several new "op-types", relocate and reconfigure, in addition to the original "createAndPowerOn" behavior.  To support the new capability, the PlaceVmsXCluster API is updated to add a new placement type field, add 2 new supported placement types (relocate and reconfigure) and to extend the spec and faults to carry addition info referencing existing VMs and an optional relocate spec.
This change does the following:
- extends the API definitions to reflect the changes.
- extends the simulator to support these new placement types.
- adds simulator tests to validate the new placement types.
NOTE: This still a draft that needs more testing.
go test -v …
=> api: Update folder.PlaceVMsXCluster to support several placement types

govc/storage/policy/info.go, govc/test/storage.bats, pbm/methods/internal_methods.go, simulator/simulator.go
- Use internalpbm namespace for PbmQueryIOFiltersFromProfileId
- vcsim: override response namespace from struct tag
=> govc: add storage.policy.info flag to query IO filters

simulator/property_collector.go, simulator/property_collector_test.go, simulator/property_filter.go, simulator/view_manager.go, simulator/view_manager_test.go, view/example_test.go
Handle the case when an object used for the traversal itself is updated (e.g. ListView).
=> vcsim: handle traversal spec object updates

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/govmomi-build.yaml, .github/workflows/govmomi-go-lint.yaml, .github/workflows/govmomi-go-tests.yaml, .github/workflows/govmomi-govc-tests.yaml, .github/workflows/govmomi-release.yaml, .mailmap, CHANGELOG.md, CONTRIBUTING.md, CONTRIBUTORS, README.md, go.mod, govc/README.md, internal/version/version.go, vcsim/README.md
chore: bump default ClientVersion
docs: sync CHANGELOG
chore: bump Go versions
chore: fix GH Action tag output param
docs: various updates
Note: some of the doc updates are just simplifying:
- Pruned the PR template
- Removed links such as used-by, blogs, etc., better left to search engines
=> Various Docs and GitHub chores

object/vm_guest_test.go, simulator/container_virtual_machine.go, simulator/dvs.go, simulator/entity.go, simulator/event_manager.go, simulator/extension_manager.go, simulator/folder.go, simulator/http_nfc_lease.go, simulator/property_collector.go, simulator/property_filter.go, simulator/registry.go, simulator/session_manager.go, simulator/snapshot.go, simulator/task.go, simulator/task_manager.go, simulator/view_manager.go, simulator/virtual_machine.go
This fixes a race recently introduced in #3574 , where PropertyFilter's `sync` field needs locking.
Since merging some PR tests have failed, such as [PR 3579]:
(https://github.com/vmware/govmomi/actions/runs/11214574334/job/31169931284?pr=3579)
```
WARNING: DATA RACE
Read at 0x00c0007f03e0 by goroutine 244:
github.com/vmware/govmomi/simulator.(*PropertyFilter).update()
/home/runner/work/govmomi/govmomi/simulator/property_filter.go:77 +0x1353
github.com/vmware/govmomi/simulator.(*PropertyCollector).WaitForUpdatesEx()
/home/runner/work/govmomi/govmomi/simulator/property_collector.go:953 +0x134e
...
Previous write at 0x00c0007f03e0 by goroutine 231:
github.com/vmware/govmomi/simulator.(*PropertyFilter).UpdateObject()
/home/runner/work/govmomi/govmomi/simulator/property_filter.go:47 +0x190 …
```
=> vcsim: add *Context param to UpdateObject interface method

govc/cli/command.go
Updates the help to use the direct URL after the `via.vmw.com` URL shortener was removed from service by Broadcom GTO.
Closes: #3374
=> govc: update help url

simulator/view_manager.go
ViewManager updates itself when objects are added to and removed from inventory. These callbacks need to lock the ViewManager when making these changes.
=> vcsim: lock ViewManager in RegisterObject callbacks

vapi/library/finder/path.go
ConvertNamespacePathToUuidPath() fails when given: "ds:/path..."
Requires:
"ds:///path..."
=> fix: ensure proper vSAN URI format in ResolveLibraryItemStorage

govc/flags/client.go, govc/test/cli.bats
When the '-vim-version' flag is set to an empty value "", service version is used. Doing the same with a value of "-" allows service version to be used via the env var.
=> govc: support use of service version via GOVC_VIM_VERSION env var

object/virtual_device_list.go, object/virtual_device_list_test.go, simulator/virtual_machine.go
This PR updates the `AssignController` function to add the assigned device to the controller's device list. This ensures that [PickController()](https://github.com/vmware/govmomi/blob/main/object/virtual_device_list.go#L454-L479) function returns the appropriate controller with available slots, as it's based on the current number of devices attached to the controller.
Closes: N/A
- Updated the existing `TestAssignController` to validate the controller's device list.
- Deployed a VM with multiple devices, invoking `AssignController` during a single VM reconfiguration task. Verified that the devices were properly assigned to the controller without exceeding the maximum allowed slots:
```console
$ govc device.ls -vm vm-iso-3-cdroms cdrom-\*
cdrom-3002  VirtualCdrom  ISO [sharedVmfs-0] …
```
=> fix: update controller's device list in AssignController

simulator/virtual_machine.go
This PR fixes potential panic in simulator's `configureDevice` function by adding a type check for BaseVirtualController.
Closes: N/A.
N/A.
=> fix: add controller type check in simulator configureDevice

govc/folder/place.go, govc/test/folder.bats, simulator/folder.go, simulator/folder_test.go, vim25/types/unreleased.go
This change adds an unreleased govc command to exercise the cross-cluster placement engine via folder.PlaceVmsXCluster.  This command is limited to supporting the only a relocate placement type but will be extended to support createAndPowerOn and reconfigure in the future.  Bats tests are added to perform basic validation of the new command.
This change also fixes the PlaceVMSXCluster action types to match the types returned by the VIM API, specifically:
ClusterReconfigurePlacementAction => ClusterClusterReconfigurePlacementAction ClusterRelocatePlacementAction => ClusterClusterRelocatePlacementAction
This change also improves the simulator to return the appropriate action types based off of the placementType and improves the tests to validate the action type.
Testing Done: …
=> govc: Add an unreleased folder.place command for PlaceVMsXCluster

fault/fault.go, fault/fault_test.go
This patch prevents fault.In from panic'ing if a valid error is sent into the function.
Closes: `NA`
```shell
go test -v -count 1 -cover ./fault
...
PASS
coverage: 100.0% of statements
ok  	github.com/vmware/govmomi/fault	0.284s	coverage: 100.0% of statements
```
=> bug: Do not panic on fault.In for valid errs

ovf/importer/importer.go, ovf/importer/importer_test.go
Closes: #3550
Ensure the absolute path to the manifest is used.
Also stops any error from being printed on stderr.
Test case added.
=> fix: Use absolute path for reading manifest

ovf/importer/importer.go
Aborts the lease on OVF upload failure.
Closes #3554.
Tested internally.
=> fix: Abort lease on upload failure

ovf/importer/archive.go
Path handling for OVF uploads was using hardcoded path separators that did not support usage on Windows. This change handles paths in a cross-platform manner and ensures the absolute path is being used at all times.
Closes: #3555 
We have tested this in our own environment and confirmed it resolves the issues we were seeing with relative paths having paths prefixed on incorrectly.
=> fix: Cross-platform path handling for OVF FileArchive uploads

govc/kms/ls.go
Example output:
```console
% govc kms.ls
gce2e-standard  Standard  green  
gce2e-native    Native    green  
test-standard   Standard  red    default
```
=> govc: display default provider in kms.ls output

govc/USAGE.md, govc/datastore/info.go, govc/flags/debug.go, govc/object/collect.go, govc/object/find.go, govc/test/alarms.bats, govc/test/object.bats
Moving up next to the other commonly used object commands (find, ls, tasks, events, etc)
'collect' is displayed in the help how, 'object.collect' is now an alias - so this is not a breaking change. Intentionally left many existing tests using 'object.collect' as-is.
=> govc: rename 'object.collect' -> 'collect'

simulator/property_filter.go
Need to lock the filter's PropertyCollector when removing reference to self.
=> fix: vcsim: avoid race in DestroyPropertyFilter

crypto/manager_kmip.go, crypto/manager_kmip_test.go, govc/kms/key/create.go, govc/kms/key/info.go, govc/kms/key/rm.go, govc/main.go, govc/test/kms.bats, simulator/crypto_manager_kmip.go
- api: change ManagerKmip.IsValidKey to use QueryCryptoKeyStatus
- vcsim: add QueryCryptoKeyStatus
- govc: add kms.key commands
Example usage with kms.key commands, where `gce2e-standard` is a standard KMS backed by PyKMIP:
```console
% export GOVC_SHOW_UNRELEASED=true
% govc kms.key.info -vms -p gce2e-standard 35
gce2e-standard  35  true  KeyStateAvailable
vm-727        /test-vpx-1729704923-1820005-wcp.wcp-sanity/vm/Namespaces/dougm/crypto-test-with-class
% govc kms.key.create gce2e-standard
36
% govc kms.key.info -vms -p gce2e-standard 36
gce2e-standard  36  false  KeyStateNotActiveOrEnabled
% govc kms.key.info -vms -p gce2e-standard invalid
gce2e-standard  invalid  false  KeyStateMissingInKMS
```
=> api: add crypto.ManagerKmip.QueryCryptoKeyStatus

object/virtual_device_list.go, object/virtual_device_list_test.go
This PR updates the `CreateSATAController()` to return an error when there is no available bus number.
Added `TestCreateSATAController`.
=> fix: CreateSATAController to return error when no bus numbers

simulator/folder.go, simulator/folder_test.go
Closes: #3610
Updates the simulator CreateFolder / CreateStoragePod to set the DuplicateName's Object to the existing one, instead of the Folder the operation is called on.
Closes: #3610
Added unit test, and run with and without the fix.
=> fix: Set DuplicateName Object to duplicate object

govc/test/test_helper.bash, guest/toolbox/example_test.go, simulator/container_host_system_test.go, simulator/container_virtual_machine_test.go, simulator/feature_test.go, test/helper.go
=> chore: skip tests unless running docker on linux

cns/types/unreleased_types.go
This patch adds support for the CNS type, BlockCreateSpec.
Closes: `NA`
It was reviewed by folks who work on CNS.
=> api: Support CnsBlockCreateSpec

find/doc.go, find/finder.go, find/finder_test.go, govc/USAGE.md, govc/flags/datacenter.go, govc/ls/command.go, govc/object/find.go, govc/test/object.bats, object/common.go, object/common_test.go, simulator/registry.go, vim25/mo/type_info.go
With this change, finder methods can convert ManagedObjectReference or MOID to an object instance. For example:
```console
% govc find -l -i -type m / -name nginx
VirtualMachine:vm-1100  /test-vpx-1730432486-649974-wcp.wcp-sanity/vm/nginx
% govc vm.info VirtualMachine:vm-1100
Name:           nginx
Path:         /test-vpx-1730432486-649974-wcp.wcp-sanity/vm/nginx
UUID:         421b8fd2-3006-0a69-1f16-7d088f90145f
Guest name:   Other (32-bit)
...
% govc find -l -I -type m / -name nginx
vm-1100  /test-vpx-1730432486-649974-wcp.wcp-sanity/vm/nginx
% govc vm.info vm-1100
Name:           nginx
Path:         /test-vpx-1730432486-649974-wcp.wcp-sanity/vm/nginx
UUID:         421b8fd2-3006-0a69-1f16-7d088f90145f
Guest name:   Other (32-bit)
...
% govc collect -s vm-1100 runtime.host | cut -d: -f2 …
```
=> api: support MOID conversion in Finder methods

govc/USAGE.md, govc/test/vm.bats, govc/vm/change.go, simulator/virtual_machine.go
=> govc: add vm.change -migrate-encryption and -ft-encryption-mode options

simulator/container_host_system.go
Lock the version of `alpine` used by vcsim to a recent one that supports `sleep infinity`.
Certain corporate-managed Docker Registry mirrors seem to never invalidate their cache for `latest`.  A machine configured with such a mirror will always pull an arbitrarily old version:
```shellsession
$ docker pull alpine
Using default tag: latest
latest: Pulling from library/alpine
e110a4a17941: Pull complete
Digest: sha256:3dcdb92d7432d56604d4545cbd324b14e647b313626d99b889d0626de158f73a
Status: Downloaded newer image for alpine:latest
docker.io/library/alpine:latest
$ docker images | grep alpine
alpine              latest            4e38e38c8ce0   8 years ago     4.8MB
```
On such a system, the simulator fails:
```shellsession
$ go test ./simulator
2024/11/15 14:35:08 unsupported placement type: …
```
=> vcsim: Lock alpine image to a recent tag

govc/USAGE.md, govc/namespace/service/create.go
`govc namespace.service.create` had flags defined in code that were never usable.
```
govc namespace.service.create -h
```
Now shows the `spec-type` `trusted` and `accept-eula` flags.  Before this commit, those flags weren't shown in help and caused an error if provided.
I looked for other incorrect usages like this, by doing `rg 'flag.*Var' ./govc`.  This was the only one.
=> fix: govc: wire up flags for namespace service create

vim25/types/byte_slice.go, vim25/types/byte_slice_test.go
=> fix: vcsim: output signed byte in ByteSlice.MarshalXML

object/virtual_device_list.go, ovf/cim.go, ovf/configspec.go, ovf/configspec_test.go, ovf/envelope.go, ovf/fixtures/haproxy-vsphere.ovf, ovf/fixtures/virtualsystemcollection.ovf, ovf/importer/spec.go, ovf/ovf_test.go, simulator/ovf_manager.go
This PR includes several enhancements to the `ovf` package:
* The OVF parser now conform to the DMTF spec for OVF content. This includes:
* support for VirtualSystemCollection
* a single OperatingSystem section in VirtualSystem
* removing the roll-up sections at the root of the Envelope that belong only under a VirtualSystem or VirtualSystemCollection
* :warning: **Breaking** :warning: Users of the `ovf` package will need to update their sources to conform to the changes from this patch. It should be a fairly simple change.
* The OVF parser now supports an enum used to define the CIM ResourceType.
* :warning: **Breaking** :warning: Users of the `ovf` package may need to cast ResourceType to a uint16 depending on how they have used the value. 
* It is now possible to transform an …
=> OVF package enhancements

cli/flags/client.go, cli/flags/version_test.go, govc/test/cli.bats
This check hasn't been useful, except maybe in the early days of govc. It's only caused problems when dev/rc versioning changes in a way that breaks our parsing. Simpler to just remove than to maintain it.
Fixes #3643
=> govc: remove minimum API version check

vim25/xml/marshal.go
PropertyCollector responses always included the 'xsi:type' attribute. When a property type is ManagedObjectReference, there are 2 'type' attributes in the response, for example:
```xml
<val xsi:type="ManagedObjectReference" type="LicenseAssignmentManager">LicenseAssignmentManager</val>
```
Some clients (Java) have problems with this. Changing the order to be the same as real vCenter to workaround:
```xml
<val type="LicenseAssignmentManager" xsi:type="ManagedObjectReference">LicenseAssignmentManager</val>
```
Fixes #2114
=> fix: vcsim: swap order of xsi type attribute

vim25/types/deep_copy.go, vim25/types/deep_copy_test.go, vim25/types/helpers.go
This patch provides a helper function, `Copy[T any](src T) T` for creating deep copies of Go objects, specifically those from vim25/types. The copy function encodes the Go object to JSON using the vim JSON encoder. Then the copy function decodes the data to a new instance of the same type. The function is implemented using Go generics, so it does not depend directly on reflection (though Go's JSON encoder does).
Closes: `NA`
```shell
go test -count 1 -v -run TestMustDeepCopy ./vim25/types
```
The above command will emit output similar to the following:
```shell
=== RUN   TestMustDeepCopy
=== RUN   TestMustDeepCopy/a_string
=== PAUSE TestMustDeepCopy/a_string
=== RUN   TestMustDeepCopy/a_*uint8
=== PAUSE TestMustDeepCopy/a_*uint8
=== RUN   TestMustDeepCopy/a_VirtualMachineConfigSpec
=== …
```
=> api: A generic copy function for vim25/types

pbm/client.go, pbm/client_test.go, pbm/simulator/simulator.go, simulator/registry.go, simulator/session_manager.go, simulator/simulator.go, ssoadmin/client.go, sts/client.go, vim25/soap/client.go, vim25/soap/json_client.go, vim25/soap/json_client_test.go, vim25/soap/soap.go, vslm/client.go
Sessions are consumed by API endpoints via one of:
- HTTP Cookie (vim25 for example)
- HTTP Header (vmodl2 /rest and /api)
- SOAP Header (pbm, vslm, sms for example)
The soap.Client had always set the SOAP Header cookie regardless if consumed by an API endpoint.
Clients must now opt-in to this behavior if they need it, such as pbm and vslm.
This also allows clients to change the name of soap.Header.Cookie (default is still "vcSessionCookie")
vcsim: add override mechanism for session mapping
On the simulator side, API endpoints can specify where a session is sourced from. Default is still the "vmware_soap_session" HTTP Cookie. The pbm simulator now specifies the "vcSessionCookie" SOAP Header, behaving as real pbm/VC does.
=> api: add override mechanism for SOAP Header.Cookie

cli/object/save.go, govc/USAGE.md, govc/test/license.bats, govc/test/object.bats, simulator/license_manager.go, simulator/license_manager_test.go, simulator/model.go
- add ProductName + ProductVersion properties to default EvalLicense
- QueryAssignedLicenses defaults to listing license for all hosts and clusters
- govc object.save '-l' flag will include all LicenseManager properties and LicenseAssignmentManager QueryAssignedLicenses response
=> vcsim: LicenseManager enhancements

cli/object/save.go, govc/test/object.bats, simulator/host_system.go
QueryTpmAttestationReport is NotImplemented, vCenter only method.
=> vcsim: fix object.save when run directly against ESX

simulator/guest_operations_manager_test.go, toolbox/process/process_test.go, toolbox/toolbox_freebsd.go
=> fix: toolbox: add freebsd stub for fileExtendedInfoFormat

object/virtual_disk_manager.go
This patch fixes object.VirtualDiskManager::CopyVirtualDisk so it takes an interface instead of a concrete type for the destination disk spec.
Closes: `NA`
The GitHub actions.
=> api: Fix object.VirtualDiskManager::Copy

pbm/client.go, vslm/client.go
Commit 19189841 refactored how we set vcSessionCookie for pbm and vslm endpoints. We need to use the value of vim25.Client's vmware_soap_session for vSessionCookie. Since the first response from pbm/vslm includes a 'Set-Cookie: vmware_soap_session=...', the value of which is _not_ valid for vcSessionCookie.
=> fix: SOAP vcSessionCookie value must be from vim25.Client

cli/fields/info.go, govc/test/fields.bats
the if branch just check `cerr !=nil` and return a nil value error `err`
so, it's a harmless bug.
I have an idea to detect the code that return a no-realte nilness error bug, and check the top 1000 github go repos, and found this. see https://github.com/alingse/sundrylint/issues/4
just use the cli can reproduce this
=> fix: check `cerr != nil` but return a nil value error `err`

cli/datastore/ls.go, govc/USAGE.md
Use human friendly name by default, rather than vSAN ID for top-level dirs.
Note that the datastore.ls command was originally written against vSphere 5.5, the 'FileInfo.FriendlyName' field was not added until 6.5
=> govc: add datastore.ls -H option

cli/disk/ls.go, govc/USAGE.md, govc/test/disk.bats
Deleting an FCD file backing can create an orphan FCD. An orphaned ID is returned by the ListVStorageObject API, but calling RetrieveVStorageObject with an orphan ID results in a NotFound fault. The disk.ls command would return an error and suggest: use 'disk.ls -R' to reconcile datastore inventory The -R flag calls ReconcileDatastoreInventory, which normally cleans up such orphans, but we have seen cases where it does not.
This change ignores orphans by default. The new '-a' flag will list *all* orphans (if any) and includes the disk.ls -R suggestion.
Fixes #3639
Example output before change:
```console
% govc disk.ls
govc: 1ad1b6b7-b6e9-4c93-ba4d-bb4139acc08f not found: use 'disk.ls -R' to reconcile datastore inventory
```
After change:
```console
% govc disk.ls …
```
=> govc: add disk.ls '-a' flag

vapi/namespace/namespace.go
This PR is to deprecate haproxy support with vSphere 9.0
=> Deprecate haproxy with vSphere 9.0

cli/library/info.go, vapi/library/finder/path.go, vapi/library/finder/path_test.go
This patch adds support for a variant of the ResolveLibraryItemStorage function named ResolveLibraryItemStorageWithDatacenter, for when the datacenter is known in advance. This is far more efficient since the ancestors of each storage item no longer need to be queried.
Closes: `NA`
@dougm, please note the test switched to an instance of vC Sim *per* test case as re-using the same one caused test cases to fail randomly. We can look more into why later.
```shell
$ go test -v -count 1 -run TestResolveLibraryItemStorageWithDatacenter ./vapi/library/finder
=== RUN   TestResolveLibraryItemStorageWithDatacenter
=== RUN   TestResolveLibraryItemStorageWithDatacenter/Nil_datacenter_and_nil_topLevelCreate
=== RUN   TestResolveLibraryItemStorageWithDatacenter/Nil_datacenter_and_false_topLevelCreate …
```
=> api: Support DC for ResolveLibItemStor

cli/library/info.go, vapi/library/finder/path.go, vapi/library/finder/path_test.go
This patch updates the ResolveLibraryItemStorage method with the ability to return the resolve datastore information beyond just the resolved URIs. Now the datastore name, URL, and whether it supports top-level directory create can be returned.
Closes: `NA`
```shell
$ go test -v -count 1 -run TestResolveLibraryItemStorage ./vapi/library/finder
=== RUN   TestResolveLibraryItemStorage
=== RUN   TestResolveLibraryItemStorage/Nil_datacenter_and_nil_topLevelCreate
=== RUN   TestResolveLibraryItemStorage/Nil_datacenter_and_false_topLevelCreate
=== RUN   TestResolveLibraryItemStorage/Nil_datacenter_and_true_topLevelCreate
=== RUN   TestResolveLibraryItemStorage/Non-nil_datacenter_and_nil_topLevelCreate
=== RUN   TestResolveLibraryItemStorage/Non-Nil_datacenter_and_false_topLevelCreate
=== RUN …
```
=> api: Support returning DS info when resolving lib stor

cli/volume/ls.go, cns/types/types.go, cns/types/unreleased_types.go, govc/USAGE.md
cns: add json tags
PR #3007 added camelCase json tags for generated types
PR #3247 added camelCase json tags for govc commands
This change does the same for cns/types.
Testing of the `-b` flag has been done manually for now, as we still don't have a `govc volume.create` command.
A volume's backing file can already being seen using `-json`:
```console
% govc volume.ls -json a24b36ff-c407-46ef-b068-a9620145a0cb | jq -r .volume[].backingObjectDetails.backingDiskPath
[sharedVmfs-0] fcd/861ed49f57e549c3a5ea25780c13fdf7.vmdk
```
With the `-b` flag, backing is included in the friendly output and also uses `QueryVolumeInfo` to verify the backing file exists, for example:
```console
% govc volume.ls -b
0b9d71d2-2236-4d67-96e7-89a46292e430	pvc-c3b456c7-01d8-4576-b3eb-6c1b0833fcea	[sharedVmfs-0] …
```
=> govc: add -b flag to volume.ls

govc/test/library.bats, simulator/virtual_disk_manager.go, vapi/simulator/simulator.go, vmdk/descriptor.go, vmdk/descriptor_test.go
Certain vcsim VirtualDiskManager methods (Copy,Move,Delete) expect a .vmdk descriptor and backing -flat.vmdk, create both when creating and syncing vmdk library items.
The new vmdk.Descriptor has more use cases in vcsim and client side, those will come in future PRs.
=> vcsim: create cls vmdk descriptor and backing files

cli/datastore/download.go, govc/USAGE.md, govc/test/library.bats, ovf/ovf.go, vmdk/descriptor.go, vmdk/descriptor_test.go
Only applies to ".ovf" and ".vmdk" files currently.
=> govc: add datastore.download -json support

vim25/soap/client.go, vim25/soap/client_test.go
In 19189841 / PR #3636 we deferred the http.CookieJar lookup until request time. Fallback to using Path="/" if initial lookup fails.
=> fix: Add session lookup fallback for soap header auth

object/datastore_test.go, vim25/mo/retrieve_test.go, vim25/mo/type_info.go
Prior to 3b7ff25f (PropertyCollector index support) mo.LoadObjectFromContent would panic when trying to load specific fields of a base type, e.g. a mo.Datastore "info.url". While that change fixed the panic, it only allowed 1 such field to be loaded - that is fixed with this change.
=> fix: support multiple property.Collector.Retrieve base type fields

cli/namespace/service/create.go, cli/namespace/service/flag.go, cli/namespace/service/version/activate.go, cli/namespace/service/version/create.go, cli/namespace/service/version/deactivate.go, cli/namespace/service/version/info.go, cli/namespace/service/version/ls.go, cli/namespace/service/version/rm.go, govc/USAGE.md, govc/main.go, govc/test/namespace.bats, vapi/namespace/internal/internal.go, vapi/namespace/simulator/simulator.go, vapi/namespace/supervisorsvc.go, vapi/simulator/simulator.go
- Update GET for both /supervisor-services and /supervisor-services/{id}/versions
- Add GET for specific service and specific version: /supervisor-services/{id} and /supervisor-services/{id}/versions/{version}
- Add DELETE for /supervisor-services/{id} and /supervisor-services/{id}/versions/{version}: DELETE for  /supervisor-services/{id} and /supervisor-services/{id}/versions/{version}
- Add activate/deactivate for a service version too (you can't delete a version of a service if it's not deactivated first):
PATCH for superrvisor-services/{id} and /supervisor-services/{id}/versions/{version}
- Introduced a "flag" package to get common CLI checks between version and service APIs
- Update namespace.bats tests to test list and get (for now)
- Update VAPI simulator to use `ServeHTTP` to make …
=> govc: add proper VAPI for vSphere Supervisor Services

simulator/model.go, vim25/mo/registry.go
govc object.save includes Alarm objects, but vcsim -load did not wrap the Alarm objects.
This causes panic when trying to call CreateAlarm() which expects wrapped Alarm objects.
=> vcsim: fix save+load of Alarm objects

session/cache/session.go
Use sha256 for session cache file names
This maintains compatibility between govc and Terraform, allowing the two to share the same cache while also ensureing SHA1 is eliminated.
Ref: 
- https://github.com/hashicorp/terraform-provider-vsphere/issues/2328
- https://github.com/vmware/govmomi/pull/1898
- https://github.com/hashicorp/terraform-provider-vsphere/pull/1808
- https://github.com/hashicorp/terraform-provider-vsphere/issues/1807
- https://github.com/hashicorp/terraform-provider-vsphere/pull/1051
=> govc: sha256 for session cache

cns/types/types.go
add `delete` flag for `CnsContainerCluster` type.
UpdateVolumeMetadata API has support for deleting containercluster metadata if delete flag is set to true.
We have requirement to allow deleting reference to older container cluster when container cluster ID changes from cluster-Moref to supervisor-id.
=> add delete flag for CnsContainerCluster type

cli/disk/ls.go, cli/disk/manager.go, cli/disk/metadata/ls.go, cli/disk/metadata/update.go, govc/USAGE.md, govc/main.go, govc/test/disk.bats, govc/test/test_helper.bash, simulator/vstorage_object_manager.go, vslm/global_object_manager.go, vslm/global_object_manager_test.go, vslm/simulator/simulator.go
- govc: add disk.metadata ls and update commands
- api: add vlsm.GlobalObjectManager.List method
=> vcsim: add disk query and metadata support

vim25/mo/retrieve.go, vim25/mo/retrieve_test.go
New property (resourceConfigSpecDetailed) is only valid when collected against vCenter. Against ESX is NotSupported and returned by RetrievePropertiesEx in the missingSet when all properties are requested, which by default is propagated as an error.
=> Add ResourcePool.resourceConfigSpecDetailed to missingSet filter

lookup/client.go, ssoadmin/client.go, sts/client.go
This soap header is unused by lookup, ssoadmin and sts endpoints.
- Avoids an error with endpoints using newer jaxws versions: "SAAJ0131: HeaderElements must be namespace qualified"
- Quote the sts SoapAction, avoiding warning in the sts logs: "Received WS-I BP non-conformant Unquoted SoapAction HTTP header"
=> fix: Drop operationID soap header for unsupported endpoints

cli/gpu/gpu.go, cli/gpu/host/info.go, cli/gpu/host/profile/ls.go, cli/gpu/vm/add.go, cli/gpu/vm/info.go, cli/gpu/vm/remove.go, govc/USAGE.md, govc/main.go, govc/test/gpu.bats
This PR adds GPU management commands to the govc CLI tool, including:
- `govc gpu.host.info`: Display GPU information for a host, including physical NVIDIA GPUs
- `govc gpu.host.profile.ls`: List available vGPU profiles on a host
- `govc gpu.vm.add`: Add vGPU to VM with specified profile
- `govc gpu.vm.info`: Display GPU information for a VM
- `govc gpu.vm.remove`: Remove all vGPUs from VM
Commands support standard and JSON formatting.
Closes: #3689
- We've done ad-hoc testing with NVIDIA A40 and L40 GPUs.
- We've asked for guidance about modifying vcsim, so that it can be properly unit tested.
=> govc: add GPU commands

cli/session/login.go, govc/USAGE.md, vapi/authentication/authentication.go
Fixes #3041
Example:
```console
% token=$(govc session.login -issue)
% govc session.login -jwt vmware-tes:vc:nsxd-v2:nsx -token "$token"
eyJraWQiOiJBNzU5OUE4Q...
```
=> govc: add session.login -jwt option

simulator/property_collector.go
The collect() method needs to continue holding the object lock while processing selectSet.
Fixes #3697
=> fix: vcsim: extend PropertyCollector lock to avoid potential races

govc/test/cli.bats, govc/test/datastore.bats, simulator/cluster_compute_resource.go, simulator/datastore.go, simulator/datastore_namespace_manager.go, simulator/datastore_test.go, simulator/file_manager.go, simulator/host_datastore_browser.go, simulator/host_datastore_system.go, simulator/model.go, simulator/option_manager.go, simulator/resource_pool.go, simulator/simulator.go, simulator/snapshot.go, simulator/virtual_machine.go, simulator/vstorage_object_manager.go, units/size.go, vapi/library/finder/path_test.go, vslm/simulator/simulator.go
- Use a single top-level TempDir for a vcsim Model instance. Make this path available via OptionManager. This top-level can be used internally as backing for vSAN Datastores.
- Split FileManager.resolve logic into Datastore.resolve and use that method everywhere for resolving a Datastore relative path to local file system absolute path. This is where top-level vSAN friendlyName is now translated to vSAN object UUID.
- ReconfigureComputeResource_Task will now create a vsanDatastore when spec.VsanConfig.Enabled == true. This Datastore will be added to existing hosts in the cluster, and any hosts later added to the cluster.
- HostDatastoreBrowser search methods now populate the FriendlyName field for vSAN Datastores.
- The tests added to datastore.bats cover these cases using existing govc …
=> vcsim: add vsan Datastore support

cli/tags/category/create.go, cli/tags/create.go, govc/USAGE.md, govc/test/tags.bats, vapi/simulator/simulator.go, vapi/tags/categories.go, vapi/tags/tags.go
- govc: Add '-id' option for tags.category and tags create commands
- vcsim: Add vapi support for CategoryID and TagID fields
Fixes #3706
=> api: Add optional CategoryID,TagID fields for category and tag creation

.github/workflows/govmomi-build.yaml, .github/workflows/govmomi-check-wip.yaml, .github/workflows/govmomi-go-lint.yaml, .github/workflows/govmomi-go-tests.yaml, .github/workflows/govmomi-govc-tests.yaml, .github/workflows/govmomi-release.yaml, .github/workflows/govmomi-stale.yaml, .github/workflows/issue-greeting.yaml, .github/workflows/verify-docker-login.yaml
Updates the use of all instances of `ubuntu-20.04` to  `ubuntu-latest`.
The 20.04 runner image was deprecated on 2025-02-01 and will be fully unsupported by 2025-04-01.
[Reference](https://github.com/actions/runner-images/issues/11101)
=> chore(gh): update to `ubuntu-latest` runner

.github/workflows/codeql-analysis.yml
Improvements to CodeQL analysis workflow:
* Renamed the workflow from `CodeQL` to `CodeQL Analysis` for better clarity. (`.github/workflows/codeql-analysis.yml`)
* Added read permissions for `contents` and removed redundant permissions from the `analyze` job. (`.github/workflows/codeql-analysis.yml`)
* Simplified the `on` event triggers by consolidating branch specifications and adding `workflow_dispatch` for manual triggering. (`.github/workflows/codeql-analysis.yml`)
* Updated the checkout step to use a specific commit reference for the `actions/checkout` action and ensured consistent naming conventions. (`.github/workflows/codeql-analysis.yml`)
* Removed the workaround for Go 1.21 compatibility, as it is no longer necessary. (`.github/workflows/codeql-analysis.yml`)
=> chore(gh): update codeql workflow

.github/workflows/issue-greeting.yaml
Updates the GitHub Actions workflow for issue greetings. 
The changes include updating permissions, simplifying the event type specification, and pinning action versions for stability.
* [`.github/workflows/issue-greeting.yaml`](diffhunk://#diff-5a1833d14853c34a2a49ab440bbfcdc292d4c01fe4ae3ba5f05659c82fbf6537L1-R32): Added specific permissions for issues and contents.
* [`.github/workflows/issue-greeting.yaml`](diffhunk://#diff-5a1833d14853c34a2a49ab440bbfcdc292d4c01fe4ae3ba5f05659c82fbf6537L1-R32): Simplified the event type specification from `["opened"]` to `opened`.
* [`.github/workflows/issue-greeting.yaml`](diffhunk://#diff-5a1833d14853c34a2a49ab440bbfcdc292d4c01fe4ae3ba5f05659c82fbf6537L1-R32): Pinned action versions for `checkout`, `render-template`, and `create-or-update-comment` …
=> chore(gh): update greeting workflow

.github/workflows/govmomi-govc-tests.yaml
Updates the `govc` tests workflow:
- Updates to Go 1.23
=> chore(gh): update govc tests workflow

.github/workflows/govmomi-go-lint.yaml
Updates to linting workflow:
- Simplifies single branch reference.
- References `go.mod` for the Go version.
=> chore(gh): update linting workflow

.github/workflows/govmomi-build.yaml
Updates to build workflow:
- Simplifies single branch reference.
- References `go.mod` for the Go version.
- Updates or cleans up comments.
=> chore(gh): update build workflow

.github/workflows/govmomi-go-tests.yaml
Updates the unit tests workflow:
- Updates to Go 1.23 and 1.24 matrix.
=> chore(gh): update unit tests workflow

toolbox/hgfs/archive.go
Updates the `archiveRead` function in the `toolbox/hgfs/archive.go` file. The change adds validation to prevent directory traversal attacks.
* [`toolbox/hgfs/archive.go`](diffhunk://#diff-dd810031b8da2e54219d302bddd91bbe1b4e9192ac40c268c56477527c423194R241-R246): Added a check to skip entries containing '..' in their names to prevent directory traversal vulnerabilities.
[Reference](https://cwe.mitre.org/data/definitions/22.html)
=> toolbox: fix codeql go/zipslip

.github/dependabot.yml
Updates the Dependabot configuration to also check for updates to Ruby dependencies in the `/gen` directory using `bundler` (Ruby's dependency manager).
=> chore(gh): update dependabot for ruby dependencies

cli/metric/performance.go
Added a check to panic if a value exceeds `math.MaxInt32` in the `Interval` method to prevent out-of-range errors.
=> govc: fix integer type conversion

cli/vm/guest/chown.go
Correct the integer type conversion for the `guest.chown`.
=> govc: fix integer type conversion for `guest.chown`

Dockerfile.govc, Dockerfile.vcsim
Updates the `Dockerfile.govc` and `Dockerfile.vcsim` to use the official Docker image based on the version used in the project. Note that the official images use Debian.
To reduce the amount of changes, I will [follow up](https://github.com/vmware/govmomi/issues/3734) with a later pull request to update the `.goreleaser.yml` configuration to v2 and to pass a `GO_VERSION` arg to the Dockerfile to make this easier to maintain.
=> chore: update `vmware/govc` and `vmware/vcsim` dockerfiles

sts/signer.go
* [`sts/signer.go`](diffhunk://#diff-8c0865d840bf0719e62b56c9bce965a2f828bc93946f5656339de5b4bb9fcc83L31-R20): Replaces `math/rand` with `crypto/rand` for nonce generation in the `SignRequest` function. This ensures that the generated nonces are more cryptographically secure.. [[1]](diffhunk://#diff-8c0865d840bf0719e62b56c9bce965a2f828bc93946f5656339de5b4bb9fcc83L31-R20) [[2]](diffhunk://#diff-8c0865d840bf0719e62b56c9bce965a2f828bc93946f5656339de5b4bb9fcc83L264-R259)
=> api: use `crypto/rand` for nonce generation

object/custom_fields_manager.go
* [`object/custom_fields_manager.go`](diffhunk://#diff-9474a57abe69d5ced9e68384e4f3b5ae512708743ba3b14aa8425d5473f1acd2L130-R124): Replaces `strconv.Atoi` with `strconv.ParseInt` to ensure proper `int32` handling and adds a bounds check to prevent out-of-range integer values. All error conditions result in `ErrKeyNameNotFound` being returned.
=> api: use `ParseInt` and add `int32` bounds check

gen/Gemfile, gen/Gemfile.lock
Updates bundler to v2 to support Dependabot.
Ref: 
- https://github.com/vmware/govmomi/security/dependabot/27
- https://github.com/vmware/govmomi/security/dependabot/25
- [bundler in /gen - Update #985577617 #352](https://github.com/vmware/govmomi/actions/runs/14034776848/job/39290201894)
```shell
govmomi/gen on  chore(deps)/bundler-v2 [!] via 💎 v3.4.2 via 🐹 v1.24.1 on 🐳 v26.1.3 (rancher-desktop) 
✦ ➜ bundle update                     
Fetching gem metadata from https://rubygems.org/.......
Resolving dependencies...
Using racc 1.8.1 (was 1.7.3)
Using power_assert 2.0.5 (was 0.4.1)
Using yaml 0.4.0 (was 0.2.1)
Fetching mini_portile2 2.8.8 (was 2.8.6)
Using nokogiri 1.18.6 (x86_64-darwin) (was 1.16.5)
Using test-unit 3.6.7 (was 3.2.3)
Installing mini_portile2 2.8.8 (was 2.8.6)
Bundle …
```
=> chore(deps): update bundler to v2 for dependabot

vcsim/main.go
Replace the use of `strconv.Atoi` with `strconv.ParseInt`, specifying the bit size as 32. This ensures that the parsed value is within the range of int32.
Ref: GHSA https://github.com/vmware/govmomi/security/code-scanning/20
=> vcsim: fix integer type conversion

simulator/property_collector.go, simulator/property_filter.go, vim25/xml/extras.go, vim25/xml/extras_test.go, vim25/xml/marshal.go, vim25/xml/marshal_test.go, vim25/xml/read.go, vim25/xml/read_test.go, vim25/xml/typeinfo.go, vim25/xml/xml.go, vim25/xml/xml_test.go
Last sync was with Go 1.15, see commit 81207eab
Move some of the added code from read{_test}.go to extras{_test}.go
to help avoid future merge conflicts.
Patched via:
```console
% cd ~/go/src/github.com/golang/go
% git diff go1.15..go1.24.1 src/encoding/xml > encoding-xml.patch
% cd ~/go/src/github.com/vmware/govmomi/vim25/xml
% patch -p4 < ~/go/src/github.com/golang/go/encoding-xml.patch
```
- fix: vcsim: fix PropertyFilter/Collector memory leak
=> chore: vim25/xml: sync with Go 1.24 encoding/xml

cli/object/collect.go, cli/vm/snapshot/export.go, govc/USAGE.md, govc/test/snapshot.bats, nfc/lease.go, simulator/snapshot.go, vim25/mo/helpers.go
This patch adds support for exporting a VM snapshot with govc as well as printing information about an HTTP NFC lease with govc.
Closes: `NA`
* Two tests were added in `snapshot.bats` for exporting a snapshot.
* The following was run against a real vCenter instance:
* Export a snapshot
```shell
govc snapshot.export -vm vm-1 root                                                                           
```
```shell
Lease:               HttpNfcLease:session[52f12f02-e8d2-cc50-3d28-43fc1c4e2073]52894ef4-885f-254d-1cfa-3e1e12bade78
InitializeProgress:  100
TransferProgress:    0
Mode:                pushOrGet
State:               ready
Capabilities:
CorsSupported:      true
PullModeSupported:  true
Info:
Entity:                 VirtualMachine:vm-226
Timeout:                5m0s …
```
=> govc: Support snapshot.export & nfc.lease.info

simulator/ovf_manager.go
Example ovf:
```console
% grep vmx- Operations-Appliance-9.0.0.0.24597071.ovf
<vssd:VirtualSystemType>vmx-10,vmx-11</vssd:VirtualSystemType>
```
Without the change, ovf import will fail here: https://github.com/vmware/govmomi/blob/cc135ecc16a098f1d84266a873cf7f9170c1244e/simulator/virtual_machine.go#L1117-L1118
=> vcsim: support multiple VirtualSystemType in OvfManager.CreateImportSpec

cli/vm/policy/ls.go, govc/USAGE.md, govc/main.go, govc/test/storage.bats
See discussion #3727
Example output:
```console
% govc vm.policy.ls -vm $vm
VM home      wcpglobal_storage_profile  compliant  Fri Mar 28 16:42:19 2025
disk-1000-0  wcpglobal_storage_profile  compliant  Fri Mar 28 16:42:19 2025
disk-1000-1  wcpglobal_storage_profile  compliant  Wed Mar 26 17:08:54 2025
```
=> govc: Add vm.policy.ls command

find/finder.go, session/manager.go, vim25/types/esxi_version.go, vim25/types/types.go
Updates (or removes) `kb.vmware.com` URLs to replacement `support.broadcom.com` URLs as necessary.
=> docs: update kb urls

scripts/vcsa/create-esxi-vm.sh, scripts/vcsa/create-vcsa-vm.sh
Removes legacy links to `docs.vmware.com` in scripts.
=> docs: remove legacy docs links

govc/test/vcsim.bats, simulator/datastore.go
PR #3705 refactored Datastore access, part of which uses the Datastore summary.url property instead of info.url
Also fix the Datastore urls for local paths, such as govc object.save of a vcsim instance
=> fix: vcsim -load Datastore summary.url property

cli/importx/ovf.go, govc/USAGE.md, govc/test/import.bats, ovf/importer/importer.go
Network can already be set via -options, but this simplifies the common case.
Added a hint to specify network (See also: #1561), example when not specified:
```console
% govc import.ovf foo.ovf
govc: Host did not have any virtual network defined. (specify Network with '-net' or '-options')
```
Fixes #3679
=> govc: Add import.ova -net flag

cli/importx/ovf.go, govc/test/import.bats
Similar to ovftool, the -ds option can now be a Datastore Cluster. Datastore with the most free space is chosen.
Fixes #1265
=> govc: Support Datastore Cluster in import.ova command

lookup/client.go, lookup/simulator/simulator.go, ssoadmin/client_test.go
If a vCenter's hostname is not in DNS (outside of VC's /etc/hosts), then lookup service URLs may fail to resolve. In this case, rewrite the URLs to use the same Host used for the vim25.Client's connection.
=> api: Rewrite lookup service URLs on DNS error

govc/test/import.bats, simulator/http_nfc_lease.go, simulator/resource_pool.go, simulator/simulator.go, simulator/snapshot.go
Host should only be '*' when connecting directly to an ESX host.
=> vcsim: Use the simulator's URL.Host in NFC lease URLs

govc/test/vcsim.bats, simulator/container.go, simulator/container_virtual_machine.go
```console
% govc collect -s -json vm/$vm guest.ipStack
[
{
"dnsConfig": {
"dhcp": false,
"hostName": "022947a82667",
"domainName": "",
"ipAddress": [
"8.8.8.8"
]
},
"ipRouteConfig": {
"ipRoute": [
{
"network": "0.0.0.0",
"prefixLength": 0,
"gateway": {
"ipAddress": "172.17.0.1",
"device": "0"
}
}
]
}
}
]
```
Note that `dnsConfig.ipAddress` is sourced from:
```console
% cat /etc/docker/daemon.json 
{
"dns": ["8.8.8.8"]
}
```
=> vcsim: Populate guest.ipStack property for container backed VMs

.goreleaser.yml
> [!IMPORTANT]
> Holding this one in draft until after the next release. 
- Updates  `.goreleaser.yml` to v2 configuration and addresses deprecations.
- Adds `vendor` and `license` to `nfpms` configuration.
Before:
```shell
➜ goreleaser check .goreleaser.yml
• only  version: 2  configuration files are supported, yours is  version: 0 , please update your configuration
⨯ command failed                                   error=only  version: 2  configuration files are supported, yours is  version: 0 , please update your configuration
```
```shell
➜ goreleaser check .goreleaser.yml
• checking                                 path=.goreleaser.yml
• DEPRECATED:  snapshot.name_template  should not be used anymore, check https://goreleaser.com/deprecations#snapshotname_template for more info
• …
```
=> chore: update `.goreleaser.yml` to v2

Makefile, govc/test/vcsim.bats, internal/helpers.go, simulator/object.go, simulator/virtual_disk_manager.go, simulator/virtual_machine.go, simulator/vpx/service_content.go, vim25/soap/client.go
api: soap.ThumbprintsSHA1 returns an empty string when GODEBUG contains "fips140=only"
Fixes #3766
=> vcsim: Avoid use of sha1 for stable UUIDs (OIDs)

.goreleaser.yml, Dockerfile.govc, Dockerfile.govc.runner, Dockerfile.vcsim, govc/README.md, scripts/runner/entrypoint.sh
- Updates the default container images to pass the `GO_VERSION` as a build argument for `FROM`.
- Adds a minimal Alpine-based image that can be used as runner image requested by the community.
> [!NOTE]
> The compressed size once published to Docker Hub will be ~39.6 MB. 
Closes: #2988
```shell
govmomi on  chore/update-container-images [✘!?] via 🐹 v1.24.2 on 🐳 v26.1.5 (rancher-desktop) 
✦3 ➜ goreleaser release --snapshot --clean                          
• skipping announce, publish, and validate...
• cleaning distribution directory
• loading environment variables
• getting and validating git state
• git state                                      commit=016b3203e91bd17687f8c74fe8fb96c5f5331f3f branch=chore/update-container-images current_tag=v0.51.0-alpha.0 previous_tag=v0.50.0-alpha.0 …
```
=> chore: update container images

cli/device/info.go, cli/importx/vmdk.go, cli/vm/disk/promote.go, govc/USAGE.md, govc/emacs/govc.el, govc/test/import.bats, govc/test/vm.bats, object/virtual_machine.go, simulator/file_manager.go, simulator/http_nfc_lease.go, simulator/session_manager.go, simulator/virtual_disk_manager.go, simulator/virtual_machine.go, simulator/virtual_machine_test.go, simulator/vstorage_object_manager.go, vapi/library/example_test.go, vapi/simulator/simulator.go, vmdk/descriptor.go, vmdk/import.go, vmdk/import_test.go
- govc: Add vm.disk.promote command
- api: Add object.VirtualMachine.PromoteDisks method
- vcsim: Use vmdk.Descriptor for vmdk file metadata
- govc: Add import.vmdk '-i' flag to output vmdk info only
- api: Extend vmdk.Info to include Descriptor
- fix: vcsim: Avoid possible race in SessionManager.Logout
=> vcsim: Add VirtualMachine.PromoteDisks_Task method

cli/host/option/set.go, cli/option/set.go, govc/USAGE.md, session/keepalive/example_test.go, simulator/option_manager.go, simulator/session_manager.go, simulator/sim25/client.go, simulator/sim25/doc.go, vapi/simulator/simulator.go
Use of SessionIdleTimeout package var can race.
Changing session timeout via OptionManager:
- Avoids races
- Works with clients other than Go
- Same method used by real vCenter
BREAKING: var `simulator.SessionIdleTimeout` has been removed.
Use `sim25.SetSessionTimeout` instead.
Example against real vCenter:
```console
% govc option.set config.vmacore.soap.sessionTimeout 42
```
Setting is persisted here:
```console
<soap>
<sessionTimeout>42</sessionTimeout>
</soap>
```
=> vcsim: Use OptionManager to configure session timeout duration

govc/test/vm.bats, simulator/esx/event_manager.go, simulator/virtual_machine.go
CustomizeVM_Task returns NicSettingMismatch if NumberOfNicsInVM != 0 NumberOfNicsInSpec. However, a NIC can be removed via ReconfigVM_Task before powering on a VM, which results in panic due to index-out-of-range.
If there is a mismatch at poweron, emit a CustomizationNetworkSetupFailed as real vCenter does.
=> vcsim: Avoid panic if VM NIC is removed after CustomizeVM

object/example_test.go, simulator/model.go, simulator/model_test.go, simulator/virtual_machine.go, simulator/virtual_machine_test.go
Real VC replaces the NSX OpaqueBacking with the DVPG found via the LogicalSwitchUuid so do the same in vcsim. For each OpaqueNetwork specified in the simulator model, create a corresponding NSX portgroup with the LogicalSwitchUuid so the each opaque backing can be resolved to a DPVG.
Tested against a slightly hacked version of vm-operator's vcsim test framework.
MR is draft atm until I can look at adding some govmoni tests
=> vcsim: Resolve NSX OpaqueBacking to the DistributedVirtualPortgroup

simulator/performance_manager.go, simulator/performance_manager_test.go
This is the case for vCLS VMs at least:
```console
> % govc collect -type m /DC/vm/vCLS name datastore
> VirtualMachine:vm-3007  name       string                          vCLS-4c4c4544-0038-3610-8057-b1c04f514a33
> VirtualMachine:vm-3007  datastore  []types.ManagedObjectReference  
> VirtualMachine:vm-3014  name       string                          vCLS-4c4c4544-0031-3310-8057-b4c04f514a33
> VirtualMachine:vm-3014  datastore  []types.ManagedObjectReference  
```
=> fix: vcsim: Avoid panic in QueryAvailablePerfMetric if VM has no Datastore

cli/volume/ls.go, cns/client_test.go, cns/simulator/simulator.go, cns/simulator/simulator_test.go, cns/types/types.go
This PR is adding changes required to support handling of vim25:NotSupported returned with CnsFault.
We need to catch this fault in the vSphere CSI Driver for the case when VC is upgraded with certain capability but none of the hosts are upgraded to support that capability. Specifically with CNS Transaction support, if VC is upgraded but none of the hosts are upgraded, API returns CNSFault with Not Supported, and vSphere CSI drier need to fall back to use API without transaction support.
```xml
<vim25:result xsi:type="CnsVolumeOperationBatchResult">
<volumeResults xsi:type="CnsVolumeCreateResult">
<fault>
<fault xsi:type="CnsFault">
<faultCause>
<fault xsi:type="vim25:NotSupported"
xmlns:vim25="urn:vim25">
</fault>
<localizedMessage>The operation is not supported on the …
```
=> handle vim25:NotSupported returned with CnsFault

go.mod, go.sum, govc/go.mod, govc/go.sum, pbm/client.go, pbm/client_test.go, pbm/methods/internal_methods.go, pbm/pbm_util.go, pbm/simulator/simulator.go, pbm/types/internal_types.go, vcsim/go.mod, vcsim/go.sum
This PR adds PBM internal types and methods that are required to set/fetch/update K8s compliant names for storage policies.
Added unittest to test the required methods and types
```
go test -v -count 1 -run TestStoragePolicyK8sCompliantNames ./pbm
=== RUN   TestStoragePolicyK8sCompliantNames
=== RUN   TestStoragePolicyK8sCompliantNames/Validate_K8sCompliantName_set_for_existing_storage_profiles
client_test.go:370: PBM version=2.0
=== RUN   TestStoragePolicyK8sCompliantNames/Validate_K8sCompliantName_set_after_new_policy_creation
client_test.go:389: PBM version=2.0
client_test.go:435: VSAN Profile: "c621a600-8840-4861-b3e1-f57e6c1f2ebb" with Name "Kubernetes-VSAN-TestPolicy" successfully created
client_test.go:445: Profile …
```
=> Add SPBM types and methods related to K8s compliant names changes

cns/client_test.go, cns/types/types.go
This PR introduces Go binding changes to support specifying Cluster MoRefs in CnsVolumeCreateSpec.
With this change in the API, the backend can determine the set of datastores applicable for volume provisioning that are accessible to the provided clusters and comply with the specified storage policy in CnsVolumeCreateSpec. 
Callers of the API no longer need to explicitly provide datastores when clusters and policy are specified.
CnsPlacementResult now includes a new Clusters field, indicating the list of clusters where the provisioned volume is accessible. This allows clients like CSI to compute node affinity rules directly from the response, eliminating the need for extra vCenter queries to determine where volume is accessible to.
Executed test on the environment with this FSS enabled. …
=> update CnsVolumeCreateSpec and CnsVolumeOperationResult

cns/client_test.go, cns/types/types.go
Add new parameters to Cns AttachDetach Spec for supporting multiwriter.
Also fixed the test where CnsAlreadyRegisteredFault is expected when the same volume is re-created. This has changed and we should not be getting any error: https://bugzilla-vcf.lvn.broadcom.net/show_bug.cgi?id=3538552#c1
Verified that these changes work with CNS_RUN_SHARED_DISK_TESTS set to true as well false.
Completed Govmomi CNS  test output: https://docs.google.com/document/d/1qNhQm46moqRvZjPdHY76uJafQuPKVQeXP3klM-YxhWo/edit?usp=sharing
Re-creating same disk:
```
client_test.go:337: reCreateVolumeOperationRes.: &types.CnsVolumeOperationResult{
DynamicData: types.DynamicData{},
VolumeId:    types.CnsVolumeId{
DynamicData: types.DynamicData{},
Id: …
```
=> Add shared disk parameters to Cns AttachDetach Spec

vim25/types/enum.go, vim25/types/if.go, vim25/types/types.go
This change introduces Govmomi bindings to support specifying placement policies for VM Service VMs.  The placement 
policies can be used to specify affinity and anti-affinity between VMs, and groups of VMs.
Ran `make go-test` locally.
=> Introduce Govmomi bindings to support VM placement policies

vim25/types/types.go
This patch fixes an issue where the WSDL names for the types related to VM placement policy changed as they were still under development.
```shell
go test -v ./simulator
```
=> api: Placement policy WSDL names changed

cli/volume/ls.go, cns/client.go, cns/client_test.go, cns/simulator/simulator.go, cns/simulator/simulator_test.go, cns/types/types.go
This PR is adding go binding for CnsKubernetesQueryFilter
Verified executing test against vCenter and confirmed QueryVolume API using CnsKubernetesQueryFilter as filter and CnsQueryFilter as filter working as expected.
Request with KubernetesQueryFilter
```
<Envelope
xmlns="http://schemas.xmlsoap.org/soap/envelope/">
<Body>
<CnsQueryVolume
xmlns="urn:vsan">
<_this type="CnsVolumeManager">cns-volume-manager</_this>
<filter
xmlns:_XMLSchema-instance="http://www.w3.org/2001/XMLSchema-instance" _XMLSchema-instance:type="CnsKubernetesQueryFilter">
<containerClusterIds>demo-cluster-id</containerClusterIds>
<namespaces>default</namespaces>
</filter>
</CnsQueryVolume>
</Body>
```
Response of QueryVolume API using KubernetesQueryFilter
```
<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope …
```
=> binding for CnsKubernetesQueryFilter

cns/client_test.go, cns/types/types.go
Added json tags to cns syncvolume api types
Added unit test for sync volume api 
(tests were commented out earlier as SyncVolume Api was not ready ref PR [#3813](https://github.com/vmware/govmomi/pull/3813))
Ran unit tests.
1. Created a volume in the specified datastore
2. Synced Volume the volume using CNSSyncVolume.
**Test Logs:**
```
client_test.go:206: volumeCreateResult &{CnsVolumeOperationResult:{DynamicData:{} VolumeId:{DynamicData:{} Id:7bb81711-2884-425b-acb7-73a1cb76ae8d} Fault:<nil>} Name:pvc-901e87eb-c2bd-11e9-806f-005056a0c9a0 PlacementResults:[{Datastore:Datastore:datastore-42 PlacementFaults:[] Clusters:[]}]}
client_test.go:213: Volume created successfully. volumeId: 7bb81711-2884-425b-acb7-73a1cb76ae8d
client_test.go:1738: …
```
=> Add tests for syncvolume api and update json tags 

cli/folder/place.go, object/folder.go, simulator/folder.go, simulator/folder_test.go, vim25/types/unreleased.go, vim25/types/unreleased_test.go
The PlaceVmsXCluster API is being updated to return the list of available candidate networks in the recommendation.
This change does the following.
1. Extend the Initial Placement Action Struct
A new type ClusterClusterInitialPlacementActionEx is defined in types/unreleased.go to extend the existing ClusterClusterInitialPlacementAction. This struct adds the new field AvailableNetworks to ClusterClusterInitialPlacementActionEx.
2. Register the Extended Type Override
Registered the extended struct as the override for ClusterClusterInitialPlacementAction using:
types.Add("ClusterClusterInitialPlacementAction", reflect.TypeOf((*types.ClusterClusterInitialPlacementActionEx)(nil)).Elem())
This registration is needed in:
types/unreleased.go (global override for simulator use)
simulator/folder.go …
=> Update folder.PlaceVMsXCluster to return available candidate networks

simulator/folder.go, simulator/folder_test.go
Currently, PlaceVmsXCluster API supports placement of only one VM at a time. In VCF 9.1, the API will support placing multiple VMs in a single call.
In this PR, I am removing the check which validates if the length of VmPlacementSpecs is equal to 1.
Also, added a new test  to verify that the placement passes with multiple VMs in input spec.
Closes: #CRM-3431
[# govmomi]$ go test ./simulator
ok      github.com/vmware/govmomi/simulator     65.270s
[# govmomi]$ go test -v ./simulator -run ^TestPlaceVmsXCluster
=== RUN   TestPlaceVmsXClusterCreateAndPowerOn
--- PASS: TestPlaceVmsXClusterCreateAndPowerOn (0.81s)
=== RUN   TestPlaceVmsXClusterCreateAndPowerOnWithCandidateNetworks
--- PASS: TestPlaceVmsXClusterCreateAndPowerOnWithCandidateNetworks (0.81s)
=== RUN   TestPlaceVmsXClusterRelocate …
=> vcsim : Remove the single VM limitation for PlaceVmsXCluster API

cli/permissions/permissions.go
Safely handle cases where the role may not exist by defaulting to the role ID as a string, and only using the role name if it is present.
Updates the role name display in `func (l *List) Write(w io.Writer) error` in `cli/permissions/permissions.go`, preventing potential nil pointer errors by falling back to the role ID when the role is not found.
Closes #3833
=> fix: guard against nil role in permissions.ls

cli/folder/place.go, object/folder.go, simulator/folder.go, vim25/types/unreleased.go
This patch introduces a base interfaces for the types `ClusterClusterInitialPlacementAction` and `ClusterClusterInitialPlacementActionEx`, named `BaseClusterClusterInitialPlacementAction`. Now clients can rely on the interface and get the base type when the new fields are not required.
With the following command:
```shell
go test -v -run TestPlaceVmsXClusterCreateAndPowerOnWithCandidateNetworks ./simulator
```
The output will resemble the following:
```shell
=== RUN   TestPlaceVmsXClusterCreateAndPowerOnWithCandidateNetworks
folder_test.go:737: AvailableNetworks for VM <nil>:
folder_test.go:739: - network-6
folder_test.go:739: - dvportgroup-12
--- PASS: TestPlaceVmsXClusterCreateAndPowerOnWithCandidateNetworks (0.90s)
PASS
ok  	github.com/vmware/govmomi/simulator …
```
=> api: BaseClusterClusterInitialPlacementAction interface

vapi/internal/internal.go, vapi/library/library.go, vapi/library/library_configuration.go, vapi/library/library_test.go, vapi/library/library_usage.go, vapi/simulator/simulator.go
This patch adds client bindings to perform library usage CRUD operations via govmomi.
Closes: NA
Added unit tests that utilize the updated simulator code included in this change.
=> API for Library Usage CRUD Operations using GoVMOMI Bindings

vim25/types/hardware_version.go, vim25/types/hardware_version_test.go
This patch adds support for the vmx-22 hardware version.
Closes: `NA`
By running the GH actions.
=> api: Support vmx-22

object/host_system.go, vim25/methods/unreleased.go, vim25/types/types.go, vim25/types/unreleased.go, vim25/types/unreleased_test.go
This patch adds support to PodVMInfo VMODL APIs under HostRuntimeInfo which includes hasPodVM and podVMOverheadInfo properties. In addition this patch also adds UpdatePodVMProperty method under HostSystem. The PodVMInfo property and method will be updated by ESXi host and will be consumed by DRS to determine PodVM placement. The change also includes a unit test that tests the setting of PodVMInfo property.
Note: PodVMOverheadInfo that is currently exposed as part of HostCapability will be removed
as a follow-up change, once existing consumers have moved away from it.
- make test:
=== RUN   TestPodVMInfo
--- PASS: TestPodVMInfo (0.69s)
- Verified UpdatePodVMProperty() method from ESXi:
--- PASS: TestSetOverheadVMODLProperty (0.20s)
PASS
=> Add PodVMInfo type and method

vapi/esx/settings/clusters/vms/transition.go
Description:
This change is to include the new EAM 2.0 Solution Transition API to migrate exsiting EAM 1.0 Agencies to 2.0.
How was this tested:
I tested it with a VC with existing EAM Agency using this test code
```
// © Broadcom. All Rights Reserved.
// The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
// SPDX-License-Identifier: Apache-2.0
package vms
import (
"context"
"encoding/json"
"os"
"testing"
"github.com/stretchr/testify/require"
"github.com/vmware/govmomi"
"github.com/vmware/govmomi/eam"
"github.com/vmware/govmomi/eam/object"
"github.com/vmware/govmomi/vapi/rest"
"github.com/vmware/govmomi/vim25/soap"
"github.com/vmware/govmomi/vim25/types"
)
// TODO: Remove this test when ready to create Pull Request
// Do not commit this file to public vmware/govmomi …
```
=> Adds EAM 2.0 Solution Transition API

vim25/types/types.go, vim25/types/unreleased_test.go
The podVMOverheadInfo property has moved to the host runtime info under the podVMInfo property. Hence this unused host capability can be removed along with its test.
Note: This is a follow up to https://github.com/vmware/govmomi/pull/3850 and reverts some unreleased changes from https://github.com/vmware/govmomi/pull/3747
Ran make test and ensured the TestPodVM test passed as it still verifies the host runtime info podVMOverheadInfo
=> api: remove podVMOverheadInfo host capability

vapi/esx/settings/clusters/vms/ovf_resource.go
1. Fix a typo in `certificate`
=> EAM 2.0 Bindings has typo in certificate
